rows = []

# ============================================================
# SUBTOPIC 1: Lung Anatomy & Airway Structure (10 Flashcards)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','easy','flashcard','Name the three lobes of the right lung.','["Superior, middle, and inferior lobes — separated by the horizontal fissure (between superior and middle) and the oblique fissure (between middle and inferior)."]','A','Mnemonic: Right lung = 3 lobes (like 3 Rs of Right). Left lung has only 2 lobes because the heart takes up space on the left.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','easy','flashcard','What is the function of Type II pneumocytes?','["Type II pneumocytes synthesise and secrete pulmonary surfactant (mainly DPPC), regenerate alveolar epithelium after injury, and convert to Type I pneumocytes to repair the alveolar surface."]','A','Memory hook: Type II = Two jobs (make surfactant + repair). They are the ''stem cells'' of the alveolar epithelium.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','easy','flashcard','What is the function of alveolar macrophages?','["Alveolar macrophages (dust cells) are the primary phagocytes of the alveolar space. They engulf inhaled particles, microorganisms, and cellular debris, and present antigens to lymphocytes. They are derived from circulating monocytes."]','A','They are the ''custodians'' of the alveolus. In smokers, macrophages become laden with carbon particles, appearing black (''anthracotic'' macrophages).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','medium','flashcard','What is the difference between anatomical dead space and physiological dead space?','["Anatomical dead space (~150 ml) is the volume of conducting airways (from nose to terminal bronchioles) that do not participate in gas exchange. Physiological dead space = anatomical dead space + alveolar dead space (alveoli that are ventilated but not perfused, V/Q → ∞). In normal lungs, physiological ≈ anatomical dead space."]','A','Physiological dead space is measured by the Bohr equation using PaCO₂. It exceeds anatomical dead space in disease states causing high V/Q units, such as pulmonary embolism.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','medium','flashcard','What is a bronchopulmonary segment and why is it clinically important?','["A bronchopulmonary segment is the largest subdivision of a lobe, supplied by its own tertiary (segmental) bronchus and pulmonary artery branch, and drained by intersegmental veins. It is the smallest unit of lung that can be surgically resected without compromising adjacent tissue."]','A','Right lung: 10 segments; Left lung: 8–10 segments (lingula = equivalent of right middle lobe). Localised pneumonia, abscess, or tumour confined to a segment can be treated by segmentectomy.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','medium','flashcard','Describe the mucociliary escalator and its clinical importance.','["The mucociliary escalator consists of ciliated epithelial cells (from trachea to terminal bronchioles) beating at ~12 Hz, propelling a mucus blanket (produced by goblet cells and submucosal glands) toward the pharynx for expectoration or swallowing. It is the primary airway defence mechanism against inhaled particles and pathogens."]','A','Damaged by smoking (cilia paralysis), cystic fibrosis (thick mucus), and primary ciliary dyskinesia (immotile cilia). Loss leads to recurrent respiratory infections.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','medium','flashcard','What distinguishes the respiratory zone from the conducting zone of the lung?','["Conducting zone (generations 1–16): trachea, bronchi, bronchioles, terminal bronchioles — no gas exchange, forms anatomical dead space (~150 ml). Respiratory zone (generations 17–23): respiratory bronchioles, alveolar ducts, alveolar sacs — contains alveoli and participates in gas exchange. Total respiratory zone volume ~2500–3000 ml."]','A','The transition from conducting to respiratory zone occurs at the respiratory bronchiole, which is the first airway generation to bear alveoli in its wall.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','hard','flashcard','What is the blood supply to the lung parenchyma vs. the bronchial tree?','["Lung parenchyma (gas exchange): supplied by deoxygenated blood from the pulmonary arteries (low-pressure, high-flow, right heart output). Bronchial tree (conducting airways down to terminal bronchioles): supplied by oxygenated blood from bronchial arteries (branches of descending thoracic aorta, high-pressure, low-flow). Venous drainage: bronchial veins drain to azygos system and some to pulmonary veins (true anatomical shunt ~2%)."]','A','The dual circulation explains why: (1) pulmonary embolism may not cause infarction if bronchial supply is intact; (2) bronchial artery haemorrhage causes massive haemoptysis (high pressure).','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','hard','flashcard','What are J-receptors (juxtacapillary receptors) and what stimulates them?','["J-receptors (C-fibre endings) are located in the alveolar walls adjacent to pulmonary capillaries. Stimulated by: pulmonary capillary engorgement/oedema, pneumonia, inhalation of irritants, microemboli, and chemicals (capsaicin, phenyldiguanide). Response: rapid, shallow breathing; bronchoconstriction; bradycardia; hypotension. They contribute to the sensation of dyspnoea."]','A','J-receptors may explain the dyspnoea of left heart failure/pulmonary oedema and may contribute to the tachypnoea in pneumonia. Named ''juxtacapillary'' because of their position next to pulmonary capillaries.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','hard','flashcard','Describe the layers of the respiratory membrane that O₂ must cross during gas exchange.','["From alveolar lumen to capillary plasma: (1) alveolar fluid layer with surfactant; (2) alveolar epithelium (mainly Type I pneumocytes, ~0.2 µm); (3) epithelial basement membrane; (4) thin interstitial space; (5) capillary endothelial basement membrane; (6) capillary endothelium (~0.2 µm). Total thickness ~0.2–0.6 µm in healthy lungs. Total alveolar surface area ~70 m²."]','A','In pulmonary oedema and fibrosis, the interstitial space expands, increasing diffusion distance and impairing gas exchange. CO₂ (20× more soluble) is unaffected long before O₂ exchange deteriorates.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 2: Pulmonary Mechanics (10 Flashcards)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','easy','flashcard','State Laplace''s law as it applies to alveolar stability.','["P = 2T/r. The pressure required to keep an alveolus open is directly proportional to surface tension (T) and inversely proportional to the radius (r). Without surfactant, small alveoli would have higher pressure and tend to empty into larger ones (alveolar instability)."]','A','Surfactant reduces T preferentially in small alveoli (more molecules per unit area when compressed), equalising pressure and stabilising alveolar size. This prevents the ''snowball'' collapse of small into large alveoli.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','easy','flashcard','What is lung compliance and how is it calculated?','["Lung compliance (C) = ΔV/ΔP (change in volume per unit change in transpulmonary pressure). Normal total lung compliance ≈ 200 ml/cm H₂O. Measured by inflating the lung in stepwise increments (static compliance) while relaxing all muscles."]','A','Decreased C (stiff lungs): fibrosis, ARDS, pulmonary oedema, NRDS. Increased C (floppy lungs): emphysema. Work of breathing increases with both abnormalities.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','medium','flashcard','How does surfactant prevent alveolar collapse?','["Surfactant (mainly DPPC) is an amphipathic molecule that lowers the surface tension at the air-water interface inside alveoli from ~50 dynes/cm (clean water) to near 0 dynes/cm at end-expiration. By reducing surface tension, it: (1) reduces the pressure tending to collapse alveoli; (2) increases compliance; (3) stabilises alveoli of different sizes; (4) reduces fluid transudation into alveoli."]','A','Without surfactant (NRDS in premature infants): high surface tension → progressive alveolar collapse → stiff lungs → enormous inspiratory work. Treatment: exogenous surfactant + CPAP/mechanical ventilation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','medium','flashcard','Define pleural pressure and explain its role in lung expansion.','["Pleural pressure (Ppl) is the pressure in the fluid layer between the visceral and parietal pleura. At rest (end-expiration), Ppl ≈ −5 cm H₂O (subatmospheric). During inspiration, Ppl decreases to −7.5 cm H₂O, expanding the lungs. The negative Ppl is maintained by the elastic recoil of the lungs pulling away from the chest wall and continuous lymphatic drainage of pleural fluid."]','A','Pneumothorax: air enters pleural space → Ppl rises toward 0 → lung collapses. Tension pneumothorax: Ppl becomes positive → lung fully collapses + mediastinal shift → emergency.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','medium','flashcard','What determines airway resistance and how is it affected in COPD?','["Airway resistance (Raw) = driving pressure / flow rate = (Palveolar − Patmospheric) / Flow. Resistance is inversely proportional to the 4th power of radius (Poiseuille). Airway resistance is greatest in medium-sized bronchi (generations 3–5) collectively. In COPD: (1) mucus hypersecretion narrows airways; (2) inflammation causes mucosal oedema; (3) loss of radial traction (emphysema) allows small airway collapse on expiration — all dramatically increase Raw."]','A','Bronchodilators (beta-2 agonists, anticholinergics) reduce Raw by dilating airways. In emphysema, loss of radial traction causes airway collapse during forced expiration — hence dynamic airflow obstruction and air trapping.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','medium','flashcard','What are the primary inspiratory muscles and their roles?','["Primary inspiratory muscle: diaphragm (accounts for ~70% of quiet inspiration; innervated by phrenic nerve C3–C5). Accessory: external intercostals (raise rib cage), sternocleidomastoid (lifts sternum), scaleni (lift first two ribs). During heavy exercise: all accessory muscles recruited. During normal quiet breathing, expiration is passive (elastic recoil); active expiration (internal intercostals, abdominals) only during forced breathing or exercise."]','A','''C3,4,5 keeps the diaphragm alive.'' Diaphragmatic paralysis (phrenic nerve injury, e.g., from cervical cord injury at C3–5) causes respiratory failure.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','hard','flashcard','Explain the concept of flow limitation during forced expiration and its clinical relevance.','["During forced expiration, positive pleural pressure is transmitted to airways. At the equal pressure point (EPP), airway luminal pressure equals pleural pressure. Downstream (mouthward) from the EPP, pleural pressure exceeds luminal pressure — airways collapse. Further expiratory effort simply collapses airways more proximally, not increasing flow. This creates an effort-independent maximum expiratory flow, determined by lung recoil and upstream airway conductance — not effort."]','A','Clinical relevance: FEV1 is effort-independent (after 20–25% of FVC) in healthy individuals. In COPD, the EPP moves upstream (into smaller airways) causing greater collapse and more severe flow limitation. Flow-volume loops show the characteristic scooped expiratory curve.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','hard','flashcard','How does auto-PEEP (intrinsic PEEP) develop in mechanically ventilated COPD patients?','["Auto-PEEP (intrinsic PEEP) occurs when expiration time is insufficient for complete lung emptying before the next breath, leaving residual positive alveolar pressure above applied PEEP. In COPD: high airway resistance + dynamic airway collapse prolong expiratory time constant (τ = R × C). Rapid ventilator rates compound this. Auto-PEEP causes: dynamic hyperinflation, increased WOB, haemodynamic compromise (impaired venous return), and barotrauma risk."]','A','Detected by an expiratory hold manoeuvre on the ventilator. Managed by: increasing expiratory time (lower RR, I:E ratio 1:3 to 1:5), bronchodilators to reduce R, and accepting mild permissive hypercapnia.','universal',true,'{year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','hard','flashcard','Explain why emphysema increases static lung compliance but worsens dynamic lung function.','["Static compliance is increased in emphysema because destruction of alveolar walls (elastin/collagen matrix) reduces the elastic recoil of the lung tissue — lungs are ''floppier'' and easier to inflate. However, this same loss of elastin destroys the radial traction holding small airways open. During forced expiration, unsupported small airways collapse early (low EPP), causing air trapping (elevated RV and FRC), reduced FEV1, and low FEV1/FVC despite high static compliance."]','A','This explains the paradox: emphysema lungs are ''easy to fill but hard to empty.'' TLC is elevated (high C), but RV is also elevated (airway collapse), and FEV1/FVC is severely reduced.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','hard','flashcard','What is the significance of the time constant (τ) in pulmonary mechanics?','["Time constant τ = Resistance (R) × Compliance (C). It represents the time for a lung unit to fill or empty to 63% of its final volume. After 3τ, ~95% filling/emptying. Regional differences in τ cause uneven ventilation: lung units with high R or high C fill slowly (slow units) — receive more ventilation at low respiratory rates; at high rates, fast units fill preferentially, worsening V/Q distribution."]','A','In COPD: high R → long τ → air trapping. In ARDS: low C → short τ (stiff units fill faster) but collapsed units may not open at all. Ventilator settings must account for τ to prevent over- or under-ventilation of lung units.','universal',false,'{year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 3: Lung Volumes & Capacities (10 Flashcards)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','easy','flashcard','State the four lung volumes and their approximate values in a healthy adult male.','["(1) Tidal volume (Vt) ≈ 500 ml — volume per normal breath. (2) Inspiratory reserve volume (IRV) ≈ 3000 ml — extra volume after normal inspiration. (3) Expiratory reserve volume (ERV) ≈ 1100 ml — extra volume after normal expiration. (4) Residual volume (RV) ≈ 1200 ml — remains after maximal expiration; cannot be measured by spirometry."]','A','Mnemonic: Tiny IRV ERVs RVing. The four volumes add up to TLC ≈ 5800 ml. Women''s volumes are 20–30% less than men''s.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','easy','flashcard','Define Functional Residual Capacity (FRC) and explain why it is clinically important.','["FRC = ERV + RV ≈ 2300 ml. It is the volume remaining in the lungs after a normal passive expiration. FRC is the equilibrium point where lung inward recoil equals chest wall outward recoil (no muscle activity). Clinically important because: (1) it acts as a buffer against extreme O₂/CO₂ swings between breaths; (2) it is altered in disease (↑ in emphysema, ↓ in fibrosis, obesity, supine posture, ARDS); (3) it cannot be measured by spirometry."]','A','FRC can be measured by: helium dilution, nitrogen washout, or body plethysmography. FRC is reduced in the supine position by ~0.7 L — important in anaesthesia, critical illness, and post-operative care.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','medium','flashcard','What is FEV1/FVC ratio, and how does it differentiate obstructive from restrictive disease?','["FEV1/FVC is the fraction of forced vital capacity expired in the first second. Normal ≥ 0.80. In obstructive disease (asthma, COPD): FEV1 falls more than FVC → FEV1/FVC < 0.70 (LLN). In restrictive disease (fibrosis, effusion): both FEV1 and FVC fall proportionally → FEV1/FVC is normal or elevated (>0.80), but TLC is reduced."]','A','The ratio is the key spirometric discriminator. If both FEV1 and FVC are reduced with a normal ratio: think restriction. If ratio is low: think obstruction. A mixed pattern exists when both are abnormal simultaneously.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','medium','flashcard','Describe the flow-volume loop in obstructive versus restrictive lung disease.','["Normal: symmetric bell-shaped peak; tall linear expiratory limb. Obstructive (COPD/asthma): reduced peak flow; concave (scooped) expiratory limb indicating reduced mid and late expiratory flows (FEF25–75% reduced); FVC may be reduced due to air trapping. Restrictive (fibrosis): small loop; peak flow relatively preserved or slightly reduced; steep, linear expiratory limb; all volumes reduced; FVC markedly reduced."]','A','The inspiratory limb also gives information: variable extrathoracic obstruction flattens the inspiratory limb; fixed obstruction flattens both. Fixed intrathoracic obstruction selectively flattens the expiratory limb.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','medium','flashcard','How is FRC measured when spirometry is insufficient?','["FRC cannot be measured by spirometry (contains RV). Methods: (1) Helium dilution: equilibrate known He concentration into lungs from FRC; He concentration falls proportionally to FRC. (2) Nitrogen washout: breathe 100% O₂, wash out N₂; total N₂ expired allows FRC calculation. (3) Body plethysmography (gold standard): uses Boyle''s law — panting against closed shutter; changes in box pressure and mouth pressure allow calculation of all thoracic gas volume including trapped gas."]','A','Body plethysmography gives the largest (most accurate) values in emphysema/bullous disease because it measures all intrathoracic gas, including gas trapped in non-communicating bullae.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','medium','flashcard','What changes in lung volumes occur in COPD and why?','["In COPD: RV increased (air trapping from early airway closure); FRC increased (hyperinflation); TLC increased or normal (in pure emphysema); VC decreased; FEV1 markedly decreased; FEV1/FVC decreased (<0.70); ERV decreased. Mechanisms: (1) emphysematous destruction → loss of radial traction → small airway collapse trapping air; (2) mucus/inflammation obstructs airways; (3) chest wall adapts to new higher resting volume (barrel chest)."]','A','In severe COPD, the diaphragm is flattened by hyperinflation, reducing its mechanical advantage — worsening respiratory muscle inefficiency. IC decreases because TLC cannot increase proportionally to match the raised FRC.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','medium','flashcard','What is closing capacity and when does it exceed FRC?','["Closing capacity (CC) = closing volume (CV) + RV. CV is the lung volume at which small airways begin to close during expiration. Normally CC < FRC, so airways remain open throughout tidal breathing. CC exceeds FRC in: elderly patients (age-related airway loss), obese patients (FRC reduced), supine position (FRC falls by ~0.7 L), smokers, and patients with early small airway disease."]','A','When CC > FRC, airway closure during tidal breathing causes gas trapping and V/Q mismatch → hypoxaemia. This explains why elderly patients have lower PaO₂ and why SpO₂ falls rapidly in the supine obese patient.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','hard','flashcard','How does the relationship between RV and TLC change in obstructive vs restrictive disease?','["Normal: RV/TLC ≈ 25% (e.g., 1200/5800). In obstructive disease (emphysema/COPD): both TLC (mild increase) and RV (marked increase from air trapping) increase, so RV/TLC ratio rises significantly (>35–40%), indicating hyperinflation. In restrictive disease: both TLC and RV decrease proportionally, so RV/TLC ratio may be normal or slightly increased (if small airways close early at higher absolute lung volumes despite smaller TLC)."]','A','RV/TLC > 35% is a sensitive marker of air trapping in obstructive disease. In severe COPD, RV/TLC can reach 50–60%.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','hard','flashcard','What is peak expiratory flow rate (PEFR) and what limits it?','["PEFR is the maximum airflow rate achievable during a forced expiration from TLC. Normal values: ~600 L/min (men), ~450 L/min (women). It is effort-dependent in the first 20 ms, then becomes effort-independent (determined by airway calibre and elastic recoil). PEFR is reduced in obstructive disease (asthma, COPD) and is used for home monitoring of asthma — >20% diurnal variation or fall of >50 L/min indicates significant airflow variability."]','A','PEFR is a simple, inexpensive point-of-care test. However, it correlates poorly with FEV1 in some patients and is highly effort-dependent — a poor effort can give falsely reassuring results. FEV1 from full spirometry is more reliable for diagnosis.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','hard','flashcard','Explain the ''gas trapping'' mechanism in severe asthma and its haemodynamic consequence (pulsus paradoxus).','["In severe asthma, widespread dynamic airway obstruction and mucus plugging cause air trapping (elevated FRC, RV). The patient breathes at high lung volumes. During inspiration, the large negative intrathoracic pressure needed to overcome resistance: (1) increases venous return to the right heart; (2) reduces LV filling (increased LV afterload via RV distension and pericardial constraint); (3) reduces systolic BP by >10 mmHg on inspiration — pulsus paradoxus."]','A','Pulsus paradoxus >10 mmHg indicates severe asthma (or cardiac tamponade). Measured by sphygmomanometer: inflate cuff above systolic; deflate slowly; note pressure at which first sound appears during expiration vs inspiration — difference > 10 mmHg is paradoxical.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

output = ',\n'.join(rows) + ','
with open('/sessions/keen-ecstatic-cannon/mnt/Skoolie/scripts/med_resp_ap_fc.sql', 'w') as f:
    f.write("INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES\n")
    f.write(output + '\n')
print(f"FC Part 1 written: {len(rows)} rows (subtopics 1-3)")
