rows = []

# ============================================================
# SUBTOPIC 4: Ventilation & Dead Space (10 Flashcards)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','easy','flashcard','State the alveolar ventilation equation and explain its clinical significance.','["VA = (Vt − VD) × RR, where VA = alveolar ventilation, Vt = tidal volume (~500 ml), VD = dead space (~150 ml), RR = respiratory rate. Also: PACO₂ = VCO₂/VA × k. Clinical significance: (1) Rapid shallow breathing dramatically reduces VA (e.g., Vt 200 ml, RR 20 → VA = 50 × 20 = 1000 ml/min vs. normal ~4200 ml/min); (2) Doubling VA halves PaCO₂; halving VA doubles PaCO₂."]','A','Clinically: a patient who takes rapid, shallow breaths may appear to be ''breathing'' but have inadequate alveolar ventilation, leading to CO₂ retention — the ''silent'' danger of rapid shallow breathing patterns.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','easy','flashcard','What is the alveolar gas equation and how is it used clinically?','["PAO₂ = PiO₂ − (PACO₂/R), where PiO₂ = FiO₂ × (PB − 47), PACO₂ ≈ PaCO₂, R = respiratory quotient (0.8). At sea level, room air: PAO₂ = 0.21 × (760 − 47) − 40/0.8 = 149.7 − 50 ≈ 100 mmHg. Used to calculate the A-a gradient: A-a gradient = PAO₂ − PaO₂ (normal 5–15 mmHg, rising with age)."]','A','An elevated A-a gradient indicates an intrinsic lung abnormality (shunt, V/Q mismatch, diffusion impairment). Normal A-a with low PaO₂ suggests hypoventilation as the cause (e.g., opioid overdose — low PaCO₂ alone explains low PaO₂).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','medium','flashcard','How does the Bohr equation measure physiological dead space?','["Bohr equation: VD/Vt = (PaCO₂ − PeCO₂) / PaCO₂, where PaCO₂ = arterial CO₂ (= alveolar CO₂, since all expired CO₂ comes from perfused alveoli), PeCO₂ = mean expired PCO₂. Rearranged: VD = Vt × (PaCO₂ − PeCO₂) / PaCO₂. Normal VD/Vt ≈ 0.30. Dead space fraction >0.60 usually requires mechanical ventilation."]','A','The Bohr equation identifies the dilution of alveolar CO₂ by dead space gas (which contains no CO₂). An elevated VD/Vt ratio in pulmonary embolism or ARDS increases the work of breathing needed to maintain normal PaCO₂.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','medium','flashcard','Explain why pulmonary embolism increases physiological dead space.','["Pulmonary embolism blocks pulmonary arterial flow to ventilated lung segments. Those segments continue to be ventilated (V remains) but receive no blood flow (Q → 0) → V/Q → infinity → alveolar dead space. Total physiological dead space = anatomical + alveolar dead space increases. If not compensated by increased ventilation, PaCO₂ rises. The patient often hyperventilates to maintain PaCO₂, leading to low PaCO₂ and respiratory alkalosis."]','A','In PE: PaCO₂ often low (hyperventilation); A-a gradient elevated; D-dimer raised; CT pulmonary angiography confirms. The low PaCO₂ in PE is from compensatory hyperventilation, not from the embolism itself.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','medium','flashcard','Compare the effects of rapid shallow breathing vs slow deep breathing on alveolar ventilation.','["Rapid shallow (Vt 200 ml, RR 20, VD 150 ml): VA = (200−150) × 20 = 1000 ml/min. Slow deep (Vt 700 ml, RR 8, VD 150 ml): VA = (700−150) × 8 = 4400 ml/min. Both give the same minute ventilation (4000 ml/min), but alveolar ventilation differs dramatically. Deep slow breathing is far more efficient because a smaller fraction of each breath is wasted on dead space."]','A','This explains why rapid shallow breathing (e.g., in pain, anxiety, splinting post-surgery) can cause CO₂ retention despite apparently adequate respiratory rate. Adequate minute ventilation does NOT guarantee adequate alveolar ventilation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','medium','flashcard','What is the effect of PEEP on dead space in mechanically ventilated patients?','["PEEP increases mean airway pressure and alveolar pressure. If PEEP exceeds pulmonary arterial pressure (Zone 1 conditions), capillaries are compressed → alveoli ventilated but not perfused → alveolar dead space increases. Paradoxically, PEEP that recruits previously collapsed alveoli can decrease V/Q mismatch and total dead space. The net effect depends on the balance between alveolar recruitment (reduces dead space) and Zone 1 creation (increases dead space)."]','A','High PEEP in ARDS: usually reduces dead space by recruiting collapsed alveoli (net beneficial). In normal lungs or in patients with low cardiac output (shock), high PEEP predominantly creates Zone 1 dead space — raising PaCO₂.','universal',false,'{year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','hard','flashcard','A patient has VT 600 ml, RR 15/min, PaCO₂ 40 mmHg, PeCO₂ 28 mmHg. Calculate physiological dead space and dead space fraction.','["VD = Vt × (PaCO₂ − PeCO₂)/PaCO₂ = 600 × (40 − 28)/40 = 600 × 0.30 = 180 ml. Dead space fraction (VD/Vt) = 180/600 = 0.30 (30%). Alveolar ventilation = (600 − 180) × 15 = 6300 ml/min. This is a normal VD/Vt. If VD/Vt rose to 0.60, VA would halve and PaCO₂ would double to ~80 mmHg unless Vt or RR increased to compensate."]','A','Normal VD/Vt ≈ 0.25–0.35. In severe ARDS or massive PE, VD/Vt can exceed 0.60–0.80, severely compromising CO₂ elimination and requiring high minute ventilation (which itself stresses the lung).','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','hard','flashcard','Explain regional differences in alveolar ventilation in the upright lung.','["In the upright lung, pleural pressure is more negative at the apex (−10 cm H₂O) and less negative at the base (−2.5 cm H₂O) due to gravity (lung weight). This means apical alveoli are more inflated at FRC (operating on a flatter, less compliant portion of their pressure-volume curve) and receive less ventilation per breath. Basal alveoli are less inflated at FRC (steeper, more compliant portion) and receive more ventilation per breath. Ventilation is therefore greater at the bases than the apices (~3:1)."]','A','The gradient of pleural pressure (~0.25 cmH₂O/cm height) means lower lung alveoli start more collapsed at FRC but have more ''room to expand'' per cmH₂O pressure change → more compliant at FRC → receive more ventilation. This matches perfusion distribution, optimising V/Q ratio.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','hard','flashcard','What is the iso-shunt diagram and how is it used in clinical practice?','["The iso-shunt diagram plots PaO₂ against FiO₂ for different levels of true shunt (0%, 10%, 20%, 30%, 50%). It allows estimation of shunt fraction from PaO₂ measured at a given FiO₂. Example: PaO₂ of 60 mmHg on FiO₂ 0.50 suggests ~20% shunt. The key concept is that true shunt cannot be corrected by increasing FiO₂ — the shunt line becomes flat at high FiO₂. V/Q mismatch lines converge toward normal PaO₂ with rising FiO₂."]','A','Clinically, a patient not responding to high FiO₂ (>50%) supplemental O₂ should be suspected of having a significant shunt (e.g., ARDS, massive atelectasis, intracardiac shunt, hepatopulmonary syndrome). This guides the decision to start PEEP or investigate for structural shunts.','universal',false,'{year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','hard','flashcard','How does low V/Q (not true shunt) cause hypoxaemia, and why does supplemental O₂ correct it?','["In low V/Q units (e.g., partially obstructed airways), ventilation is reduced but not zero. Alveolar PO₂ in these units is low (between venous and normal alveolar values). Blood leaving them has low PO₂. When this is mixed with blood from normal units, overall PaO₂ falls. However, because ventilation is not zero, supplemental O₂ can raise alveolar PO₂ in these low V/Q units, increasing O₂ content of blood from those units and correcting hypoxaemia."]','A','Key distinction: Low V/Q → corrects with O₂. True shunt (V/Q = 0) → does NOT correct with O₂ (blood never contacts ventilated alveoli regardless of FiO₂). Clinically tested: if PaO₂ rises to >400 mmHg on 100% O₂, shunt fraction is minimal.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 5: Gas Exchange & Diffusion (10 Flashcards)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','easy','flashcard','State Fick''s law of diffusion as applied to pulmonary gas exchange.','["Rate of diffusion = (A × D × ΔP) / T, where A = surface area (~70 m² in healthy lungs), D = diffusion coefficient (proportional to gas solubility, inversely proportional to √molecular weight), ΔP = partial pressure difference across membrane, T = membrane thickness (~0.2–0.6 µm). CO₂ diffuses ~20× faster than O₂ despite being heavier because its solubility is ~24× greater."]','A','Mnemonic: ''SADPT'' — Surface area, And Diffusivity, Pressure difference, divided by Thickness. Clinical reductions in gas exchange: ↓A (emphysema), ↑T (oedema/fibrosis), ↓ΔP (altitude/hypoventilation), ↓D (rare).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','easy','flashcard','What is the normal capillary transit time for blood in pulmonary capillaries, and how does this relate to gas exchange?','["Normal pulmonary capillary transit time ≈ 0.75 seconds at rest. O₂ equilibrates with alveolar gas in ~0.25 seconds (end of first third of transit) — considerable reserve for equilibration. During strenuous exercise, transit time falls to ~0.25 seconds; in healthy lungs, O₂ still equilibrates fully. In diffusion-impaired lungs (fibrosis, ARDS), O₂ cannot equilibrate in the shortened transit time during exercise — causing exercise-induced hypoxaemia."]','A','This explains why patients with fibrosis can maintain normal PaO₂ at rest (0.75 s is adequate despite thickened membrane) but desaturate on exertion (transit time shortens to 0.25 s → equilibration fails). This is ''diffusion-limited exercise desaturation.''','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','medium','flashcard','Distinguish between perfusion-limited and diffusion-limited gas exchange with examples.','["Perfusion-limited gas exchange: the gas equilibrates rapidly across the membrane; further uptake depends only on increasing blood flow. Example: N₂O, O₂ (normally), CO₂. Diffusion-limited: the gas does not fully equilibrate during transit time; a partial pressure gradient persists at the end of the capillary. Example: CO (very high Hb affinity keeps PCO near zero), O₂ during exercise in fibrosis, O₂ at altitude with high cardiac output."]','A','CO is the extreme diffusion-limited example — Hb binds CO so avidly that blood PCO stays near 0 throughout transit, maintaining a maximum gradient. This property makes CO ideal for measuring DLCO.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','medium','flashcard','What is DLCO, what does it measure, and what causes it to decrease?','["DLCO (diffusing capacity for CO) = rate of CO uptake (ml/min) / alveolar PCO (mmHg). It reflects: (1) alveolar surface area for gas exchange; (2) alveolar membrane thickness; (3) pulmonary capillary blood volume. Reduced DLCO: emphysema (↓ surface area), pulmonary fibrosis (↑ thickness, ↓ surface area), pulmonary hypertension (↓ capillary blood volume), pulmonary embolism. Elevated DLCO: polycythaemia, left-to-right shunt, pulmonary haemorrhage (extra Hb in alveolar space)."]','A','DLCO is the single most sensitive spirometric test for emphysema (reduced before flow limitation becomes obvious) and the key test for interstitial lung disease severity. It is measured by single-breath CO technique (10-second breath-hold).','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','medium','flashcard','Explain the causes and mechanisms of hypoxaemia — the five mechanisms.','["(1) Hypoventilation: ↑PaCO₂ → ↓PAO₂ (alveolar gas equation); A-a gradient normal. (2) V/Q mismatch (commonest): regions of low V/Q contribute venous-like blood; A-a gradient elevated; corrects with O₂. (3) Shunt: blood bypasses ventilated alveoli; A-a gradient elevated; does NOT correct with O₂. (4) Diffusion impairment: thickened membrane/reduced surface area; A-a gradient elevated; worst on exercise. (5) Low inspired PO₂: altitude; A-a gradient normal."]','A','Quick clinical approach: (1) check A-a gradient; (2) if normal → hypoventilation or altitude; (3) if elevated → shunt, V/Q mismatch, or diffusion; (4) give 100% O₂: corrects V/Q mismatch but NOT true shunt.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','medium','flashcard','How are partial pressures of gases calculated and what is Dalton''s law?','["Dalton''s law: in a gas mixture, each gas exerts its own partial pressure independently of others. Partial pressure = fractional concentration × total pressure. At sea level (PB = 760 mmHg, PH₂O = 47 mmHg at body temperature): PO₂ (inspired) = 0.21 × (760 − 47) = 149.7 mmHg; PCO₂ (inspired) = 0.0003 × 713 ≈ 0.23 mmHg; PN₂ (inspired) ≈ 563 mmHg. Water vapour pressure must be subtracted from total pressure before calculating alveolar gas values."]','A','Water vapour pressure at body temperature (37°C) is always 47 mmHg regardless of altitude — it fully saturates inspired air in the airways. This is why altitude reduces PAO₂ more than expected from barometric pressure alone.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','hard','flashcard','Explain how pulmonary oedema impairs gas exchange via multiple mechanisms.','["Pulmonary oedema impairs gas exchange by: (1) Increasing diffusion distance — alveolar fluid and interstitial fluid widen the diffusion path for O₂; (2) Reducing functional alveolar surface area — fluid-filled alveoli cannot participate in gas exchange (shunt, V/Q = 0); (3) Reducing compliance — fluid-filled alveoli require higher inflation pressures, increasing work of breathing; (4) Stimulating J-receptors — causing tachypnoea and dyspnoea; (5) Promoting atelectasis — surfactant dilution in oedema fluid reduces surface tension maintenance."]','A','In cardiogenic pulmonary oedema: raised pulmonary capillary wedge pressure forces fluid through the Starling mechanism. In non-cardiogenic (ARDS): increased permeability floods alveoli with protein-rich exudate. Both create diffuse bilateral opacification and severe hypoxaemia.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','hard','flashcard','Why is CO₂ elimination rarely impaired by diffusion limitation, while O₂ often is?','["CO₂ is ~24 times more soluble in tissue fluid than O₂, giving it a diffusion coefficient ~20 times greater (Fick''s law: D ∝ solubility/√mol.wt). Therefore CO₂ equilibrates across the respiratory membrane ~20× faster. Even with doubled membrane thickness (fibrosis), CO₂ equilibrates in a fraction of the 0.75-second transit time. O₂, being less soluble and having a lower pressure gradient, is more vulnerable to diffusion limitation when membrane thickness increases or transit time shortens."]','A','Clinical consequence: in early/moderate interstitial lung disease, PaCO₂ is often normal or low (from hyperventilation) while PaO₂ is impaired. CO₂ retention due to diffusion limitation alone is essentially never seen; CO₂ retention implies hypoventilation or severe V/Q mismatch.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','hard','flashcard','A patient with hepatopulmonary syndrome (HPS) has PaO₂ that improves minimally with 100% O₂. What is the mechanism of hypoxaemia?','["HPS is characterised by intrapulmonary vascular dilatations (IPVDs) — dilated pulmonary capillaries (up to 100 µm diameter vs normal 7–15 µm). Three mechanisms of hypoxaemia: (1) Diffusion limitation — O₂ cannot reach red cells in the centre of dilated capillaries; (2) True shunt — some IPVDs are arteriovenous-like connections (V/Q = 0); (3) V/Q mismatch — non-uniform perfusion. The shunt component explains poor response to 100% O₂ (orthodeoxia — PaO₂ falls on standing as basilar IPVDs open more with upright posture)."]','A','Orthodeoxia + platypnoea (dyspnoea worse sitting up, better lying down) is the hallmark of HPS — the opposite of most pulmonary conditions. Liver transplantation reverses HPS as portal hypertension resolves.','universal',true,'{year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','hard','flashcard','How does anaemia differ from hypoxaemia in terms of O₂ delivery and tissue hypoxia?','["Hypoxaemia: reduced PaO₂ and SaO₂ → reduced O₂ content (CaO₂); both dissolved and Hb-bound O₂ reduced; A-a gradient may be elevated. Anaemia: normal PaO₂ and SaO₂ (normal gas exchange); reduced CaO₂ due to reduced Hb concentration → reduced O₂ delivery (DO₂ = CO × CaO₂). In anaemia, the O₂-Hb curve is normal, so Hb is fully saturated. Tissue hypoxia occurs from reduced O₂ delivery, not impaired gas exchange. DLCO is normal in anaemia."]','A','Key distinction: pulse oximetry (SpO₂) is NORMAL in anaemia (Hb is fully saturated). SpO₂ measures % saturation, not content. A patient can have normal SpO₂ but severely reduced O₂ delivery. Hb level must be checked separately.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

output = ',\n'.join(rows) + ','
with open('/sessions/keen-ecstatic-cannon/mnt/Skoolie/scripts/med_resp_ap_fc.sql', 'a') as f:
    f.write(output + '\n')
print(f"FC Part 2 written: {len(rows)} rows (subtopics 4-5)")
