rows = []

# ============================================================
# SUBTOPIC 6: Oxygen Transport (10 Flashcards)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','easy','flashcard','Describe the shape of the oxygen-haemoglobin dissociation curve and its physiological significance.','["The O₂-Hb dissociation curve is sigmoid (S-shaped) due to cooperative binding (binding of one O₂ increases affinity for subsequent O₂ molecules — allosteric transition from T-state to R-state). Key points: PO₂ 100 mmHg → SaO₂ ~98%; PO₂ 60 mmHg → SaO₂ ~90% (steep decline begins here); PO₂ 40 mmHg → SaO₂ ~75% (mixed venous). The flat upper portion stabilises arterial SaO₂ despite moderate falls in PaO₂ (protective); the steep lower portion enables efficient O₂ unloading at tissues."]','A','The threshold at PO₂ 60 mmHg (SaO₂ 90%) is clinically critical — below this, SaO₂ falls steeply. O₂ therapy targets PaO₂ >60 mmHg to remain on the safe, flat part of the curve. SpO₂ <90% requires urgent intervention.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','easy','flashcard','What is oxygen delivery (DO₂) and how is it calculated?','["DO₂ = CO × CaO₂, where CO = cardiac output (~5 L/min), CaO₂ = arterial O₂ content = (1.34 × Hb × SaO₂) + (0.003 × PaO₂). Normal: DO₂ = 5 × 20 ml/dl = 1000 ml/min. Normal VO₂ = 250 ml/min, so O₂ extraction ratio ≈ 25% (considerable reserve). DO₂ is reduced by: low CO (cardiogenic shock), low Hb (anaemia), low SaO₂ (respiratory failure), or any combination."]','A','The three pillars of O₂ delivery: Pump (cardiac output), Pipe (haemoglobin), and P (PO₂/SaO₂). To optimise O₂ delivery in shock: fluids/inotropes (CO), transfusion (Hb), supplemental O₂ (SaO₂).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','medium','flashcard','List the factors that shift the O₂-Hb dissociation curve to the right (decreased affinity) and explain their physiological benefit.','["Rightward shift (increased P50, decreased O₂ affinity — promotes O₂ release to tissues): (1) Increased PCO₂ (Bohr effect); (2) Decreased pH / increased H⁺ (Bohr effect); (3) Increased temperature; (4) Increased 2,3-DPG. These factors are all elevated in metabolically active tissues — so Hb releases O₂ precisely where it is most needed. In pulmonary capillaries, the reverse applies (lower PCO₂, higher pH → leftward shift → favours O₂ loading)."]','A','Memory: ''CADET face RIGHT'' — CO₂, Altitude adaptations (2,3-DPG), DEcrease in pH, Temperature. The Bohr effect is a 2-for-1 benefit: tissues generate CO₂ and H⁺, both of which shift the curve rightward, enhancing O₂ delivery to those very tissues.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','medium','flashcard','Explain the pathophysiology and management of carbon monoxide (CO) poisoning.','["CO binds haemoglobin with ~240× greater affinity than O₂, forming COHb. Mechanisms of toxicity: (1) Reduces O₂-carrying capacity (COHb cannot carry O₂); (2) Leftward shift of O₂-Hb curve (remaining oxyHb holds O₂ more tightly → impaired tissue O₂ release); (3) Binds cytochrome c oxidase (inhibits mitochondrial respiration). Management: 100% O₂ (reduces COHb half-life from ~5h in room air to ~60–90 min); hyperbaric O₂ (reduces half-life to ~20–30 min) for severe poisoning."]','A','Beware: pulse oximetry cannot distinguish COHb from OHb — SpO₂ appears normal despite life-threatening poisoning. Must use CO-oximetry (arterial blood gas with co-oximeter) to measure COHb directly.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','medium','flashcard','What is the role of 2,3-DPG in oxygen transport?','["2,3-Diphosphoglycerate (2,3-DPG) is produced by RBCs via the Rapoport-Luebering shunt of glycolysis. It binds preferentially to deoxy-Hb (in the central cleft between beta chains), stabilising the deoxy (T) state and reducing O₂ affinity (rightward shift, ↑P50). Increased in: chronic hypoxaemia, anaemia, high altitude, hyperthyroidism. Decreased in: banked blood (after 2–3 weeks), hypothyroidism, acidosis (acutely)."]','A','Banked blood loses 2,3-DPG over time → stored blood may not release O₂ efficiently to tissues immediately after transfusion. 2,3-DPG levels normalise within 24 hours of transfusion as RBC metabolism restores normal levels.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','medium','flashcard','Compare adult haemoglobin (HbA) and foetal haemoglobin (HbF) in terms of structure and O₂ affinity.','["HbA: 2α + 2β chains; P50 ≈ 27 mmHg; binds 2,3-DPG in β-chain cleft. HbF: 2α + 2γ chains; P50 ≈ 20 mmHg (leftward shift); γ chains bind 2,3-DPG less avidly → less 2,3-DPG effect → higher O₂ affinity. HbF''s higher O₂ affinity allows the fetus to extract O₂ from maternal blood across the placenta (maternal O₂-Hb curve dissociates at placental PO₂ ~50 mmHg, loading onto HbF)."]','A','Double Bohr effect: at the placenta, maternal HbA releases CO₂ → maternal blood becomes more alkaline (leftward shift, less O₂ release — actually helps). Fetal CO₂ enters maternal blood → favours maternal O₂ release; fetal Hb loads O₂. This elegant system maximises placental O₂ transfer.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','hard','flashcard','A patient has PaO₂ = 95 mmHg, SaO₂ = 98%, Hb = 5 g/dl. Calculate CaO₂ and DO₂ (CO = 5 L/min). Why is this patient at risk despite normal gas exchange?','["CaO₂ = (1.34 × 5 × 0.98) + (0.003 × 95) = 6.57 + 0.29 = 6.86 ml/dl (~7 ml/dl). Normal CaO₂ ≈ 20 ml/dl. DO₂ = 5 L/min × 70 ml/L = 350 ml/min. Normal DO₂ ≈ 1000 ml/min. Normal VO₂ ≈ 250 ml/min — O₂ delivery is barely above consumption. Any increase in O₂ demand (fever, exertion) will cause tissue hypoxia despite normal SpO₂ and PaO₂."]','A','This illustrates that normal SpO₂ (and PaO₂) does NOT exclude life-threatening tissue hypoxia in severe anaemia. Mixed venous O₂ saturation (SvO₂) would be very low, indicating near-maximal O₂ extraction. Transfusion is indicated.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','hard','flashcard','Describe the biochemical mechanism of the Bohr effect at the molecular level.','["The Bohr effect occurs because CO₂ and H⁺ bind to specific sites on deoxyhaemoglobin and stabilise the T (tense/deoxy) state. (1) CO₂ reacts with N-terminal amino groups of α and β chains to form carbamino compounds (–NHCOO⁻), which form salt bridges stabilising T-state. (2) H⁺ binds histidine residues (especially His146 of β-chains) in T-state, raising pKa of these residues. Both effects reduce O₂ affinity, facilitating O₂ release in acidic, CO₂-rich tissues."]','A','This allosteric mechanism links tissue metabolic activity directly to haemoglobin O₂ affinity — the more a tissue metabolises (producing CO₂ and H⁺), the more Hb releases O₂ to that tissue. It is a classic example of physiological elegance.','universal',false,'{year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','hard','flashcard','What is cyanosis, and when does it appear clinically?','["Cyanosis is a bluish discolouration of skin and mucous membranes due to increased reduced (deoxygenated) haemoglobin in capillary blood. Central cyanosis: reduced SaO₂ → reduced Hb throughout circulation; best seen on tongue and mucous membranes. Peripheral cyanosis: increased O₂ extraction in periphery (poor perfusion); warm central areas (tongue) are normal. Cyanosis becomes clinically detectable when absolute deoxyHb ≥ 5 g/dl in capillary blood."]','A','Key caveat: cyanosis is absent in anaemia (insufficient total Hb to reach 5 g/dl deoxyHb — even fully desaturated Hb in anaemia may only be 3–4 g/dl). Conversely, polycythaemia can cause cyanosis at relatively high SaO₂. Cyanosis is an unreliable marker of O₂ status — always check SpO₂ and/or ABG.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','hard','flashcard','Explain the concept of O₂ supply dependency and critical DO₂ in shock states.','["Normally, O₂ consumption (VO₂) is independent of O₂ delivery (DO₂) above a critical threshold (DO₂ ~300 ml/min) — tissues increase O₂ extraction as DO₂ falls (O₂ extraction ratio rises from 25% to up to 75%). Below the critical DO₂, tissues cannot extract enough O₂ → VO₂ falls with DO₂ (O₂ supply dependency) → anaerobic metabolism → lactic acidosis. In sepsis/ARDS, the critical DO₂ may be elevated and extraction may be impaired (pathological supply dependency)."]','A','Clinical target: maintain DO₂ > critical threshold by optimising CO (fluids, inotropes), Hb (transfusion target varies by context), and SaO₂ (supplemental O₂). Mixed venous SvO₂ < 65% suggests inadequate DO₂ relative to VO₂.','universal',true,'{year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 7: CO2 Transport & Acid-Base (10 Flashcards)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','easy','flashcard','Summarise the three forms of CO₂ transport in blood and their proportions.','["(1) Dissolved CO₂ in plasma: ~7–10% (CO₂ is more soluble than O₂ — 0.03 mmol/L/mmHg); (2) Carbamino compounds (CO₂ bound to amine groups of Hb and plasma proteins): ~20–23%, especially deoxy-Hb (Haldane effect); (3) Bicarbonate (HCO₃⁻): ~70% — formed in RBCs by carbonic anhydrase (CO₂ + H₂O ↔ H₂CO₃ ↔ HCO₃⁻ + H⁺), HCO₃⁻ exits via AE1 exchanger (chloride shift)."]','A','Mnemonic: ''70-23-7'' — HCO₃⁻ (70%), Carbamino (23%), dissolved (7%). The Haldane effect means more CO₂ is carried in the venous (deoxygenated) form — deoxygenation in tissues promotes CO₂ loading; oxygenation in lungs promotes CO₂ offloading.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','easy','flashcard','Define the bicarbonate buffer system and the Henderson-Hasselbalch equation.','["The bicarbonate buffer system: CO₂ + H₂O ↔ H₂CO₃ ↔ H⁺ + HCO₃⁻. Henderson-Hasselbalch: pH = 6.1 + log([HCO₃⁻] / 0.03 × PCO₂). At normal values: pH = 6.1 + log(24 / 0.03 × 40) = 6.1 + log(24/1.2) = 6.1 + log(20) = 6.1 + 1.30 = 7.40. Lungs control PCO₂ (rapidly, seconds-minutes); kidneys control HCO₃⁻ (slowly, hours-days)."]','A','The ratio [HCO₃⁻] / (0.03 × PCO₂) determines pH — it must equal 20 for pH 7.40. Any acid-base disturbance can be understood as a change in this ratio. Compensation always moves the ratio back toward 20.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','medium','flashcard','Explain the Haldane effect and its physiological role in CO₂ transport.','["The Haldane effect: deoxygenated haemoglobin (deoxy-Hb) carries more CO₂ than oxygenated Hb, by two mechanisms: (1) Deoxy-Hb is a better buffer (accepts H⁺ generated during HCO₃⁻ formation); (2) Deoxy-Hb''s amino groups bind CO₂ more readily as carbamino compounds. In peripheral tissues: Hb deoxygenates → CO₂ loading facilitated. In pulmonary capillaries: Hb oxygenates → H⁺ released → shifts HCO₃⁻ back to CO₂ for exhalation; carbamino-CO₂ released."]','A','The Haldane and Bohr effects are complementary: Bohr effect promotes O₂ unloading in tissues; Haldane effect promotes CO₂ loading in tissues. Both are reversed in the lungs to optimise gas exchange.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','medium','flashcard','Describe the systemic and renal compensation for respiratory acidosis.','["Respiratory acidosis: primary ↑PaCO₂ → ↓pH. Immediate buffering: H⁺ is buffered intracellularly by proteins and phosphates, raising HCO₃⁻ slightly (~1 mEq/L per 10 mmHg ↑PCO₂). Chronic renal compensation (2–5 days): kidneys ↑H⁺ secretion (via H⁺-ATPase and H⁺-K⁺-ATPase in collecting duct), ↑HCO₃⁻ reabsorption, ↑ammoniagenesis → HCO₃⁻ rises ~3.5 mEq/L per 10 mmHg ↑PCO₂. pH moves toward (rarely to) normal."]','A','In COPD with chronic hypercapnia, expected HCO₃⁻ = 24 + 3.5 × [(PaCO₂ − 40)/10]. If HCO₃⁻ is higher than expected, suspect concurrent metabolic alkalosis (e.g., diuretics). If lower, suspect concurrent metabolic acidosis.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','medium','flashcard','How does the respiratory system compensate for metabolic acidosis?','["Metabolic acidosis: primary ↓HCO₃⁻ → ↓pH. H⁺ stimulates peripheral and central chemoreceptors → hyperventilation → ↓PaCO₂ → ↑pH (moves ratio back toward 20). Kussmaul breathing (deep, rapid) is the clinical manifestation (e.g., diabetic ketoacidosis). Expected respiratory compensation (Winter''s formula): PaCO₂ = 1.5 × [HCO₃⁻] + 8 (± 2). Compensation begins within minutes, maximally complete in 12–24 hours."]','A','Winter''s formula is clinically essential. If actual PaCO₂ is HIGHER than predicted: concurrent respiratory acidosis. If LOWER than predicted: concurrent respiratory alkalosis. Never over-compensate to alkalosis — this is a limit.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','medium','flashcard','Explain the acid-base changes and mechanism in metabolic alkalosis from vomiting.','["Vomiting causes loss of HCl from the stomach → loss of H⁺ and Cl⁻ from the body. Direct effect: ↑plasma HCO₃⁻ (for each H⁺ lost, one HCO₃⁻ remains) → ↑pH → metabolic alkalosis. Respiratory compensation: hypoventilation → ↑PaCO₂ (expected: PaCO₂ = 40 + 0.7 × [ΔHCO₃⁻]). Renal: normally rapidly excretes excess HCO₃⁻, BUT: volume depletion (from vomiting) → angiotensin II/aldosterone → avid NaCl reabsorption → H⁺ secretion maintained to reabsorb Na⁺ (contraction alkalosis perpetuated)."]','A','Paradoxical aciduria: despite metabolic alkalosis, urine pH may be acidic because kidneys prioritise volume (Na⁺/H₂O) over pH balance. Treatment: IV normal saline (restores Cl⁻ and volume, allowing kidney to excrete HCO₃⁻).','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','hard','flashcard','Explain why giving high-flow O₂ to a COPD patient with chronic CO₂ retention can worsen hypercapnia.','["In chronic COPD with CO₂ retention, central chemoreceptors are reset to the elevated PaCO₂ baseline. The remaining ventilatory drive comes from: (1) Hypoxic drive (peripheral carotid body chemoreceptors responding to low PaO₂); (2) The Haldane effect — O₂ therapy reverses the Haldane effect, displacing CO₂ from Hb back into plasma, raising PaCO₂ (''Haldane effect-mediated hypercapnia''); (3) Relieving HPV in hypoventilated areas → more blood to those units → V/Q worsens. Correcting hypoxia too rapidly removes the peripheral drive."]','A','Target SpO₂ 88–92% in COPD patients with known or suspected CO₂ retention (BTS guidelines). Use controlled O₂ (24–28% Venturi mask). The Haldane effect may account for more of the rise in PaCO₂ than removal of hypoxic drive in some patients.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','hard','flashcard','What is the anion gap and how does it help classify metabolic acidosis?','["Anion gap (AG) = Na⁺ − (Cl⁻ + HCO₃⁻). Normal = 8–12 mEq/L (unmeasured anions: albumin, phosphate, sulphate, organic acids). Elevated AG metabolic acidosis (MUDPILES): Methanol, Uraemia, Diabetic ketoacidosis, Paracetamol/Propylene glycol, Iron/Isoniazid, Lactic acidosis, Ethylene glycol, Salicylates. Normal AG metabolic acidosis (hyperchloraemic): diarrhoea (HCO₃⁻ loss), RTA, fistulae, acetazolamide. Respiratory acidosis does NOT elevate the AG."]','A','Albumin correction: For every 1 g/dl fall in albumin below 4 g/dl, subtract 2.5 from the normal AG. In hypoalbuminaemia, a ''normal'' AG may actually represent a masked elevated AG metabolic acidosis (e.g., sepsis with hypoalbuminaemia).','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','hard','flashcard','Explain the buffering role of haemoglobin in blood pH regulation.','["Haemoglobin is the most important non-bicarbonate buffer in blood, accounting for ~80% of non-bicarbonate buffering capacity. Mechanism: Hb has multiple ionisable histidine residues (pKa ~6.5–8.0) that can accept or donate H⁺ over the physiological pH range. Key property: deoxy-Hb (pKa of His146β ~8.0) is a better proton acceptor than oxy-Hb (pKa ~6.7). When Hb deoxygenates in tissues, it accepts H⁺ generated during CO₂→HCO₃⁻ conversion, buffering the pH fall."]','A','This is the molecular basis of the Haldane effect''s buffering component. Hb buffering is instantaneous (unlike renal compensation taking days) and is why patients with severe anaemia have reduced buffering capacity and are more vulnerable to rapid pH swings.','universal',false,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','hard','flashcard','How does acute mountain sickness (AMS) relate to respiratory alkalosis and cerebral effects?','["At high altitude: low PaO₂ → peripheral chemoreceptor stimulation → hyperventilation → ↓PaCO₂ → respiratory alkalosis. Brain effects: (1) Alkalosis causes cerebral vasoconstriction (CO₂ normally vasodilates cerebral vessels) → reduced cerebral blood flow → headache, dizziness; (2) Simultaneously, hypoxia causes cerebral vasodilation. Net effect is complex, but AMS = headache + ≥1 of: fatigue, dizziness, nausea, sleep disturbance. HACE (high altitude cerebral oedema) is life-threatening — cerebral oedema from BBB disruption."]','A','Treatment of AMS: descent (definitive), dexamethasone (reduces cerebral oedema), acetazolamide (promotes acclimatisation by renal HCO₃⁻ excretion, acidifying plasma → stimulates ventilation). Portable hyperbaric bags (Gamow bags) can temporise in the field.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

output = ',\n'.join(rows) + ','
with open('/sessions/keen-ecstatic-cannon/mnt/Skoolie/scripts/med_resp_ap_fc.sql', 'a') as f:
    f.write(output + '\n')
print(f"FC Part 3 written: {len(rows)} rows (subtopics 6-7)")
