rows = []

# ============================================================
# SUBTOPIC 8: V/Q Matching & Pulmonary Blood Flow (10 Flashcards)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','easy','flashcard','Describe West''s three zones of the lung and the pressure relationships in each.','["Zone 1 (apex): PA > Pa > Pv — alveolar pressure exceeds arterial pressure; capillaries collapsed; no flow (alveolar dead space). Zone 2 (mid): Pa > PA > Pv — arterial pressure exceeds alveolar; intermittent flow proportional to Pa−PA; Starling resistor (waterfall effect). Zone 3 (base): Pa > Pv > PA — both arterial and venous pressures exceed alveolar; continuous flow throughout cardiac cycle; flow = Pa−Pv. PA = alveolar pressure, Pa = pulmonary arterial pressure, Pv = pulmonary venous pressure."]','A','Memory: In Zone 1 — All Pressure from Air wins; Zone 2 — Arterial overcomes Alveolar; Zone 3 — all pressures exceed Alveolar so flow is continuous. Zone 4 exists at very high lung volumes (interstitial pressure compresses extra-alveolar vessels).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','easy','flashcard','Explain hypoxic pulmonary vasoconstriction (HPV) — mechanism, stimulus, and benefit.','["HPV is a unique response of the pulmonary vasculature: low alveolar PO₂ (PAO₂ < ~70 mmHg) causes adjacent pulmonary arterioles to constrict. Mechanism: hypoxia inhibits voltage-gated K⁺ channels in pulmonary arterial smooth muscle cells → membrane depolarisation → L-type Ca²⁺ channel opening → vasoconstriction. Also involves ROS, endothelin-1. Physiological benefit: diverts blood from poorly ventilated (low V/Q) alveoli to better-ventilated regions, optimising V/Q matching."]','A','HPV is the OPPOSITE of the systemic response (where hypoxia causes vasodilation). This is physiologically perfect: pulmonary circulation routes blood to where O₂ is; systemic circulation routes blood to where O₂ is needed. Anaesthetic agents, calcium channel blockers, and nitric oxide inhibit HPV, worsening V/Q mismatch.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','medium','flashcard','How does pulmonary arterial hypertension (PAH) develop in chronic lung disease and what are its consequences?','["Chronic hypoxia (COPD, ILD, altitude) → sustained HPV → smooth muscle hypertrophy and intimal proliferation in pulmonary arterioles → fixed elevated PVR → PAH (mean PA pressure >25 mmHg at rest). Consequences: (1) Increased RV afterload → RV hypertrophy → cor pulmonale; (2) RV dilation → D-shaped interventricular septum (shifts toward LV) → impaired LV filling → reduced cardiac output; (3) Tricuspid regurgitation; (4) Right heart failure → oedema, ascites, raised JVP."]','A','''Cor pulmonale'' = RV failure due to lung disease (not LV failure). Signs: raised JVP, peripheral oedema, hepatomegaly, parasternal heave, loud P2, tricuspid regurgitation murmur. ECG: right axis deviation, right bundle branch block, P pulmonale.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','medium','flashcard','Why is the V/Q ratio highest at the lung apex and lowest at the base in an upright person?','["Both ventilation (V) and perfusion (Q) increase from apex to base in the upright lung due to gravity. However, perfusion increases more steeply (~5-fold apex to base) than ventilation (~2–3 fold apex to base). At the apex: low Q relative to V → high V/Q (~3.3). At the base: high Q relative to V → low V/Q (~0.6). The perfusion gradient is steeper because pulmonary arterial pressure is relatively low, making it more susceptible to gravitational pressure differences."]','A','Consequence: apical alveoli have high PAO₂ (~130 mmHg) and low PACO₂ (~28 mmHg) — near inspired air composition. Basal alveoli have lower PAO₂ (~89 mmHg) and higher PACO₂ (~42 mmHg). The overall arterial blood is a weighted average (perfusion-weighted), so it resembles basal blood more.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','medium','flashcard','Describe the Starling forces governing fluid exchange in pulmonary capillaries and how oedema develops.','["Starling equation: Net filtration = Kf[(Pc − Pi) − σ(πc − πi)], where Pc = capillary hydrostatic pressure (~8 mmHg), Pi = interstitial hydrostatic pressure (~−8 mmHg), πc = capillary oncotic pressure (~28 mmHg), πi = interstitial oncotic pressure (~14 mmHg). Net: slight filtration from capillary to interstitium → drained by lymphatics. Oedema occurs when: (1) Pc rises (left heart failure, ARDS); (2) πc falls (hypoalbuminaemia); (3) Capillary permeability ↑ (ARDS, infection); (4) Lymphatic obstruction."]','A','In cardiogenic pulmonary oedema: PCWP > 18 mmHg → hydrostatic oedema (low-protein fluid). In ARDS/non-cardiogenic: normal PCWP but ↑capillary permeability → high-protein exudate. Distinguishing is critical for management.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','medium','flashcard','What are the consequences of one-lung ventilation (OLV) during thoracic surgery for V/Q matching?','["During OLV (e.g., lobectomy/pneumonectomy), the operative (non-ventilated) lung collapses → V = 0 → V/Q = 0 → blood passing through creates a true right-to-left shunt. This shunt fraction can be 20–30% of cardiac output. Compensating mechanisms: (1) HPV in the non-ventilated lung reduces blood flow to it; (2) Lateral decubitus position (operative lung up) reduces its perfusion by gravity; (3) Clamping the operative pulmonary artery (if done early) eliminates the shunt."]','A','HPV is the key protective mechanism during OLV. Drugs inhibiting HPV (volatile anaesthetics, Ca²⁺-channel blockers) worsen hypoxaemia during OLV. TIVA (total intravenous anaesthesia with propofol) preserves HPV better than volatile agents and may improve OLV oxygenation.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','hard','flashcard','Explain how prone positioning improves oxygenation in ARDS.','["In ARDS (supine): dorsal lung regions are dependent → compressive atelectasis from mediastinum and abdominal viscera → V/Q = 0 → shunt. Ventral regions are non-dependent → aerated but over-distended. In prone position: (1) Dorsal (now non-dependent) regions re-aerate and recruit; (2) Ventral (now dependent) regions partially collapse — but these were already aerated, so overall V/Q mismatch and shunt decrease; (3) Perfusion redistributes more evenly; (4) Secretion drainage improves; (5) Functional recruitment increases EELV."]','A','PROSEVA trial (2013): >16 hours/day prone positioning in severe ARDS (P/F < 150) reduced 28-day mortality from 32.8% to 16.0% (p<0.001). Prone positioning is now standard of care for severe ARDS. Contraindications: unstable spinal injuries, open abdomen, facial fractures.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','hard','flashcard','How does nitric oxide (NO) selectively vasodilate perfused pulmonary vessels and improve V/Q matching?','["Inhaled NO is a selective pulmonary vasodilator. It diffuses from alveoli into the adjacent pulmonary arteriolar smooth muscle → activates guanylyl cyclase → ↑cGMP → smooth muscle relaxation → vasodilation. Crucially, NO only reaches arterioles adjacent to VENTILATED alveoli (it is inhaled with air). Non-ventilated lung units receive no NO → HPV is preserved in those areas. This selectively increases perfusion to ventilated areas, improving V/Q matching without systemic vasodilation (NO is inactivated by Hb in the bloodstream)."]','A','Inhaled NO improves oxygenation in ARDS and primary PAH. However, it has not shown mortality benefit in ARDS trials (possibly because it causes methemoglobinaemia at high doses and rebound vasoconstriction when stopped). Used as a bridge to other therapies.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','hard','flashcard','Describe the haemodynamic consequences of a massive pulmonary embolism on the right ventricle.','["Massive PE (>50% pulmonary artery obstruction): acute rise in PVR → acute RV pressure overload → RV dilation → RV wall stress ↑ → myocardial ischaemia (RCA compression + increased O₂ demand) → RV failure. LV effects: (1) Reduced pulmonary venous return → reduced LV preload → low CO + hypotension; (2) Interventricular septal shift (D-sign) further impairs LV filling. McConnell''s sign on echo: RV free wall hypokinesia with apical sparing (relatively specific for PE)."]','A','Massive PE management: systemic thrombolysis (alteplase 100 mg over 2 hours) if no contraindications; surgical embolectomy or catheter-directed thrombolysis if thrombolysis contraindicated. Vasopressors (norepinephrine) for hypotension; AVOID aggressive fluids (worsen RV dilation).','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','hard','flashcard','What is hepatopulmonary syndrome (HPS) and how does it produce V/Q mismatch?','["HPS: a triad of (1) liver disease/portal hypertension; (2) intrapulmonary vascular dilatations (IPVDs); (3) hypoxaemia. Mechanism: portal hypertension → increased NO production (via bacterial translocation stimulating NOS in pulmonary vasculature) → pulmonary vascular dilatation. IPVDs create shunt (V/Q = 0 for AV connections) and diffusion limitation (O₂ cannot reach RBCs in dilated, wide capillaries). Clinical hallmark: orthodeoxia (PaO₂ falls on standing — basilar IPVDs worsen; improves supine)."]','A','Confirmed by: contrast echocardiography (bubbles appear in left heart after >3 beats in right heart — normal passage is <3 beats). Treatment: liver transplantation is the only definitive cure. Supplemental O₂ and TIPS may temporarily improve oxygenation.','universal',true,'{year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 9: Control of Breathing (10 Flashcards)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','easy','flashcard','Describe the organisation of the respiratory control centres in the brainstem.','["Medulla: (1) Dorsal Respiratory Group (DRG) — in nucleus tractus solitarius (NTS); houses pre-Bötzinger complex (rhythmogenic pacemaker); drives inspiratory activity via phrenic and intercostal motor neurons. (2) Ventral Respiratory Group (VRG) — active during forceful breathing; controls accessory muscle recruitment and abdominal/expiratory muscles. Pons: (1) Pneumotaxic centre (nucleus parabrachialis, upper pons) — limits inspiration, increases RR. (2) Apneustic centre (lower pons) — prolongs inspiration (normally overridden by pneumotaxic centre)."]','A','Memory: ''PAD'' from bottom to top: Pre-Bötzinger/DRG (medulla), Apneustic (lower pons), pneumotaxic centre at the top of the Pons. Cerebral cortex overrides automatic control (voluntary breath-holding, voluntary hyperventilation).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','easy','flashcard','What do central chemoreceptors respond to, and where are they located?','["Central chemoreceptors are located on the ventrolateral surface of the medulla (near the chemosensitive area). They respond to changes in H⁺ concentration of cerebrospinal fluid (CSF). CO₂ crosses the blood-brain barrier (BBB) freely; in CSF it forms H₂CO₃ → H⁺ + HCO₃⁻ (via carbonic anhydrase). The resulting fall in CSF pH stimulates the chemoreceptors → increased ventilation. They do NOT directly sense PO₂. They account for ~70% of the ventilatory response to CO₂."]','A','The BBB is relatively impermeable to H⁺ and HCO₃⁻ but freely permeable to CO₂. This is why CO₂ is a more potent stimulus to ventilation than systemic metabolic acidosis (H⁺ cannot cross the BBB rapidly). Over 24–48 hours, CSF HCO₃⁻ can change to partially normalise CSF pH.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','medium','flashcard','Describe the peripheral chemoreceptors — location, sensing mechanism, and stimuli.','["Location: carotid bodies (at common carotid artery bifurcation; transmit via CN IX glossopharyngeal → NTS) and aortic bodies (near aortic arch; transmit via CN X vagus → NTS). Carotid bodies dominate in humans. Sensing: Type I (glomus) cells sense low PaO₂, high PaCO₂, and low pH; depolarise via inhibited K⁺ channels → release dopamine/acetylcholine → activate afferent nerve. Stimuli by potency: PaCO₂ rise > pH fall > PaO₂ fall (PaO₂ must fall below ~60 mmHg for significant stimulation)."]','A','Key distinction: peripheral chemoreceptors are responsible for the ENTIRE ventilatory response to hypoxia (central chemoreceptors do not sense O₂). In bilateral carotid body resection (e.g., for glomus tumour), the hypoxic ventilatory response is abolished but CO₂ response is largely preserved.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','medium','flashcard','What is the ventilatory response to CO₂ and how is it altered by disease and drugs?','["Ventilatory response to CO₂: for each mmHg rise in PaCO₂ above ~37 mmHg, ventilation increases by ~2–3 L/min (approximately linear). This response is mediated 70% by central and 30% by peripheral chemoreceptors. Blunted CO₂ response in: chronic hypercapnia (COPD — CSF HCO₃⁻ adaptation), opioids (reduce central chemoreceptor sensitivity), benzodiazepines, severe hypothyroidism, obesity hypoventilation syndrome (OHS). Enhanced: salicylates (at toxic doses), progesterone."]','A','Opioids and benzodiazepines primarily depress the central CO₂ response — the hallmark of their respiratory toxicity. Naloxone reverses opioid respiratory depression. Progesterone-mediated hyperventilation explains reduced PaCO₂ in pregnancy (~30 mmHg in 3rd trimester).','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','medium','flashcard','Explain the Hering-Breuer inflation reflex and its clinical relevance.','["The Hering-Breuer inflation reflex: as lung volume increases with each breath, slowly adapting stretch receptors (SARs) in airway smooth muscle are activated. Impulses travel via vagus nerve (CN X) afferents to the NTS → inhibit the inspiratory neurons → terminate inspiration (inspiratory off-switch). This prevents excessive lung inflation. In anaesthetised adults and infants, this reflex is prominent. In conscious adults, it plays a minimal role in normal breathing but becomes important with large Vt."]','A','Clinical relevance: (1) Basis of Hering-Breuer-triggered breathing patterns in some ventilators (pressure support ventilation uses flow cycling rather than SAR-based timing). (2) Bilateral vagotomy (or vagal block during thoracic surgery) can cause slow, deep breathing with high Vt.','universal',false,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','medium','flashcard','How does the body control breathing during sleep, and why are some patients at particular risk?','["During NREM sleep: ventilatory drive decreases, PaCO₂ rises slightly (~2–3 mmHg), PaO₂ falls slightly. Upper airway muscle tone decreases, increasing upper airway resistance. During REM sleep: breathing becomes irregular (''REM breathing''); skeletal muscle atonia (including intercostals); breathing maintained mainly by diaphragm; no response to auditory arousal. Patients at risk: severe COPD (reduced respiratory reserve; REM-related desaturation), neuromuscular disease (diaphragm dependence during REM), OHS, and OSA."]','A','Nocturnal non-invasive ventilation (NIV/BiPAP) is indicated in patients with severe nocturnal hypoventilation (e.g., Duchenne muscular dystrophy, severe COPD with nocturnal SpO₂ <88% for >30% of recording time, OHS with PaCO₂ >45 mmHg).','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','hard','flashcard','Explain the neurophysiology of the pre-Bötzinger complex as the respiratory pacemaker.','["The pre-Bötzinger complex (preBötC) is a cluster of interneurons in the ventrolateral medulla (within the VRG) that generates the inspiratory rhythm via intrinsic pacemaker properties (persistent Na⁺ channels, Ca²⁺-activated nonselective cation channels) and network burst activity. Excitatory interneurons within the preBötC excite each other and the inspiratory motor neurons, then burst activity is terminated by inhibitory post-inspiratory neurons and slowly adapting lung stretch receptor feedback. The rhythm is modulated but not generated by pontine centres."]','A','The preBötC was identified by Feldman et al. in 1991. Lesioning the preBötC in animals abolishes breathing. It is intrinsically rhythmic even in brainstem slice preparations in vitro — making it a true pacemaker. Understanding it is key to developing treatments for central apnoea.','universal',false,'{year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','hard','flashcard','Describe the ventilatory control abnormality in obesity hypoventilation syndrome (OHS) and its management.','["OHS: BMI >30 + PaCO₂ >45 mmHg (daytime hypercapnia) in the absence of other causes. Mechanisms: (1) Increased work of breathing (WOB) from obesity-related restriction; (2) Leptin resistance — leptin normally stimulates ventilation via hypothalamic receptors; obese patients have high leptin levels but central resistance; (3) Blunted central chemoreceptor CO₂ response (adaptation to chronic hypercapnia); (4) Coexisting OSA worsening nocturnal hypoventilation. Most develop during sleep first (nocturnal hypoventilation → daytime CO₂ retention)."]','A','Management: Weight loss (definitive); NIV (bilevel PAP/BiPAP) with a backup rate — provides ventilatory support during sleep, reduces nocturnal hypoventilation, and over time can partially restore CO₂ chemosensitivity. Distinguishing OHS from simple OSA on CPAP is important (OHS needs BiPAP, not just CPAP).','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','hard','flashcard','What is the phenomenon of ''post-hyperventilation apnoea'' and why is it dangerous?','["Post-hyperventilation apnoea occurs when deliberate or reflex hyperventilation lowers PaCO₂ well below the ''apnoeic threshold'' (~35 mmHg). If PaCO₂ falls below this threshold, the respiratory drive from central chemoreceptors is eliminated, and breathing stops until PaCO₂ rises back above the threshold. Duration of apnoea depends on how far PaCO₂ fell and the rate of CO₂ production. During the apnoea, if PaO₂ also falls low enough, loss of consciousness (especially during swimming/diving) can cause drowning before CO₂ rises to trigger breathing."]','A','The apnoeic threshold is ~35 mmHg — just below normal resting PaCO₂. During assisted ventilation, if the ventilator drives PaCO₂ below 35, spontaneous breathing is suppressed. This must be considered when transitioning patients from controlled to spontaneous ventilation modes.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','hard','flashcard','How does the body adapt ventilatory control to sustained hypoxia over days (acclimatisation)?','["Day 0: Low PaO₂ → carotid body stimulation → hyperventilation → ↓PaCO₂ → respiratory alkalosis → partially inhibits further ventilation (CSF alkalinity dampens central drive). Days 1–4: Kidneys excrete HCO₃⁻ → CSF and blood pH normalise → central chemoreceptor inhibition removed → peripheral carotid body-driven hyperventilation proceeds unchecked → PaCO₂ falls further (to 30–35 mmHg on high mountains) → PAO₂ rises further. Simultaneously: EPO ↑ → polycythaemia; ↑2,3-DPG; ↑pulmonary diffusing capacity."]','A','The acclimatisation time course explains why mountaineers must ascend slowly. The ventilatory acclimatisation is largely mediated by: (1) carotid body sensitisation (increased O₂-sensing sensitivity); (2) renal HCO₃⁻ excretion allowing sustained hypoxic ventilatory drive. Acetazolamide accelerates renal adaptation.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 10: Respiratory Responses (10 Flashcards)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','easy','flashcard','How does ventilation change during exercise and what are the key controlling mechanisms?','["Three phases: (1) Immediate onset: rapid ↑ventilation within seconds of starting exercise (before blood gas changes) — mediated by cortical irradiation (motor cortex to respiratory centres) and joint/muscle proprioceptors. (2) Moderate exercise: sustained hyperventilation matched to metabolic rate; PaO₂, PaCO₂, and pH remain nearly normal — the oscillations in CO₂ delivery stimulate peripheral chemoreceptors; (3) Heavy exercise (above anaerobic threshold): additional lactic acidosis → H⁺ stimulates chemoreceptors → VE/VCO₂ rises → respiratory compensation; PaCO₂ may fall below 40 mmHg."]','A','During moderate exercise, the precision of V-metabolism matching is remarkable — PaO₂, PaCO₂, and pH are nearly unchanged despite 10–20× increase in ventilation. The mechanism is not fully explained but likely involves CO₂ oscillations and neurogenic stimulation acting in synergy.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','easy','flashcard','Summarise the immediate and delayed physiological adaptations to high altitude.','["Immediate (hours): ↑ventilation (peripheral chemoreceptors); ↑HR and CO; ↑EPO secretion begins; acute mountain sickness may occur. Short-term (days): renal HCO₃⁻ excretion → pH normalises → sustained hyperventilation; ↑2,3-DPG; ↑pulmonary diffusing capacity (capillary recruitment). Long-term (weeks): polycythaemia (↑Hb and haematocrit); RV hypertrophy (from HPV-induced PAH); right shift of O₂-Hb curve (2,3-DPG); chronic HPV → cor pulmonale in those with maladaptation."]','A','Native high-altitude populations (Tibetans, Andeans, Ethiopians) have evolved distinct adaptive strategies: Tibetans maintain lower Hb but higher NO levels; Andeans develop polycythaemia (Monge''s disease); Ethiopians maintain near sea-level PaO₂ via enhanced ventilatory response.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','medium','flashcard','What respiratory changes occur during pregnancy and what is their physiological basis?','["Progesterone directly stimulates the medullary respiratory centres → ↑tidal volume (~40%), ↑alveolar ventilation → ↓PaCO₂ (to ~30 mmHg) → mild respiratory alkalosis → renal HCO₃⁻ excretion → HCO₃⁻ falls to ~20 mEq/L (compensated respiratory alkalosis). FRC decreases (~20%) due to elevated diaphragm from the enlarging uterus. Minute ventilation ↑40%. Oxygen consumption ↑20%. Net: pregnant women have mild respiratory alkalosis, low PaCO₂, and lower FRC."]','A','Clinical importance: (1) ↓FRC means faster desaturation during apnoea (e.g., induction of anaesthesia) — rapid pre-oxygenation essential; (2) Normal PaCO₂ in a pregnant woman is ~30 mmHg — a PaCO₂ of 40 mmHg indicates respiratory failure in pregnancy; (3) Dyspnoea of pregnancy is common and physiological.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','medium','flashcard','Describe the respiratory response to acute metabolic acidosis (e.g., diabetic ketoacidosis).','["Metabolic acidosis → ↑plasma H⁺ → stimulates peripheral chemoreceptors (immediately) and central chemoreceptors (as H⁺ slowly crosses BBB) → hyperventilation (Kussmaul breathing: deep, rapid, laboured respirations) → ↓PaCO₂ → respiratory compensation. Kussmaul breathing can reduce PaCO₂ to 10–15 mmHg in severe acidosis. Winter''s formula: expected PaCO₂ = (1.5 × [HCO₃⁻]) + 8 ± 2. If actual PaCO₂ > predicted: concurrent respiratory acidosis; if < predicted: concurrent respiratory alkalosis."]','A','DKA hallmarks: hyperglycaemia, anion gap metabolic acidosis, ketonaemia/ketonuria, Kussmaul breathing, fruity breath (acetone). Respiratory compensation cannot fully correct pH (limited by minimum PaCO₂ ~10 mmHg); definitive treatment is insulin to stop ketogenesis.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','medium','flashcard','How do the lungs respond to increased CO₂ production during fever?','["Fever increases cellular metabolic rate → ↑CO₂ production (VCO₂). If ventilation does not change, PaCO₂ would rise → respiratory acidosis. In healthy individuals: ↑CO₂ delivery to central and peripheral chemoreceptors → ↑ventilation proportionally → PaCO₂ maintained near 40 mmHg. Additionally, temperature itself activates peripheral chemoreceptors and hypothalamic projections → direct stimulation of respiratory centres. Net effect: tachypnoea proportional to the degree of fever (~increase of 1 breath/min per 1°C rise in temperature)."]','A','The clinical rule of thumb: each 1°C rise in body temperature increases O₂ consumption and CO₂ production by ~10–13%. In patients with limited respiratory reserve (COPD, neuromuscular disease), fever can precipitate hypercapnic respiratory failure — treat the fever aggressively.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','medium','flashcard','What is the respiratory response to acute blood loss (haemorrhagic shock)?','["Acute blood loss → ↓venous return → ↓CO → ↓O₂ delivery → tissue hypoxia → lactic acidosis → ↑H⁺ stimulates peripheral chemoreceptors → hyperventilation → ↓PaCO₂. Simultaneously: ↓perfusion pressure may move lung from Zone 3 to Zone 1/2, increasing alveolar dead space (worsened by tachycardia reducing transit time). Initially: respiratory alkalosis (from hyperventilation). Later: if CO critically low → metabolic lactic acidosis → mixed picture. Zone 1 creation (if pulmonary artery pressure falls below alveolar) worsens gas exchange."]','A','The classic ABG in haemorrhagic shock: initial respiratory alkalosis (compensatory hyperventilation), then metabolic acidosis (lactic acid accumulation), with rising A-a gradient. Aggressive fluid resuscitation restores CO and pulmonary perfusion, but excessive crystalloid causes pulmonary oedema (dilutes albumin, raises hydrostatic pressure).','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','hard','flashcard','Describe the mechanisms and clinical features of high altitude cerebral oedema (HACE).','["HACE = severe end of AMS spectrum. Pathophysiology: Hypoxia → ↓cellular ATP → Na⁺/K⁺-ATPase failure → cytotoxic oedema (intracellular swelling). Simultaneously: vasogenic oedema from BBB disruption (hypoxia-induced VEGF → ↑permeability). HPV raises intracranial venous pressure. ↑CO (from sympathetic activation) may overperfuse cerebral vasculature bypassing impaired autoregulation. Result: cerebral oedema → raised ICP → headache, ataxia, altered consciousness (''ataxia + altered mental status'' is HACE until proven otherwise). Fundoscopy: papilloedema, retinal haemorrhages."]','A','Management: (1) Immediate descent (most effective); (2) Dexamethasone 8 mg loading dose (reduces vasogenic oedema); (3) Supplemental O₂; (4) Portable hyperbaric chamber (Gamow bag). HACE can progress to coma and death within hours. Acetazolamide prevents but does not adequately treat established HACE.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','hard','flashcard','Explain the integrated respiratory response to maximal dynamic exercise and identify the limiting factor in healthy individuals.','["During maximal exercise (VO₂max): (1) Ventilation rises to 100–180 L/min (tachypnoea + ↑Vt); PaCO₂ may fall (respiratory compensation for lactic acidosis); (2) Cardiac output rises to 20–30 L/min (athletes); (3) Pulmonary capillary transit time falls to 0.25 s; (4) DLCO doubles (capillary recruitment, ↑perfusion pressure); (5) O₂ extraction ratio rises from 25% to ~75%. Limiting factor in healthy individuals: cardiac output (O₂ delivery, not pulmonary gas exchange). Elite athletes may show diffusion limitation at maximal intensity (exercise-induced arterial hypoxaemia)."]','A','In patients with lung disease: the respiratory system becomes the limiting factor (ventilatory limitation: breathing reserve used up; PaO₂ falls; PaCO₂ rises). Cardiopulmonary exercise testing (CPET) distinguishes cardiac vs. respiratory vs. deconditioning limits to exercise.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','hard','flashcard','What is the oxygen cascade and how is it affected at high altitude?','["The O₂ cascade: sequential fall in PO₂ from atmosphere to mitochondria. Atmospheric: 159 mmHg (sea level) → Inspired (humidified): 149 mmHg → Alveolar: ~100 mmHg (PAO₂) → Arterial: ~95 mmHg (A-a gradient ~5 mmHg) → Mixed venous/tissue: ~40 mmHg (O₂ extraction) → Mitochondrial: <5 mmHg (sufficient for oxidative phosphorylation). At 5500 m: PB ~380 mmHg; PAO₂ falls to ~45–50 mmHg; arterial PO₂ ~40 mmHg (on steep part of O₂-Hb curve) → SpO₂ ~70–75%. Mitochondrial PO₂ maintains oxidative function until very low levels (~0.5 mmHg critical PO₂)."]','A','The oxygen cascade explains why even small reductions in alveolar ventilation (hypoventilation at altitude) have dramatically amplified effects on tissue PO₂. Each step in the cascade introduces losses — and altitude reduces the starting pressure, magnifying each step''s proportional cost.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','hard','flashcard','Describe the respiratory mechanics and gas exchange changes in ARDS and how they guide ventilator management.','["ARDS: diffuse alveolar damage → ↑capillary permeability → protein-rich exudate fills alveoli → diffuse bilateral consolidation → ↓FRC; ↓CRS (compliance ≤ 40 ml/cmH₂O, normal ~100 ml/cmH₂O); ↑PVR; severe V/Q mismatch and shunt → refractory hypoxaemia (PaO₂/FiO₂ < 300 = ARDS, < 100 = severe). Ventilator strategy (ARDSnet): low Vt (6 ml/kg PBW) to prevent VILI; PEEP to recruit and stabilise alveoli; high FiO₂; permissive hypercapnia acceptable. Plateau pressure < 28 cmH₂O; driving pressure (Pplat − PEEP) < 15 cmH₂O."]','A','The ''baby lung'' concept: in ARDS, only 20–30% of lung is recruitable and normally aerated. Ventilating the whole tidal volume into this small ''baby lung'' causes high alveolar pressure and VILI. Low Vt protects by matching Vt to the available lung volume, not the whole lung weight.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

output = ',\n'.join(rows)
# Last entry needs ); not ,
with open('/sessions/keen-ecstatic-cannon/mnt/Skoolie/scripts/med_resp_ap_fc.sql', 'a') as f:
    f.write(output + '\n);\n')
print(f"FC Part 4 written: {len(rows)} rows (subtopics 8-10)")
