#!/usr/bin/env python3
"""Generate 100 Renal System Pharmacology MCQs."""

mcq_rows = []

YL = "'{year1,year2,year3,year4,year5,year6,practitioner}'"
SRC = "Lippincott Illustrated Reviews Pharmacology 7th Ed"
PROF = '\'{"medicine"}\''
COURSE = 'Medicine'
TOPIC = 'Renal System'
CAT = 'Pharmacology'

def q(subtopic, difficulty, question_text, opts, correct_answer, explanation, high_yield):
    opts_escaped = [o.replace("'", "''") for o in opts]
    opts_json = '["' + '","'.join(opts_escaped) + '"]'
    qt = question_text.replace("'", "''")
    ex = explanation.replace("'", "''")
    st = subtopic.replace("'", "''")
    hy = 'true' if high_yield else 'false'
    return (f"INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, "
            f"question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES\n"
            f"({PROF},'{COURSE}','{TOPIC}','{CAT}','{st}','{difficulty}','mcq','{qt}','{opts_json}',"
            f"'{correct_answer}','{ex}','universal',{hy},{YL},'{SRC}');")

# ─── SUBTOPIC 1: Loop Diuretics ───────────────────────────────────────────────
S1 = "Loop Diuretics"
mcq_rows.append(q(S1,"easy",
    "Furosemide exerts its primary diuretic action by inhibiting which transporter in the nephron?",
    ["A. Na+/Cl- cotransporter in the distal convoluted tubule",
     "B. Na+/K+/2Cl- cotransporter in the ascending loop of Henle",
     "C. Epithelial sodium channel in the collecting duct",
     "D. Na+/K+-ATPase pump in the proximal convoluted tubule"],
    "B",
    "Loop diuretics inhibit the Na+/K+/2Cl- cotransporter (NKCC2) in the thick ascending limb of the loop of Henle, blocking reabsorption of 25-30% of filtered NaCl — the greatest diuretic efficacy of any class.",
    True))

mcq_rows.append(q(S1,"medium",
    "A patient with heart failure is receiving IV furosemide. Which adverse effect is most likely to require potassium supplementation?",
    ["A. Hyperkalemia due to aldosterone antagonism",
     "B. Hypokalemia from increased Na+ delivery to the collecting duct",
     "C. Hypernatremia from free water retention",
     "D. Hypomagnesemia from proximal tubule inhibition"],
    "B",
    "Loop diuretics deliver a heavy Na+ load to the collecting duct, driving increased Na+/K+ exchange and K+ loss. Hypokalemia is the most common electrolyte adverse effect, often requiring supplementation or addition of a K+-sparing diuretic.",
    True))

mcq_rows.append(q(S1,"medium",
    "Which of the following best explains why loop diuretics cause hypercalciuria rather than hypocalciuria?",
    ["A. They inhibit parathyroid hormone secretion",
     "B. They block Na+/K+/2Cl- cotransport, reducing the paracellular driving force for Ca2+ reabsorption in the ascending loop",
     "C. They directly inhibit calcium channels in the distal convoluted tubule",
     "D. They increase aldosterone, which promotes Ca2+ excretion"],
    "C",
    "In the thick ascending loop of Henle, Ca2+ reabsorption is paracellular and driven by the electropositive lumen voltage generated by NKCC2 activity. By inhibiting NKCC2, loop diuretics collapse this driving force, increasing Ca2+ excretion — the opposite of thiazides.",
    True))

mcq_rows.append(q(S1,"hard",
    "A patient with oliguric acute kidney injury (eGFR 12 mL/min/1.73 m2) remains fluid overloaded despite standard IV furosemide doses. Which dosing strategy is most appropriate?",
    ["A. Switch to hydrochlorothiazide, which is effective at low GFR",
     "B. Increase furosemide dose, as higher doses are required to achieve the tubular threshold at low GFR",
     "C. Discontinue all diuretics because they are contraindicated in AKI",
     "D. Switch to spironolactone because it does not require renal secretion"],
    "D",
    "Loop diuretics must reach tubular fluid via proximal tubule secretion to act. In severe renal dysfunction, reduced secretion raises the dose needed to cross the threshold. Higher doses (or continuous infusion) are used. Loop diuretics remain active in AKI and are not contraindicated — they are preferred over thiazides, which lose efficacy at low GFR.",
    True))

mcq_rows.append(q(S1,"easy",
    "Which loop diuretic is considered most appropriate for a patient who requires reliable oral bioavailability?",
    ["A. Furosemide, due to its predictable 60-80% oral bioavailability",
     "B. Ethacrynic acid, due to absence of sulfonamide structure",
     "C. Torsemide, due to reliable oral bioavailability of 80-100%",
     "D. Bumetanide IV only, as oral formulations are unavailable"],
    "A",
    "Torsemide and bumetanide have reliable oral bioavailability of 80-100%, making them preferred for outpatient oral dosing. Furosemide has highly variable bioavailability (10-90%), which can lead to unpredictable diuretic response.",
    True))

mcq_rows.append(q(S1,"medium",
    "A patient taking furosemide develops sudden sensorineural hearing loss after rapid IV administration. Which mechanism best explains this ototoxicity?",
    ["A. Inhibition of cochlear Na+/K+/2Cl- cotransporter in the stria vascularis",
     "B. Blockade of inner ear calcium channels",
     "C. Ototoxicity mediated by direct free radical generation",
     "D. Accumulation of furosemide in the auditory cortex"],
    "B",
    "Loop diuretics inhibit NKCC1 (the isoform expressed in the stria vascularis of the cochlea), disrupting the endocochlear potential. High IV doses or rapid infusion rates pose the greatest risk. Ethacrynic acid is most ototoxic; aminoglycosides potentiate the risk.",
    True))

mcq_rows.append(q(S1,"medium",
    "Which of the following correctly describes the dose-response relationship of loop diuretics?",
    ["A. Linear increase in diuresis proportional to dose with no ceiling effect",
     "B. Sigmoidal curve with a threshold effect, steep rise, and a ceiling effect",
     "C. Flat dose-response because they are low-ceiling diuretics",
     "D. Inverse relationship — higher doses reduce urine output via feedback"],
    "C",
    "Loop diuretics display a sigmoidal dose-response curve with three phases: a threshold below which no diuresis occurs, a steep dose-response phase, and a ceiling above which further dose increases produce no additional diuresis. Clinicians adjust frequency rather than exceeding the ceiling dose.",
    True))

mcq_rows.append(q(S1,"hard",
    "A patient on furosemide for heart failure also takes indomethacin for gout. Which pharmacodynamic interaction is most clinically significant?",
    ["A. Indomethacin inhibits renal prostaglandin synthesis, reducing furosemide efficacy",
     "B. Indomethacin blocks furosemide secretion into the proximal tubule",
     "C. Combined use causes hyperkalemia via aldosterone suppression",
     "D. Indomethacin increases furosemide bioavailability by inhibiting P-glycoprotein"],
    "D",
    "NSAIDs such as indomethacin inhibit renal prostaglandin synthesis. Since prostaglandins contribute to renal blood flow and furosemide partly depends on prostaglandin-mediated vasodilation for its action, NSAIDs blunt loop diuretic efficacy. This is a clinically important drug-drug interaction.",
    True))

mcq_rows.append(q(S1,"easy",
    "Loop diuretics are the diuretics of choice for which of the following clinical scenarios?",
    ["A. Nephrogenic diabetes insipidus",
     "B. Acute pulmonary edema requiring rapid fluid removal",
     "C. Idiopathic hypercalciuria with recurrent kidney stones",
     "D. Mild essential hypertension as first-line therapy"],
    "A",
    "Loop diuretics are the drugs of choice for acute pulmonary edema because of their rapid onset (particularly IV), potent diuretic effect, and acute venodilation that reduces left ventricular filling pressures via enhanced prostaglandin synthesis before diuresis begins.",
    True))

mcq_rows.append(q(S1,"medium",
    "Furosemide is used acutely to treat hypercalcemia. What is the mechanism underlying this effect?",
    ["A. It blocks intestinal calcium absorption",
     "B. It inhibits parathyroid hormone release",
     "C. It increases urinary Ca2+ excretion by blocking paracellular Ca2+ reabsorption in the ascending loop",
     "D. It promotes Ca2+ uptake into bone via osteoblast activation"],
    "B",
    "Loop diuretics increase Ca2+ excretion by blocking the paracellular calcium reabsorption in the ascending limb of Henle (which depends on the lumen-positive voltage driven by NKCC2). Combined with IV saline hydration, furosemide is used to treat hypercalcemia of malignancy.",
    True))

# ─── SUBTOPIC 2: Thiazide Diuretics ──────────────────────────────────────────
S2 = "Thiazide Diuretics"
mcq_rows.append(q(S2,"easy",
    "Hydrochlorothiazide inhibits which transporter to produce its diuretic effect?",
    ["A. Na+/K+/2Cl- cotransporter in the ascending loop of Henle",
     "B. Na+/Cl- cotransporter in the distal convoluted tubule",
     "C. Epithelial sodium channel in the collecting duct",
     "D. Na+/H+ exchanger in the proximal convoluted tubule"],
    "B",
    "Thiazides inhibit the Na+/Cl- cotransporter (NCC) in the distal convoluted tubule, reducing reabsorption of 5-10% of filtered NaCl. They are called 'low-ceiling' diuretics because maximal effect is limited compared to loop diuretics.",
    True))

mcq_rows.append(q(S2,"medium",
    "A patient with hypertension on hydrochlorothiazide develops hyperuricemia and a gout flare. What is the mechanism?",
    ["A. Thiazides directly activate xanthine oxidase, increasing uric acid production",
     "B. Thiazides compete with uric acid for the organic acid secretory system in the proximal tubule",
     "C. Thiazides increase GFR, leading to uric acid filtration and precipitation",
     "D. Thiazides reduce renal blood flow, decreasing uric acid clearance"],
    "B",
    "Thiazides are organic acids secreted by the proximal tubule. They compete with uric acid for the same secretory system, reducing uric acid excretion and raising serum levels. This can precipitate gout attacks in predisposed individuals.",
    True))

mcq_rows.append(q(S2,"medium",
    "Which metabolic effect distinguishes thiazide diuretics from loop diuretics regarding calcium?",
    ["A. Thiazides increase urinary calcium excretion; loop diuretics decrease it",
     "B. Thiazides decrease urinary calcium excretion; loop diuretics increase it",
     "C. Both classes decrease urinary calcium excretion equally",
     "D. Thiazides have no effect on calcium; only loop diuretics alter calcium handling"],
    "B",
    "Thiazides decrease Ca2+ excretion by promoting reabsorption in the distal convoluted tubule (useful for hypercalciuria and nephrolithiasis). Conversely, loop diuretics increase Ca2+ excretion (useful for hypercalcemia). This is a high-yield distinction.",
    True))

mcq_rows.append(q(S2,"hard",
    "A patient with nephrogenic diabetes insipidus is given hydrochlorothiazide. Urine output decreases from 11 L/day to 3 L/day. What paradoxical mechanism explains this response?",
    ["A. Thiazides stimulate V2 receptors, restoring aquaporin-2 insertion",
     "B. Thiazide-induced mild volume depletion increases proximal tubule reabsorption, reducing distal delivery and overall urine output",
     "C. Thiazides block prostaglandin synthesis, restoring ADH sensitivity",
     "D. Thiazides directly activate ADH release from the posterior pituitary"],
    "D",
    "Thiazides cause mild volume depletion, which increases proximal tubule Na+ and water reabsorption. Less fluid reaches the ADH-unresponsive distal segments, paradoxically reducing urine volume. This makes thiazides useful in nephrogenic DI where ADH cannot act.",
    True))

mcq_rows.append(q(S2,"easy",
    "Which adverse effect is most commonly associated with thiazide diuretic therapy?",
    ["A. Hyperkalemia",
     "B. Hypokalemia",
     "C. Hypocalcemia",
     "D. Hypermagnesemia"],
    "A",
    "Hypokalemia is the most frequent adverse effect of thiazide diuretics. Increased Na+ delivery to the collecting duct results in enhanced K+ secretion. Serum K+ should be monitored periodically, and supplementation or a K+-sparing diuretic may be required.",
    True))

mcq_rows.append(q(S2,"medium",
    "Indapamide differs from hydrochlorothiazide in which of the following pharmacokinetic properties?",
    ["A. Indapamide is renally eliminated unchanged; hydrochlorothiazide undergoes hepatic metabolism",
     "B. Indapamide undergoes hepatic metabolism and biliary/renal excretion; HCTZ is primarily excreted unchanged in urine",
     "C. Indapamide must be administered IV; HCTZ is oral only",
     "D. Indapamide has a shorter half-life and requires three-times-daily dosing"],
    "B",
    "Indapamide is unique among thiazide-like diuretics in undergoing significant hepatic metabolism and excretion in both urine and bile. Most other thiazides are excreted primarily unchanged in the urine, making renal function more relevant to their clearance.",
    True))

mcq_rows.append(q(S2,"medium",
    "A patient with diabetes mellitus asks if thiazides are safe. Which statement is most accurate?",
    ["A. Thiazides are absolutely contraindicated in diabetes due to fatal hypoglycemia risk",
     "B. Thiazides can cause mild hyperglycemia, possibly due to impaired insulin release from hypokalemia, but patients with diabetes still benefit",
     "C. Thiazides lower blood glucose by sensitizing insulin receptors",
     "D. Thiazides are the preferred antihypertensive in diabetes because they protect against nephropathy"],
    "C",
    "Thiazides can cause mild hyperglycemia, likely due to hypokalemia impairing pancreatic beta-cell insulin release. However, patients with diabetes are not excluded from thiazide therapy — they should monitor blood glucose when initiating therapy and adjust diabetes medications if needed.",
    True))

mcq_rows.append(q(S2,"hard",
    "Why do thiazide diuretics lose their diuretic efficacy (but not necessarily antihypertensive effect) when eGFR falls below 30 mL/min/1.73 m2?",
    ["A. Reduced tubular secretion of thiazides limits their concentration at the site of action in the distal tubule",
     "B. Thiazides are metabolized by the kidney and accumulate in renal failure",
     "C. The Na+/Cl- cotransporter is upregulated in CKD, overcoming thiazide blockade",
     "D. Reduced aldosterone in CKD makes thiazide diuresis ineffective"],
    "D",
    "Thiazides must be secreted into the proximal tubule lumen to reach the distal convoluted tubule. In advanced CKD (eGFR <30), reduced tubular secretion means inadequate drug reaches the NCC transporter for effective diuresis. However, some antihypertensive effect may persist via vascular mechanisms.",
    True))

mcq_rows.append(q(S2,"easy",
    "A patient has idiopathic hypercalciuria with recurrent calcium oxalate stones. Which diuretic class is most appropriate?",
    ["A. Loop diuretics",
     "B. Thiazide diuretics",
     "C. Potassium-sparing diuretics",
     "D. Osmotic diuretics"],
    "A",
    "Thiazides reduce urinary calcium excretion by promoting calcium reabsorption in the distal convoluted tubule. This property makes them the drug of choice for hypercalciuria and prevention of recurrent calcium oxalate nephrolithiasis.",
    True))

mcq_rows.append(q(S2,"medium",
    "Chlorthalidone is considered preferred over hydrochlorothiazide by some clinicians for hypertension management. What is the primary pharmacokinetic advantage?",
    ["A. Chlorthalidone has superior renal protective effects independent of blood pressure",
     "B. Chlorthalidone has a longer half-life of 50-60 hours, providing more sustained 24-hour blood pressure control",
     "C. Chlorthalidone does not cause hypokalemia unlike hydrochlorothiazide",
     "D. Chlorthalidone is the only thiazide that can be used in patients with sulfonamide allergy"],
    "B",
    "Chlorthalidone has a half-life of 50-60 hours compared to ~10-15 hours for HCTZ, providing more sustained blood pressure reduction throughout the day. It is approximately twice as potent as HCTZ. However, current hypertension guidelines do not preferentially recommend one thiazide over another.",
    True))

# ─── SUBTOPIC 3: Potassium-Sparing Diuretics ─────────────────────────────────
S3 = "Potassium-Sparing Diuretics"
mcq_rows.append(q(S3,"easy",
    "Spironolactone produces its diuretic effect by which mechanism?",
    ["A. Blocking Na+/K+/2Cl- cotransporter in the ascending limb of Henle",
     "B. Antagonizing aldosterone receptors in the collecting duct, preventing synthesis of Na+-reabsorbing proteins",
     "C. Directly blocking epithelial sodium channels in the collecting duct",
     "D. Inhibiting carbonic anhydrase in the proximal tubule"],
    "B",
    "Spironolactone is a synthetic steroid that competitively antagonizes intracellular mineralocorticoid (aldosterone) receptors. It prevents receptor translocation to the nucleus, reducing synthesis of proteins that stimulate epithelial Na+ channels and Na+/K+-ATPase, thereby reducing Na+ reabsorption and K+ excretion.",
    True))

mcq_rows.append(q(S3,"medium",
    "A patient on spironolactone develops gynecomastia. Which drug from the same class would be preferred to avoid this adverse effect?",
    ["A. Amiloride",
     "B. Triamterene",
     "C. Eplerenone",
     "D. Furosemide"],
    "B",
    "Eplerenone is a more selective aldosterone receptor antagonist that does not bind progesterone or androgen receptors, unlike spironolactone. This selectivity reduces antiandrogenic effects such as gynecomastia, breast tenderness, and menstrual irregularities.",
    True))

mcq_rows.append(q(S3,"medium",
    "Amiloride produces potassium-sparing diuresis through which mechanism?",
    ["A. Aldosterone receptor antagonism in the principal cells",
     "B. Direct blockade of epithelial sodium channels (ENaC) in the collecting duct",
     "C. Inhibition of Na+/K+-ATPase in the distal tubule",
     "D. Increased renal prostaglandin synthesis reducing Na+ reabsorption"],
    "C",
    "Amiloride and triamterene directly block epithelial sodium channels (ENaC) in the principal cells of the collecting tubule and duct, independently of aldosterone. This reduces Na+ entry into the cell and consequently reduces K+ secretion.",
    True))

mcq_rows.append(q(S3,"hard",
    "A patient with CKD stage 4 (eGFR 22 mL/min) and heart failure is started on spironolactone. What is the primary concern?",
    ["A. Hypokalemia from excessive K+ loss",
     "B. Hyperkalemia due to impaired renal K+ excretion combined with aldosterone blockade",
     "C. Acute tubular necrosis from spironolactone nephrotoxicity",
     "D. Volume overload because spironolactone has minimal diuretic effect"],
    "D",
    "Potassium-sparing diuretics should be used cautiously in moderate renal dysfunction and avoided in severe renal dysfunction (eGFR <30 or severe CKD). The kidney's already impaired ability to excrete K+, compounded by aldosterone blockade preventing K+ secretion in the collecting duct, creates a high risk of life-threatening hyperkalemia.",
    True))

mcq_rows.append(q(S3,"easy",
    "Potassium-sparing diuretics are most commonly combined with which other diuretic class to prevent electrolyte imbalance?",
    ["A. Osmotic diuretics",
     "B. Carbonic anhydrase inhibitors",
     "C. Thiazide or loop diuretics to counteract hypokalemia",
     "D. Beta-blockers to enhance the diuretic effect"],
    "A",
    "Thiazide and loop diuretics cause hypokalemia, while potassium-sparing diuretics cause hyperkalemia. Combining them (e.g., HCTZ + triamterene, furosemide + spironolactone) allows potassium-neutral diuresis. Fixed-dose combinations like Dyazide (HCTZ/triamterene) exploit this complementary mechanism.",
    True))

mcq_rows.append(q(S3,"medium",
    "Spironolactone is used in which of the following conditions beyond its diuretic indication?",
    ["A. Hyperkalemia management in CKD",
     "B. Heart failure with reduced ejection fraction for mortality benefit",
     "C. Acute pulmonary edema as first-line therapy",
     "D. Nephrogenic diabetes insipidus"],
    "B",
    "Spironolactone (and eplerenone) demonstrate mortality benefit in heart failure with reduced ejection fraction (HFrEF) and post-MI ventricular dysfunction. Aldosterone promotes cardiac fibrosis and remodeling; blocking these non-renal aldosterone receptor sites explains the survival benefit beyond simple diuresis.",
    True))

mcq_rows.append(q(S3,"medium",
    "A patient taking spironolactone starts an ACE inhibitor. What electrolyte monitoring is most critical?",
    ["A. Serum sodium — risk of hyponatremia from combined water retention",
     "B. Serum potassium — both agents reduce K+ excretion, risking severe hyperkalemia",
     "C. Serum calcium — ACE inhibitors promote hypercalcemia when combined with spironolactone",
     "D. Serum magnesium — spironolactone depletes Mg2+ when combined with ACE inhibitors"],
    "C",
    "Both spironolactone (aldosterone antagonism, reducing K+ excretion) and ACE inhibitors (reducing angiotensin II-driven aldosterone, reducing K+ excretion) independently raise serum potassium. Their combination markedly increases hyperkalemia risk. Serum K+ must be closely monitored, especially in patients with CKD or diabetes.",
    True))

mcq_rows.append(q(S3,"hard",
    "Which statement best explains why potassium-sparing diuretics have weaker diuretic potency compared to loop diuretics?",
    ["A. They are rapidly metabolized before reaching the kidney",
     "B. The collecting duct only reabsorbs 1-2% of filtered sodium, limiting the maximum diuretic effect",
     "C. They inhibit aldosterone synthesis rather than receptor activity, causing slower onset",
     "D. They require renal tubular secretion like loop diuretics, which is impaired in most patients"],
    "B",
    "Potassium-sparing diuretics act in the collecting tubule and duct, where only 1-2% of filtered sodium is reabsorbed via ENaC. Regardless of complete blockade of this segment, only a small fraction of filtered Na+ is affected — unlike loop diuretics acting on the 25-30% reabsorbed in the thick ascending limb.",
    True))

mcq_rows.append(q(S3,"easy",
    "Which adverse effect is the primary safety concern when using triamterene in a patient also receiving trimethoprim?",
    ["A. Combined nephrotoxicity causing acute interstitial nephritis",
     "B. Additive hyperkalemia, as both drugs block collecting duct Na+ reabsorption",
     "C. Reduced efficacy of triamterene due to competition for tubular secretion",
     "D. Severe hyponatremia from synergistic water retention"],
    "A",
    "Trimethoprim (like amiloride and triamterene) blocks ENaC in the collecting duct and reduces K+ excretion. When combined with other K+-sparing drugs, the risk of hyperkalemia is additive. This is a clinically important interaction, particularly in patients with reduced renal function.",
    True))

mcq_rows.append(q(S3,"medium",
    "In primary hyperaldosteronism (Conn syndrome), spironolactone is particularly effective. Why?",
    ["A. Spironolactone increases aldosterone degradation by the liver",
     "B. Excess aldosterone drives Na+ retention and K+ loss; spironolactone competitively blocks aldosterone receptors, reversing both effects",
     "C. Spironolactone inhibits aldosterone synthesis in the adrenal cortex",
     "D. Spironolactone increases GFR, allowing excess aldosterone to be filtered"],
    "B",
    "In primary hyperaldosteronism, elevated aldosterone drives Na+ retention, hypertension, and K+ wasting (hypokalemia). Spironolactone directly antagonizes the aldosterone receptor, reversing the Na+-retaining and K+-losing effects. It is both diagnostic and therapeutic in this condition.",
    True))

# ─── SUBTOPIC 4: Osmotic Diuretics & CAIs ────────────────────────────────────
S4 = "Osmotic Diuretics and Carbonic Anhydrase Inhibitors"
mcq_rows.append(q(S4,"easy",
    "Mannitol produces diuresis through which primary mechanism?",
    ["A. Inhibiting Na+/K+/2Cl- cotransporter in the ascending limb",
     "B. Acting as a freely filtered, non-reabsorbable solute that retains water in the tubular lumen by osmosis",
     "C. Blocking aldosterone receptors in the collecting duct",
     "D. Inhibiting carbonic anhydrase in the proximal tubule"],
    "B",
    "Mannitol is an osmotically active sugar alcohol that is freely filtered at the glomerulus but not reabsorbed. It retains water in the tubular lumen osmotically, increasing urine flow. It also draws water from intracellular compartments, making it useful for reducing cerebral edema and ICP.",
    True))

mcq_rows.append(q(S4,"medium",
    "A neurosurgery patient with acutely elevated intracranial pressure is started on mannitol. What is the most critical monitoring parameter?",
    ["A. Serum potassium, due to risk of hyperkalemia",
     "B. Serum osmolality, to prevent hyperosmolar state and rebound cerebral edema",
     "C. Urinary pH, to detect bicarbonate wasting",
     "D. Serum glucose, as mannitol is metabolized to glucose"],
    "B",
    "Mannitol administration raises serum osmolality. The osmol gap (measured minus calculated osmolality) should be monitored. If serum osmolality rises excessively (>320 mOsm/kg), the risk of renal toxicity and paradoxical rebound cerebral edema increases. Serum Na+ and osmolality must be closely watched.",
    True))

mcq_rows.append(q(S4,"medium",
    "Acetazolamide inhibits carbonic anhydrase in the proximal tubule. Which acid-base disturbance results from its use?",
    ["A. Metabolic alkalosis due to increased HCO3- reabsorption",
     "B. Metabolic acidosis due to increased HCO3- excretion in the urine",
     "C. Respiratory acidosis from central respiratory depression",
     "D. Respiratory alkalosis from stimulation of peripheral chemoreceptors"],
    "C",
    "Acetazolamide inhibits carbonic anhydrase, preventing H+ secretion and HCO3- reabsorption in the proximal tubule. Increased urinary HCO3- excretion leads to a hyperchloremic metabolic acidosis. This limits its long-term use as a diuretic, as metabolic acidosis reduces its own efficacy.",
    True))

mcq_rows.append(q(S4,"hard",
    "Acetazolamide is used as adjunctive treatment in altitude sickness (acute mountain sickness). What is the mechanism of benefit?",
    ["A. Increasing oxygen delivery by stimulating erythropoietin production",
     "B. Causing metabolic acidosis which stimulates ventilation, increasing PO2 at altitude",
     "C. Reducing pulmonary vascular resistance to prevent high-altitude pulmonary edema",
     "D. Blocking cerebral carbonic anhydrase to reduce CSF production and headache"],
    "B",
    "Acetazolamide-induced metabolic acidosis stimulates peripheral chemoreceptors to increase ventilation depth and rate. The resulting hyperventilation helps acclimatize climbers by maintaining higher arterial PO2. The metabolic acidosis compensates for the respiratory alkalosis of altitude, improving the ventilatory response.",
    True))

mcq_rows.append(q(S4,"easy",
    "Acetazolamide is used in the management of open-angle glaucoma. What is the therapeutic rationale?",
    ["A. It reduces intraocular pressure by decreasing aqueous humor production via carbonic anhydrase inhibition in the ciliary body",
     "B. It improves aqueous humor drainage through the trabecular meshwork",
     "C. It causes miosis via muscarinic receptor activation in the iris sphincter",
     "D. It blocks prostaglandin synthesis in the anterior chamber"],
    "A",
    "Carbonic anhydrase in the ciliary body epithelium is essential for aqueous humor secretion (requires HCO3- secretion). Acetazolamide inhibits this enzyme, reducing aqueous humor production and thereby lowering intraocular pressure. Topical CAIs (dorzolamide, brinzolamide) are preferred for long-term use.",
    True))

mcq_rows.append(q(S4,"medium",
    "Why is mannitol contraindicated in patients with congestive heart failure?",
    ["A. Mannitol causes direct cardiac toxicity via calcium channel blockade",
     "B. Initial expansion of intravascular volume from osmotic fluid shift can precipitate acute pulmonary edema",
     "C. Mannitol competes with diuretics for tubular secretion, reducing heart failure therapy efficacy",
     "D. Mannitol causes hyponatremia, worsening fluid retention in heart failure"],
    "B",
    "Mannitol draws water from the intracellular space into the extravascular compartment, transiently expanding plasma volume. In patients with impaired cardiac function, this acute volume expansion can precipitate congestive heart failure exacerbation or acute pulmonary edema. It is contraindicated in heart failure and anuria.",
    True))

mcq_rows.append(q(S4,"medium",
    "Which diuretic class acts primarily on the descending loop of Henle in addition to the proximal tubule?",
    ["A. Thiazide diuretics",
     "B. Osmotic diuretics",
     "C. Potassium-sparing diuretics",
     "D. Loop diuretics"],
    "C",
    "Osmotic diuretics like mannitol exert their effect partly in the descending loop of Henle (a water-permeable segment), where the osmotically active mannitol in the lumen retains water and opposes water reabsorption. They also act in the proximal tubule to reduce proximal Na+ and water reabsorption.",
    True))

mcq_rows.append(q(S4,"hard",
    "A patient with idiopathic intracranial hypertension (pseudotumor cerebri) is treated with acetazolamide. What additional benefit does acetazolamide provide beyond reducing ICP?",
    ["A. It directly dissolves excess CSF protein deposits",
     "B. It reduces CSF production by inhibiting carbonic anhydrase in the choroid plexus epithelium",
     "C. It stimulates CSF reabsorption through the arachnoid granulations",
     "D. It constricts cerebral blood vessels, reducing CSF formation"],
    "B",
    "Carbonic anhydrase in the choroid plexus epithelium is critical for CSF secretion. Acetazolamide inhibits this enzyme, reducing CSF production and lowering intracranial pressure. This is its primary mechanism in treating idiopathic intracranial hypertension.",
    True))

mcq_rows.append(q(S4,"easy",
    "Which of the following is the most appropriate indication for mannitol?",
    ["A. Chronic heart failure with fluid overload",
     "B. Acute management of cerebral edema and elevated intracranial pressure following head injury",
     "C. Treatment of nephrogenic diabetes insipidus",
     "D. Prophylaxis of thiazide-induced hypokalemia"],
    "A",
    "Mannitol's primary clinical indication is cerebral edema and elevated intracranial pressure (from trauma, stroke, or surgery). By drawing fluid osmotically from brain parenchyma into the vasculature, it reduces brain volume and ICP. IV administration is required.",
    True))

mcq_rows.append(q(S4,"medium",
    "Acetazolamide is used in metabolic alkalosis in some clinical situations. What is the rationale?",
    ["A. It stimulates aldosterone release, increasing K+ and H+ excretion",
     "B. By inhibiting carbonic anhydrase, it causes bicarbonate wasting in the urine, correcting alkalosis",
     "C. It raises urinary pH, facilitating reabsorption of acid",
     "D. It increases ammonium excretion, generating new bicarbonate"],
    "B",
    "In contraction alkalosis (e.g., post-diuretic therapy where Cl- depletion prevents renal correction of alkalosis), acetazolamide can be used to increase urinary HCO3- excretion, directly correcting the metabolic alkalosis. This is useful when NaCl replacement is not appropriate (e.g., heart failure).",
    True))

# ─── SUBTOPIC 5: ACE Inhibitors & ARBs in Renal Disease ─────────────────────
S5 = "ACE Inhibitors and ARBs in Renal Disease"
mcq_rows.append(q(S5,"easy",
    "How do ACE inhibitors exert renoprotective effects in diabetic nephropathy?",
    ["A. By increasing GFR to flush toxic metabolites from the kidney",
     "B. By reducing efferent arteriolar resistance, lowering intraglomerular pressure and proteinuria",
     "C. By blocking tubular reabsorption of glucose, preventing glycosuria-induced damage",
     "D. By inhibiting aldosterone, which directly damages the glomerular basement membrane"],
    "B",
    "Angiotensin II preferentially constricts the efferent arteriole, raising intraglomerular pressure. ACE inhibitors reduce angiotensin II levels, dilating the efferent arteriole, lowering glomerular capillary pressure, and reducing hyperfiltration. This decreases proteinuria and slows progression of diabetic nephropathy.",
    True))

mcq_rows.append(q(S5,"medium",
    "A patient with bilateral renal artery stenosis is started on an ARB for hypertension. Which acute complication is most likely?",
    ["A. Acute hyperkalemia from aldosterone suppression",
     "B. Acute kidney injury from loss of efferent arteriolar tone needed to maintain GFR",
     "C. Severe hypotension due to sudden drop in aldosterone-driven fluid retention",
     "D. Pulmonary edema from acute sodium retention"],
    "B",
    "In bilateral renal artery stenosis, the kidney depends on high angiotensin II levels to constrict the efferent arteriole and maintain GFR despite reduced perfusion pressure. Blocking the RAS (with ACE inhibitors or ARBs) removes this compensatory mechanism, causing acute prerenal AKI. This is a contraindication.",
    True))

mcq_rows.append(q(S5,"medium",
    "A patient on lisinopril develops a dry, nonproductive cough. What is the mechanism?",
    ["A. Direct irritation of bronchial smooth muscle by lisinopril itself",
     "B. Accumulation of bradykinin due to ACE inhibition, stimulating cough receptors",
     "C. Increased angiotensin II levels causing bronchoconstriction",
     "D. ACE inhibitor-induced eosinophilia causing airway inflammation"],
    "C",
    "ACE not only converts angiotensin I to II but also degrades bradykinin. When ACE is inhibited, bradykinin accumulates and stimulates cough receptors in the airway. The cough occurs in ~10-15% of patients (more common in Asian populations). Switching to an ARB (which does not affect bradykinin) resolves the cough.",
    True))

mcq_rows.append(q(S5,"hard",
    "Which mechanism explains the acute rise in serum creatinine (up to 30%) acceptable after starting an ACE inhibitor in a patient with CKD?",
    ["A. Direct tubular toxicity from the ACE inhibitor molecule",
     "B. Reduced efferent arteriolar tone lowers intraglomerular pressure, reducing GFR — a hemodynamic effect that signals renoprotection",
     "C. ACE inhibitors compete with creatinine for tubular secretion, falsely raising serum creatinine",
     "D. ACE inhibitor-induced ADH suppression causes prerenal azotemia"],
    "D",
    "A creatinine rise of up to 30% within 2 weeks of starting an ACE inhibitor is expected and acceptable — it reflects the intended reduction in intraglomerular pressure (efferent dilation reducing filtration pressure). This hemodynamic change is the mechanism of renoprotection. Greater rises or rising creatinine suggest volume depletion, bilateral RAS, or another cause.",
    True))

mcq_rows.append(q(S5,"easy",
    "Which drug combination represents the most dangerous interaction with ACE inhibitors regarding hyperkalemia?",
    ["A. ACE inhibitor + calcium channel blocker",
     "B. ACE inhibitor + potassium-sparing diuretic (e.g., spironolactone)",
     "C. ACE inhibitor + thiazide diuretic",
     "D. ACE inhibitor + loop diuretic"],
    "A",
    "ACE inhibitors reduce aldosterone-mediated K+ excretion, raising serum K+. When combined with a K+-sparing diuretic (spironolactone, amiloride), both mechanisms independently reduce K+ excretion, substantially increasing hyperkalemia risk — particularly dangerous in CKD patients.",
    True))

mcq_rows.append(q(S5,"medium",
    "ARBs (e.g., losartan) differ from ACE inhibitors in which clinically important way?",
    ["A. ARBs do not reduce blood pressure as effectively as ACE inhibitors",
     "B. ARBs block AT1 receptors, allowing bradykinin degradation to proceed normally, avoiding cough and angioedema",
     "C. ARBs cause more hyperkalemia than ACE inhibitors",
     "D. ARBs are contraindicated in heart failure, unlike ACE inhibitors"],
    "B",
    "ARBs block angiotensin II at the AT1 receptor but do not inhibit ACE. Since ACE continues to degrade bradykinin normally, ARBs do not cause the bradykinin-mediated cough or angioedema associated with ACE inhibitors. This makes ARBs the preferred alternative when ACE inhibitor cough is intolerable.",
    True))

mcq_rows.append(q(S5,"medium",
    "A patient with type 2 diabetes, hypertension, and proteinuria (1.8 g/day) is managed. Which drug class provides the best evidence for slowing CKD progression?",
    ["A. Calcium channel blockers",
     "B. ACE inhibitors or ARBs",
     "C. Beta-blockers",
     "D. Alpha-blockers"],
    "C",
    "ACE inhibitors and ARBs have Level A evidence for reducing proteinuria and slowing CKD progression in diabetic nephropathy. They reduce intraglomerular pressure independent of blood pressure lowering, and their antiproteinuric effect correlates with renoprotection. They are first-line antihypertensives in CKD with proteinuria.",
    True))

mcq_rows.append(q(S5,"hard",
    "The combination of an ACE inhibitor PLUS an ARB (dual RAS blockade) for CKD was previously advocated. Current guidelines recommend against this. Why?",
    ["A. Combined therapy provides no additional blood pressure reduction over monotherapy",
     "B. Clinical trials (ONTARGET) showed dual blockade increased adverse events — hypotension, AKI, hyperkalemia — without added cardiovascular benefit",
     "C. ARBs block the efficacy of ACE inhibitors at the receptor level",
     "D. Dual RAS blockade causes paradoxical angiotensin II upregulation"],
    "D",
    "The ONTARGET trial demonstrated that combining an ACE inhibitor (ramipril) with an ARB (telmisartan) increased the risk of hypotension, hyperkalemia, and acute kidney injury without additional cardiovascular or renal benefits. Dual RAS blockade is now generally contraindicated except in select cases under specialist supervision.",
    True))

mcq_rows.append(q(S5,"easy",
    "ACE inhibitors and ARBs are absolutely contraindicated during which condition?",
    ["A. Chronic stable angina",
     "B. Pregnancy",
     "C. Mild hypertension with microalbuminuria",
     "D. Asthma"],
    "A",
    "ACE inhibitors and ARBs are absolutely contraindicated in pregnancy (Category X / Risk Category D in 2nd and 3rd trimesters). They cause fetal renal hypoperfusion leading to renal tubular dysgenesis, oligohydramnios, limb contractures, pulmonary hypoplasia, and neonatal renal failure (fetopathy).",
    True))

mcq_rows.append(q(S5,"medium",
    "A patient on lisinopril develops sudden facial and oropharyngeal swelling requiring emergency intubation. What is this reaction and what causes it?",
    ["A. Anaphylaxis from IgE-mediated sensitization to lisinopril protein",
     "B. ACE inhibitor-induced angioedema from bradykinin accumulation causing increased vascular permeability",
     "C. Allergic reaction to sulfonamide moiety in the ACE inhibitor structure",
     "D. Direct mast cell degranulation by lisinopril causing histamine release"],
    "B",
    "ACE inhibitor-induced angioedema is a rare (~0.1-0.7%) but potentially life-threatening reaction caused by bradykinin accumulation increasing vascular permeability. It is not IgE-mediated and does not respond to antihistamines or epinephrine as reliably. Switching to an ARB is required, as cross-reactivity with angioedema is low but not zero.",
    True))

# ─── SUBTOPIC 6: Drugs in CKD ────────────────────────────────────────────────
S6 = "Drugs in CKD"
mcq_rows.append(q(S6,"easy",
    "NSAIDs are nephrotoxic particularly in patients with CKD or reduced renal perfusion. What is the mechanism?",
    ["A. NSAIDs directly lyse tubular epithelial cells via oxidative stress",
     "B. NSAIDs inhibit renal prostaglandin synthesis, removing vasodilatory support for afferent arteriolar tone, causing ischemia",
     "C. NSAIDs block aldosterone receptors, causing sodium retention and tubular injury",
     "D. NSAIDs competitively inhibit creatinine secretion, raising serum creatinine without true GFR reduction"],
    "B",
    "In states of reduced renal perfusion (CKD, heart failure, dehydration), the kidney depends on prostaglandin-mediated afferent arteriolar vasodilation to maintain GFR. NSAIDs inhibit COX enzymes, blocking prostaglandin synthesis. The afferent arteriole constricts, reducing renal blood flow and GFR, precipitating AKI.",
    True))

mcq_rows.append(q(S6,"medium",
    "A patient with CKD stage 3b (eGFR 32 mL/min) is prescribed metformin for type 2 diabetes. What is the primary concern?",
    ["A. Metformin is directly nephrotoxic at low GFR",
     "B. Reduced renal clearance leads to metformin accumulation and risk of lactic acidosis",
     "C. Metformin causes hyperkalemia by inhibiting aldosterone",
     "D. Metformin cannot lower blood glucose effectively when GFR is below 45 mL/min"],
    "B",
    "Metformin is renally cleared and accumulates in renal impairment. In conditions of reduced GFR and poor tissue perfusion, it inhibits mitochondrial complex I, promoting lactate production and causing potentially fatal lactic acidosis. Metformin is typically discontinued when eGFR falls below 30 mL/min and used cautiously below 45 mL/min.",
    True))

mcq_rows.append(q(S6,"medium",
    "Aminoglycoside antibiotics cause nephrotoxicity by which mechanism?",
    ["A. Direct glomerular basement membrane disruption causing nephrotic syndrome",
     "B. Concentration-dependent accumulation in proximal tubular cells causing oxidative damage and tubular necrosis",
     "C. Hypersensitivity-mediated acute interstitial nephritis",
     "D. Renal vasoconstriction from direct smooth muscle activation"],
    "C",
    "Aminoglycosides are taken up by proximal tubular epithelial cells via endocytosis, where they accumulate. They generate reactive oxygen species, disrupt lysosomal function, and cause proximal tubular cell death (non-oliguric acute tubular necrosis). Risk is reduced by once-daily dosing, adequate hydration, and therapeutic drug monitoring.",
    True))

mcq_rows.append(q(S6,"hard",
    "A patient with CKD (eGFR 25 mL/min) requires anticoagulation for atrial fibrillation. Which direct oral anticoagulant requires the most careful dose adjustment or avoidance?",
    ["A. Apixaban — nearly entirely renally eliminated; must be avoided in severe CKD",
     "B. Dabigatran — 80% renally eliminated; must be dose-reduced or avoided in severe CKD",
     "C. Rivaroxaban — exclusively hepatically metabolized; safe in any degree of renal impairment",
     "D. Warfarin — renally cleared; requires dose reduction proportional to GFR decline"],
    "D",
    "Dabigatran is approximately 80% renally eliminated and is contraindicated when CrCl <15-30 mL/min depending on indication. It has the highest renal dependence among DOACs. Apixaban has the lowest renal dependence (~27%), making it relatively safer in CKD. Rivaroxaban (~33% renal) requires dose adjustment. Warfarin is hepatically metabolized but monitored by INR.",
    True))

mcq_rows.append(q(S6,"easy",
    "Which class of drugs should generally be avoided in patients with advanced CKD due to risk of accumulation and nephrotoxicity?",
    ["A. Calcium channel blockers",
     "B. Iodinated contrast media, NSAIDs, and aminoglycosides",
     "C. ACE inhibitors and ARBs",
     "D. Statins and fibrates"],
    "A",
    "Classic nephrotoxic drugs to avoid or use cautiously in CKD include: NSAIDs (reduce renal prostaglandins), aminoglycosides (proximal tubular toxicity), iodinated contrast (contrast-induced nephropathy via vasoconstriction and oxidative stress), and IV contrast. These can precipitate AKI on CKD.",
    True))

mcq_rows.append(q(S6,"medium",
    "Iodinated contrast media causes contrast-induced nephropathy primarily through which mechanism?",
    ["A. Hyperosmolar contrast causes direct cellular toxicity and renal medullary ischemia via vasoconstriction",
     "B. Iodine is directly deposited in the glomerulus causing membranous nephropathy",
     "C. Contrast activates the complement system, causing glomerulonephritis",
     "D. Contrast inhibits carbonic anhydrase, causing proximal tubular acidosis"],
    "A",
    "Contrast-induced nephropathy (CIN) results from: (1) direct tubular cytotoxicity of contrast molecules, and (2) renal medullary ischemia from contrast-induced vasoconstriction of the vasa recta. Risk factors include CKD, diabetes, high contrast volume, and dehydration. Prevention includes IV hydration and N-acetylcysteine.",
    True))

mcq_rows.append(q(S6,"medium",
    "Lithium, used for bipolar disorder, causes chronic kidney disease through what mechanism?",
    ["A. Lithium causes membranous glomerulonephritis by binding to glomerular antigens",
     "B. Chronic lithium exposure causes tubulointerstitial nephritis and also causes nephrogenic diabetes insipidus by downregulating aquaporin-2",
     "C. Lithium accumulates in mesangial cells and causes IgA nephropathy",
     "D. Lithium inhibits erythropoietin production, causing renal hypoxia"],
    "B",
    "Long-term lithium therapy causes two renal effects: (1) nephrogenic diabetes insipidus — lithium blocks ADH-stimulated aquaporin-2 insertion, causing polyuria/polydipsia; and (2) chronic tubulointerstitial nephritis with progressive CKD. Regular monitoring of renal function and lithium levels is mandatory.",
    True))

mcq_rows.append(q(S6,"hard",
    "A patient with severe CKD (eGFR 18 mL/min) requires pain management. Which analgesic is safest?",
    ["A. Naproxen, because it has a short half-life and less accumulation than other NSAIDs",
     "B. Acetaminophen at standard doses, as it is hepatically metabolized with minimal renal impact",
     "C. Codeine, as it is the weakest opioid and least likely to accumulate",
     "D. Ketorolac IM, as parenteral administration avoids enteral absorption complications"],
    "D",
    "Acetaminophen is the preferred analgesic in CKD — it is hepatically metabolized and its inactive sulfate/glucuronide metabolites (not the parent drug) are renally cleared; it does not reduce renal blood flow. NSAIDs (including ketorolac and naproxen) are contraindicated in advanced CKD. Codeine metabolites accumulate and cause toxicity in CKD.",
    True))

mcq_rows.append(q(S6,"easy",
    "In CKD, the general principle of drug dosing requires which adjustment?",
    ["A. Reduce the loading dose but maintain the maintenance dose",
     "B. Maintain the loading dose (achieves target concentration) but reduce maintenance dose and/or extend dosing interval for renally cleared drugs",
     "C. Double the dose of all drugs because CKD impairs drug absorption",
     "D. Switch all drugs to IV formulations to bypass renal clearance issues"],
    "A",
    "For renally eliminated drugs, the loading dose is generally unchanged (it depends on volume of distribution, not clearance), but the maintenance dose is reduced and/or the dosing interval is extended proportionally to the degree of renal impairment. This prevents drug accumulation and toxicity.",
    True))

mcq_rows.append(q(S6,"medium",
    "A patient with CKD and gout is being considered for allopurinol therapy. What dose adjustment is required?",
    ["A. Allopurinol requires no dose adjustment in CKD as it is hepatically cleared",
     "B. Allopurinol and its active metabolite oxypurinol are renally cleared; dose must be reduced in CKD to prevent toxicity (rash, bone marrow suppression)",
     "C. Allopurinol is contraindicated in all patients with CKD regardless of severity",
     "D. Allopurinol dose must be doubled in CKD to overcome reduced tubular secretion"],
    "B",
    "Allopurinol is converted to oxypurinol (active, longer half-life), which is renally eliminated. In CKD, oxypurinol accumulates, increasing the risk of severe adverse effects including Stevens-Johnson syndrome, allopurinol hypersensitivity syndrome, and bone marrow suppression. Dose reduction proportional to eGFR is essential.",
    True))

# ─── SUBTOPIC 7: Phosphate Binders & ESAs ────────────────────────────────────
S7 = "Phosphate Binders and Erythropoiesis-Stimulating Agents"
mcq_rows.append(q(S7,"easy",
    "In CKD-mineral bone disease, elevated phosphate levels are managed with phosphate binders. Which binder is preferred in patients with hypercalcemia?",
    ["A. Calcium carbonate, as it corrects both hyperphosphatemia and hypocalcemia",
     "B. Sevelamer hydrochloride or lanthanum carbonate — non-calcium binders that avoid worsening hypercalcemia",
     "C. Aluminum hydroxide for long-term use as it is the most effective phosphate binder",
     "D. Calcium acetate, as it has the lowest calcium content per tablet"],
    "B",
    "Non-calcium phosphate binders (sevelamer, lanthanum carbonate) are preferred when serum calcium is elevated, when PTH is suppressed, or when vascular calcification is a concern. Calcium-based binders (calcium carbonate, calcium acetate) increase calcium load and can worsen hypercalcemia and vascular calcification.",
    True))

mcq_rows.append(q(S7,"medium",
    "Aluminum-containing phosphate binders are not recommended for long-term use in CKD. Why?",
    ["A. Aluminum competes with calcium for intestinal absorption, causing severe hypocalcemia",
     "B. Aluminum accumulates in bone and CNS in CKD, causing adynamic bone disease and encephalopathy",
     "C. Aluminum hydroxide causes metabolic alkalosis by neutralizing gastric acid",
     "D. Aluminum is directly nephrotoxic and accelerates CKD progression"],
    "B",
    "Aluminum hydroxide is highly effective at binding phosphate but aluminum is absorbed from the gut and cleared by the kidneys. In CKD, it accumulates in bone (causing adynamic bone disease), brain (dialysis dementia/encephalopathy), and blood (anemia). Long-term use is therefore contraindicated; short courses are occasionally used.",
    True))

mcq_rows.append(q(S7,"medium",
    "Erythropoiesis-stimulating agents (ESAs) such as epoetin alfa are used in CKD anemia. What is the target hemoglobin level to guide ESA therapy?",
    ["A. Normalize Hb to >13 g/dL to maximize oxygen delivery and quality of life",
     "B. Maintain Hb between 10-11.5 g/dL; higher targets increase cardiovascular events",
     "C. Target Hb >12 g/dL in all CKD patients regardless of cardiovascular history",
     "D. Correct anemia rapidly to Hb 12-13 g/dL within 4 weeks of ESA initiation"],
    "B",
    "Clinical trials (CHOIR, TREAT, CREATE) showed that targeting higher Hb levels (>13 g/dL) with ESAs in CKD increased cardiovascular events (stroke, MI) and mortality. Current KDIGO guidelines recommend ESA initiation when Hb <10 g/dL and targeting Hb 10-11.5 g/dL to avoid both anemia symptoms and ESA-related cardiovascular risk.",
    True))

mcq_rows.append(q(S7,"hard",
    "A patient on ESA therapy for CKD anemia has a poor response despite adequate doses. Which is the most common cause of ESA hyporesponsiveness?",
    ["A. Anti-erythropoietin antibodies causing pure red cell aplasia",
     "B. Iron deficiency — absolute or functional — limiting erythropoiesis",
     "C. Folate deficiency from CKD dietary restrictions",
     "D. Uremic inhibition of erythropoietin receptors on bone marrow progenitors"],
    "D",
    "Iron deficiency (absolute: ferritin <200 ng/mL, transferrin saturation <20%; or functional: iron unavailable for erythropoiesis despite adequate stores) is the most common reason for ESA hyporesponsiveness. Iron must be repleted (often IV iron in dialysis patients) before and during ESA therapy. Other causes include chronic inflammation, infection, vitamin B12/folate deficiency, and hyperparathyroidism.",
    True))

mcq_rows.append(q(S7,"easy",
    "In CKD-mineral bone disease (CKD-MBD), what is the sequence of events leading to secondary hyperparathyroidism?",
    ["A. Hyperphosphatemia → suppressed FGF-23 → reduced calcitriol → hypocalcemia → elevated PTH",
     "B. Reduced GFR → hyperphosphatemia → reduced calcitriol production → hypocalcemia → elevated PTH",
     "C. Elevated PTH → hyperphosphatemia → reduced calcitriol → hypocalcemia",
     "D. Hypocalcemia → hyperphosphatemia → reduced FGF-23 → elevated PTH"],
    "A",
    "In CKD: (1) reduced GFR causes phosphate retention; (2) elevated FGF-23 suppresses renal 1-alpha hydroxylase, reducing calcitriol production; (3) low calcitriol reduces intestinal Ca2+ absorption → hypocalcemia; (4) low Ca2+ and low calcitriol both stimulate PTH secretion → secondary hyperparathyroidism.",
    True))

mcq_rows.append(q(S7,"medium",
    "Cinacalcet is used in CKD to manage secondary hyperparathyroidism. How does it work?",
    ["A. It binds to the calcium-sensing receptor on parathyroid cells, allosterically increasing its sensitivity to calcium, suppressing PTH release",
     "B. It directly inhibits PTH gene transcription in the parathyroid gland",
     "C. It reduces intestinal phosphate absorption, lowering the stimulus for PTH secretion",
     "D. It replaces calcitriol signaling by binding to vitamin D receptors in the parathyroid gland"],
    "A",
    "Cinacalcet is a calcimimetic that allosterically activates (sensitizes) the calcium-sensing receptor (CaSR) on parathyroid cells. This makes the CaSR respond as if calcium levels are higher, reducing PTH secretion. It can lower PTH, Ca2+, and phosphate simultaneously. Hypocalcemia is the most common adverse effect.",
    True))

mcq_rows.append(q(S7,"medium",
    "A hemodialysis patient is started on IV iron sucrose. What is the most important immediate adverse effect to monitor?",
    ["A. Hypersensitivity/anaphylactic reactions, particularly with rapid infusion",
     "B. Hyperferritinemia causing liver damage within 24 hours",
     "C. Acute pulmonary edema from osmotic fluid shift",
     "D. Hypokalemia from iron-potassium exchange in the gut"],
    "A",
    "IV iron preparations, including iron sucrose, ferric gluconate, and ferric carboxymaltose, carry a risk of hypersensitivity reactions ranging from mild flushing to anaphylaxis. Iron dextran carries the highest risk. Patients should be monitored during and after infusion; resuscitation equipment should be available. Newer formulations (iron sucrose, ferric carboxymaltose) have lower hypersensitivity rates.",
    True))

mcq_rows.append(q(S7,"hard",
    "Pure red cell aplasia (PRCA) is a rare but serious complication of ESA therapy. What is the mechanism?",
    ["A. ESAs directly inhibit erythroid burst-forming units in the bone marrow",
     "B. Development of anti-erythropoietin neutralizing antibodies that cross-react with endogenous erythropoietin",
     "C. ESA-induced iron sequestration depleting erythropoiesis cofactors",
     "D. ESA-mediated T-cell activation causing autoimmune bone marrow destruction"],
    "B",
    "PRCA complicating ESA therapy is caused by the development of neutralizing IgG antibodies against recombinant erythropoietin. These antibodies cross-react with endogenous erythropoietin, abolishing native erythropoiesis. It presents as severe anemia with absent erythroblasts on bone marrow biopsy. ESA must be discontinued immediately; immunosuppression may be required.",
    True))

mcq_rows.append(q(S7,"easy",
    "Active vitamin D analogs (calcitriol, paricalcitol) are used in CKD. What is the primary role?",
    ["A. Replace reduced renal calcitriol production to suppress PTH and maintain calcium/phosphate balance",
     "B. Increase intestinal phosphate absorption to correct hyperphosphatemia",
     "C. Stimulate erythropoietin production in place of the failed kidney",
     "D. Directly inhibit osteoclast activity to prevent renal osteodystrophy"],
    "A",
    "In CKD, reduced 1-alpha hydroxylase activity impairs conversion of 25-OH vitamin D to calcitriol. Supplementing active vitamin D (calcitriol) or its analogs (paricalcitol, doxercalciferol) suppresses PTH secretion and helps maintain calcium/phosphate homeostasis to manage CKD-MBD.",
    True))

mcq_rows.append(q(S7,"medium",
    "Sevelamer hydrochloride has which additional benefit beyond phosphate binding in CKD?",
    ["A. It provides calcium supplementation to prevent secondary hyperparathyroidism",
     "B. It reduces LDL cholesterol by binding bile acids in addition to phosphate",
     "C. It stimulates FGF-23 production, reducing phosphate absorption",
     "D. It chelates urea, reducing uremic toxin burden in predialysis CKD"],
    "B",
    "Sevelamer hydrochloride (and carbonate) is a non-absorbed polymer that binds phosphate and bile acids in the gut. Clinical studies show sevelamer reduces LDL cholesterol by 15-30%, potentially contributing to cardiovascular benefits in CKD patients who are at high cardiovascular risk. Unlike calcium-based binders, it avoids hypercalcemia.",
    True))

# ─── SUBTOPIC 8: Immunosuppressants in Transplant ────────────────────────────
S8 = "Immunosuppressants in Transplant"
mcq_rows.append(q(S8,"easy",
    "Cyclosporine exerts its immunosuppressive effect primarily by which mechanism?",
    ["A. Inhibiting mTOR (mammalian target of rapamycin), blocking T-cell proliferation",
     "B. Binding cyclophilin, forming a complex that inhibits calcineurin, preventing IL-2 transcription and T-cell activation",
     "C. Blocking purine synthesis, reducing B- and T-cell proliferation",
     "D. Directly lysing alloreactive T cells via Fas-ligand upregulation"],
    "B",
    "Cyclosporine binds intracellular cyclophilin, forming a complex that inhibits calcineurin phosphatase. This prevents dephosphorylation of NFAT (nuclear factor of activated T cells), blocking IL-2 gene transcription and T-cell activation — the central mechanism of cyclosporine immunosuppression.",
    True))

mcq_rows.append(q(S8,"medium",
    "A renal transplant patient on cyclosporine develops hypertension, hirsutism, gingival hyperplasia, and tremor. Which characteristic side effect best helps distinguish cyclosporine from tacrolimus?",
    ["A. Nephrotoxicity — unique to cyclosporine, not tacrolimus",
     "B. Hirsutism and gingival hyperplasia — characteristic of cyclosporine but not tacrolimus",
     "C. Hyperkalemia — characteristic of cyclosporine but not tacrolimus",
     "D. Neurotoxicity — unique to tacrolimus, not cyclosporine"],
    "B",
    "Both cyclosporine and tacrolimus are calcineurin inhibitors with overlapping toxicities (nephrotoxicity, hypertension, hyperkalemia, neurotoxicity). However, hirsutism and gingival hyperplasia are characteristic of cyclosporine. Tacrolimus causes more new-onset diabetes after transplant (NODAT) and alopecia. Tacrolimus does NOT cause hirsutism.",
    True))

mcq_rows.append(q(S8,"medium",
    "Tacrolimus is metabolized by CYP3A4. Which drug interaction is most likely to cause tacrolimus toxicity?",
    ["A. Rifampin (CYP3A4 inducer) — increases tacrolimus levels, causing nephrotoxicity",
     "B. Fluconazole (CYP3A4 inhibitor) — increases tacrolimus levels, causing nephrotoxicity",
     "C. Phenytoin (CYP3A4 inducer) — increases tacrolimus levels, causing nephrotoxicity",
     "D. St. John''s Wort (CYP3A4 inhibitor) — increases tacrolimus levels, causing nephrotoxicity"],
    "B",
    "CYP3A4 inhibitors (azole antifungals like fluconazole, voriconazole; macrolides; grapefruit juice) increase tacrolimus and cyclosporine blood levels, raising the risk of nephrotoxicity and other toxicities. CYP3A4 inducers (rifampin, phenytoin, carbamazepine, St. John''s Wort) decrease levels and risk of rejection.",
    True))

mcq_rows.append(q(S8,"hard",
    "Mycophenolate mofetil (MMF) is used in transplant immunosuppression. What is its mechanism and key adverse effect profile?",
    ["A. Blocks calcineurin, inhibiting IL-2 production; key toxicity is nephrotoxicity and hypertension",
     "B. Inhibits inosine monophosphate dehydrogenase (IMPDH), selectively blocking de novo purine synthesis in lymphocytes; key toxicities are GI effects and bone marrow suppression",
     "C. Blocks mTOR, inhibiting T- and B-cell proliferation; key toxicity is wound healing impairment and hyperlipidemia",
     "D. Inhibits dihydrofolate reductase, blocking all rapidly dividing cells; key toxicity is mucositis"],
    "D",
    "Mycophenolate mofetil is a prodrug converted to mycophenolic acid (MPA), which inhibits IMPDH — the rate-limiting enzyme in de novo purine synthesis. Lymphocytes are uniquely dependent on de novo synthesis (unlike other cells that can use the salvage pathway), making MMF relatively lymphocyte-selective. Key toxicities: GI (diarrhea, nausea), leukopenia, teratogenicity.",
    True))

mcq_rows.append(q(S8,"easy",
    "Which immunosuppressant used in transplant inhibits mTOR signaling?",
    ["A. Cyclosporine",
     "B. Tacrolimus",
     "C. Sirolimus (rapamycin)",
     "D. Mycophenolate mofetil"],
    "A",
    "Sirolimus (rapamycin) and everolimus bind the intracellular receptor FKBP-12, forming a complex that inhibits mTOR (mechanistic target of rapamycin). This blocks the response to IL-2 and other growth signals, preventing T-cell proliferation in G1 phase. Unlike calcineurin inhibitors, mTOR inhibitors do not directly inhibit IL-2 production.",
    True))

mcq_rows.append(q(S8,"medium",
    "A transplant recipient on tacrolimus develops new-onset diabetes (NODAT) 3 months post-transplant. What is the mechanism?",
    ["A. Tacrolimus-induced weight gain causing insulin resistance",
     "B. Tacrolimus inhibits calcineurin in pancreatic beta-cells, impairing insulin gene transcription and secretion",
     "C. Tacrolimus induces glucocorticoid production, causing steroid-induced diabetes",
     "D. Tacrolimus reduces glucagon-like peptide-1 secretion from the gut"],
    "B",
    "Tacrolimus inhibits calcineurin in pancreatic beta-cells (not just T-cells). NFAT in beta-cells is required for insulin gene transcription. Calcineurin inhibition thus impairs insulin synthesis and secretion, causing NODAT. Tacrolimus causes more NODAT than cyclosporine. Concurrent steroid use amplifies the risk.",
    True))

mcq_rows.append(q(S8,"medium",
    "Calcineurin inhibitors (cyclosporine, tacrolimus) cause nephrotoxicity via which mechanism?",
    ["A. Glomerular immune complex deposition leading to membranous nephropathy",
     "B. Afferent arteriolar vasoconstriction causing chronic renal ischemia and tubular injury",
     "C. Direct tubular toxicity from drug accumulation in proximal tubular cells",
     "D. Activation of complement leading to thrombotic microangiopathy"],
    "C",
    "Calcineurin inhibitors cause nephrotoxicity through afferent arteriolar vasoconstriction (reducing renal blood flow and GFR), tubular toxicity, and chronic fibrosis with striped interstitial fibrosis on biopsy. Acute: functional reduction in GFR; chronic: progressive fibrosis. TDM (therapeutic drug monitoring) is essential to balance efficacy and nephrotoxicity.",
    True))

mcq_rows.append(q(S8,"hard",
    "Which statement best describes the rationale for using triple immunosuppression (calcineurin inhibitor + antimetabolite + corticosteroid) in renal transplantation?",
    ["A. Each agent targets the same step in T-cell activation, providing redundancy",
     "B. Each agent targets a different phase of T-cell activation, providing synergistic immunosuppression at lower individual doses, reducing toxicity",
     "C. Triple therapy is required because single agents do not achieve therapeutic blood levels in transplant patients",
     "D. Only triple therapy can prevent both humoral and cellular rejection simultaneously"],
    "D",
    "Triple immunosuppression combines drugs targeting distinct steps: calcineurin inhibitors block IL-2 production (TCR signal 1/3), antimetabolites (MMF, azathioprine) block lymphocyte proliferation (signal 3), and corticosteroids broadly suppress inflammation and antigen presentation (signal 1). This allows lower doses of each agent, reducing individual toxicities while achieving synergistic immunosuppression.",
    True))

mcq_rows.append(q(S8,"easy",
    "Which monitoring parameter is most critical for patients on calcineurin inhibitors (cyclosporine or tacrolimus)?",
    ["A. Serum calcium — risk of hypercalcemia from calcineurin inhibition",
     "B. Trough blood drug levels — narrow therapeutic index requires therapeutic drug monitoring",
     "C. Urinary protein — risk of nephrotic syndrome from immune complex deposition",
     "D. Serum magnesium — both agents cause hypermagnesemia requiring dietary restriction"],
    "B",
    "Calcineurin inhibitors have a narrow therapeutic index. Subtherapeutic levels risk rejection; supratherapeutic levels cause nephrotoxicity, neurotoxicity, hypertension, and infection. Trough whole-blood concentrations are monitored regularly. Target levels vary by time post-transplant and individual patient factors.",
    True))

mcq_rows.append(q(S8,"medium",
    "Sirolimus (rapamycin) is NOT used as the primary calcineurin inhibitor replacement in early post-transplant period. Why?",
    ["A. Sirolimus has no immunosuppressive effect within the first 6 months post-transplant",
     "B. Sirolimus impairs wound healing and is associated with lymphocele formation; it is deferred for several weeks post-transplant",
     "C. Sirolimus causes immediate anaphylaxis in a significant proportion of transplant recipients",
     "D. Sirolimus is ineffective when combined with corticosteroids, the standard post-transplant treatment"],
    "B",
    "mTOR inhibitors like sirolimus impair wound healing (by inhibiting mTOR-dependent cell growth and angiogenesis) and increase the risk of lymphoceles and delayed graft function. They are typically introduced weeks to months post-transplant, after wounds have healed, or as a calcineurin inhibitor-sparing strategy to reduce nephrotoxicity.",
    True))

# ─── SUBTOPIC 9: Urinary Tract Drugs ─────────────────────────────────────────
S9 = "Urinary Tract Drugs"
mcq_rows.append(q(S9,"easy",
    "Tamsulosin is used in benign prostatic hyperplasia (BPH). What is its mechanism of action?",
    ["A. Blocking alpha-1A adrenergic receptors in the prostate and bladder neck, reducing smooth muscle tone and urinary obstruction",
     "B. Inhibiting 5-alpha reductase, reducing DHT-mediated prostate growth",
     "C. Blocking muscarinic receptors in the detrusor muscle, reducing bladder spasm",
     "D. Antagonizing beta-3 adrenergic receptors in the bladder wall, increasing bladder capacity"],
    "A",
    "Tamsulosin is an alpha-1A selective adrenergic receptor antagonist. Alpha-1A receptors are predominantly expressed in the prostate stroma and bladder neck. Blockade relaxes smooth muscle, reducing urethral resistance and improving urine flow in BPH. Its selectivity for alpha-1A over alpha-1B (vascular) reduces orthostatic hypotension compared to non-selective alpha-blockers.",
    True))

mcq_rows.append(q(S9,"medium",
    "A patient with BPH starts tamsulosin and is scheduled for cataract surgery. Which surgical complication must be disclosed to the ophthalmologist?",
    ["A. Tamsulosin causes corneal clouding, complicating cataract extraction",
     "B. Intraoperative floppy iris syndrome (IFIS) — alpha-1 blockade relaxes iris dilator muscle causing iris billowing and prolapse during surgery",
     "C. Tamsulosin increases IOP, complicating intraocular lens insertion",
     "D. Tamsulosin causes miosis that cannot be reversed with atropine during surgery"],
    "B",
    "Intraoperative floppy iris syndrome (IFIS) is associated with alpha-1 adrenergic antagonist use (especially tamsulosin). The iris dilator muscle contains alpha-1A receptors; blockade causes iris flaccidity, billowing of iris stroma, and tendency to prolapse through cataract incisions. Ophthalmologists must be informed before surgery to modify their technique.",
    True))

mcq_rows.append(q(S9,"medium",
    "Oxybutynin is used for overactive bladder (OAB). What is its pharmacological mechanism?",
    ["A. Beta-3 adrenergic agonist causing detrusor muscle relaxation and increased bladder capacity",
     "B. Anticholinergic (muscarinic receptor antagonist) that reduces involuntary detrusor contractions",
     "C. Alpha-1 adrenergic agonist increasing urethral sphincter tone",
     "D. Potassium channel opener causing detrusor smooth muscle hyperpolarization"],
    "C",
    "Oxybutynin is a muscarinic receptor antagonist (anticholinergic) with selectivity for M2 and M3 receptors in the detrusor muscle. Blocking M3 receptors prevents acetylcholine-mediated detrusor contractions, increasing bladder capacity and reducing urgency and frequency. It also has direct smooth muscle relaxant and local anesthetic properties.",
    True))

mcq_rows.append(q(S9,"hard",
    "An elderly man with BPH and a history of urinary retention is started on finasteride. What is the mechanism and expected timeline for clinical benefit?",
    ["A. Finasteride blocks testosterone synthesis; maximum benefit within 1 week",
     "B. Finasteride inhibits 5-alpha reductase type 2, reducing DHT-mediated prostate growth; symptom improvement takes 3-6 months due to slow prostate size reduction",
     "C. Finasteride blocks alpha-1 receptors; smooth muscle relaxation occurs within hours",
     "D. Finasteride inhibits estrogen receptors in the prostate, allowing testosterone-mediated shrinkage"],
    "D",
    "Finasteride (and dutasteride) inhibit 5-alpha reductase, preventing conversion of testosterone to dihydrotestosterone (DHT) — the primary androgen driving prostate growth. The result is prostate volume reduction of ~20-30% over 3-6 months. Unlike alpha-blockers (rapid symptom relief), 5-ARI benefit takes months because glandular involution is gradual.",
    True))

mcq_rows.append(q(S9,"easy",
    "Mirabegron is a newer treatment for overactive bladder. How does it differ mechanistically from oxybutynin?",
    ["A. Mirabegron blocks M3 muscarinic receptors more selectively than oxybutynin",
     "B. Mirabegron is a beta-3 adrenergic receptor agonist that relaxes the detrusor muscle without anticholinergic side effects",
     "C. Mirabegron blocks alpha-1 adrenergic receptors in the bladder neck to reduce outlet resistance",
     "D. Mirabegron is a calcium channel blocker that prevents detrusor smooth muscle contraction"],
    "A",
    "Mirabegron activates beta-3 adrenergic receptors in the detrusor, causing smooth muscle relaxation and increasing bladder storage capacity. Unlike anticholinergics (oxybutynin, tolterodine), it does not cause dry mouth, constipation, urinary retention, or cognitive impairment — making it preferred in elderly patients or those with contraindications to anticholinergics.",
    True))

mcq_rows.append(q(S9,"medium",
    "Dutasteride differs from finasteride in its inhibition of 5-alpha reductase. Which statement is correct?",
    ["A. Finasteride inhibits both type 1 and type 2 5-alpha reductase; dutasteride inhibits only type 2",
     "B. Dutasteride inhibits both type 1 and type 2 5-alpha reductase; finasteride inhibits only type 2",
     "C. Both drugs inhibit only type 1 isoenzyme, which predominates in the prostate",
     "D. Dutasteride has a shorter half-life than finasteride due to rapid hepatic metabolism"],
    "B",
    "Finasteride selectively inhibits 5-alpha reductase type 2 (predominantly in the prostate and genital skin). Dutasteride inhibits both type 1 (skin, liver, brain) and type 2, producing a more complete suppression of DHT (>90% vs ~70% with finasteride). Dutasteride also has a much longer half-life (~5 weeks vs ~6 hours for finasteride).",
    True))

mcq_rows.append(q(S9,"medium",
    "Phenazopyridine is used for urinary tract discomfort. What must patients be warned about?",
    ["A. It is an antibiotic that may select for resistant organisms if used without culture guidance",
     "B. It causes orange-red discoloration of urine, tears, and contact lenses, which is harmless but expected",
     "C. It causes acute urinary retention by stimulating urethral sphincter contraction",
     "D. It causes dangerous serotonin syndrome when combined with antibiotics"],
    "B",
    "Phenazopyridine is a urinary analgesic (not an antibiotic) that relieves dysuria, urgency, and frequency. It is metabolized to orange-red azo dyes excreted in urine, which stain urine, contact lenses, and clothing. Patients must be warned that this discoloration is expected and harmless. It is typically used for only 1-2 days as a urinary analgesic while antibiotic therapy takes effect.",
    True))

mcq_rows.append(q(S9,"hard",
    "Which drug is used for neurogenic detrusor overactivity in spinal cord injury patients and works by a different mechanism than standard anticholinergics?",
    ["A. Bethanechol — a muscarinic agonist that strengthens detrusor contractions",
     "B. Intravesical onabotulinumtoxin A — blocks acetylcholine release at neuromuscular junctions in the detrusor, reducing involuntary contractions",
     "C. Desmopressin — an ADH analog that reduces urine production",
     "D. Tamsulosin — reduces outlet resistance to facilitate bladder emptying"],
    "D",
    "Onabotulinumtoxin A (Botox) injected directly into the detrusor muscle cleaves SNAP-25 proteins required for acetylcholine vesicle fusion at neuromuscular junctions. This blocks involuntary detrusor contractions for 6-12 months. It is highly effective for neurogenic detrusor overactivity and anticholinergic-resistant OAB, though patients must be able to perform self-catheterization due to urinary retention risk.",
    True))

mcq_rows.append(q(S9,"easy",
    "Bethanechol is used for urinary retention (non-obstructive). What is its mechanism?",
    ["A. Alpha-adrenergic blockade reducing urethral resistance",
     "B. Muscarinic receptor agonism stimulating detrusor contraction and bladder emptying",
     "C. 5-alpha reductase inhibition reducing prostate volume",
     "D. Beta-3 agonism relaxing the detrusor to increase bladder capacity"],
    "A",
    "Bethanechol is a direct muscarinic (M3) agonist that stimulates detrusor smooth muscle contraction, facilitating bladder emptying. It is used for non-obstructive urinary retention (e.g., postoperative atony, neurogenic bladder). It is contraindicated in obstructive uropathy (BPH) as it can cause bladder rupture.",
    True))

mcq_rows.append(q(S9,"medium",
    "Tolterodine is preferred over oxybutynin in some patients for overactive bladder. Why?",
    ["A. Tolterodine is more potent and requires less frequent dosing",
     "B. Tolterodine is more selective for bladder M3 receptors and causes fewer CNS anticholinergic effects (less cognitive impairment) than oxybutynin",
     "C. Tolterodine works faster than oxybutynin by bypassing first-pass metabolism",
     "D. Tolterodine does not cause dry mouth, unlike oxybutynin"],
    "B",
    "Tolterodine has greater selectivity for bladder muscarinic receptors over salivary glands and crosses the blood-brain barrier less readily than oxybutynin, resulting in fewer CNS anticholinergic effects (confusion, cognitive impairment) — important in elderly patients. Extended-release formulations of both drugs reduce side effects compared to immediate-release.",
    True))

# ─── SUBTOPIC 10: Drug-Induced Nephrotoxicity ────────────────────────────────
S10 = "Drug-Induced Nephrotoxicity"
mcq_rows.append(q(S10,"easy",
    "Aminoglycoside antibiotics (e.g., gentamicin) most commonly cause which pattern of nephrotoxicity?",
    ["A. Membranous nephropathy with nephrotic-range proteinuria",
     "B. Non-oliguric acute tubular necrosis affecting the proximal tubule",
     "C. Acute interstitial nephritis with eosinophilia",
     "D. Hemolytic uremic syndrome with thrombotic microangiopathy"],
    "B",
    "Aminoglycosides are polycationic and bind to the brush border of proximal tubular cells, where they are endocytosed and accumulate. They generate reactive oxygen species, disrupt mitochondrial function, and cause tubular cell necrosis. Characteristically non-oliguric AKI (tubular cells still produce urine but cannot concentrate it). Once-daily dosing reduces nephrotoxicity.",
    True))

mcq_rows.append(q(S10,"medium",
    "Cisplatin causes nephrotoxicity through which primary mechanism?",
    ["A. Allergic interstitial nephritis from platinum-protein hapten formation",
     "B. DNA cross-linking in renal proximal tubular cells, causing oxidative stress, inflammation, and tubular cell death",
     "C. Glomerular immune complex deposition causing proliferative glomerulonephritis",
     "D. Renal artery thrombosis from platelet activation"],
    "B",
    "Cisplatin accumulates in proximal tubular cells, where it forms DNA intrastrand and interstrand crosslinks (same mechanism as antitumor activity). This triggers p53-mediated apoptosis, oxidative stress, and mitochondrial dysfunction. Clinical pearl: prophylaxis with aggressive IV saline hydration, mannitol, and amifostine can reduce cisplatin nephrotoxicity.",
    True))

mcq_rows.append(q(S10,"medium",
    "A patient on long-term lithium develops polyuria of 6 liters/day that does not respond to exogenous desmopressin (DDAVP). What is the diagnosis and mechanism?",
    ["A. Central diabetes insipidus — lithium destroys the posterior pituitary",
     "B. Nephrogenic diabetes insipidus — lithium blocks V2 receptor-mediated aquaporin-2 insertion in the collecting duct",
     "C. Primary polydipsia — lithium stimulates thirst centers in the hypothalamus",
     "D. Osmotic diuresis — lithium inhibits glucose reabsorption causing glucosuria"],
    "B",
    "Lithium enters principal cells of the collecting duct via ENaC and intracellularly inhibits the adenylyl cyclase signaling downstream of V2 receptors. This prevents cAMP-mediated aquaporin-2 insertion into the apical membrane, causing nephrogenic DI. Since the defect is at the renal level (not ADH deficiency), desmopressin is ineffective. Amiloride (blocks ENaC, reducing lithium entry) can help.",
    True))

mcq_rows.append(q(S10,"hard",
    "Which mechanism best explains why NSAIDs cause AKI predominantly in states of reduced effective circulating volume (heart failure, cirrhosis, dehydration) rather than in healthy individuals?",
    ["A. NSAID metabolism produces nephrotoxic metabolites only in the presence of reduced perfusion",
     "B. In states of reduced renal perfusion, afferent arteriolar vasodilation by prostaglandins becomes critical to maintaining GFR; NSAIDs remove this compensatory vasodilation",
     "C. NSAIDs accumulate to higher concentrations in the kidney when cardiac output is low",
     "D. Reduced effective volume increases renal angiotensin II, which synergizes with NSAID toxicity via ROS generation"],
    "D",
    "Under normal conditions, renal prostaglandins play a minor role in renal blood flow regulation. However, in states of reduced effective circulating volume, activation of vasoconstrictive systems (angiotensin II, norepinephrine, ADH) threatens renal blood flow. Prostaglandins (PGE2, PGI2) act as a counter-regulatory vasodilatory mechanism. NSAIDs remove this protective vasodilation, leading to unopposed vasoconstriction and AKI.",
    True))

mcq_rows.append(q(S10,"easy",
    "Acute interstitial nephritis (AIN) is a hypersensitivity nephrotoxicity pattern commonly caused by which drug classes?",
    ["A. Aminoglycosides and cisplatin",
     "B. Beta-lactam antibiotics (penicillins, cephalosporins), NSAIDs, and proton pump inhibitors",
     "C. ACE inhibitors and ARBs",
     "D. Calcineurin inhibitors (cyclosporine, tacrolimus)"],
    "A",
    "Acute interstitial nephritis (AIN) is an immune-mediated reaction causing interstitial inflammation and tubular damage. Classic causes include beta-lactam antibiotics, NSAIDs, proton pump inhibitors (most common cause of drug-induced AIN currently), sulfonamides, and rifampin. Classic triad: fever, rash, eosinophilia — though often absent. Eosinophiluria is a classic but insensitive finding.",
    True))

mcq_rows.append(q(S10,"medium",
    "Contrast-induced nephropathy (CIN) risk can be reduced by which prophylactic strategy with the strongest evidence?",
    ["A. Pre-procedure oral acetylcysteine alone",
     "B. IV isotonic saline hydration before and after contrast administration",
     "C. Pre-procedure furosemide to promote diuresis",
     "D. Bicarbonate infusion alone for 12 hours prior to contrast"],
    "B",
    "IV isotonic saline hydration before and after iodinated contrast administration has the strongest evidence for preventing CIN. It dilutes contrast in the tubular lumen, reduces tubular concentration, and improves renal medullary blood flow. N-acetylcysteine (NAC) has uncertain benefit. Pre-contrast furosemide is harmful. Using the lowest effective contrast dose and iso-osmolar contrast also reduces risk.",
    True))

mcq_rows.append(q(S10,"medium",
    "Tenofovir (antiviral for HIV/HBV) can cause which renal syndrome?",
    ["A. Membranous nephropathy from immune complex deposition",
     "B. Fanconi syndrome from proximal tubular dysfunction with phosphaturia, glucosuria, aminoaciduria, and hypophosphatemia",
     "C. Distal renal tubular acidosis from collecting duct dysfunction",
     "D. Papillary necrosis from medullary ischemia"],
    "C",
    "Tenofovir disoproxil fumarate (TDF) accumulates in proximal tubular cells and inhibits mitochondrial DNA polymerase gamma, causing mitochondrial dysfunction. This results in proximal tubular dysfunction — full Fanconi syndrome (phosphaturia, glucosuria, proteinuria, aminoaciduria) and can progress to AKI. Tenofovir alafenamide (TAF) has lower nephrotoxicity due to reduced tubular concentration.",
    True))

mcq_rows.append(q(S10,"hard",
    "A patient with multiple myeloma is treated with high-dose IV methotrexate. What renal toxicity is expected and what is the prevention strategy?",
    ["A. Interstitial nephritis — treated with corticosteroids",
     "B. Tubular precipitation of methotrexate crystals in acidic urine — prevented by urinary alkalinization with sodium bicarbonate and aggressive hydration",
     "C. Glomerulonephritis from immune complex deposition — prevented by antihistamines",
     "D. Renal vein thrombosis — prevented by anticoagulation"],
    "D",
    "High-dose methotrexate (and its metabolite 7-OH-methotrexate) precipitates in renal tubules at acidic pH, causing intratubular obstruction and AKI. Prevention: (1) aggressive IV hydration to maintain high urine flow, (2) urinary alkalinization with sodium bicarbonate (target urine pH >7) to increase methotrexate solubility, (3) leucovorin rescue to protect normal cells. Carboxypeptidase G2 (glucarpidase) is used to rescue patients with toxic methotrexate levels.",
    True))

mcq_rows.append(q(S10,"easy",
    "Which statement best describes the risk of nephrotoxicity with aminoglycosides and how dosing strategy affects it?",
    ["A. Divided doses (TID) are safer than once-daily dosing as they produce lower peak concentrations",
     "B. Once-daily dosing reduces nephrotoxicity by allowing a trough period during which proximal tubular cells can clear accumulated drug",
     "C. Nephrotoxicity is independent of dosing frequency and depends only on total cumulative dose",
     "D. Aminoglycoside nephrotoxicity is irreversible regardless of dosing strategy"],
    "B",
    "Aminoglycoside uptake into proximal tubular cells is saturable (concentration-dependent). Once-daily dosing achieves a high bactericidal peak concentration (exploiting concentration-dependent killing) but allows a drug-free trough period during which tubular cells can export accumulated drug. This trough period reduces total tubular accumulation and nephrotoxicity compared to multiple daily doses.",
    True))

mcq_rows.append(q(S10,"medium",
    "Vancomycin nephrotoxicity is potentiated by concurrent use of which drug class?",
    ["A. Fluoroquinolones — direct tubular toxicity synergy",
     "B. Loop diuretics — volume depletion increases vancomycin concentration in tubular lumen",
     "C. Aminoglycosides — additive/synergistic proximal tubular toxicity",
     "D. Beta-lactams — inhibit tubular secretion of vancomycin, raising serum levels"],
    "C",
    "Vancomycin and aminoglycosides both cause proximal tubular toxicity, and their combination is synergistically nephrotoxic. The combination is common in severe infections (e.g., MRSA endocarditis with gram-negative organisms), requiring close renal function monitoring, TDM for both drugs, and adequate hydration.",
    True))

# Write SQL file
output_path = '/sessions/keen-ecstatic-cannon/mnt/Skoolie/scripts/med_renal_pharm_mcq.sql'
with open(output_path, 'w') as f:
    f.write("-- Renal System Pharmacology MCQs\n")
    f.write("-- 100 questions across 10 subtopics (10 each)\n")
    f.write("-- Source: Lippincott Illustrated Reviews Pharmacology 7th Ed\n\n")
    for row in mcq_rows:
        f.write(row + "\n\n")

print(f"Written {len(mcq_rows)} MCQ rows to {output_path}")
