#!/usr/bin/env python3
"""
Generate 100 Renal System Pharmacology MCQs.
Correct answer sequence per subtopic: A,B,C,D,A,B,C,D,A,B (Q1-Q10).
Options are rotated so the factually correct content falls at the required letter.
"""

YL = "'{year1,year2,year3,year4,year5,year6,practitioner}'"
SRC = "Lippincott Illustrated Reviews Pharmacology 7th Ed"
PROF = '\'{"medicine"}\''

# Required correct_answer pattern per subtopic (Q1..Q10)
PATTERN = ['A','B','C','D','A','B','C','D','A','B']

def build(subtopic, difficulty, question_text, correct_content, distractors, correct_pos, explanation, high_yield):
    """
    correct_pos: 0=A, 1=B, 2=C, 3=D
    correct_content: the correct answer text (without letter prefix)
    distractors: list of 3 distractor texts (without letter prefix)
    """
    assert len(distractors) == 3
    options_content = []
    letters = ['A','B','C','D']
    # Insert correct answer at correct_pos, distractors fill rest
    d_iter = iter(distractors)
    for i in range(4):
        if i == correct_pos:
            options_content.append(correct_content)
        else:
            options_content.append(next(d_iter))

    opts = [f"{letters[i]}. {options_content[i]}" for i in range(4)]
    correct_letter = letters[correct_pos]

    opts_escaped = [o.replace("'", "''") for o in opts]
    opts_json = '["' + '","'.join(opts_escaped) + '"]'
    qt = question_text.replace("'", "''")
    ex = explanation.replace("'", "''")
    st = subtopic.replace("'", "''")
    hy = 'true' if high_yield else 'false'

    return (
        f"INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, "
        f"question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES\n"
        f"({PROF},'Medicine','Renal System','Pharmacology','{st}','{difficulty}','mcq','{qt}','{opts_json}',"
        f"'{correct_letter}','{ex}','universal',{hy},{YL},'{SRC}');"
    )

rows = []

# Helper: convert PATTERN letter to index
def pi(n):
    return {'A':0,'B':1,'C':2,'D':3}[PATTERN[n]]

# ─── SUBTOPIC 1: Loop Diuretics ───────────────────────────────────────────────
S1 = "Loop Diuretics"
# Q1 → A (index 0)
rows.append(build(S1,"easy",
    "Furosemide exerts its primary diuretic action by inhibiting which transporter in the nephron?",
    "Na+/K+/2Cl- cotransporter (NKCC2) in the thick ascending limb of the loop of Henle",
    ["Na+/Cl- cotransporter in the distal convoluted tubule",
     "Epithelial sodium channel (ENaC) in the collecting duct",
     "Na+/K+-ATPase pump in the proximal convoluted tubule"],
    pi(0),
    "Loop diuretics inhibit NKCC2 in the thick ascending limb, blocking reabsorption of 25-30% of filtered NaCl — the greatest diuretic efficacy of any class.",
    True))

# Q2 → B (index 1)
rows.append(build(S1,"medium",
    "Which adverse effect of loop diuretics most commonly requires potassium supplementation?",
    "Hypokalemia — excess Na+ delivery to collecting duct drives Na+/K+ exchange and K+ loss",
    ["Hyperkalemia from aldosterone receptor blockade",
     "Hypernatremia from free water retention",
     "Hypomagnesemia from proximal tubular inhibition"],
    pi(1),
    "The heavy Na+ load delivered to the collecting tubule increases K+ secretion. Hypokalemia is the most common electrolyte adverse effect of loop diuretics; it may require K+ supplementation or addition of a K+-sparing diuretic.",
    True))

# Q3 → C (index 2)
rows.append(build(S1,"medium",
    "Loop diuretics cause hypercalciuria rather than hypocalciuria. What is the mechanism?",
    "Inhibition of NKCC2 collapses the lumen-positive voltage that drives paracellular Ca2+ reabsorption in the ascending loop",
    ["Loop diuretics inhibit parathyroid hormone secretion",
     "Loop diuretics directly inhibit calcium channels in the distal convoluted tubule",
     "Loop diuretics increase aldosterone, which promotes Ca2+ excretion"],
    pi(2),
    "In the thick ascending limb, paracellular Ca2+ reabsorption depends on the lumen-positive electrical gradient generated by NKCC2. Loop diuretics remove this driving force, increasing Ca2+ excretion — the opposite of thiazides.",
    True))

# Q4 → D (index 3)
rows.append(build(S1,"hard",
    "A patient with oliguric AKI (eGFR 10 mL/min) remains fluid overloaded despite standard IV furosemide. The most appropriate next step is:",
    "Increase the furosemide dose, since higher doses are needed to cross the secretory threshold at low GFR",
    ["Switch to hydrochlorothiazide, which is more effective at low GFR",
     "Discontinue all diuretics as they are contraindicated in AKI",
     "Switch to spironolactone which does not require renal secretion"],
    pi(3),
    "Loop diuretics require proximal tubule secretion to reach the tubular lumen. In severe renal dysfunction, reduced secretion raises the dose needed to cross the response threshold. Higher IV doses (or continuous infusion) restore tubular drug concentration. Loop diuretics are not contraindicated in AKI.",
    True))

# Q5 → A (index 0)
rows.append(build(S1,"easy",
    "Which loop diuretic is preferred for reliable oral outpatient dosing due to predictable bioavailability?",
    "Torsemide — 80-100% oral bioavailability compared to furosemide''s variable 10-90%",
    ["Furosemide — because it is the most widely studied loop diuretic",
     "Ethacrynic acid — preferred in all outpatients due to non-sulfonamide structure",
     "Bumetanide IV only — no reliable oral formulation exists"],
    pi(4),
    "Torsemide and bumetanide both have reliable oral bioavailability of 80-100%, making them preferred for outpatient oral therapy. Furosemide''s variable absorption (10-90%) can produce unpredictable diuretic responses.",
    True))

# Q6 → B (index 1)
rows.append(build(S1,"medium",
    "A patient develops sensorineural hearing loss after rapid IV furosemide infusion. What is the mechanism of ototoxicity?",
    "Inhibition of NKCC1 in the stria vascularis of the cochlea disrupts the endocochlear potential",
    ["Free radical generation in the cochlea by furosemide metabolites",
     "Direct blockade of calcium channels in inner hair cells",
     "Furosemide accumulation in the auditory cortex causing central deafness"],
    pi(5),
    "Loop diuretics inhibit NKCC1 (the non-renal isoform in the stria vascularis), disrupting the endocochlear potential required for hair cell transduction. Risk is highest with rapid IV infusion, high doses, and concurrent aminoglycosides. Ethacrynic acid is most ototoxic.",
    True))

# Q7 → C (index 2)
rows.append(build(S1,"medium",
    "Which best describes the dose-response curve of loop diuretics?",
    "Sigmoidal curve: threshold effect → steep rise in diuresis → ceiling above which more drug produces no more response",
    ["Linear increase proportional to dose with no ceiling",
     "Flat curve because they are ''low-ceiling'' diuretics like thiazides",
     "Inverse relationship — higher doses suppress diuresis via tubular feedback"],
    pi(6),
    "The sigmoidal dose-response has three phases: (1) below the threshold — no diuresis; (2) steep phase — small dose increases produce large diuresis changes; (3) ceiling — no additional diuresis with higher doses. Clinicians adjust frequency, not dose beyond the ceiling.",
    True))

# Q8 → D (index 3)
rows.append(build(S1,"hard",
    "A heart failure patient on furosemide starts indomethacin for gout. Which interaction is most clinically significant?",
    "Indomethacin inhibits renal prostaglandin synthesis, reducing furosemide''s diuretic and vasodilatory efficacy",
    ["Indomethacin blocks furosemide secretion into the proximal tubule via OAT competition",
     "Combined use causes severe hyperkalemia via aldosterone suppression",
     "Indomethacin increases furosemide bioavailability by inhibiting P-glycoprotein"],
    pi(7),
    "NSAIDs inhibit prostaglandin synthesis. Renal prostaglandins (PGE2, PGI2) contribute to tubular secretion of furosemide and its vasodilatory pre-diuretic effect. NSAIDs blunt both mechanisms, reducing diuretic response — a clinically important pharmacodynamic interaction.",
    True))

# Q9 → A (index 0)
rows.append(build(S1,"easy",
    "Loop diuretics are drugs of choice for which acute emergency?",
    "Acute pulmonary edema — rapid IV onset, potent diuresis, and immediate venodilation reduce left ventricular filling pressure",
    ["Nephrogenic diabetes insipidus — thiazides are preferred for this indication",
     "Idiopathic hypercalciuria — thiazides are preferred to reduce Ca2+ excretion",
     "Mild essential hypertension as first-line monotherapy"],
    pi(8),
    "Loop diuretics (particularly IV furosemide) provide rapid relief in acute pulmonary edema through: (1) prostaglandin-mediated venodilation within minutes of administration, and (2) subsequent potent diuresis. They are also used for hypercalcemia of malignancy.",
    True))

# Q10 → B (index 1)
rows.append(build(S1,"medium",
    "Why is furosemide used acutely to treat hypercalcemia of malignancy?",
    "Furosemide increases urinary Ca2+ excretion by blocking paracellular Ca2+ reabsorption in the ascending loop of Henle",
    ["Furosemide blocks intestinal calcium absorption by inhibiting vitamin D activation",
     "Furosemide inhibits parathyroid hormone release from the parathyroid gland",
     "Furosemide promotes Ca2+ uptake into bone by stimulating osteoblast activity"],
    pi(9),
    "Loop diuretics collapse the lumen-positive voltage in the thick ascending limb, reducing the electrochemical driving force for paracellular Ca2+ reabsorption. Combined with aggressive IV saline hydration, furosemide promotes calciuresis and lowers serum Ca2+.",
    True))

# ─── SUBTOPIC 2: Thiazide Diuretics ──────────────────────────────────────────
S2 = "Thiazide Diuretics"
# Q1 → A
rows.append(build(S2,"easy",
    "Hydrochlorothiazide inhibits which transporter in the nephron?",
    "Na+/Cl- cotransporter (NCC) in the distal convoluted tubule",
    ["Na+/K+/2Cl- cotransporter in the ascending loop of Henle",
     "Epithelial sodium channel (ENaC) in the collecting duct",
     "Na+/H+ exchanger in the proximal convoluted tubule"],
    pi(0),
    "Thiazides inhibit the NCC in the DCT, reducing reabsorption of 5-10% of filtered NaCl. They are ''low-ceiling'' diuretics with limited maximum diuretic effect compared to loop diuretics.",
    True))

# Q2 → B
rows.append(build(S2,"medium",
    "A patient on hydrochlorothiazide develops gout. What is the mechanism of thiazide-induced hyperuricemia?",
    "Thiazides compete with uric acid for the organic acid secretory system in the proximal tubule, reducing uric acid excretion",
    ["Thiazides directly activate xanthine oxidase, increasing uric acid synthesis",
     "Thiazides increase GFR, accelerating filtration and precipitation of uric acid",
     "Thiazides inhibit tubular uric acid reabsorption, paradoxically causing urate deposition"],
    pi(1),
    "Thiazides are organic acids secreted by the proximal tubule. They compete with uric acid at the OAT1/OAT3 transporters, reducing uric acid secretion and raising serum urate. This can precipitate gout attacks in predisposed individuals.",
    True))

# Q3 → C
rows.append(build(S2,"medium",
    "How does thiazide diuretic use affect urinary calcium, and how does this differ from loop diuretics?",
    "Thiazides DECREASE urinary Ca2+ excretion (promote DCT Ca2+ reabsorption); loop diuretics INCREASE Ca2+ excretion (block ascending limb paracellular reabsorption)",
    ["Both classes increase urinary Ca2+ excretion equally",
     "Thiazides increase Ca2+ excretion; loop diuretics decrease it",
     "Neither class significantly affects urinary calcium handling"],
    pi(2),
    "This is a high-yield distinction: thiazides → hypocalciuria (useful for nephrolithiasis/hypercalciuria); loop diuretics → hypercalciuria (useful for hypercalcemia). Thiazides promote Ca2+ reabsorption in the DCT via PTH-regulated mechanisms.",
    True))

# Q4 → D
rows.append(build(S2,"hard",
    "A patient with nephrogenic diabetes insipidus is prescribed hydrochlorothiazide and urine output decreases paradoxically. What is the mechanism?",
    "Mild thiazide-induced volume depletion increases proximal tubule Na+ and water reabsorption, reducing distal delivery and overall urine volume despite ADH insensitivity",
    ["Thiazides stimulate V2 receptors, restoring aquaporin-2 insertion in the collecting duct",
     "Thiazides block prostaglandin synthesis, partially restoring ADH sensitivity",
     "Thiazides directly activate ADH release from the posterior pituitary"],
    pi(3),
    "The paradox: thiazide-induced mild hypovolemia triggers compensatory proximal tubule Na+ and water reabsorption. Less fluid reaches ADH-insensitive collecting duct segments, reducing total urine output. This mechanism makes thiazides therapeutic in nephrogenic DI.",
    True))

# Q5 → A
rows.append(build(S2,"easy",
    "What is the most frequent electrolyte adverse effect of thiazide diuretics?",
    "Hypokalemia — increased Na+ delivery to the collecting duct drives K+ secretion via Na+/K+ exchange",
    ["Hyperkalemia from distal tubule Na+ retention",
     "Hypercalcemia from excess Ca2+ absorption",
     "Hypermagnesemia from reduced Mg2+ excretion"],
    pi(4),
    "Hypokalemia is the most common adverse effect of thiazides. More Na+ reaches the collecting duct, driving K+ secretion. Serum K+ should be monitored, and K+ supplementation or a K+-sparing diuretic may be required.",
    True))

# Q6 → B
rows.append(build(S2,"medium",
    "Indapamide differs from hydrochlorothiazide in pharmacokinetics. Which statement is correct?",
    "Indapamide undergoes hepatic metabolism and biliary/renal excretion; hydrochlorothiazide is excreted primarily unchanged in urine",
    ["Hydrochlorothiazide undergoes extensive hepatic metabolism; indapamide is eliminated unchanged",
     "Indapamide must be administered intravenously; HCTZ is oral only",
     "Indapamide has a shorter half-life than HCTZ and requires three-times-daily dosing"],
    pi(5),
    "Indapamide is unique among thiazide-like diuretics in undergoing significant hepatic metabolism with excretion in both bile and urine. Most other thiazides are excreted unchanged in urine, making renal function critical for their clearance.",
    True))

# Q7 → C
rows.append(build(S2,"medium",
    "A patient with type 2 diabetes asks if thiazides are safe for hypertension management. Which statement is most accurate?",
    "Thiazides can cause mild hyperglycemia (possibly via hypokalemia-impaired insulin release), but patients with diabetes still benefit and should monitor glucose",
    ["Thiazides are absolutely contraindicated in type 2 diabetes due to severe hypoglycemia risk",
     "Thiazides improve insulin sensitivity and are the preferred antihypertensive in diabetes",
     "Thiazides are contraindicated only if HbA1c >8% at baseline"],
    pi(6),
    "Thiazide-induced hypokalemia can impair pancreatic beta-cell insulin secretion, causing mild hyperglycemia. However, patients with diabetes are not excluded from thiazide therapy — the cardiovascular benefits typically outweigh the mild glucose effect.",
    True))

# Q8 → D
rows.append(build(S2,"hard",
    "Why do thiazides lose diuretic efficacy (but retain some antihypertensive effect) when eGFR falls below 30 mL/min?",
    "Reduced proximal tubular secretion in advanced CKD limits the amount of thiazide reaching the NCC in the DCT below the therapeutic threshold",
    ["Thiazides are metabolized by the kidney and accumulate in CKD, saturating their own receptors",
     "NCC is upregulated in CKD, overcoming thiazide blockade",
     "Reduced aldosterone in CKD renders the distal tubule unresponsive to thiazide-mediated Na+ delivery"],
    pi(7),
    "Thiazides must be secreted into the proximal tubule lumen to reach the DCT. In CKD, reduced OAT secretory capacity means insufficient drug reaches NCC. Antihypertensive effects may persist via vasodilatory mechanisms even when diuresis is inadequate.",
    True))

# Q9 → A
rows.append(build(S2,"easy",
    "A patient with recurrent calcium oxalate nephrolithiasis due to idiopathic hypercalciuria benefits from which diuretic class?",
    "Thiazide diuretics — promote Ca2+ reabsorption in the DCT, reducing urinary calcium and the risk of stone formation",
    ["Loop diuretics — promote Ca2+ excretion, helpful for stones",
     "Potassium-sparing diuretics — reduce urinary Ca2+ by blocking aldosterone",
     "Osmotic diuretics — dilute urinary calcium concentration, preventing stone formation"],
    pi(8),
    "Thiazides reduce Ca2+ excretion via PTH-regulated Ca2+ reabsorption in the DCT. This is the drug-of-choice for idiopathic hypercalciuria and primary prevention of recurrent Ca2+ nephrolithiasis.",
    True))

# Q10 → B
rows.append(build(S2,"medium",
    "Why might some clinicians prefer chlorthalidone over HCTZ for hypertension management?",
    "Chlorthalidone has a longer half-life (50-60 hours vs 10-15 hours for HCTZ), providing sustained 24-hour blood pressure control with once-daily dosing",
    ["Chlorthalidone is a more potent diuretic at equivalent doses with no additional metabolic side effects",
     "Chlorthalidone does not cause hypokalemia unlike HCTZ",
     "Chlorthalidone is the only thiazide that does not cause hyperuricemia"],
    pi(9),
    "Chlorthalidone''s prolonged half-life may provide more consistent blood pressure control over a 24-hour period. It is also approximately twice as potent as HCTZ. However, current guidelines do not preferentially recommend one thiazide over another.",
    True))

# ─── SUBTOPIC 3: Potassium-Sparing Diuretics ─────────────────────────────────
S3 = "Potassium-Sparing Diuretics"
# Q1 → A
rows.append(build(S3,"easy",
    "Spironolactone produces its diuretic and potassium-sparing effects through which mechanism?",
    "Competitive antagonism of aldosterone receptors in the collecting duct principal cells, preventing synthesis of Na+-retaining proteins",
    ["Direct blockade of epithelial Na+ channels (ENaC) independent of aldosterone",
     "Inhibition of Na+/K+/2Cl- cotransporter in the ascending limb",
     "Inhibition of carbonic anhydrase in the proximal tubule"],
    pi(0),
    "Spironolactone binds the mineralocorticoid receptor, preventing its translocation to the nucleus and blocking aldosterone-induced synthesis of ENaC and Na+/K+-ATPase. This reduces Na+ reabsorption and K+ secretion in the collecting duct.",
    True))

# Q2 → B
rows.append(build(S3,"medium",
    "A renal transplant patient on spironolactone develops gynecomastia. Which drug from the same class avoids this adverse effect?",
    "Eplerenone — more selective for mineralocorticoid receptors; does not bind androgen or progesterone receptors",
    ["Amiloride — blocks ENaC directly without binding steroid receptors",
     "Triamterene — weaker mineralocorticoid receptor affinity than spironolactone",
     "Furosemide — has no sex hormone receptor interactions"],
    pi(1),
    "Spironolactone''s lack of receptor selectivity leads to antiandrogenic effects (gynecomastia, breast tenderness, menstrual irregularity, impotence). Eplerenone is selective for mineralocorticoid receptors, avoiding these sex hormone-mediated effects.",
    True))

# Q3 → C
rows.append(build(S3,"medium",
    "Amiloride and triamterene produce potassium-sparing diuresis through which mechanism?",
    "Direct blockade of epithelial Na+ channels (ENaC) in the collecting duct, independent of aldosterone levels",
    ["Aldosterone receptor antagonism in the principal cells",
     "Inhibition of Na+/K+-ATPase pump in the distal tubule",
     "Increased prostaglandin synthesis reducing Na+ reabsorption in the collecting duct"],
    pi(2),
    "Amiloride and triamterene block ENaC directly (not by blocking aldosterone receptor). This means they retain K+ even when aldosterone is absent — unlike spironolactone, which requires aldosterone to be present to show an effect.",
    True))

# Q4 → D
rows.append(build(S3,"hard",
    "A patient with CKD stage 4 (eGFR 22 mL/min) and heart failure is prescribed spironolactone. What is the primary concern?",
    "Severe hyperkalemia — impaired renal K+ excretion combined with aldosterone blockade preventing collecting duct K+ secretion creates dangerously elevated K+",
    ["Hypokalemia from excessive aldosterone antagonism at low GFR",
     "Acute tubular necrosis from direct spironolactone nephrotoxicity",
     "Volume overload because spironolactone has no diuretic effect in advanced CKD"],
    pi(3),
    "Potassium-sparing diuretics should be avoided in severe renal dysfunction (eGFR <30 mL/min). The kidney''s already impaired K+ excretion, compounded by aldosterone blockade in the collecting duct, creates high risk of life-threatening hyperkalemia.",
    True))

# Q5 → A
rows.append(build(S3,"easy",
    "Potassium-sparing diuretics are most commonly combined with which class to provide electrolyte-balanced diuresis?",
    "Thiazide or loop diuretics — these cause hypokalemia, which is offset by the K+-retaining property of K+-sparing diuretics",
    ["Osmotic diuretics to enhance free water clearance",
     "Carbonic anhydrase inhibitors to alkalinize the urine",
     "Beta-blockers to reduce aldosterone-mediated effects"],
    pi(4),
    "Fixed-dose combinations like Dyazide (HCTZ + triamterene) or Aldactazide (HCTZ + spironolactone) exploit this complementary mechanism, allowing diuresis while minimizing K+ disturbances and reducing the need for K+ supplementation.",
    True))

# Q6 → B
rows.append(build(S3,"medium",
    "Spironolactone is used in which condition beyond diuresis, due to evidence of mortality benefit?",
    "Heart failure with reduced ejection fraction (HFrEF) — aldosterone causes cardiac fibrosis and remodeling; spironolactone blocks these non-renal aldosterone effects to reduce mortality",
    ["Nephrogenic diabetes insipidus — spironolactone blocks collecting duct V2 receptors",
     "Acute pulmonary edema — first-line diuretic for rapid fluid removal",
     "Hypercalcemia — spironolactone promotes Ca2+ excretion via aldosterone blockade"],
    pi(5),
    "The RALES trial showed 30% mortality reduction with low-dose spironolactone in severe HFrEF. Aldosterone promotes myocardial fibrosis and ventricular remodeling independent of its renal effects. Eplerenone showed similar benefit in the EPHESUS trial (post-MI LV dysfunction).",
    True))

# Q7 → C
rows.append(build(S3,"medium",
    "A patient begins spironolactone and lisinopril concurrently. What electrolyte requires most urgent monitoring?",
    "Serum potassium — both spironolactone (reduces aldosterone-mediated K+ excretion) and lisinopril (reduces angiotensin II-driven aldosterone) independently cause K+ retention; together, risk is additive",
    ["Serum sodium — both agents cause hyponatremia by different mechanisms",
     "Serum calcium — combined therapy causes hypercalcemia by unclear mechanism",
     "Serum magnesium — spironolactone depletes Mg2+ when combined with ACE inhibitors"],
    pi(6),
    "Both K+-sparing diuretics and ACE inhibitors raise serum K+ via complementary mechanisms. Their combination is particularly dangerous in CKD or diabetes, where baseline K+ excretion may already be compromised. Monitor K+ within 1 week of initiating or adjusting doses.",
    True))

# Q8 → D
rows.append(build(S3,"hard",
    "Why do potassium-sparing diuretics produce weaker diuresis compared to loop diuretics?",
    "The collecting duct only handles 1-2% of filtered sodium; maximum blockade of ENaC can only affect this small fraction — far less than the 25-30% blocked by loop diuretics in the thick ascending limb",
    ["K+-sparing diuretics are rapidly metabolized before reaching the collecting duct",
     "K+-sparing diuretics require blood aldosterone levels to be low before they can work",
     "K+-sparing diuretics must compete with high luminal K+ concentrations, reducing their efficacy"],
    pi(7),
    "The anatomical site limits the maximum effect. The thick ascending limb reabsorbs 25-30% of filtered NaCl; the collecting duct handles only 1-2% via ENaC. This makes K+-sparing agents weak diuretics but effective K+-retention agents and useful for non-diuretic indications.",
    True))

# Q9 → A
rows.append(build(S3,"easy",
    "In primary hyperaldosteronism (Conn syndrome), spironolactone is uniquely effective. What is the mechanism?",
    "Spironolactone directly antagonizes the aldosterone receptor, reversing both sodium retention (hypertension) and potassium wasting (hypokalemia) caused by excess aldosterone",
    ["Spironolactone inhibits adrenal aldosterone synthesis in the zona glomerulosa",
     "Spironolactone increases GFR, facilitating aldosterone renal filtration and clearance",
     "Spironolactone blocks angiotensin II, reducing the stimulus for aldosterone secretion"],
    pi(8),
    "Primary hyperaldosteronism features autonomous aldosterone excess causing hypertension, hypokalemia, and metabolic alkalosis. Spironolactone directly blocks the aldosterone receptor, treating all three features and serving as both a diagnostic and therapeutic agent.",
    True))

# Q10 → B
rows.append(build(S3,"medium",
    "Trimethoprim (antibiotic) can cause hyperkalemia. How does this relate to drug interactions with K+-sparing diuretics?",
    "Trimethoprim blocks ENaC in the collecting duct (like amiloride), reducing K+ excretion — additive hyperkalemia risk when combined with other K+-sparing drugs",
    ["Trimethoprim blocks aldosterone receptors, synergizing with spironolactone to reduce K+ secretion",
     "Trimethoprim inhibits K+ reabsorption in the proximal tubule, compounding collecting duct effects",
     "Trimethoprim directly activates renin secretion, paradoxically worsening aldosterone-mediated effects"],
    pi(9),
    "Trimethoprim structurally resembles amiloride and blocks ENaC. This clinically important interaction causes hyperkalemia, particularly in HIV patients (frequent trimethoprim-sulfamethoxazole use) with CKD on spironolactone or ACE inhibitors.",
    True))

# ─── SUBTOPIC 4: Osmotic Diuretics & CAIs ────────────────────────────────────
S4 = "Osmotic Diuretics and Carbonic Anhydrase Inhibitors"
# Q1 → A
rows.append(build(S4,"easy",
    "Mannitol produces diuresis by which mechanism?",
    "Acting as a freely filtered, non-reabsorbable solute that retains water osmotically in the tubular lumen",
    ["Inhibiting Na+/K+/2Cl- cotransporter in the ascending limb",
     "Blocking aldosterone receptors in the collecting duct principal cells",
     "Inhibiting carbonic anhydrase, reducing bicarbonate reabsorption"],
    pi(0),
    "Mannitol is freely filtered at the glomerulus but not reabsorbed by tubular cells. The osmotically active mannitol obligates water to remain in the tubular lumen, increasing urine flow. It also draws intracellular water into the extracellular space, reducing cerebral edema.",
    True))

# Q2 → B
rows.append(build(S4,"medium",
    "A neurosurgery patient receiving IV mannitol for elevated ICP. What is the most critical monitoring parameter?",
    "Serum osmolality — to prevent hyperosmolar state (>320 mOsm/kg) and AKI from mannitol accumulation",
    ["Serum potassium — risk of severe hyperkalemia from mannitol-induced K+ release",
     "Urinary pH — to detect bicarbonate wasting from carbonic anhydrase inhibition",
     "Serum glucose — mannitol is metabolized to glucose, risking hyperglycemia"],
    pi(1),
    "Mannitol accumulation raises serum osmolality. An osmol gap >10-20 mOsm/kg indicates significant levels. If serum osmolality exceeds 320 mOsm/kg, AKI risk increases and paradoxical rebound cerebral edema can occur. Serum Na+ and osmolality must be closely monitored.",
    True))

# Q3 → C
rows.append(build(S4,"medium",
    "Acetazolamide inhibits carbonic anhydrase in the proximal tubule. Which acid-base disturbance results?",
    "Hyperchloremic metabolic acidosis from urinary HCO3- wasting",
    ["Metabolic alkalosis from enhanced HCO3- reabsorption",
     "Respiratory acidosis from central respiratory depression",
     "Respiratory alkalosis from peripheral chemoreceptor stimulation"],
    pi(2),
    "Blocking CA prevents H+ secretion and HCO3- reabsorption in the proximal tubule. Urinary HCO3- excretion increases, producing hyperchloremic metabolic acidosis. This limits long-term acetazolamide use as a diuretic — the acidosis reduces luminal HCO3- available for the drug to act on.",
    True))

# Q4 → D
rows.append(build(S4,"hard",
    "Acetazolamide is used for acute mountain sickness (altitude sickness). What is the mechanism of benefit?",
    "Acetazolamide induces metabolic acidosis which stimulates ventilation via peripheral chemoreceptors, increasing arterial PO2 at altitude",
    ["Acetazolamide stimulates erythropoietin to improve O2 delivery",
     "Acetazolamide reduces pulmonary vascular resistance to prevent high-altitude pulmonary edema",
     "Acetazolamide reduces CSF production, decreasing altitude headache severity"],
    pi(3),
    "The metabolic acidosis from acetazolamide-induced HCO3- wasting compensates for the respiratory alkalosis of altitude, normalizing the ventilatory drive. Stimulated ventilation raises PaO2, aiding acclimatization. Acetazolamide is started 24-48 hours before ascent.",
    True))

# Q5 → A
rows.append(build(S4,"easy",
    "Acetazolamide reduces intraocular pressure in open-angle glaucoma. What is the mechanism?",
    "Inhibiting carbonic anhydrase in the ciliary body epithelium reduces aqueous humor production, lowering intraocular pressure",
    ["Increasing trabecular meshwork aqueous humor outflow via osmotic effects",
     "Causing miosis via muscarinic receptor activation, improving drainage",
     "Blocking prostaglandin synthesis in the anterior chamber, reducing inflammation"],
    pi(4),
    "Carbonic anhydrase in the ciliary body is essential for secreting HCO3- into the aqueous humor, driving Na+ and water secretion. Inhibiting CA reduces aqueous humor production and IOP. Topical CAIs (dorzolamide, brinzolamide) are preferred for long-term glaucoma management.",
    True))

# Q6 → B
rows.append(build(S4,"medium",
    "Why is mannitol contraindicated in congestive heart failure?",
    "Mannitol initially expands intravascular volume by drawing intracellular fluid into the vascular space — this acute volume expansion can precipitate pulmonary edema in patients with impaired cardiac function",
    ["Mannitol is directly cardiotoxic via mitochondrial dysfunction in cardiomyocytes",
     "Mannitol competes with loop diuretics for tubular secretion, reducing heart failure therapy efficacy",
     "Mannitol causes severe hypernatremia in heart failure patients, worsening congestion"],
    pi(5),
    "Before its diuretic effect occurs, mannitol draws water from cells into the extracellular space, transiently increasing plasma volume and preload. Patients with impaired cardiac function cannot tolerate this acute volume expansion. Mannitol is also contraindicated in anuria.",
    True))

# Q7 → C
rows.append(build(S4,"medium",
    "In which nephron segments do osmotic diuretics primarily exert their effect?",
    "Proximal convoluted tubule and descending loop of Henle (water-permeable segments where osmotic water retention is possible)",
    ["Distal convoluted tubule and collecting duct — high water permeability allows osmotic retention",
     "Thick ascending limb only — where most osmotic gradient is established",
     "Glomerulus — mannitol reduces filtration fraction by diluting plasma"],
    pi(6),
    "Osmotic diuretics act in water-permeable segments: the proximal tubule (where they reduce Na+ and water reabsorption) and the descending limb of Henle (where they oppose water reabsorption). The impermeable ascending limb and DCT are not sites of osmotic diuretic action.",
    True))

# Q8 → D
rows.append(build(S4,"hard",
    "A patient with idiopathic intracranial hypertension (pseudotumor cerebri) is treated with acetazolamide. What is the primary mechanism of ICP reduction?",
    "Acetazolamide inhibits carbonic anhydrase in the choroid plexus epithelium, reducing CSF production and lowering intracranial pressure",
    ["Acetazolamide improves CSF reabsorption via arachnoid granulation stimulation",
     "Acetazolamide constricts cerebral vessels, reducing cerebral blood volume and ICP",
     "Acetazolamide dissolves excess CSF protein deposits, improving circulation"],
    pi(7),
    "CSF secretion by the choroid plexus depends on carbonic anhydrase to generate HCO3- for active transport. Acetazolamide inhibits this enzyme, reducing CSF production by ~50-60%, which directly lowers ICP in idiopathic intracranial hypertension.",
    True))

# Q9 → A
rows.append(build(S4,"easy",
    "What is the most appropriate indication for IV mannitol?",
    "Acute cerebral edema and elevated intracranial pressure following head trauma or stroke",
    ["Chronic heart failure with peripheral edema refractory to loop diuretics",
     "Nephrogenic diabetes insipidus to reduce urine volume",
     "Thiazide-induced hypokalemia prophylaxis in patients with low dietary K+"],
    pi(8),
    "Mannitol draws water from brain parenchyma into the vascular space, reducing brain volume and ICP. It is given as an IV bolus (0.25-1 g/kg) for cerebral edema. Contraindications include heart failure, anuria, and severe hypernatremia.",
    True))

# Q10 → B
rows.append(build(S4,"medium",
    "Acetazolamide is used in metabolic alkalosis complicating heart failure diuretic therapy. What is the rationale?",
    "Acetazolamide causes urinary bicarbonate wasting, directly correcting metabolic alkalosis without requiring NaCl administration (which would worsen heart failure congestion)",
    ["Acetazolamide stimulates aldosterone, increasing H+ and K+ excretion to correct alkalosis",
     "Acetazolamide raises urine pH, increasing the reabsorption of organic bases to neutralize alkalosis",
     "Acetazolamide increases ammonium excretion, generating new bicarbonate to replace what was lost"],
    pi(9),
    "Contraction alkalosis from diuretic therapy (Cl- depletion prevents spontaneous correction) is treated with acetazolamide by promoting urinary HCO3- excretion. This avoids the need for NaCl infusion, which would worsen fluid overload in heart failure patients.",
    True))

# ─── SUBTOPIC 5: ACE Inhibitors & ARBs in Renal Disease ─────────────────────
S5 = "ACE Inhibitors and ARBs in Renal Disease"
# Q1 → A
rows.append(build(S5,"easy",
    "How do ACE inhibitors provide renoprotection in diabetic nephropathy?",
    "By dilating the efferent arteriole (reducing angiotensin II-mediated constriction), they lower intraglomerular pressure and reduce hyperfiltration and proteinuria",
    ["By increasing GFR to flush nephrotoxic glucose metabolites from the kidney",
     "By blocking tubular glucose reabsorption, preventing glycosuria-induced epithelial damage",
     "By inhibiting aldosterone, which directly damages the glomerular basement membrane"],
    pi(0),
    "Angiotensin II preferentially constricts the efferent arteriole, raising glomerular capillary pressure. ACE inhibitors reduce angiotensin II → efferent dilation → reduced intraglomerular pressure → less hyperfiltration → slower GFR decline and reduced proteinuria.",
    True))

# Q2 → B
rows.append(build(S5,"medium",
    "A patient with bilateral renal artery stenosis starts an ARB for hypertension. Which complication is most likely?",
    "Acute kidney injury — loss of angiotensin II-mediated efferent arteriolar tone removes the mechanism maintaining GFR against reduced perfusion pressure",
    ["Severe hypotension from loss of aldosterone-driven fluid retention",
     "Pulmonary edema from acute sodium retention when RAS is blocked",
     "Paradoxical hypertension from renin rebound after RAAS blockade"],
    pi(1),
    "In bilateral RAS, low perfusion pressure to both kidneys is compensated by high angiotensin II constricting efferent arterioles to maintain glomerular filtration pressure. RAAS blockade removes this compensation → GFR collapses → acute kidney injury. This is a contraindication.",
    True))

# Q3 → C
rows.append(build(S5,"medium",
    "A patient on lisinopril develops persistent dry cough. What is the mechanism?",
    "ACE inhibition prevents bradykinin degradation → bradykinin accumulates → stimulates cough receptors in the respiratory epithelium",
    ["Direct bronchial irritation by the lisinopril molecule",
     "Increased angiotensin II levels causing bronchoconstriction",
     "ACE inhibitor-induced eosinophilia causing airway inflammation"],
    pi(2),
    "ACE normally degrades bradykinin. When ACE is inhibited, bradykinin accumulates and stimulates sensory C-fibers in the airway, causing dry cough in ~10-15% of patients (higher in Asian populations). Switching to an ARB (which does not affect bradykinin) resolves the cough.",
    True))

# Q4 → D
rows.append(build(S5,"hard",
    "After starting an ACE inhibitor in a patient with CKD, serum creatinine rises 25% and stabilizes. The most appropriate response is:",
    "Continue the ACE inhibitor — this hemodynamic creatinine rise reflects the intended reduction in intraglomerular pressure and is the mechanism of renoprotection",
    ["Immediately stop the ACE inhibitor — any creatinine rise indicates nephrotoxicity",
     "Reduce the ACE inhibitor dose by half and recheck creatinine in 4 weeks",
     "Add a loop diuretic to increase renal blood flow and restore baseline creatinine"],
    pi(3),
    "A creatinine rise of up to 30% within 2 weeks of starting an ACE inhibitor is expected — it reflects efferent dilation reducing filtration pressure (the therapeutic mechanism). If the rise is >30%, continues to rise after 2 weeks, or if other causes (bilateral RAS, volume depletion) are present, reconsider the drug.",
    True))

# Q5 → A
rows.append(build(S5,"easy",
    "Which drug combination creates the highest risk of hyperkalemia when combined with an ACE inhibitor?",
    "Potassium-sparing diuretic (e.g., spironolactone) — both independently reduce K+ excretion via complementary mechanisms, dramatically raising hyperkalemia risk",
    ["Calcium channel blocker — independent K+ effects combine with ACE inhibitor",
     "Thiazide diuretic — both cause K+ loss, leading to severe hypokalemia",
     "Loop diuretic — both cause renal K+ wasting when combined"],
    pi(4),
    "ACE inhibitors reduce aldosterone → less K+ secretion in collecting duct. K+-sparing diuretics (spironolactone, amiloride) directly block Na+ reabsorption/K+ secretion. Combined: profound hyperkalemia, especially dangerous in CKD or diabetes patients.",
    True))

# Q6 → B
rows.append(build(S5,"medium",
    "How do ARBs differ from ACE inhibitors in their effect on bradykinin?",
    "ARBs block AT1 receptors but do not inhibit ACE — bradykinin degradation continues normally, so ARBs do NOT cause cough or angioedema from bradykinin accumulation",
    ["ARBs inhibit ACE more potently than ACE inhibitors, causing more bradykinin accumulation",
     "ARBs stimulate bradykinin breakdown via kininase II activation",
     "ARBs and ACE inhibitors have identical effects on bradykinin metabolism"],
    pi(5),
    "ARBs block angiotensin II at the AT1 receptor level. Since they do not inhibit ACE, the ACE enzyme continues to degrade bradykinin normally. This is why ARBs cause cough and angioedema far less commonly than ACE inhibitors — making them the preferred alternative.",
    True))

# Q7 → C
rows.append(build(S5,"medium",
    "A patient with type 2 diabetes, hypertension, and proteinuria 2.5 g/day — which drug class has the best evidence for slowing CKD progression?",
    "ACE inhibitors or ARBs — provide renoprotection beyond blood pressure lowering by reducing intraglomerular pressure and proteinuria in diabetic nephropathy",
    ["Calcium channel blockers — most potent blood pressure lowering in CKD",
     "Beta-blockers — reduce proteinuria via reduction of cardiac output and renal perfusion pressure",
     "Alpha-blockers — most selective for renal vasculature, reducing hyperfiltration"],
    pi(6),
    "RAAS blockade with ACE inhibitors or ARBs is Level A evidence for renoprotection in diabetic nephropathy. They reduce proteinuria, slow GFR decline, and delay ESRD onset — effects that are partially independent of blood pressure lowering.",
    True))

# Q8 → D
rows.append(build(S5,"hard",
    "Current guidelines recommend against dual RAAS blockade (ACE inhibitor + ARB). What is the clinical rationale?",
    "The ONTARGET trial demonstrated that dual blockade increased hypotension, AKI, and hyperkalemia without providing additional cardiovascular or renal benefit",
    ["Dual blockade provides no additional blood pressure reduction over monotherapy",
     "ARBs prevent ACE inhibitor binding to its enzyme target when used concurrently",
     "Dual blockade paradoxically upregulates angiotensin II via renin feedback, worsening outcomes"],
    pi(7),
    "ONTARGET (N=25,620) compared ramipril, telmisartan, and combination therapy. The combination arm had similar cardiovascular outcomes but significantly more adverse events (hypotension, syncope, AKI, hyperkalemia). Dual RAAS blockade is now generally contraindicated.",
    True))

# Q9 → A
rows.append(build(S5,"easy",
    "ACE inhibitors and ARBs are absolutely contraindicated in which condition?",
    "Pregnancy — cause fetal renal tubular dysgenesis, oligohydramnios, limb contractures, pulmonary hypoplasia, and neonatal renal failure",
    ["Mild asthma — risk of bronchospasm from bradykinin accumulation",
     "Stable chronic angina — worsen coronary vasospasm",
     "Chronic stable CKD — accelerate renal progression"],
    pi(8),
    "RAAS blockade in pregnancy (especially 2nd and 3rd trimesters) is teratogenic — angiotensin II is required for normal fetal renal development. The resulting fetal renal hypoperfusion causes the fetopathy syndrome. Category X (highest risk) in later pregnancy.",
    True))

# Q10 → B
rows.append(build(S5,"medium",
    "A patient on lisinopril develops sudden oropharyngeal swelling. What is the mechanism of ACE inhibitor-induced angioedema?",
    "Bradykinin accumulation increases vascular permeability in the submucosa of the lips, tongue, and airway — not IgE-mediated",
    ["IgE-mediated mast cell degranulation causing histamine release and tissue edema",
     "Direct toxic effect of lisinopril on vascular endothelium",
     "Aldosterone-mediated water retention causing localized soft tissue swelling"],
    pi(9),
    "ACE inhibitor angioedema is bradykinin-mediated (C-1 esterase inhibitor pathway). It is not IgE-mediated and does not reliably respond to antihistamines or epinephrine. Icatibant (bradykinin B2 antagonist) or fresh frozen plasma are specific treatments. Stop ACE inhibitor permanently — recurrence risk is high.",
    True))

# ─── SUBTOPIC 6: Drugs in CKD ────────────────────────────────────────────────
S6 = "Drugs in CKD"
# Q1 → A
rows.append(build(S6,"easy",
    "NSAIDs are nephrotoxic in patients with reduced effective circulating volume. What is the mechanism?",
    "NSAIDs inhibit prostaglandin synthesis, removing prostaglandin-mediated afferent arteriolar vasodilation critical for maintaining GFR in low-perfusion states",
    ["NSAIDs directly lyse proximal tubular cells via oxidative stress independent of prostaglandins",
     "NSAIDs block aldosterone receptors, causing sodium retention and tubular back-pressure",
     "NSAIDs competitively inhibit creatinine secretion, raising measured creatinine without true GFR reduction"],
    pi(0),
    "In normal perfusion, renal prostaglandins play a minor role. In heart failure, CKD, cirrhosis, or dehydration, afferent arteriolar vasodilation by prostaglandins (PGE2, PGI2) is critical for maintaining GFR. NSAIDs remove this compensatory vasodilation → unopposed vasoconstriction → AKI.",
    True))

# Q2 → B
rows.append(build(S6,"medium",
    "A patient with CKD stage 3b (eGFR 32 mL/min) is on metformin. What is the primary safety concern?",
    "Reduced renal clearance causes metformin accumulation — inhibits mitochondrial complex I → increased lactate production → lactic acidosis",
    ["Metformin is directly nephrotoxic at low GFR via proximal tubular toxicity",
     "Metformin cannot lower blood glucose effectively when eGFR falls below 45 mL/min",
     "Metformin causes hyperkalemia by blocking aldosterone-mediated K+ excretion"],
    pi(1),
    "Metformin is renally eliminated unchanged. In CKD, accumulation occurs. Severe lactic acidosis (potentially fatal) occurs when tissue hypoxia (sepsis, decompensated HF) coexists. Discontinue if eGFR <30; use with caution 30-45 mL/min; withold before contrast or surgery.",
    True))

# Q3 → C
rows.append(build(S6,"medium",
    "Aminoglycosides cause nephrotoxicity by which mechanism?",
    "Saturable endocytosis into proximal tubular cells → mitochondrial dysfunction and ROS generation → tubular cell necrosis (non-oliguric ATN)",
    ["Glomerular basement membrane disruption causing nephrotic syndrome",
     "Hypersensitivity-mediated acute interstitial nephritis with eosinophilia",
     "Renal artery vasoconstriction from direct vascular smooth muscle activation"],
    pi(2),
    "Aminoglycosides are polycationic and bind to the brush border of proximal tubular cells where they are endocytosed. They disrupt lysosomal and mitochondrial function, generating ROS and causing tubular cell death. Once-daily dosing exploits saturable uptake to reduce accumulation and toxicity.",
    True))

# Q4 → D
rows.append(build(S6,"hard",
    "A patient with CKD (eGFR 25 mL/min) needs anticoagulation for atrial fibrillation. Which DOAC has the highest renal dependence and should be avoided or most carefully dosed?",
    "Dabigatran — approximately 80% renally eliminated; contraindicated when CrCl <30 mL/min for AF. Apixaban (~27% renal) is safest in CKD.",
    ["Apixaban — nearly entirely renally eliminated; requires avoidance in moderate CKD",
     "Rivaroxaban — exclusively hepatically metabolized; safe in any degree of CKD",
     "Warfarin — renally cleared and requires dose reduction proportional to eGFR decline"],
    pi(3),
    "Renal elimination proportions: dabigatran ~80%, edoxaban ~35%, rivaroxaban ~33%, apixaban ~27%. Dabigatran has the highest renal dependence and accumulates most in CKD. Apixaban is relatively safest. Warfarin is hepatically metabolized but INR control is erratic in CKD.",
    True))

# Q5 → A
rows.append(build(S6,"easy",
    "Which group of drugs should be avoided or used with extreme caution in advanced CKD due to nephrotoxic potential?",
    "NSAIDs, aminoglycosides, and iodinated contrast media — all cause AKI by distinct mechanisms and can precipitate irreversible CKD progression",
    ["Calcium channel blockers and beta-blockers — direct nephrotoxicity and K+ retention",
     "ACE inhibitors and ARBs — absolutely contraindicated in all patients with CKD",
     "Statins and fibrates — cause rhabdomyolysis and myoglobinuria leading to AKI in all CKD patients"],
    pi(4),
    "NSAIDs: remove protective prostaglandin vasodilation; aminoglycosides: proximal tubular ATN; contrast: direct tubular toxicity + medullary vasoconstriction. All three have reduced clearance in CKD and cause disproportionate injury at standard doses.",
    True))

# Q6 → B
rows.append(build(S6,"medium",
    "What is the primary mechanism by which iodinated contrast media causes contrast-induced nephropathy (CIN)?",
    "Direct proximal tubular cytotoxicity AND renal medullary vasoconstriction (vasa recta) causing medullary ischemia in an already hypoxic zone",
    ["Immune complex deposition in the glomerulus causing membranoproliferative nephritis",
     "Contrast activates complement system causing thrombotic microangiopathy",
     "Contrast inhibits carbonic anhydrase causing proximal tubular acidosis"],
    pi(5),
    "CIN results from two mechanisms: (1) direct cytotoxicity of osmolar/ionic contrast agents to tubular cells; (2) vasoconstriction of vasa recta reducing medullary oxygen delivery. The medullary thick ascending limb is highly susceptible to ischemia due to its high metabolic demands.",
    True))

# Q7 → C
rows.append(build(S6,"medium",
    "Long-term lithium therapy causes which renal complications?",
    "Nephrogenic diabetes insipidus (blocks V2 receptor-AQP2 signaling) and chronic tubulointerstitial nephritis progressing to CKD",
    ["Membranous nephropathy from lithium-protein hapten formation",
     "IgA nephropathy from lithium-induced immunoglobulin A overproduction",
     "Renal vein thrombosis from lithium-induced hypercoagulability"],
    pi(6),
    "Lithium causes two distinct renal syndromes: (1) NDI — lithium enters collecting duct cells via ENaC, blocking cAMP signaling downstream of V2 receptors → no AQP2 insertion → polyuria/polydipsia; (2) interstitial nephritis → progressive CKD. Regular monitoring of eGFR and lithium levels is mandatory.",
    True))

# Q8 → D
rows.append(build(S6,"hard",
    "A patient with CKD stage 5 (eGFR 12 mL/min) requires treatment for moderate pain. Which analgesic is most appropriate?",
    "Acetaminophen at standard doses — hepatically metabolized; inactive conjugates are excreted renally but not nephrotoxic at therapeutic doses",
    ["Naproxen — short half-life minimizes accumulation in advanced CKD",
     "Codeine — weakest opioid, least likely to cause accumulation in CKD",
     "Ketorolac IM — parenteral administration reduces GI side effects and renal impact"],
    pi(7),
    "Acetaminophen is the analgesic of choice in CKD. NSAIDs (including ketorolac and naproxen) are contraindicated in advanced CKD. Codeine''s active metabolite (codeine-6-glucuronide, morphine-6-glucuronide) accumulates in CKD causing respiratory depression. Acetaminophen inactive metabolites accumulate but are not inherently nephrotoxic.",
    True))

# Q9 → A
rows.append(build(S6,"easy",
    "For renally cleared drugs in CKD, what is the standard pharmacokinetic dose-adjustment principle?",
    "Loading dose unchanged (determined by volume of distribution); REDUCE maintenance dose and/or EXTEND dosing interval proportional to GFR decline",
    ["Reduce the loading dose by the same factor as the maintenance dose",
     "Double all doses to overcome reduced tubular drug secretion",
     "Switch all drugs to IV formulations to bypass renal clearance impairment"],
    pi(8),
    "The loading dose achieves the target concentration quickly (dependent on Vd, not clearance). The maintenance dose maintains steady-state concentration — this must be reduced in CKD (proportional to GFR) to prevent drug accumulation and toxicity.",
    True))

# Q10 → B
rows.append(build(S6,"medium",
    "Allopurinol requires dose reduction in CKD. What is the reason and clinical risk if not adjusted?",
    "Allopurinol''s active metabolite oxypurinol is renally eliminated; accumulation in CKD increases risk of severe cutaneous reactions (SJS/TEN) and allopurinol hypersensitivity syndrome",
    ["Allopurinol is directly nephrotoxic at standard doses in CKD via xanthine deposits",
     "Allopurinol is contraindicated in any patient with gout and CKD regardless of severity",
     "Allopurinol causes severe hypokalemia by blocking aldosterone in CKD patients"],
    pi(9),
    "Oxypurinol has a much longer half-life than allopurinol (18-40 hours vs 1-2 hours) and is renally cleared. In CKD, it accumulates significantly, raising the risk of Stevens-Johnson syndrome, toxic epidermal necrolysis, and bone marrow suppression — all features of allopurinol hypersensitivity syndrome.",
    True))

# ─── SUBTOPIC 7: Phosphate Binders & ESAs ────────────────────────────────────
S7 = "Phosphate Binders and Erythropoiesis-Stimulating Agents"
# Q1 → A
rows.append(build(S7,"easy",
    "A CKD patient with hyperphosphatemia and hypercalcemia requires a phosphate binder. Which is most appropriate?",
    "Sevelamer or lanthanum carbonate — non-calcium binders that avoid worsening hypercalcemia and vascular calcification",
    ["Calcium carbonate — provides both phosphate binding and Ca2+ supplementation simultaneously",
     "Calcium acetate — provides the least Ca2+ per tablet while binding phosphate effectively",
     "Aluminum hydroxide — most potent phosphate binder for use in hypercalcemic CKD patients"],
    pi(0),
    "Non-calcium binders (sevelamer, lanthanum) are preferred when serum Ca is elevated, PTH is suppressed, or vascular calcification is present. Calcium-based binders worsen hypercalcemia. Aluminum hydroxide is avoided long-term due to CNS/bone toxicity from accumulation.",
    True))

# Q2 → B
rows.append(build(S7,"medium",
    "Aluminum-containing phosphate binders are not recommended for long-term use in CKD. What is the primary reason?",
    "Aluminum accumulates in bone and brain in CKD, causing adynamic bone disease (dialysis osteodystrophy) and dialysis dementia (encephalopathy)",
    ["Aluminum is directly nephrotoxic and accelerates CKD progression at any dose",
     "Aluminum causes severe metabolic alkalosis that is incompatible with long-term use",
     "Aluminum competitively inhibits iron absorption, causing severe anemia in CKD"],
    pi(1),
    "Aluminum is absorbed from the GI tract and cleared by the kidneys. In CKD, it accumulates in bone (preventing normal bone turnover), brain (causing progressive neurological deterioration), and blood (causing microcytic anemia). Short-term use for phosphate control is occasionally acceptable.",
    True))

# Q3 → C
rows.append(build(S7,"medium",
    "ESA therapy is initiated in CKD anemia. What is the target hemoglobin range to balance symptom control with cardiovascular safety?",
    "10-11.5 g/dL — higher targets (>13 g/dL) increase cardiovascular events (stroke, MI, thrombosis) as shown in CHOIR and TREAT trials",
    ["12-14 g/dL to restore normal oxygen delivery and maximize quality of life",
     "8-9 g/dL to minimize ESA dose and reduce cardiovascular risk",
     "The goal should be complete normalization of hemoglobin to pre-CKD baseline"],
    pi(2),
    "Clinical trials (CHOIR, TREAT, CREATE) demonstrated that targeting high Hb levels (>13 g/dL) with ESAs increased cardiovascular mortality and stroke. Current KDIGO guidelines recommend initiating ESAs when Hb <10 g/dL and targeting 10-11.5 g/dL.",
    True))

# Q4 → D
rows.append(build(S7,"hard",
    "A CKD patient on epoetin alfa has persistently low hemoglobin despite dose escalation. What is the most common cause of ESA hyporesponsiveness?",
    "Iron deficiency (absolute: ferritin <200 ng/mL, TSAT <20%; or functional: insufficient iron available for erythropoiesis despite adequate stores)",
    ["Anti-EPO neutralizing antibodies causing pure red cell aplasia",
     "Uremic inhibition of erythropoietin receptors on bone marrow erythroid progenitors",
     "Vitamin C deficiency impairing erythropoietin receptor signaling"],
    pi(3),
    "Iron deficiency is by far the most common reason for ESA hyporesponsiveness. Adequate iron stores are essential for EPO-stimulated erythropoiesis. Always assess and replete iron (IV preferred in dialysis patients) before escalating ESA dose. Other causes: infection, inflammation, B12/folate deficiency, hyperparathyroidism.",
    True))

# Q5 → A
rows.append(build(S7,"easy",
    "What is the correct sequence of events causing secondary hyperparathyroidism in CKD?",
    "Reduced GFR → phosphate retention + reduced calcitriol → hypocalcemia → elevated PTH (secondary hyperparathyroidism)",
    ["Elevated PTH → hyperphosphatemia → calcitriol suppression → hypocalcemia",
     "Hypocalcemia → reduced FGF-23 → hyperphosphatemia → elevated PTH",
     "Reduced GFR → hypocalcemia directly → elevated PTH → hyperphosphatemia"],
    pi(4),
    "The sequence: reduced GFR → phosphate retention and reduced 1α-hydroxylase activity → reduced calcitriol → reduced Ca2+ absorption → hypocalcemia → PTH secretion. FGF-23 rises early (suppresses 1α-hydroxylase), contributing to low calcitriol before overt phosphate retention.",
    True))

# Q6 → B
rows.append(build(S7,"medium",
    "Cinacalcet is a calcimimetic used in secondary hyperparathyroidism. What is its mechanism?",
    "Allosterically sensitizes the calcium-sensing receptor (CaSR) on parathyroid cells, making them respond as if extracellular Ca2+ is higher → suppresses PTH secretion",
    ["Directly inhibits PTH gene transcription in the parathyroid chief cells",
     "Reduces intestinal phosphate absorption, lowering the stimulus for PTH secretion",
     "Replaces calcitriol signaling by binding vitamin D receptors in the parathyroid gland"],
    pi(5),
    "Cinacalcet is a positive allosteric modulator of the CaSR — it increases receptor sensitivity to Ca2+, suppressing PTH release even without raising actual Ca2+ levels. It simultaneously lowers PTH, Ca2+, and phosphate. Key adverse effect: hypocalcemia (requires Ca2+ monitoring).",
    True))

# Q7 → C
rows.append(build(S7,"medium",
    "A hemodialysis patient starts IV iron sucrose infusion. Which adverse effect requires immediate monitoring?",
    "Hypersensitivity/anaphylactic reaction — ranging from flushing to anaphylaxis; resuscitation equipment must be available, especially for the first dose",
    ["Hyperferritinemia causing acute hepatotoxicity within hours of infusion",
     "Acute pulmonary edema from osmotic fluid expansion during infusion",
     "Severe hypokalemia from iron-potassium exchange in red blood cells"],
    pi(6),
    "IV iron formulations carry hypersensitivity risk, highest with iron dextran (older formulation). Newer formulations (iron sucrose, ferric gluconate, ferric carboxymaltose) have lower rates but still require monitoring. Infuse slowly and observe for 30 minutes after completion of the first dose.",
    True))

# Q8 → D
rows.append(build(S7,"hard",
    "Pure red cell aplasia (PRCA) is a rare complication of ESA therapy. What is the mechanism and management?",
    "Neutralizing anti-EPO IgG antibodies develop against recombinant EPO, cross-reacting with endogenous EPO, abolishing all erythropoiesis. Stop ESA immediately; treat with immunosuppression.",
    ["ESAs inhibit erythroid burst-forming units directly via receptor downregulation",
     "ESAs cause iron sequestration in the liver, starving erythropoiesis of cofactors",
     "ESA-induced T-cell activation causes autoimmune marrow destruction"],
    pi(7),
    "PRCA presents as severe anemia with absent erythroblasts on bone marrow biopsy. Anti-EPO antibodies can be confirmed by assay. Switching to a different ESA does NOT help (antibodies cross-react). Immunosuppression (corticosteroids, cyclosporine, IVIG) may be required. Renal transplantation may allow ESA re-challenge.",
    True))

# Q9 → A
rows.append(build(S7,"easy",
    "What is the role of active vitamin D analogs (calcitriol, paricalcitol) in CKD-MBD?",
    "Replace deficient renal calcitriol production to suppress PTH, improve Ca2+ absorption, and maintain bone health in CKD-MBD",
    ["Stimulate erythropoietin production in place of the failing kidney",
     "Directly inhibit osteoclast activity to reverse renal osteodystrophy",
     "Increase phosphate excretion as an alternative to dietary restriction in CKD"],
    pi(8),
    "In CKD, reduced 1α-hydroxylase activity impairs calcitriol production. Active vitamin D analogs suppress PTH transcription directly and indirectly (by raising Ca2+ through enhanced intestinal absorption). Paricalcitol may cause less hypercalcemia/hyperphosphatemia than calcitriol.",
    True))

# Q10 → B
rows.append(build(S7,"medium",
    "Sevelamer has which additional benefit beyond phosphate binding that may benefit CKD patients with high cardiovascular risk?",
    "Sevelamer binds bile acids in the gut in addition to phosphate, reducing LDL cholesterol by 15-30%",
    ["Sevelamer directly stimulates FGF-23 secretion, reducing phosphate absorption at the intestinal level",
     "Sevelamer chelates uremic toxins (indoxyl sulfate, p-cresol), reducing uremic burden",
     "Sevelamer directly inhibits aldosterone, reducing blood pressure and cardiac remodeling"],
    pi(9),
    "Sevelamer is a cationic polymer that binds both phosphate and bile acids. The bile acid binding reduces LDL-C and total cholesterol, potentially contributing to cardiovascular risk reduction in CKD patients who are at markedly elevated cardiovascular risk. This is a clinically recognized secondary benefit.",
    True))

# ─── SUBTOPIC 8: Immunosuppressants in Transplant ────────────────────────────
S8 = "Immunosuppressants in Transplant"
# Q1 → A
rows.append(build(S8,"easy",
    "Cyclosporine exerts its immunosuppressive effect by which primary mechanism?",
    "Binding cyclophilin → forming a complex that inhibits calcineurin → blocking NFAT dephosphorylation → preventing IL-2 gene transcription and T-cell activation",
    ["Inhibiting mTOR, blocking T-cell response to IL-2 and proliferation",
     "Blocking purine de novo synthesis, selectively reducing lymphocyte proliferation",
     "Direct lysis of alloreactive T cells via Fas-FasL pathway activation"],
    pi(0),
    "Cyclosporine binds intracellular cyclophilin; the complex inhibits calcineurin phosphatase, which normally dephosphorylates NFAT to allow its nuclear entry. Blocked NFAT = no IL-2 transcription = no T-cell activation. Tacrolimus has the same target via a different binding protein (FKBP-12).",
    True))

# Q2 → B
rows.append(build(S8,"medium",
    "Which side effects are characteristic of cyclosporine but NOT tacrolimus?",
    "Hirsutism, gingival hyperplasia, and more pronounced hyperlipidemia — caused by cyclosporine''s non-selectivity for androgen/progesterone receptors",
    ["Alopecia and new-onset diabetes after transplant (NODAT) — unique to cyclosporine",
     "Nephrotoxicity and hypertension — these only occur with cyclosporine, not tacrolimus",
     "Neurotoxicity (tremor, seizures) — unique to cyclosporine at toxic levels"],
    pi(1),
    "Distinguishing features: Cyclosporine → hirsutism, gingival hyperplasia, dyslipidemia. Tacrolimus → more NODAT (via beta-cell calcineurin inhibition), alopecia. Both cause nephrotoxicity, hypertension, hyperkalemia, and neurotoxicity (shared class effects of calcineurin inhibitors).",
    True))

# Q3 → C
rows.append(build(S8,"medium",
    "Tacrolimus is metabolized by CYP3A4. Which drug interaction is most likely to cause tacrolimus toxicity?",
    "CYP3A4 inhibitors (e.g., fluconazole, voriconazole, clarithromycin, diltiazem) increase tacrolimus blood levels, raising nephrotoxicity risk",
    ["Rifampin (CYP3A4 inducer) increases tacrolimus levels by decreasing its clearance",
     "Phenytoin (CYP3A4 inhibitor) increases tacrolimus levels, causing renal injury",
     "St. John''s Wort (CYP3A4 inhibitor) increases tacrolimus levels, precipitating nephrotoxicity"],
    pi(2),
    "CYP3A4 inhibitors reduce tacrolimus/cyclosporine metabolism → increased drug levels → toxicity. Key inhibitors: azole antifungals, macrolides, diltiazem, verapamil, grapefruit juice. CYP3A4 inducers (rifampin, phenytoin, carbamazepine, St. John''s Wort) decrease levels → risk of rejection.",
    True))

# Q4 → D
rows.append(build(S8,"hard",
    "Mycophenolate mofetil (MMF) has selective immunosuppressive activity. What is the mechanism of this selectivity for lymphocytes?",
    "MMF inhibits IMPDH (inosine monophosphate dehydrogenase), blocking de novo purine synthesis; lymphocytes uniquely depend on de novo synthesis — other cells use the salvage pathway",
    ["MMF blocks calcineurin, which is only expressed in lymphocytes",
     "MMF selectively enters lymphocytes via the adenosine transporter, concentrating in immune cells",
     "MMF is activated to mycophenolic acid only in lymphoid tissue by tissue-specific enzymes"],
    pi(3),
    "Mycophenolate mofetil → mycophenolic acid → IMPDH inhibition → blocked de novo purine synthesis. Non-lymphoid cells can use the hypoxanthine-guanine phosphoribosyltransferase (HGPRT) salvage pathway for purines, making them less vulnerable. Lymphocytes lack efficient salvage capacity.",
    True))

# Q5 → A
rows.append(build(S8,"easy",
    "Which immunosuppressant used in transplantation inhibits mTOR signaling?",
    "Sirolimus (rapamycin) — binds FKBP-12, forming a complex that inhibits mTOR → blocks T-cell response to IL-2 → prevents proliferation",
    ["Cyclosporine — binds mTOR directly to block interleukin signaling",
     "Tacrolimus — binds FKBP-12 and directly inhibits mTOR kinase activity",
     "Mycophenolate — inhibits mTOR downstream of purine synthesis blockade"],
    pi(4),
    "Sirolimus (rapamycin) and everolimus are mTOR inhibitors. Unlike calcineurin inhibitors (which block IL-2 production), sirolimus blocks T-cell response TO IL-2 (G1-to-S phase). Key adverse effects: wound healing impairment, hyperlipidemia, thrombocytopenia, lymphocele — deferred post-operatively.",
    True))

# Q6 → B
rows.append(build(S8,"medium",
    "A renal transplant recipient develops NODAT 4 months after transplantation. Tacrolimus is the likely cause. What is the mechanism?",
    "Tacrolimus inhibits calcineurin in pancreatic beta-cells → blocks NFAT-mediated insulin gene transcription → impaired insulin synthesis and secretion → diabetes",
    ["Tacrolimus-induced weight gain from corticosteroid synergy causes severe insulin resistance",
     "Tacrolimus reduces glucagon-like peptide-1 (GLP-1) secretion from gut enteroendocrine cells",
     "Tacrolimus stimulates glucocorticoid receptors in adipose tissue, increasing gluconeogenesis"],
    pi(5),
    "NFAT in pancreatic beta-cells regulates insulin gene expression. Calcineurin inhibition by tacrolimus blocks NFAT, impairing insulin transcription and secretion. Tacrolimus causes more NODAT than cyclosporine. Concurrent corticosteroids amplify the risk by increasing insulin resistance.",
    True))

# Q7 → C
rows.append(build(S8,"medium",
    "Calcineurin inhibitors (cyclosporine, tacrolimus) cause nephrotoxicity through which primary mechanism?",
    "Afferent arteriolar vasoconstriction → reduced renal blood flow and GFR (acute, functional); chronic exposure causes interstitial fibrosis (striped pattern on biopsy)",
    ["Immune complex deposition in the glomerulus causing membranous nephropathy",
     "Direct tubular cell toxicity from drug accumulation in tubular mitochondria",
     "Complement activation leading to thrombotic microangiopathy"],
    pi(6),
    "CNI nephrotoxicity: acute phase — functional reduction in GFR from afferent vasoconstriction (elevated renal angiotensin II and endothelin, reduced prostaglandins); chronic phase — striped interstitial fibrosis and tubular atrophy on biopsy, with progressive CKD. TDM is essential to minimize toxicity while maintaining immunosuppression.",
    True))

# Q8 → D
rows.append(build(S8,"hard",
    "Why is triple immunosuppression (calcineurin inhibitor + antimetabolite + corticosteroid) the standard in renal transplantation?",
    "Each agent targets a different step in T-cell activation (signal 1/2/3), allowing synergistic immunosuppression at lower individual doses — reducing each drug''s specific toxicities while maintaining efficacy",
    ["Triple therapy is required to prevent both acute and chronic rejection — no single agent can achieve this",
     "Each agent targets the same pathway redundantly, providing pharmacodynamic security if one drug fails",
     "Triple therapy overcomes the subtherapeutic blood levels each drug achieves individually"],
    pi(7),
    "Signal 1 (TCR activation): calcineurin inhibitors block IL-2 production; corticosteroids block antigen presentation. Signal 3 (proliferation response): antimetabolites (MMF) block lymphocyte division. Synergistic suppression at reduced doses of each component minimizes class-specific toxicities (CNI nephrotoxicity, steroid metabolic effects, MMF GI effects).",
    True))

# Q9 → A
rows.append(build(S8,"easy",
    "Which monitoring parameter is most critical for patients receiving cyclosporine or tacrolimus?",
    "Trough whole-blood drug concentrations — narrow therapeutic index requires therapeutic drug monitoring to avoid toxicity (supratherapeutic) or rejection (subtherapeutic)",
    ["Serum calcium — risk of hypercalcemia from calcineurin pathway modulation",
     "Urinary protein — risk of membranous nephropathy from immune complex deposition",
     "Serum magnesium — both agents cause dangerous hypermagnesemia"],
    pi(8),
    "CNIs have a narrow therapeutic index with highly variable pharmacokinetics (CYP3A4, P-gp, food effects). Trough levels (drawn before morning dose) guide dose adjustments. Target levels are higher early post-transplant and lower over time as immunological risk decreases.",
    True))

# Q10 → B
rows.append(build(S8,"medium",
    "Why is sirolimus initiation typically deferred to several weeks after renal transplantation?",
    "Sirolimus inhibits mTOR-dependent cell proliferation and angiogenesis, impairing wound healing and increasing risk of lymphoceles and anastomotic complications",
    ["Sirolimus has no immunosuppressive effect until 6 weeks post-transplant",
     "Sirolimus causes immediate anaphylaxis when combined with surgical anesthesia agents",
     "Sirolimus is ineffective when combined with corticosteroids used in the immediate post-transplant period"],
    pi(9),
    "mTOR is critical for fibroblast proliferation and angiogenesis during wound healing. Sirolimus inhibition of mTOR impairs surgical wound closure, increases lymphocele formation at the graft site, and may worsen delayed graft function. It is introduced weeks-to-months post-operatively, often as a CNI-sparing strategy.",
    True))

# ─── SUBTOPIC 9: Urinary Tract Drugs ─────────────────────────────────────────
S9 = "Urinary Tract Drugs"
# Q1 → A
rows.append(build(S9,"easy",
    "Tamsulosin is used for BPH. What is its primary mechanism of action?",
    "Alpha-1A selective adrenergic receptor blockade → relaxes prostate and bladder neck smooth muscle → reduces urethral resistance and improves urine flow",
    ["Inhibiting 5-alpha reductase type 2, reducing DHT-mediated prostate growth",
     "Blocking muscarinic M3 receptors in the detrusor, reducing bladder outflow obstruction",
     "Blocking beta-3 receptors in the bladder wall, increasing bladder storage capacity"],
    pi(0),
    "Alpha-1A receptors are predominant in prostate stroma and bladder neck. Tamsulosin''s selectivity for alpha-1A over vascular alpha-1B reduces orthostatic hypotension compared to non-selective alpha-blockers (doxazosin, terazosin). Rapid symptom relief within days.",
    True))

# Q2 → B
rows.append(build(S9,"medium",
    "A patient taking tamsulosin for BPH is scheduled for cataract surgery. What surgical complication must be disclosed to the ophthalmologist?",
    "Intraoperative floppy iris syndrome (IFIS) — alpha-1 blockade relaxes iris dilator muscle, causing iris billowing, prolapse through incisions, and poor dilation during surgery",
    ["Tamsulosin causes corneal clouding, complicating cataract lens extraction technique",
     "Tamsulosin increases intraocular pressure, complicating intraocular lens insertion",
     "Tamsulosin causes irreversible miosis unresponsive to intraoperative atropine"],
    pi(1),
    "IFIS is associated with alpha-1A antagonists (especially tamsulosin). The iris dilator contains alpha-1A receptors; blockade causes a lax, floppy iris that billows and prolapses through cataract incisions, complicating surgery. The ophthalmologist must be informed pre-operatively, as IFIS can persist even if tamsulosin is stopped.",
    True))

# Q3 → C
rows.append(build(S9,"medium",
    "Oxybutynin is prescribed for overactive bladder (OAB). What is its mechanism?",
    "Muscarinic receptor antagonist (M3 selectivity) — blocks ACh-mediated involuntary detrusor contractions, increasing bladder capacity",
    ["Beta-3 adrenergic agonist causing detrusor relaxation and increased bladder capacity",
     "Alpha-1A antagonist reducing bladder neck resistance and improving urine flow",
     "Potassium channel opener causing detrusor membrane hyperpolarization"],
    pi(2),
    "Oxybutynin is a muscarinic antagonist with M2/M3 activity. M3 receptor blockade in the detrusor prevents involuntary contractions, reducing urgency and frequency. Oxybutynin also has direct smooth muscle relaxant properties. Its BBB penetration causes significant CNS anticholinergic effects in elderly patients.",
    True))

# Q4 → D
rows.append(build(S9,"hard",
    "A patient with BPH and urinary retention is started on finasteride. What is the expected timeline and mechanism for clinical benefit?",
    "Finasteride inhibits 5-alpha reductase type 2, blocking DHT production; prostate volume reduction of 20-30% requires 3-6 months, as glandular involution is gradual",
    ["Finasteride blocks testosterone synthesis; maximum benefit within 1 week",
     "Finasteride blocks estrogen receptors in the prostate, allowing testosterone-mediated shrinkage within 2 weeks",
     "Finasteride directly triggers prostate apoptosis; shrinkage begins within days but complete benefit takes 1 month"],
    pi(3),
    "Unlike alpha-blockers (rapid smooth muscle relaxation), 5-alpha reductase inhibitors reduce prostate glandular size over months. DHT is the primary androgen for prostate cell survival and proliferation; its reduction causes glandular involution. 5-ARIs reduce long-term risk of acute urinary retention and need for surgery.",
    True))

# Q5 → A
rows.append(build(S9,"easy",
    "Mirabegron treats overactive bladder with which advantage over oxybutynin?",
    "Mirabegron is a beta-3 adrenergic agonist that relaxes the detrusor — avoids all anticholinergic adverse effects (dry mouth, constipation, urinary retention, cognitive impairment)",
    ["Mirabegron blocks M3 receptors more selectively than oxybutynin for bladder-specific action",
     "Mirabegron blocks alpha-1A receptors in the urethra to reduce outlet resistance",
     "Mirabegron is a calcium channel blocker preventing smooth muscle contraction in the detrusor"],
    pi(4),
    "Mirabegron activates beta-3 receptors on detrusor smooth muscle → increased cAMP → relaxation → increased bladder storage capacity. No anticholinergic effects means it is safe in elderly patients with dementia, glaucoma, constipation, or dry mouth. Main adverse effect: hypertension (can raise BP).",
    True))

# Q6 → B
rows.append(build(S9,"medium",
    "Dutasteride differs from finasteride in which key way?",
    "Dutasteride inhibits BOTH type 1 and type 2 5-alpha reductase isoenzymes, achieving >90% DHT reduction; finasteride inhibits only type 2 (~70% DHT reduction)",
    ["Finasteride inhibits both type 1 and type 2 isoenzymes; dutasteride inhibits only type 2",
     "Both drugs inhibit only type 1 isoenzyme, which predominates in the prostate",
     "Dutasteride has a shorter half-life (1 hour) requiring twice-daily dosing unlike once-daily finasteride"],
    pi(5),
    "Type 2 predominates in the prostate/genital skin (target for BPH/male-pattern baldness). Type 1 is expressed in skin/liver/brain. Dutasteride''s dual inhibition produces more complete DHT suppression. Its very long half-life (~5 weeks vs ~6 hours for finasteride) means effects persist weeks after stopping.",
    True))

# Q7 → C
rows.append(build(S9,"medium",
    "A patient prescribed phenazopyridine for UTI-related dysuria. What must they be warned about?",
    "Orange-red discoloration of urine, tears, sweat, and contact lenses — harmless but alarming if unexpected; phenazopyridine is NOT an antibiotic and should be used only 1-2 days",
    ["Phenazopyridine causes acute renal failure and must be stopped if urine output decreases",
     "Phenazopyridine causes dangerous serotonin syndrome when combined with fluoroquinolone antibiotics",
     "Phenazopyridine permanently stains the bladder wall and requires cystoscopy to monitor for mucosal damage"],
    pi(6),
    "Phenazopyridine is a urinary analgesic (azo dye) excreted by the kidneys, turning urine bright orange-red. Patients must be counseled this is expected and harmless. It does not treat the infection — antibiotics are required. Using beyond 2 days risks masking treatment failure and delays proper antibiotic therapy.",
    True))

# Q8 → D
rows.append(build(S9,"hard",
    "For neurogenic detrusor overactivity refractory to anticholinergics, which treatment delivers a qualitatively different mechanism?",
    "Intravesical onabotulinumtoxin A — cleaves SNAP-25, blocking presynaptic ACh vesicle fusion → prevents detrusor contractions for 6-12 months",
    ["Tolterodine at higher doses — same mechanism as oxybutynin, more selective for M3",
     "Desmopressin — reduces urine production by V2 agonism, reducing OAB trigger volume",
     "Tamsulosin — reduces outlet resistance, improving coordination of detrusor-sphincter function"],
    pi(7),
    "Botulinum toxin is injected cystoscopically into the detrusor. It blocks neuromuscular transmission by preventing ACh release. Effect lasts 6-12 months. Approximately 20-30% of patients develop urinary retention requiring self-catheterization — this must be discussed pre-treatment. It is highly effective for both neurogenic and idiopathic OAB.",
    True))

# Q9 → A
rows.append(build(S9,"easy",
    "Bethanechol treats non-obstructive urinary retention by which mechanism?",
    "Direct muscarinic M3 agonism → stimulates detrusor contraction, facilitating bladder emptying",
    ["Alpha-1 receptor blockade at the bladder neck, reducing outlet resistance",
     "5-alpha reductase inhibition, reducing prostate volume and urethral compression",
     "Beta-3 agonism relaxing the detrusor to increase bladder capacity"],
    pi(8),
    "Bethanechol directly activates M3 muscarinic receptors on the detrusor, producing contraction and facilitating emptying. It is used for post-operative bladder atony and neurogenic atonic bladder. Contraindicated in obstructive uropathy — forcing contraction against an obstruction can cause bladder rupture.",
    True))

# Q10 → B
rows.append(build(S9,"medium",
    "Tolterodine is preferred over oxybutynin in elderly patients for overactive bladder. What is the primary reason?",
    "Tolterodine penetrates the blood-brain barrier less readily than oxybutynin, causing significantly fewer CNS anticholinergic effects (less cognitive impairment, confusion, and delirium)",
    ["Tolterodine is more potent, requiring lower doses with no systemic absorption",
     "Tolterodine has no peripheral anticholinergic effects, unlike oxybutynin",
     "Tolterodine activates rather than blocks M3 receptors in the detrusor for more natural bladder function"],
    pi(9),
    "Both are muscarinic antagonists, but oxybutynin has high lipophilicity and crosses the BBB extensively. Tolterodine has lower CNS penetration and greater bladder selectivity. Extended-release oxybutynin also has fewer CNS effects than immediate-release, but tolterodine ER is generally preferred in elderly patients.",
    True))

# ─── SUBTOPIC 10: Drug-Induced Nephrotoxicity ────────────────────────────────
S10 = "Drug-Induced Nephrotoxicity"
# Q1 → A
rows.append(build(S10,"easy",
    "Aminoglycosides most commonly cause which pattern of nephrotoxicity?",
    "Non-oliguric acute tubular necrosis of the proximal tubule from mitochondrial dysfunction and ROS generation",
    ["Membranous nephropathy with nephrotic-range proteinuria from glomerular immune deposits",
     "Acute interstitial nephritis with eosinophilia from delayed hypersensitivity",
     "Hemolytic uremic syndrome from endothelial toxicity and microthrombus formation"],
    pi(0),
    "Aminoglycosides bind the proximal tubule brush border and are endocytosed, accumulating in lysosomes and mitochondria. They generate ROS and cause cell death. The result is non-oliguric ATN (tubular cells die but the filtration continues, producing dilute urine without concentration ability).",
    True))

# Q2 → B
rows.append(build(S10,"medium",
    "Cisplatin causes nephrotoxicity through which primary mechanism?",
    "Cisplatin accumulates in proximal tubular cells, forms DNA crosslinks → p53-mediated apoptosis and ROS generation → tubular cell death",
    ["Glomerular immune complex deposition causing membranoproliferative nephritis",
     "Renal artery thrombosis from cisplatin-induced platelet activation",
     "Allergic interstitial nephritis from platinum-hapten formation on tubular cell proteins"],
    pi(1),
    "Cisplatin preferentially accumulates in proximal tubular cells (via basolateral uptake transporters). The same DNA-crosslinking mechanism responsible for antitumor activity causes cytotoxicity in the tubule. Prevention: aggressive IV saline hydration (0.9% NaCl), mannitol, and amifostine (free radical scavenger).",
    True))

# Q3 → C
rows.append(build(S10,"medium",
    "A patient on lithium develops 6 L/day polyuria unresponsive to desmopressin. What is the diagnosis and mechanism?",
    "Nephrogenic diabetes insipidus — lithium blocks intracellular cAMP signaling downstream of V2 receptors, preventing AQP-2 insertion into collecting duct apical membrane",
    ["Central diabetes insipidus — lithium destroys ADH-producing neurons in the hypothalamus",
     "Primary polydipsia — lithium stimulates thirst centers in the hypothalamus",
     "Osmotic diuresis — lithium inhibits glucose reabsorption in the proximal tubule causing glucosuria"],
    pi(2),
    "Lithium enters collecting duct principal cells via ENaC and inhibits adenylyl cyclase. Without cAMP generation, PKA cannot phosphorylate AQP2-containing vesicles for membrane insertion. Since the defect is post-receptor (in the kidney), exogenous ADH (desmopressin) has no effect. Amiloride (blocks lithium entry via ENaC) can help.",
    True))

# Q4 → D
rows.append(build(S10,"hard",
    "NSAIDs cause AKI predominantly in patients with reduced effective circulating volume. What is the precise pharmacodynamic mechanism?",
    "In low-perfusion states, afferent arteriolar vasodilation by renal prostaglandins (PGE2, PGI2) is critical for maintaining GFR against reduced perfusion pressure; NSAIDs remove this compensatory vasodilation",
    ["NSAIDs are nephrotoxic metabolites that accumulate in ischemic kidneys",
     "NSAIDs accumulate to toxic concentrations when cardiac output is low",
     "NSAIDs activate angiotensin II, which synergizes with renal ischemia to cause ATN"],
    pi(3),
    "Under normal conditions, renal prostaglandins play a minor role. In low-perfusion states (heart failure, cirrhosis, dehydration, CKD), activated vasoconstrictors (angiotensin II, norepinephrine) threaten renal blood flow. Prostaglandins provide counter-regulatory vasodilation of the afferent arteriole. NSAIDs block this → unopposed vasoconstriction → AKI.",
    True))

# Q5 → A
rows.append(build(S10,"easy",
    "Which drug classes most commonly cause acute interstitial nephritis (AIN)?",
    "Beta-lactam antibiotics, NSAIDs, and proton pump inhibitors (PPIs) — the classic triad; also sulfonamides, rifampin, and allopurinol",
    ["Aminoglycosides and cisplatin — direct tubular toxins causing ATN, not AIN",
     "ACE inhibitors and ARBs — cause functional AKI from hemodynamic effects",
     "Calcineurin inhibitors — cause afferent arteriolar vasoconstriction and interstitial fibrosis"],
    pi(4),
    "AIN is an immune-mediated (T-cell) drug reaction causing interstitial inflammation with eosinophils and tubulitis. Classic triad: fever + rash + eosinophilia (often incomplete in PPI/NSAID-AIN). PPIs are now the most common cause. Treatment: remove offending drug; corticosteroids in severe or progressive cases.",
    True))

# Q6 → B
rows.append(build(S10,"medium",
    "Which prophylactic strategy has the strongest evidence for preventing contrast-induced nephropathy (CIN)?",
    "IV isotonic saline hydration before and after contrast administration — maintains renal perfusion, dilutes tubular contrast, and reduces medullary ischemia",
    ["Oral N-acetylcysteine (NAC) given 24 hours before contrast — blocks oxidative stress",
     "IV furosemide to promote diuresis during contrast administration",
     "IV bicarbonate infusion alone without concurrent saline hydration"],
    pi(5),
    "IV isotonic saline (0.9% NaCl or bicarbonate) before and after contrast has the most robust evidence. It optimizes renal perfusion and dilutes tubular contrast concentration. NAC may provide marginal additional benefit. Pre-contrast furosemide increases CIN risk by causing volume depletion.",
    True))

# Q7 → C
rows.append(build(S10,"medium",
    "Tenofovir disoproxil fumarate (TDF) causes which renal syndrome in some HIV patients?",
    "Fanconi syndrome from proximal tubular dysfunction — glucosuria, phosphaturia, aminoaciduria, and low-molecular-weight proteinuria from mitochondrial toxicity in tubular cells",
    ["Membranous nephropathy from immune complex deposition related to HIV antigenemia reduction",
     "Acute interstitial nephritis from delayed hypersensitivity to tenofovir haptens",
     "Distal renal tubular acidosis from collecting duct principal cell toxicity"],
    pi(6),
    "TDF accumulates in proximal tubular cells and inhibits mitochondrial DNA polymerase gamma (same as in HIV reverse transcriptase, but mitochondrial). Mitochondrial dysfunction causes generalized proximal tubular dysfunction (Fanconi syndrome), with phosphate wasting leading to hypophosphatemia and bone loss. TAF (tenofovir alafenamide) has ~90% less nephrotoxicity.",
    True))

# Q8 → D
rows.append(build(S10,"hard",
    "High-dose IV methotrexate is prescribed for lymphoma. What renal toxicity should be anticipated and how is it prevented?",
    "Intratubular crystal precipitation of methotrexate and 7-OH-methotrexate at acidic urine pH → tubular obstruction → AKI. Prevention: IV hydration + urinary alkalinization (NaHCO3 to urine pH >7) + leucovorin rescue",
    ["Immune complex membranous nephropathy requiring high-dose steroids",
     "Glomerulonephritis from anti-DHFR antibody cross-reactivity with glomerular antigens",
     "Renal vein thrombosis from methotrexate-induced hypercoagulable state"],
    pi(7),
    "Methotrexate and its metabolite 7-OH-methotrexate are poorly soluble at acidic pH. In the tubular lumen, they can precipitate, causing intratubular obstruction. Alkalinization (urine pH >7) dramatically increases their solubility. Monitor MTX levels and serum creatinine. Glucarpidase (carboxypeptidase G2) cleaves MTX in patients with AKI preventing normal elimination.",
    True))

# Q9 → A
rows.append(build(S10,"easy",
    "Once-daily dosing of aminoglycosides reduces nephrotoxicity compared to multiple-daily dosing. What is the mechanism?",
    "Proximal tubular aminoglycoside uptake is saturable — once-daily dosing allows a drug-free trough period during which tubular cells can export accumulated drug, reducing total tubular accumulation",
    ["Divided doses maintain higher serum troughs, reducing peak renal cortical concentrations",
     "Once-daily dosing produces lower 24-hour AUC, reducing total drug exposure to tubular cells",
     "Multiple-daily dosing allows renal tubular adaptation that is prevented by once-daily dosing"],
    pi(8),
    "The saturable tubular uptake mechanism means that high peak concentrations do not proportionally increase tubular accumulation (the transporter is saturated). The drug-free trough allows cells to export the drug via MDR transporters. Once-daily dosing also achieves higher peak-to-MIC ratios (improved bactericidal activity).",
    True))

# Q10 → B
rows.append(build(S10,"medium",
    "Concurrent use of vancomycin and aminoglycosides significantly increases nephrotoxicity risk. What is the mechanism of synergistic toxicity?",
    "Both drugs independently cause proximal tubular damage (oxidative stress and mitochondrial dysfunction); concurrent use produces additive to synergistic proximal tubular toxicity",
    ["Vancomycin blocks aminoglycoside tubular secretion, dramatically increasing aminoglycoside renal levels",
     "Aminoglycosides displace vancomycin from plasma protein binding, increasing free vancomycin concentration",
     "Combined use triggers immune-mediated interstitial nephritis through T-cell activation against tubular antigens"],
    pi(9),
    "Vancomycin causes oxidative stress in proximal tubular cells (via increased mitochondrial ROS). Aminoglycosides cause similar mitochondrial dysfunction. Together, the tubular toxicity is additive or synergistic. Piperacillin-tazobactam (pip-tazo) also appears to enhance vancomycin nephrotoxicity (mechanism under investigation). TDM for both drugs is essential.",
    True))

# Write SQL file
output_path = '/sessions/keen-ecstatic-cannon/mnt/Skoolie/scripts/med_renal_pharm_mcq.sql'
with open(output_path, 'w') as f:
    f.write("-- Renal System Pharmacology MCQs\n")
    f.write("-- 100 questions across 10 subtopics (10 each)\n")
    f.write("-- Correct answer pattern per subtopic: A,B,C,D,A,B,C,D,A,B\n")
    f.write("-- Source: Lippincott Illustrated Reviews Pharmacology 7th Ed\n\n")
    for row in rows:
        f.write(row + "\n\n")

print(f"Written {len(rows)} MCQ rows to {output_path}")
