rows = []

# ============================================================
# SUBTOPIC 6: Oxygen Transport (10 MCQs)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','easy','mcq','Normal haemoglobin oxygen-carrying capacity (Hüfner''s constant) is approximately:','["A. 0.5 ml O₂/g Hb","B. 1.34 ml O₂/g Hb","C. 2.0 ml O₂/g Hb","D. 3.5 ml O₂/g Hb"]','B','Each gram of haemoglobin can bind 1.34 ml of O₂ when fully saturated (Hüfner''s constant). With normal Hb of 15 g/dl, O₂-carrying capacity = 15 × 1.34 = 20.1 ml/dl. This Hb-bound O₂ dominates transport; dissolved O₂ contributes only ~0.3 ml/dl.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','easy','mcq','The oxyhaemoglobin dissociation curve shifts to the RIGHT in response to:','["A. Decreased temperature","B. Decreased PCO₂","C. Increased 2,3-DPG","D. Alkalosis (increased pH)"]','C','Increased 2,3-DPG, increased PCO₂, increased H⁺ (acidosis), and increased temperature all shift the O₂-Hb curve rightward (Bohr effect), reducing Hb affinity for O₂ and promoting O₂ offloading to tissues. Decreased temperature, alkalosis, and decreased PCO₂ shift the curve leftward.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','medium','mcq','The P50 of haemoglobin refers to:','["A. The PO₂ at which haemoglobin is 50% saturated under standard conditions","B. The PO₂ in arterial blood under normal conditions","C. The maximum PO₂ that haemoglobin can bind","D. The PO₂ at which cardiac output is 50% of maximum"]','A','P50 is the PO₂ at which Hb is 50% saturated at standard conditions (pH 7.4, 37°C, PCO₂ 40 mmHg). Normal P50 ≈ 26–27 mmHg. A rightward shift increases P50 (lower affinity, better tissue O₂ delivery). Foetal Hb (HbF) has a lower P50 (~20 mmHg) indicating higher O₂ affinity.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','medium','mcq','Carbon monoxide (CO) poisoning causes tissue hypoxia by which primary mechanism?','["A. CO binds cytochrome oxidase, blocking cellular respiration","B. CO displaces O₂ from Hb with 240× affinity and shifts the O₂-Hb curve leftward, impairing O₂ delivery","C. CO causes bronchospasm, reducing alveolar ventilation","D. CO reacts with surfactant, causing alveolar collapse"]','B','CO binds Hb with ~240 times the affinity of O₂, forming carboxyhaemoglobin (COHb). This reduces available Hb binding sites AND shifts the O₂-Hb curve leftward (increased affinity for remaining O₂), severely impairing O₂ unloading at tissues. PaO₂ may be normal; SpO₂ on pulse oximetry is falsely normal.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','medium','mcq','2,3-Diphosphoglycerate (2,3-DPG) production by red blood cells is increased in:','["A. Storage of blood in blood banks","B. Anaemia and chronic hypoxaemia","C. Hypothyroidism","D. Alkalosis alone"]','B','2,3-DPG is produced by RBCs in the Rapoport-Luebering shunt of glycolysis. Production increases with anaemia, chronic hypoxaemia (altitude, COPD), and hyperthyroidism — situations requiring enhanced tissue O₂ delivery. 2,3-DPG decreases during blood storage, reducing O₂-releasing capacity of banked blood.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','medium','mcq','The Bohr effect describes:','["A. Increased Hb O₂ affinity in the presence of CO₂ and H⁺, promoting O₂ loading in the lungs","B. Decreased Hb O₂ affinity in the presence of CO₂ and H⁺, promoting O₂ unloading in tissues","C. Increased O₂ solubility at high partial pressures","D. The relationship between CO₂ and bicarbonate formation"]','B','The Bohr effect: rising PCO₂ and falling pH in metabolically active tissues shift the O₂-Hb curve rightward, facilitating O₂ release. In pulmonary capillaries, CO₂ leaves and pH rises, shifting the curve leftward — promoting O₂ loading. This bidirectional benefit is a key physiological adaptation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','medium','mcq','Arterial oxygen content (CaO₂) is calculated as:','["A. CaO₂ = 1.34 × Hb × SaO₂ only","B. CaO₂ = (1.34 × Hb × SaO₂) + (0.003 × PaO₂)","C. CaO₂ = PaO₂ / SaO₂","D. CaO₂ = Cardiac output × PaO₂"]','B','CaO₂ = (1.34 × Hb × SaO₂) + (0.003 × PaO₂). The first term is Hb-bound O₂; the second is dissolved O₂. At normal values: (1.34 × 15 × 0.98) + (0.003 × 95) ≈ 19.7 + 0.3 ≈ 20 ml/dl. Dissolved O₂ becomes important only during hyperbaric O₂ therapy.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','hard','mcq','Foetal haemoglobin (HbF) has higher O₂ affinity than adult HbA. The molecular basis is:','["A. HbF contains alpha and gamma chains; gamma chains bind 2,3-DPG less avidly than beta chains in HbA","B. HbF contains beta and delta chains with increased cooperative binding","C. HbF is smaller and can carry more O₂ per molecule","D. HbF has additional iron atoms in its haem groups"]','A','HbF = 2 alpha + 2 gamma chains (vs. 2 alpha + 2 beta in HbA). The gamma chains have lower affinity for 2,3-DPG (which normally stabilises the deoxy T-state by binding the beta-chain cleft). Less 2,3-DPG binding means HbF stays in the higher-affinity oxy-R state more readily — lower P50 (~20 mmHg vs. 27 mmHg for HbA).','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','hard','mcq','Methaemoglobinaemia causes hypoxia by which mechanism?','["A. Conversion of Fe²⁺ to Fe³⁺, which cannot bind O₂, and a leftward shift of the O₂-Hb curve in remaining normal subunits","B. Inhibition of cytochrome oxidase in mitochondria","C. Competitive displacement of O₂ by nitric oxide","D. Oxidative haemolysis destroying red blood cells"]','A','Methaemoglobin contains Fe³⁺ instead of Fe²⁺, which cannot bind O₂. Furthermore, in tetramers with mixed Fe²⁺/Fe³⁺ subunits, the Fe²⁺ subunits show increased O₂ affinity (leftward shift), impairing O₂ release to tissues. Treatment is methylene blue (reduces Fe³⁺ back to Fe²⁺). Causes include nitrites, dapsone, and prilocaine.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Oxygen Transport','hard','mcq','During acclimatisation to high altitude, renal bicarbonate excretion sustains the ventilatory response to hypoxia by:','["A. Increasing 2,3-DPG production","B. Restoring pH toward normal despite low PCO₂, allowing peripheral chemoreceptors to respond fully to hypoxia","C. Directly stimulating the carotid bodies via aldosterone","D. Increasing haemoglobin synthesis through EPO"]','B','Acute hyperventilation at altitude lowers PCO₂ and raises pH (respiratory alkalosis), which dampens ventilatory drive. Over 2–4 days, kidneys excrete HCO₃⁻, restoring pH toward normal. This ''unlocks'' peripheral chemoreceptors to respond fully to the continuing hypoxic stimulus, sustaining elevated ventilation — the acclimatisation response.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 7: CO2 Transport & Acid-Base (10 MCQs)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','easy','mcq','The majority of CO₂ in blood is transported as:','["A. Dissolved CO₂ in plasma","B. Carbamino compounds bound to haemoglobin","C. Bicarbonate ions (HCO₃⁻)","D. Carbonic acid (H₂CO₃)"]','C','Approximately 70% of CO₂ is transported as HCO₃⁻, formed when CO₂ enters RBCs and is hydrated by carbonic anhydrase to H₂CO₃, then dissociates to HCO₃⁻ + H⁺. About 23% is carried as carbamino-Hb, and ~7% is dissolved in plasma.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','easy','mcq','Respiratory acidosis is characterised by:','["A. Decreased PaCO₂ and increased pH","B. Increased PaCO₂ and decreased pH","C. Decreased HCO₃⁻ and decreased pH with normal PaCO₂","D. Normal PaCO₂ with decreased pH"]','B','Respiratory acidosis results from CO₂ retention (hypoventilation), causing PaCO₂ to rise and pH to fall. Common causes: COPD exacerbation, neuromuscular weakness, opioid overdose. Renal compensation increases HCO₃⁻ reabsorption over days to partially restore pH.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','medium','mcq','The Haldane effect describes:','["A. Increased CO₂-carrying capacity of deoxygenated haemoglobin compared with oxygenated haemoglobin","B. Decreased O₂ affinity of haemoglobin in acidic conditions","C. Increased solubility of CO₂ in cold blood","D. The stimulatory effect of CO₂ on peripheral chemoreceptors"]','A','The Haldane effect: deoxygenated Hb carries more CO₂ than oxygenated Hb — both as bicarbonate (deoxy-Hb is a better buffer, generating less H⁺ per CO₂) and as carbamino-Hb (amino groups on deoxy-Hb bind CO₂ more readily). This aids CO₂ loading in peripheral tissues and unloading in pulmonary capillaries.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','medium','mcq','Carbonic anhydrase in red blood cells catalyses which reaction?','["A. CO₂ + H₂O ⇌ H₂CO₃ ⇌ H⁺ + HCO₃⁻","B. HCO₃⁻ + H⁺ → CO₂ + H₂O (one direction only)","C. O₂ + CO₂ → carbonate + water","D. Haemoglobin + CO₂ → carboxyhaemoglobin"]','A','Carbonic anhydrase (CA) catalyses: CO₂ + H₂O ⇌ H₂CO₃ ⇌ H⁺ + HCO₃⁻. This reaction is bidirectional: in peripheral tissues (CO₂ → HCO₃⁻ for transport) and in pulmonary capillaries (HCO₃⁻ → CO₂ for exhalation). CA inhibitors like acetazolamide block this and cause metabolic acidosis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','medium','mcq','The chloride shift (Hamburger phenomenon) occurs when:','["A. Cl⁻ enters RBCs in exchange for HCO₃⁻ exiting, maintaining electrical neutrality during CO₂ loading in tissues","B. Cl⁻ leaves RBCs in exchange for HCO₃⁻ entering during O₂ loading in lungs","C. Na⁺ exchanges with HCO₃⁻ across the RBC membrane","D. H⁺ ions shift from plasma into RBCs"]','A','In peripheral tissues, CO₂ → HCO₃⁻ + H⁺ inside RBCs. HCO₃⁻ exits the RBC via the AE1 (Band 3) anion exchanger and Cl⁻ enters to maintain electroneutrality — the chloride shift. In the lungs, the process reverses: Cl⁻ leaves and HCO₃⁻ re-enters RBCs to regenerate CO₂ for exhalation.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','medium','mcq','A patient hyperventilates due to anxiety, producing PaCO₂ of 25 mmHg. The expected pH is:','["A. 7.20–7.25","B. 7.35–7.45","C. 7.50–7.60","D. 7.65–7.70"]','C','Acute hyperventilation causes respiratory alkalosis. For each 10 mmHg acute fall in PaCO₂, pH rises by ~0.08 units. PaCO₂ falls from 40 to 25 mmHg (Δ15 mmHg), so pH rises by ~0.12 → pH ≈ 7.52. Symptoms include perioral tingling and carpopedal spasm from decreased ionised Ca²⁺.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','medium','mcq','In compensated chronic respiratory acidosis (e.g., stable COPD), expected blood gas findings include:','["A. High PaCO₂, low pH, high HCO₃⁻","B. High PaCO₂, near-normal pH, high HCO₃⁻","C. Normal PaCO₂, high HCO₃⁻, high pH","D. Low PaCO₂, low HCO₃⁻, low pH"]','B','In chronic respiratory acidosis, renal compensation increases HCO₃⁻ reabsorption by ~3.5 mEq/L per 10 mmHg rise in PaCO₂. pH moves toward (but rarely reaches) normal. Classic: PaCO₂ 60 mmHg, pH 7.34, HCO₃⁻ 34 mEq/L. This distinction is important before giving supplemental O₂ to COPD patients.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','hard','mcq','Using the Henderson-Hasselbalch equation (pH = 6.1 + log[HCO₃⁻] / 0.03 × PCO₂), in a patient with pH 7.30 and PaCO₂ 52 mmHg, the approximate HCO₃⁻ is:','["A. 12 mEq/L","B. 18 mEq/L","C. 24 mEq/L","D. 30 mEq/L"]','C','7.30 = 6.1 + log([HCO₃⁻] / 0.03 × 52) → 1.20 = log([HCO₃⁻] / 1.56) → [HCO₃⁻] = 1.56 × 10^1.20 ≈ 1.56 × 15.85 ≈ 24.7 ≈ 24 mEq/L. This acute respiratory acidosis has a normal HCO₃⁻, indicating no significant renal compensation yet.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','hard','mcq','Acetazolamide is used prophylactically for altitude sickness. Its mechanism involves:','["A. Stimulating peripheral chemoreceptors directly","B. Inhibiting renal carbonic anhydrase, causing metabolic acidosis that stimulates ventilation","C. Increasing 2,3-DPG production in red blood cells","D. Dilating pulmonary arterioles to reduce hypoxic vasoconstriction"]','B','Acetazolamide inhibits carbonic anhydrase in renal tubules, reducing HCO₃⁻ reabsorption and causing mild metabolic acidosis (HCO₃⁻ loss). The resulting acidaemia stimulates central and peripheral chemoreceptors, increasing ventilation and raising PAO₂. This counteracts the respiratory alkalosis that blunts ventilatory drive at altitude.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','CO2 Transport & Acid-Base','hard','mcq','A patient with salicylate overdose has pH 7.48, PaCO₂ 28 mmHg, HCO₃⁻ 18 mEq/L. This pattern represents:','["A. Primary respiratory alkalosis with secondary metabolic alkalosis","B. Primary metabolic acidosis with full respiratory compensation","C. Mixed respiratory alkalosis and metabolic acidosis occurring simultaneously","D. Primary metabolic alkalosis with respiratory compensation"]','C','Salicylate toxicity causes a mixed disorder: direct stimulation of the medullary respiratory centre causes respiratory alkalosis (low PCO₂, high pH tendency), while salicylate-induced uncoupling of oxidative phosphorylation causes metabolic acidosis (low HCO₃⁻). Both processes coexist simultaneously — the net pH depends on which dominates.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 8: V/Q Matching & Pulmonary Blood Flow (10 MCQs)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','easy','mcq','In the upright lung, pulmonary blood flow (perfusion) is greatest at:','["A. The apex","B. The mid-zone","C. The base","D. Equally distributed throughout"]','C','In the upright position, gravity causes blood flow to be greatest at the lung bases (Zone 3) and least at the apices (Zone 1). Pulmonary arterial pressure (~25/8 mmHg) is relatively low, making gravity a dominant factor with a hydrostatic gradient of ~1 mmHg/cm height.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','easy','mcq','Hypoxic pulmonary vasoconstriction (HPV) is unique because it:','["A. Causes vasodilation in response to low alveolar O₂","B. Causes vasoconstriction in response to low alveolar O₂, diverting blood to better-ventilated regions","C. Is mediated primarily by the sympathetic nervous system","D. Occurs only in the systemic circulation"]','B','HPV is a local homeostatic reflex: low alveolar PO₂ (below ~70 mmHg) causes adjacent pulmonary arterioles to constrict, diverting blood to better-ventilated regions. This improves V/Q matching. It is mediated by inhibition of K⁺ channels → smooth muscle depolarisation → Ca²⁺ influx. This is the OPPOSITE of the systemic O₂ response.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','medium','mcq','In West''s Zone 1 (lung apex in upright position), flow characteristics are:','["A. PA > Pa > Pv — alveolar pressure exceeds arterial pressure, capillaries are collapsed, creating alveolar dead space","B. Pa > PA > Pv — arterial pressure exceeds alveolar, flow is continuous","C. Pa > Pv > PA — all pressures exceed alveolar, flow is maximum","D. PA = Pa = Pv — all pressures equal, flow is moderate"]','A','Zone 1 (apex): Alveolar pressure (PA) > Pulmonary arterial pressure (Pa) > Pulmonary venous pressure (Pv). When PA exceeds Pa, capillaries collapse and there is no flow — creating alveolar dead space. Zone 1 occurs normally at the apex and pathologically when Pa falls (haemorrhagic shock) or PA rises (high positive pressure ventilation).','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','medium','mcq','The V/Q ratio at the lung apex in an upright individual is approximately:','["A. 0.6","B. 1.0","C. 3.3","D. 0.1"]','C','At the lung apex, ventilation is relatively preserved but perfusion is very low, giving a high V/Q ratio (~3.3). Apical alveoli have near-atmospheric composition: high PAO₂ (~130 mmHg) and low PACO₂ (~28 mmHg). The lung bases have lower V/Q (~0.6) due to greater perfusion relative to ventilation.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','medium','mcq','Pulmonary vascular resistance (PVR) differs from systemic vascular resistance (SVR) in that PVR is:','["A. 5–10 times higher than SVR","B. Much lower than SVR, reflecting the low-pressure high-flow pulmonary circulation","C. Regulated primarily by the sympathetic nervous system","D. Unchanged with increased cardiac output"]','B','PVR = (Mean PA pressure − LA pressure) / cardiac output = (15 − 5) / 5 = 2 Wood units. SVR ≈ (95 − 5) / 5 = 18 Wood units. PVR is ~6–10 times lower than SVR. PVR decreases further with increased cardiac output (capillary recruitment and distension) — the opposite of most tissues.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','medium','mcq','A V/Q ratio of 0 (zero) in a lung unit represents:','["A. Ideal gas exchange","B. Alveolar dead space (ventilation without perfusion)","C. True intrapulmonary shunt (perfusion without ventilation)","D. Normal V/Q mismatch"]','C','V/Q = 0 means perfusion present but no ventilation — blood passes through completely unventilated alveoli (e.g., atelectasis, consolidation, flooding with pus or oedema). Blood exiting these units has the same O₂/CO₂ as mixed venous blood and cannot be corrected by O₂ supplementation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','medium','mcq','Chronic hypoxia (e.g., severe COPD or living at high altitude) can lead to cor pulmonale. The sequence of events is:','["A. Hypoxia → pulmonary vasodilation → reduced PVR → right ventricular dilation","B. Hypoxia → hypoxic pulmonary vasoconstriction → pulmonary hypertension → right ventricular hypertrophy","C. Hypoxia → polycythaemia → reduced viscosity → reduced PVR","D. Hypoxia → systemic hypotension → compensatory right heart failure"]','B','Chronic hypoxia causes sustained hypoxic pulmonary vasoconstriction and subsequent pulmonary vascular remodelling (smooth muscle hypertrophy, intimal fibrosis), leading to pulmonary arterial hypertension. Elevated RV afterload causes right ventricular hypertrophy and eventual dilation — cor pulmonale.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','hard','mcq','In West''s Zone 3 (lung base), blood flow is determined by:','["A. The difference between alveolar pressure and venous pressure (PA − Pv)","B. The arterial-venous pressure gradient (Pa − Pv), independent of alveolar pressure","C. Alveolar pressure alone","D. Venous pressure minus arterial pressure"]','B','Zone 3 (base): Pa > Pv > PA. Both arterial and venous pressures exceed alveolar pressure, so capillaries remain open throughout the cardiac cycle. Flow is determined by the arterial-venous pressure gradient (Pa − Pv) — the classic Starling resistor. This zone has the greatest and most continuous blood flow.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','hard','mcq','A patient on high positive pressure mechanical ventilation (PEEP 20 cm H₂O) develops hypotension. The most likely respiratory mechanism is:','["A. High alveolar pressure expands Zone 3 and increases venous return","B. High alveolar pressure compresses pulmonary capillaries, increasing PVR and reducing cardiac output; elevated intrathoracic pressure also reduces venous return","C. PEEP causes widespread hypoxic vasoconstriction","D. PEEP increases FRC, worsening V/Q mismatch"]','B','High PEEP raises mean intrathoracic pressure, impeding venous return (reducing preload) and compressing pulmonary capillaries (increasing PVR and RV afterload). This reduces cardiac output and blood pressure. It also converts more lung to Zone 1/2 (PEEP-generated alveolar pressure exceeds arterial pressure), increasing alveolar dead space.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','V/Q Matching & Pulmonary Blood Flow','hard','mcq','In a patient with pulmonary embolism occluding the right lower lobe pulmonary artery, which immediate V/Q change occurs in the affected lung zone?','["A. V/Q ratio falls toward 0 (shunt effect)","B. V/Q ratio rises toward infinity (dead space effect)","C. V/Q ratio remains 0.8 due to compensatory redistribution","D. Hypoxic vasoconstriction reduces ventilation to match lost perfusion"]','B','Pulmonary embolism blocks perfusion (Q → 0) while ventilation of that unit continues (V remains). V/Q rises toward infinity — creating alveolar dead space. The embolised lung units ventilate but cannot participate in gas exchange, increasing physiological dead space and (if significant) raising PaCO₂. Hypoxaemia results from V/Q mismatch in remaining perfused lung units.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 9: Control of Breathing (10 MCQs)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','easy','mcq','The primary generator of the respiratory rhythm (breathing pacemaker) is located in:','["A. The pneumotaxic centre in the upper pons","B. The dorsal respiratory group/pre-Bötzinger complex in the medulla","C. The apneustic centre in the lower pons","D. The cerebral cortex"]','B','The dorsal respiratory group (DRG) in the nucleus tractus solitarius, specifically the pre-Bötzinger complex, generates the basic inspiratory rhythm. It produces rhythmic burst discharges driving each breath. Pontine centres modulate this rhythm but are not essential for its generation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','easy','mcq','Peripheral chemoreceptors that respond to low PaO₂ are located in the:','["A. Medullary ventral surface","B. Carotid and aortic bodies","C. Pulmonary stretch receptors","D. J-receptors in alveolar walls"]','B','The carotid bodies (at the bifurcation of the common carotid artery) and aortic bodies (near the aortic arch) are peripheral chemoreceptors. They respond to decreased PaO₂ (below ~60 mmHg), increased PaCO₂, and decreased pH. The carotid bodies are quantitatively more important in humans (transmit via CN IX, glossopharyngeal nerve).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','medium','mcq','Central chemoreceptors in the medulla respond primarily to:','["A. Changes in arterial PO₂","B. Changes in cerebrospinal fluid (CSF) pH, reflecting arterial PCO₂","C. Changes in arterial pH directly","D. Pulmonary stretch receptor signals"]','B','Central chemoreceptors on the ventral medullary surface are surrounded by CSF. CO₂ crosses the blood-brain barrier readily; it hydrates (via carbonic anhydrase) to H₂CO₃ → H⁺ + HCO₃⁻, lowering CSF pH. The receptors respond to this pH change (effectively sensing PCO₂). They account for ~70% of the ventilatory response to CO₂ and do NOT respond to PO₂.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','medium','mcq','The pneumotaxic centre in the upper pons primarily functions to:','["A. Generate the basic inspiratory rhythm","B. Limit the duration of inspiration, thereby increasing respiratory rate","C. Prolong inspiration to allow maximum tidal volumes","D. Respond directly to blood PO₂ changes"]','B','The pneumotaxic centre (nucleus parabrachialis, upper pons) sends continuous inhibitory signals to the inspiratory area, switching off inspiration and controlling inspiratory duration and respiratory rate. Without pneumotaxic input, inspiration is prolonged (apneusis), reducing respiratory rate and increasing tidal volume.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','medium','mcq','In long-standing COPD with chronic CO₂ retention, the primary stimulus for breathing becomes:','["A. Elevated PaCO₂ stimulating central chemoreceptors","B. Low PaO₂ stimulating peripheral chemoreceptors (hypoxic drive)","C. Low pH stimulating central chemoreceptors directly","D. Reduced lung compliance stimulating J-receptors"]','B','With chronic CO₂ retention, central chemoreceptors reset to the elevated PCO₂ baseline. CSF bicarbonate rises to normalise CSF pH, blunting the central CO₂ response. The patient relies mainly on peripheral hypoxic drive (low PaO₂). This is why excessive supplemental O₂ can paradoxically suppress ventilation in these patients and worsen CO₂ retention.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','medium','mcq','The Hering-Breuer reflex prevents over-inflation of the lungs. The receptors responsible are:','["A. Carotid body chemoreceptors","B. Slowly adapting pulmonary stretch receptors in airway smooth muscle, transmitting via the vagus nerve","C. J-receptors (juxtacapillary receptors) in alveolar walls","D. Irritant receptors in the tracheal mucosa"]','B','Slowly adapting pulmonary stretch receptors (SARs) in airway smooth muscle detect lung inflation. During large tidal breaths, they send inhibitory signals via the vagus nerve (CN X) to the inspiratory centre, terminating inspiration (inspiratory off-switch). The Hering-Breuer reflex is prominent in infants and anaesthetised adults, less so in conscious adults during normal breathing.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','medium','mcq','Which of the following is the strongest stimulus for increasing alveolar ventilation?','["A. A fall in PaO₂ from 100 to 80 mmHg","B. A rise in PaCO₂ from 40 to 50 mmHg","C. A fall in pH from 7.40 to 7.35 with normal PCO₂","D. An increase in body temperature by 1°C"]','B','CO₂/H⁺ is the most powerful stimulus for ventilation. An acute 10 mmHg rise in PaCO₂ approximately doubles alveolar ventilation. PaO₂ must fall below ~60 mmHg before peripheral chemoreceptors significantly stimulate ventilation. The CO₂ response is mediated by central (~70%) and peripheral (~30%) chemoreceptors.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','hard','mcq','Damage to the apneustic centre in the lower pons results in:','["A. Complete apnoea","B. Apneusis — prolonged inspiratory gasps with brief expirations","C. Cheyne-Stokes breathing","D. Increased respiratory rate with normal tidal volume"]','B','The apneustic centre promotes sustained inspiration. Normally the pneumotaxic centre overrides it. If the pneumotaxic centre is damaged AND vagal afferents (Hering-Breuer) are cut, the apneustic centre drives prolonged sustained inspiration (apneusis) interrupted by brief expirations. This pattern can occur with lower pontine strokes.','universal',false,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','hard','mcq','Hyperventilation before a breath-hold dive increases breath-hold time but is dangerous because:','["A. Hyperventilation raises PaO₂, providing a larger O₂ reserve but causes alkalosis","B. Hyperventilation lowers PaCO₂, delaying the CO₂ urge to breathe, but O₂ may fall to unconscious levels before PaCO₂ rises sufficiently to force breathing (shallow water blackout)","C. Hyperventilation increases lung compliance, reducing effort of breath-holding","D. Hyperventilation alkalinises blood, sensitising chemoreceptors to O₂"]','B','Hyperventilation lowers PaCO₂ significantly below normal, delaying the CO₂-stimulated urge to breathe. However, O₂ stores are only marginally increased (flat part of O₂-Hb curve). During breath-hold, O₂ falls to dangerously low levels (PaO₂ 30–40 mmHg) before PaCO₂ rises enough to force breathing — the diver may lose consciousness without warning (shallow water blackout), a life-threatening phenomenon.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Control of Breathing','hard','mcq','Congenital central hypoventilation syndrome (Ondine''s curse) results from PHOX2B mutations. Breathing is characterised by:','["A. Normal automatic breathing with inability to breathe voluntarily","B. Normal voluntary breathing but failure of automatic metabolic respiratory control during sleep","C. Increased ventilatory response to CO₂ with periodic hyperventilation","D. Episodic bronchospasm due to vagal hyperactivity"]','B','PHOX2B mutations disrupt development of chemoreceptor neurons and the automatic respiratory control system. Patients breathe normally during wakefulness (voluntary cortical control intact) but hypoventilate or apnoeae during sleep (when automatic metabolic control is required). They require nocturnal ventilatory support (e.g., home mechanical ventilation or diaphragm pacing).','universal',true,'{year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 10: Respiratory Responses (10 MCQs)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','easy','mcq','During moderate aerobic exercise, ventilation increases primarily because of:','["A. A significant rise in PaCO₂ stimulating central chemoreceptors","B. Neural signals from exercising muscles and joints (neurogenic drive), with CO₂ precisely matching ventilation to metabolism","C. A significant fall in PaO₂","D. Adrenaline release from the adrenal medulla"]','B','At the onset of exercise, ventilation increases almost instantaneously due to cortical irradiation and proprioceptive signals from muscles and joints — before any blood gas changes occur. PaCO₂, PaO₂, and pH remain near-normal during moderate exercise because ventilation increases proportionally to CO₂ production.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','easy','mcq','Acclimatisation to high altitude over several days involves which adaptive changes?','["A. Decreased erythropoietin and lower haemoglobin concentration","B. Increased erythropoietin, polycythaemia, increased 2,3-DPG, and sustained hyperventilation","C. Decreased 2,3-DPG to improve O₂ loading onto haemoglobin","D. Bronchodilation to reduce airway resistance"]','B','Altitude acclimatisation: (1) acute hyperventilation; (2) renal HCO₃⁻ excretion restoring pH to allow sustained ventilation; (3) increased EPO → polycythaemia (weeks); (4) increased 2,3-DPG (rightward shift aids tissue O₂ delivery); (5) increased pulmonary diffusing capacity. These collectively improve O₂ delivery at reduced PAO₂.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','medium','mcq','During strenuous exercise beyond the anaerobic threshold, ventilation increases disproportionately because:','["A. PaCO₂ falls significantly, stimulating central chemoreceptors","B. Lactic acidosis adds H⁺ ions that stimulate peripheral chemoreceptors, causing excess ventilation above metabolic CO₂ production","C. Core temperature directly activates the pneumotaxic centre","D. Diaphragmatic fatigue receptors increase rate"]','B','Above the anaerobic (lactate) threshold, lactic acid accumulates and H⁺ ions stimulate peripheral and central chemoreceptors in addition to the normal CO₂ drive. This produces disproportionate ventilation increase (VE/VCO₂ rises), causing PaCO₂ to fall below normal — respiratory compensation for metabolic acidosis.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','medium','mcq','Acute exposure to very high altitude (above 5500 m) produces which immediate respiratory change?','["A. Hypoventilation due to suppressed peripheral chemoreceptors","B. Hyperventilation causing respiratory alkalosis, driven by peripheral chemoreceptor response to low PaO₂","C. Increased PaCO₂ as CO₂ production rises with hypoxia","D. Decreased respiratory rate with increased tidal volume"]','B','Acute high altitude exposure lowers PAO₂ and PaO₂. When PaO₂ falls below ~60 mmHg, carotid body peripheral chemoreceptors are strongly activated, causing hyperventilation. This reduces PaCO₂ (respiratory alkalosis). The resulting alkalosis partially dampens the drive, but peripheral hypoxic stimulation maintains elevated ventilation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','medium','mcq','Obstructive sleep apnoea (OSA) is characterised by:','["A. Central apnoea with no respiratory effort","B. Repetitive upper airway collapse causing cessation of airflow despite continued respiratory effort","C. Reduced tidal volume without upper airway obstruction","D. Paradoxical increase in ventilation during REM sleep"]','B','OSA is caused by upper airway muscle hypotonia during sleep (especially pharyngeal dilators), causing repetitive pharyngeal collapse. Continued inspiratory effort against the closed airway generates large negative intrathoracic pressures without airflow (obstructive apnoeas), terminating with arousal. This is distinguished from central apnoea where respiratory effort ceases entirely.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','medium','mcq','Cheyne-Stokes breathing is characterised by:','["A. Rapid shallow breathing at a fixed rate","B. Cyclic crescendo-decrescendo breathing with periods of apnoea, caused by oscillation in the ventilatory control system","C. Prolonged inspiration followed by rapid expiration","D. Increased tidal volume without change in respiratory rate"]','B','Cheyne-Stokes breathing occurs due to instability in the respiratory control loop — most commonly when circulation time from lungs to brain is prolonged (e.g., severe heart failure), causing delayed and oscillating CO₂ signals. Also seen in CNS lesions, uraemia, and high altitude (where hypocapnia from hyperventilation periodically silences breathing).','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','medium','mcq','High altitude pulmonary oedema (HAPE) is caused primarily by:','["A. Alveolar hypoventilation causing CO₂ retention and fluid shift","B. Non-uniform hypoxic vasoconstriction with regions of high-pressure blood flow causing pulmonary capillary stress failure","C. Decreased serum albumin causing low oncotic pressure","D. Increased pleural pressure compressing alveoli"]','B','HAPE pathophysiology: non-uniform HPV diverts blood to regions with less vasoconstriction, which then experience high blood flow and high capillary hydrostatic pressure. This leads to mechanical capillary injury (stress failure) and high-protein oedema. Risk factors include rapid ascent and physical exertion at altitude.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','hard','mcq','During REM sleep, breathing becomes irregular because:','["A. Chemoreceptor sensitivity is markedly increased during REM sleep","B. Upper airway muscle tone is preserved but cortical respiratory drive is reduced","C. The automatic medullary breathing centres are suppressed; breathing becomes driven by variable cortical input, with reduced skeletal muscle tone making it irregular","D. Tidal volume increases by 50% during REM due to diaphragmatic hyperstimulation"]','C','During REM sleep, the medullary respiratory centres are relatively suppressed and breathing becomes irregular — resembling voluntary waking patterns. Skeletal (intercostal and accessory) muscle tone is markedly reduced (REM atonia), so breathing depends mainly on the diaphragm. Patients with neuromuscular disease or severe COPD are most vulnerable to respiratory failure during REM sleep.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','hard','mcq','At maximal exercise in a trained athlete, O₂ delivery (VO₂max up to 4–5 L/min) is primarily maintained by:','["A. Increased haemoglobin concentration by splenic contraction alone","B. Increased cardiac output (up to 25–30 L/min), wider arteriovenous O₂ difference, and increased pulmonary diffusing capacity","C. Activation of anaerobic metabolism as the dominant pathway","D. Increased respiratory rate only, with unchanged cardiac output"]','B','VO₂max depends primarily on: (1) cardiac output (rises from 5 to 25+ L/min in athletes); (2) increased O₂ extraction (C(a-v)O₂ widens from ~5 to ~15 ml/dl); (3) increased DLCO (capillary recruitment). Ventilation rises to 100–150 L/min but is rarely the limiting factor in healthy individuals; cardiac output is the primary constraint.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Respiratory Responses','hard','mcq','A mountaineer at 8000 m breathing ambient air (PB ≈ 267 mmHg) without supplemental O₂, with hyperventilation reducing PaCO₂ to 12 mmHg, would have an estimated PAO₂ of approximately:','["A. 100 mmHg","B. 60 mmHg","C. 31 mmHg","D. 15 mmHg"]','C','PiO₂ = 0.21 × (267 − 47) = 0.21 × 220 = 46.2 mmHg. PAO₂ = 46.2 − (12/0.8) = 46.2 − 15 = 31.2 ≈ 31 mmHg. Actual measurements on the summit of Everest (8849 m) show PAO₂ ≈ 28–35 mmHg — near the level of loss of consciousness without acclimatisation. Only extreme acclimatisation allows survival.','universal',true,'{year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# Write to file (appending, replacing last comma with );)
output = ',\n'.join(rows)
# The last row needs ); instead of ,
with open('/sessions/keen-ecstatic-cannon/mnt/Skoolie/scripts/med_resp_ap_mcq.sql', 'a') as f:
    f.write(output + '\n);\n')
print(f"Part 2 written: {len(rows)} rows (subtopics 6-10)")
