import os

output_path = "/sessions/keen-ecstatic-cannon/mnt/Skoolie/scripts/med_resp_ap_mcq.sql"

rows = []

# ============================================================
# SUBTOPIC 1: Lung Anatomy & Airway Structure (10 MCQs)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','easy','mcq','How many lobes does the right lung contain?','["A. Two","B. Three","C. Four","D. Five"]','B','The right lung is divided into three lobes — superior, middle, and inferior — separated by the horizontal and oblique fissures. The left lung has only two lobes due to the cardiac notch.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','easy','mcq','Which cell type produces pulmonary surfactant?','["A. Type I pneumocytes","B. Type II pneumocytes","C. Club (Clara) cells","D. Alveolar macrophages"]','B','Type II pneumocytes (granular pneumocytes) synthesise and secrete surfactant, a phospholipid-rich mixture that reduces alveolar surface tension. Type I pneumocytes are thin cells responsible for gas exchange.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','medium','mcq','Which cell type lines the majority (~97%) of the alveolar surface area and is primarily responsible for gas exchange?','["A. Type II pneumocytes","B. Alveolar macrophages","C. Type I pneumocytes","D. Club (Clara) cells"]','C','Type I pneumocytes are flat squamous cells covering approximately 97% of the alveolar surface. Their extreme thinness (~0.1–0.5 µm) minimises diffusion distance for gas exchange. Type II cells cover only ~3% but are metabolically far more active.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','medium','mcq','Which structure marks the boundary between the conducting zone and the respiratory zone of the lung?','["A. Terminal bronchiole","B. Respiratory bronchiole","C. Alveolar duct","D. Alveolar sac"]','B','The respiratory bronchiole is the first airway that contains alveoli in its wall and therefore participates in gas exchange. All airway generations proximal to it — including the terminal bronchiole — form the purely conducting zone.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','medium','mcq','The right main bronchus is more prone to foreign body aspiration than the left primarily because it is:','["A. Wider and more vertical","B. Narrower and more horizontal","C. Longer with more cartilaginous rings","D. Lined with non-ciliated epithelium"]','A','The right main bronchus diverges at a smaller angle (~25°) from the trachea, making it more vertical and wider than the left (~45°). This anatomy makes inhaled foreign bodies more likely to enter the right lung.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','medium','mcq','How many bronchopulmonary segments does the right lung contain?','["A. 8","B. 9","C. 10","D. 12"]','C','The right lung contains 10 bronchopulmonary segments: 3 in the upper lobe, 2 in the middle lobe, and 5 in the lower lobe. Each segment is supplied by its own segmental bronchus and pulmonary arterial branch, making them surgically resectable units.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','medium','mcq','Approximately at which generation of the airway tree do cartilaginous rings disappear, marking the transition to bronchioles?','["A. Generation 4","B. Generation 8","C. Generation 11","D. Generation 16"]','C','Bronchioles begin at approximately generation 11 of the airway tree where cartilage is absent. They are maintained patent by radial traction from surrounding alveolar tissue rather than cartilaginous support. Loss of this traction (e.g., emphysema) causes small airway collapse.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','hard','mcq','A patient undergoes surgical resection of the lingula. Which lobe and segments of the left lung are removed?','["A. Left upper lobe, superior and inferior lingular segments","B. Left lower lobe, anterior basal and lateral basal segments","C. Left upper lobe, apicoposterior and anterior segments","D. Left lower lobe, superior segment only"]','A','The lingula is a tongue-like projection of the left upper lobe anatomically equivalent to the right middle lobe. It consists of two bronchopulmonary segments: superior lingular (B4) and inferior lingular (B5).','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','hard','mcq','Club (Clara) cells, found predominantly in terminal and respiratory bronchioles, primarily serve which function?','["A. Mucociliary clearance of inhaled particles","B. Secretion of a protective lipid-rich material and cytochrome P450-mediated detoxification of inhaled toxins","C. Phagocytosis of alveolar debris","D. Production of secretory IgA for mucosal immunity"]','B','Club cells are non-ciliated secretory cells that produce a lipid-protein secretion protecting the bronchiolar epithelium. They also contain cytochrome P450 enzymes that detoxify inhaled xenobiotics, and they serve as progenitor cells for bronchiolar epithelium repair.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Anatomy & Airway Structure','hard','mcq','Pores of Kohn are inter-alveolar communications that become clinically significant when they allow:','["A. Surfactant to redistribute between adjacent alveoli","B. Collateral ventilation, which can maintain aeration of lung distal to an obstructed airway","C. Transfer of alveolar macrophages between alveoli","D. Spread of pulmonary oedema fluid to adjacent alveoli"]','B','Pores of Kohn permit collateral ventilation between adjacent alveoli and, via the canals of Lambert, between bronchioles and alveoli. This prevents atelectasis when a small airway is blocked, but also allows spread of infection across a lobe (e.g., pneumococcal lobar pneumonia).','universal',false,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 2: Pulmonary Mechanics (10 MCQs)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','easy','mcq','Normal total lung compliance in a healthy adult is approximately:','["A. 50 ml/cm H₂O","B. 100 ml/cm H₂O","C. 200 ml/cm H₂O","D. 400 ml/cm H₂O"]','C','Normal total lung compliance is approximately 200 ml/cm H₂O, meaning the lungs expand by 200 ml for every 1 cm H₂O increase in transpulmonary pressure. Reduced compliance occurs in pulmonary fibrosis; increased compliance in emphysema.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','easy','mcq','According to Laplace''s law, the pressure required to keep an alveolus open is:','["A. Directly proportional to both surface tension and radius","B. Directly proportional to surface tension and inversely proportional to radius","C. Inversely proportional to both surface tension and radius","D. Independent of surface tension"]','B','Laplace''s law: P = 2T/r. Pressure is proportional to surface tension (T) and inversely proportional to radius (r). Smaller alveoli therefore tend to collapse unless surfactant reduces their surface tension more than larger alveoli, stabilising the system.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','medium','mcq','Which phospholipid is the most abundant and functionally important component of pulmonary surfactant?','["A. Phosphatidylglycerol","B. Phosphatidylinositol","C. Dipalmitoylphosphatidylcholine (DPPC)","D. Sphingomyelin"]','C','Dipalmitoylphosphatidylcholine (DPPC, also called dipalmitoyl lecithin) constitutes approximately 40–50% of surfactant and is the principal surface-tension-lowering molecule. Surfactant production begins at about 26–28 weeks gestation, explaining respiratory distress syndrome in premature neonates.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','medium','mcq','At FRC, breathing muscles are relaxed. The equilibrium is maintained because:','["A. Inspiratory muscle force equals expiratory muscle force","B. Inward elastic recoil of lungs equals outward elastic recoil of the chest wall","C. Diaphragm contraction balances abdominal pressure","D. Alveolar pressure equals atmospheric pressure"]','B','At FRC, no respiratory muscles are active. The inward elastic recoil of the lungs (tendency to collapse) equals the outward elastic recoil of the chest wall (tendency to spring out). These opposing forces balance, defining the resting end-expiratory lung volume.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','medium','mcq','Transpulmonary pressure is defined as:','["A. Atmospheric pressure minus alveolar pressure","B. Alveolar pressure minus pleural pressure","C. Pleural pressure minus atmospheric pressure","D. Alveolar pressure minus atmospheric pressure"]','B','Transpulmonary pressure = Palveolar − Ppleural. It is the distending pressure that keeps the lung open. At end-expiration (FRC), Palv = 0 cmH₂O (atmospheric), Ppleural = −5 cmH₂O, so transpulmonary pressure = +5 cmH₂O, preventing lung collapse.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','medium','mcq','A patient with pulmonary fibrosis has decreased lung compliance. Which spirometric pattern is expected?','["A. Increased TLC with decreased FEV1/FVC","B. Decreased TLC with normal or increased FEV1/FVC","C. Normal TLC with severely decreased FEV1 only","D. Increased RV with decreased VC"]','B','Pulmonary fibrosis is restrictive. Stiff (low-compliance) lungs reduce all volumes — TLC, VC, FRC, and RV. Because airways are not intrinsically obstructed, FEV1 and FVC fall proportionally, so FEV1/FVC is normal or increased (>0.80).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','medium','mcq','During forced expiration, dynamic airway compression occurs at the equal pressure point because:','["A. Increased positive pleural pressure compresses airways at the point where luminal pressure equals pleural pressure","B. The diaphragm descends and narrows the bronchi","C. Surfactant is depleted during forced exhalation","D. Pulmonary vascular pressure rises and compresses bronchi externally"]','A','During forced expiration, positive pleural pressure is transmitted to airways. At the equal pressure point, airway luminal pressure = pleural pressure; downstream (mouthward), pleural pressure exceeds luminal pressure, collapsing airways. This creates effort-independent maximum expiratory flow — the hallmark of obstructive disease.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','hard','mcq','A premature neonate at 28 weeks gestation develops progressive respiratory distress shortly after birth. The primary pathophysiological mechanism is:','["A. Airway obstruction by meconium","B. Surfactant deficiency causing alveolar collapse and markedly reduced compliance","C. Excess surfactant production causing alveolar flooding","D. Immature medullary respiratory centres causing central apnoea"]','B','Neonatal respiratory distress syndrome (NRDS) results from surfactant deficiency; type II pneumocytes are functionally immature before ~35 weeks gestation. Without surfactant, high surface tension causes progressive atelectasis and the infant must generate enormous inspiratory pressures. Treatment is exogenous surfactant and antenatal glucocorticoids.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','hard','mcq','Hysteresis in the lung pressure-volume curve means:','["A. Compliance is identical during inspiration and expiration","B. Greater pressure is required to inflate the lung to a given volume than to maintain that volume during deflation, due to surface tension forces","C. Airway resistance increases during expiration only","D. Tidal volume is identical on inspiration and expiration"]','B','Hysteresis occurs because during inspiration, pressure must overcome elastic recoil AND surface tension to recruit collapsed alveoli. During expiration, surfactant compresses and further reduces surface tension, so less pressure is needed. The inspiratory and expiratory pressure-volume curves trace different paths.','universal',false,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Pulmonary Mechanics','hard','mcq','In emphysema, static compliance is increased but expiratory flow is severely reduced. The mechanism of airflow obstruction is:','["A. Bronchoconstriction from airway inflammation","B. Loss of alveolar radial traction that normally holds small airways open during expiration","C. Mucus plugging of large central airways","D. Increased surface tension from surfactant destruction"]','B','In emphysema, destruction of alveolar walls removes the radial traction that normally holds small airways open. During expiration (especially forced), these unsupported airways collapse prematurely, trapping air and increasing RV. FEV1 is reduced disproportionately, giving low FEV1/FVC despite high static compliance.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 3: Lung Volumes & Capacities (10 MCQs)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','easy','mcq','Which lung volume CANNOT be measured directly by spirometry?','["A. Tidal volume","B. Inspiratory reserve volume","C. Residual volume","D. Expiratory reserve volume"]','C','Residual volume (RV) is the air remaining after maximal expiration — it cannot be expelled into the spirometer. It requires indirect methods such as helium dilution, nitrogen washout, or body plethysmography. Any capacity containing RV (FRC, TLC) also cannot be measured by spirometry alone.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','easy','mcq','Normal tidal volume in a healthy adult male at rest is approximately:','["A. 150 ml","B. 350 ml","C. 500 ml","D. 1200 ml"]','C','Tidal volume (Vt) averages ~500 ml (0.5 L) in a healthy adult male at rest. This is the volume moved with each normal effortless breath. At 12–16 breaths/min, this gives a minute ventilation of 6–8 L/min.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','medium','mcq','Total Lung Capacity (TLC) in a healthy young adult male averages approximately:','["A. 3500 ml","B. 4600 ml","C. 5800 ml","D. 7000 ml"]','C','TLC = VC + RV ≈ 4600 + 1200 = 5800 ml in a healthy young adult male (Guyton & Hall values). TLC is increased in emphysema (air trapping) and decreased in restrictive diseases such as fibrosis or pleural effusion.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','medium','mcq','A patient has a FEV1 of 1.2 L and an FVC of 3.0 L (FEV1/FVC = 0.40). This pattern is most consistent with:','["A. Restrictive lung disease (e.g., pulmonary fibrosis)","B. Obstructive lung disease (e.g., COPD or asthma)","C. Normal spirometry","D. Mixed obstructive-restrictive pattern with normal ratio"]','B','FEV1/FVC < 0.70 defines airflow obstruction. Here the ratio is 0.40, indicating severe obstruction. In obstructive disease, FEV1 falls disproportionately more than FVC because airways collapse during forced expiration. Normal FEV1/FVC ≥ 0.80.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','medium','mcq','Functional Residual Capacity (FRC) equals:','["A. Tidal volume + Inspiratory reserve volume","B. Expiratory reserve volume + Residual volume","C. Vital capacity + Residual volume","D. Inspiratory capacity + Expiratory reserve volume"]','B','FRC = ERV + RV. It is the volume remaining in the lungs after a normal passive expiration. In healthy adult males, FRC ≈ 1100 + 1200 = 2300 ml. FRC increases in emphysema (hyperinflation) and decreases in the supine position, obesity, and restrictive diseases.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','medium','mcq','On a flow-volume loop, obstructive disease characteristically shows which expiratory pattern?','["A. A tall narrow peak with steep linear descent","B. A scooped-out (concave) expiratory curve with reduced mid and late expiratory flows","C. A vertical expiratory limb with increased FVC","D. No change from the normal pattern"]','B','In obstructive disease (asthma, COPD), the expiratory limb shows a classic scooped or concave shape due to disproportionate reduction in flow at low lung volumes. Peak expiratory flow may be relatively preserved initially, but FEF25–75% is markedly reduced.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','medium','mcq','Inspiratory Capacity (IC) is equal to:','["A. Tidal volume + Inspiratory reserve volume only","B. TLC − FRC only","C. The maximal volume inspireable from FRC only","D. All of the above — these are equivalent definitions"]','D','IC = Vt + IRV = TLC − FRC = maximum volume inspireable from FRC. In a healthy adult male, IC ≈ 500 + 3000 = 3500 ml. IC is reduced in restrictive disease and hyperinflation (elevated FRC reduces IC because TLC cannot increase proportionally).','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','hard','mcq','Body plethysmography measures TLC using Boyle''s law. Compared with helium dilution, plethysmographic TLC in a patient with severe COPD and bullae will be:','["A. Lower, because gas cannot exit the bullae during helium equilibration","B. Higher, because plethysmography measures all intrathoracic gas including trapped air in bullae","C. Identical, since both methods measure total lung gas","D. Lower, because plethysmography underestimates large lung volumes"]','B','Helium dilution measures only gas communicating with the airways; trapped gas in bullae is excluded, giving a falsely low TLC/FRC. Body plethysmography measures total thoracic gas volume (by Boyle''s law using pressure-volume changes during panting) and therefore includes trapped gas, giving a larger, more accurate value.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','hard','mcq','In a patient with a large right pleural effusion, which spirometric pattern is most expected?','["A. Decreased FVC and decreased TLC with normal FEV1/FVC — restrictive pattern","B. Decreased FEV1/FVC with normal TLC — obstructive pattern","C. Increased TLC with decreased FVC","D. Normal spirometry with increased RV"]','A','A large pleural effusion compresses the lung externally, reducing FRC, VC, and TLC — a restrictive defect. Airways are not intrinsically obstructed, so FEV1 and FVC fall proportionally, maintaining or increasing FEV1/FVC ratio.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Lung Volumes & Capacities','hard','mcq','Closing capacity (CC) exceeds FRC in elderly and obese patients. The physiological consequence is:','["A. Improved V/Q matching in the lung bases","B. Small airway closure during tidal breathing, causing gas trapping and V/Q mismatch with resultant hypoxaemia","C. Decreased airway resistance throughout the respiratory cycle","D. Reduced work of breathing due to early airway closure"]','B','When CC > FRC, small airways close during normal tidal breathing, trapping gas distally and creating V/Q mismatch with consequent hypoxaemia. This explains why the elderly and obese have lower PaO₂, particularly when supine (FRC decreases further in the supine position).','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 4: Ventilation & Dead Space (10 MCQs)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','easy','mcq','Anatomical dead space in a healthy young adult normally measures approximately:','["A. 50 ml","B. 150 ml","C. 350 ml","D. 500 ml"]','B','Anatomical dead space is ~150 ml in a young adult male — approximately 1 ml per pound (2.2 ml/kg) body weight. It represents the volume of conducting airways (nose to terminal bronchioles) that contain fresh air but do not participate in gas exchange.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','easy','mcq','Alveolar ventilation (VA) is calculated as:','["A. Tidal volume × Respiratory rate","B. (Tidal volume − Dead space volume) × Respiratory rate","C. Minute ventilation + Dead space ventilation","D. Tidal volume / Respiratory rate"]','B','Alveolar ventilation = (Vt − VD) × RR. Only the portion of each breath reaching the alveoli participates in gas exchange. Example: (500 ml − 150 ml) × 12 = 4200 ml/min alveolar ventilation. Minute ventilation overestimates effective ventilation by including dead space.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','medium','mcq','In the clinical application of the Bohr equation for physiological dead space, what is used as the surrogate for alveolar PCO₂?','["A. Mixed expired O₂ tension","B. Arterial PCO₂ (PaCO₂)","C. End-tidal CO₂ tension alone","D. Venous PCO₂"]','B','Bohr equation: VD/Vt = (PaCO₂ − PeCO₂) / PaCO₂. Since all CO₂ in expired gas comes from perfused alveoli, arterial PCO₂ equals ideal alveolar PCO₂. In normal lungs, physiological dead space ≈ anatomical dead space; it increases with V/Q mismatch (e.g., pulmonary embolism).','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','medium','mcq','A patient breathes at 20 breaths/min with a tidal volume of 200 ml and a dead space of 150 ml. What is the alveolar ventilation rate?','["A. 4000 ml/min","B. 1000 ml/min","C. 2600 ml/min","D. 3400 ml/min"]','B','Alveolar ventilation = (Vt − VD) × RR = (200 − 150) × 20 = 50 × 20 = 1000 ml/min. This rapid shallow breathing pattern is very inefficient — nearly all of the minute ventilation (4000 ml/min) is wasted ventilating dead space. This pattern leads to CO₂ retention.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','medium','mcq','Which condition increases physiological dead space ABOVE anatomical dead space?','["A. Hypoventilation","B. Pulmonary embolism","C. Pneumonia causing lung consolidation","D. Bronchospasm"]','B','Physiological dead space = anatomical dead space + alveolar dead space. Alveolar dead space arises when alveoli are ventilated but not perfused (high V/Q units). Pulmonary embolism blocks perfusion to ventilated lung units, creating alveolar dead space and increasing physiological dead space. PaCO₂ rises or ventilation must increase to compensate.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','medium','mcq','Alveolar PCO₂ (PACO₂) is related to alveolar ventilation (VA) and CO₂ production (VCO₂) as follows:','["A. PACO₂ is directly proportional to both VCO₂ and alveolar ventilation","B. PACO₂ is directly proportional to VCO₂ and inversely proportional to alveolar ventilation","C. PACO₂ is inversely proportional to VCO₂ and directly proportional to minute ventilation","D. PACO₂ is independent of alveolar ventilation"]','B','PACO₂ = (VCO₂ / VA) × k. When CO₂ production increases (exercise, fever) or alveolar ventilation decreases (hypoventilation, sedation), PACO₂ rises. This is the basis of the alveolar ventilation equation and explains hypercapnia in respiratory failure.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','medium','mcq','A mechanically ventilated patient has PaCO₂ of 55 mmHg. The most appropriate ventilator adjustment to lower PaCO₂ is:','["A. Decrease tidal volume to 300 ml","B. Increase respiratory rate or tidal volume to increase alveolar ventilation","C. Add PEEP to recruit alveoli","D. Reduce FiO₂"]','B','PaCO₂ is inversely proportional to alveolar ventilation. To lower PaCO₂, increase alveolar ventilation by increasing RR or Vt (increasing Vt is more efficient since dead space proportion decreases). PEEP recruits alveoli to improve oxygenation, not CO₂ clearance directly.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','hard','mcq','The normal whole-lung V/Q ratio is approximately 0.8. This means:','["A. For every litre of ventilation there are 0.8 litres of perfusion","B. Alveolar ventilation (~4 L/min) is slightly less than pulmonary blood flow/cardiac output (~5 L/min)","C. Both A and B describe the same ratio","D. Ventilation exceeds perfusion, giving a ratio greater than 1"]','C','Normal resting alveolar ventilation ≈ 4 L/min; cardiac output (pulmonary blood flow) ≈ 5 L/min; V/Q = 4/5 = 0.8. The lung is slightly over-perfused relative to ventilation, contributing to the normal alveolar-arterial PO₂ gradient.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','hard','mcq','A patient receives a tracheostomy, reducing anatomical dead space from 150 ml to 50 ml. With unchanged respiratory pattern (Vt 500 ml, RR 12/min), alveolar ventilation increases by:','["A. 600 ml/min","B. 1200 ml/min","C. 2400 ml/min","D. No change — dead space reduction does not affect alveolar ventilation"]','B','Original VA = (500 − 150) × 12 = 4200 ml/min. Post-tracheostomy VA = (500 − 50) × 12 = 5400 ml/min. Increase = 1200 ml/min. Reducing dead space improves alveolar ventilation efficiency — important in patients with borderline ventilatory reserve.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Ventilation & Dead Space','hard','mcq','Using the alveolar gas equation (PAO₂ = PiO₂ − PACO₂/R) at sea level on room air (PB=760, PH₂O=47 mmHg, FiO₂=0.21, PaCO₂=40 mmHg, R=0.8), the expected PAO₂ is closest to:','["A. 100 mmHg","B. 150 mmHg","C. 40 mmHg","D. 60 mmHg"]','A','PiO₂ = 0.21 × (760 − 47) = 0.21 × 713 = 149.7 mmHg. PAO₂ = 149.7 − (40/0.8) = 149.7 − 50 = 99.7 ≈ 100 mmHg. Comparing this to arterial PO₂ (~95 mmHg) gives the normal A-a gradient of ~5–10 mmHg.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# ============================================================
# SUBTOPIC 5: Gas Exchange & Diffusion (10 MCQs)
# ============================================================
rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','easy','mcq','According to Fick''s law of diffusion, the rate of gas transfer across the alveolar membrane is INVERSELY proportional to:','["A. Surface area of the membrane","B. Partial pressure difference across the membrane","C. Membrane thickness","D. Solubility of the gas"]','C','Fick''s law: Rate ∝ (A × D × ΔP) / T, where A = surface area, D = diffusivity, ΔP = pressure gradient, T = thickness. Diffusion rate is INVERSELY proportional to thickness. Increased thickness in pulmonary oedema or fibrosis reduces gas exchange.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','easy','mcq','Carbon dioxide diffuses across the respiratory membrane approximately how many times faster than oxygen?','["A. The same rate","B. 2 times faster","C. 20 times faster","D. 100 times faster"]','C','CO₂ diffuses ~20 times faster than O₂ across the respiratory membrane primarily due to its much higher solubility in tissue fluids, even though its molecular weight is slightly higher. This is why CO₂ exchange is rarely impaired by diffusion limitation, unlike O₂.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','medium','mcq','A patient with interstitial pulmonary fibrosis has reduced DLCO. Exercise-induced hypoxaemia occurs because:','["A. Reduced surface area and thickened membrane limit O₂ diffusion, worsened when capillary transit time shortens during exercise","B. Increased CO₂ production drives O₂ off haemoglobin via the Bohr effect","C. Increased cardiac output causes pulmonary oedema during exercise","D. Ventilatory failure causes hypoventilation during exercise"]','A','In fibrosis, the diffusion capacity (DLCO) is reduced due to thickened membrane and reduced surface area. At rest, 0.75-second capillary transit time is sufficient for O₂ equilibration. During exercise, transit time shortens to ~0.25 seconds — insufficient for O₂ equilibration through the thickened membrane — causing diffusion-limited hypoxaemia.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','medium','mcq','Which gas is perfusion-limited (rather than diffusion-limited) under normal resting conditions?','["A. Carbon monoxide (CO)","B. Nitrous oxide (N₂O)","C. Oxygen at high altitude","D. Oxygen in pulmonary fibrosis"]','B','Nitrous oxide (N₂O) is perfusion-limited because it equilibrates so rapidly across the alveolar membrane that its uptake depends entirely on blood flow. CO is diffusion-limited because it binds avidly to haemoglobin, maintaining near-zero blood PCO and a persistent gradient. O₂ is normally perfusion-limited but becomes diffusion-limited in fibrosis or during heavy exercise.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','medium','mcq','The normal diffusing capacity for O₂ (DLO₂) at rest in a young adult male is approximately:','["A. 5 ml/min/mmHg","B. 21 ml/min/mmHg","C. 60 ml/min/mmHg","D. 100 ml/min/mmHg"]','B','Resting DLO₂ ≈ 21 ml/min/mmHg (Guyton & Hall). During strenuous exercise it can rise to ~65 ml/min/mmHg due to recruitment of additional pulmonary capillaries and improved V/Q matching. DLCO (measured clinically) is ~17–25 ml/min/mmHg at rest.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','medium','mcq','True intrapulmonary shunt (V/Q = 0) differs from V/Q mismatch in that shunt:','["A. Is corrected by administering 100% oxygen","B. Cannot be corrected by 100% oxygen because shunted blood bypasses ventilated alveoli entirely","C. Only occurs with anatomical cardiac defects such as ASD","D. Causes hypercapnia more than hypoxaemia"]','B','True shunt (V/Q = 0) bypasses ventilated alveoli entirely, so no amount of supplemental oxygen can oxygenate the shunted blood. In V/Q mismatch (low but non-zero V/Q), supplemental O₂ can oxygenate poorly ventilated units. Failure to correct hypoxaemia with high-flow O₂ suggests shunt physiology.','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','medium','mcq','The normal alveolar-arterial (A-a) PO₂ gradient on room air in a healthy young adult is:','["A. 0 mmHg","B. 5–15 mmHg","C. 40 mmHg","D. Greater than 20 mmHg always"]','B','The normal A-a gradient is 5–15 mmHg, arising from ~2% anatomical shunt (bronchial and Thebesian veins) and minor V/Q inequality. It increases with age (normal ≤ [age/4 + 4] mmHg) and is elevated in all forms of intrinsic lung disease (shunt, V/Q mismatch, or diffusion impairment).','universal',true,'{year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','hard','mcq','A patient has an elevated A-a gradient that fully corrects with 100% O₂ inhalation. The most likely cause is:','["A. Intracardiac right-to-left shunt (e.g., patent foramen ovale)","B. Pulmonary arteriovenous malformation","C. V/Q mismatch (e.g., pulmonary embolism or COPD)","D. Diffusion impairment alone without any shunt"]','C','When the A-a gradient corrects fully with 100% O₂, it indicates low but non-zero V/Q units that can be recruited with supplemental O₂. True shunts (anatomical or intrapulmonary) do NOT correct with 100% O₂. The 100% O₂ test distinguishes V/Q mismatch from shunt physiology.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','hard','mcq','DLCO is measured using carbon monoxide because:','["A. CO has the highest solubility of all gases","B. CO binds haemoglobin with ~240× greater affinity than O₂, keeping capillary PCO near zero, making CO uptake purely diffusion-limited","C. CO is non-toxic in the concentrations used","D. CO does not react with haemoglobin and stays dissolved"]','B','CO binds haemoglobin with ~240 times the affinity of O₂, maintaining near-zero dissolved CO in blood and a persistent driving gradient. This makes CO uptake purely diffusion-limited, so DLCO = (CO uptake rate) / (alveolar PCO − capillary PCO) measures membrane conductance.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

rows.append("""('{"medicine"}','Medicine','Respiratory System','Anatomy & Physiology','Gas Exchange & Diffusion','hard','mcq','A 35-year-old with scleroderma has PaO₂ 68 mmHg at rest and PaO₂ 48 mmHg on exercise (room air). DLCO is 40% predicted. The mechanism most responsible for exercise desaturation is:','["A. Increased O₂ consumption overwhelms cardiac output","B. Diffusion impairment with shortened pulmonary capillary transit time during exercise","C. V/Q mismatch from exercise-induced hypoxic vasoconstriction","D. CO₂ retention causing the Haldane effect"]','B','Scleroderma causes interstitial lung disease with reduced DLCO due to thickened diffusion membrane and reduced surface area. Exercise increases cardiac output, shortening pulmonary capillary transit time from ~0.75 s to ~0.25 s. The already-impaired membrane cannot achieve O₂ equilibration, causing diffusion-limited exercise desaturation.','universal',true,'{year3,year4,year5,year6,practitioner}','Guyton & Hall Textbook of Medical Physiology 14th Ed')""")

# Write to file
output = ',\n'.join(rows) + ','
with open('/sessions/keen-ecstatic-cannon/mnt/Skoolie/scripts/med_resp_ap_mcq.sql', 'a') as f:
    f.write(output + '\n')
print(f"Part 1 written: {len(rows)} rows (subtopics 1-5)")
