-- Renal System Pharmacology Flashcards
-- 100 flashcards across 10 subtopics (10 each)
-- Source: Lippincott Illustrated Reviews Pharmacology 7th Ed

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Loop Diuretics','easy','flashcard','What transporter does furosemide inhibit, and where is it located?','["Na+/K+/2Cl- cotransporter (NKCC2) in the thick ascending limb of the loop of Henle"]','A','NKCC2 in the thick ascending limb reabsorbs 25-30% of filtered NaCl. Loop diuretics block this, producing the greatest diuretic effect of any class.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Loop Diuretics','easy','flashcard','What is the most common electrolyte adverse effect of loop diuretics?','["Hypokalemia — excess Na+ delivery to the collecting duct drives K+ secretion via Na+/K+ exchange"]','A','Hypokalemia is the most frequent adverse effect. Management: KCl supplementation, dietary K+, or addition of a K+-sparing diuretic.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Loop Diuretics','medium','flashcard','How do loop diuretics affect urinary calcium, and what is the clinical use?','["Loop diuretics INCREASE urinary Ca2+ excretion (hypercalciuria) — useful for treating hypercalcemia of malignancy (with IV saline)"]','A','Loop diuretics block paracellular Ca2+ reabsorption in the ascending loop. Opposite of thiazides, which DECREASE Ca2+ excretion.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Loop Diuretics','medium','flashcard','Why does furosemide have unpredictable oral bioavailability, and which loop diuretic is preferred for reliable oral dosing?','["Furosemide bioavailability ranges 10-90%. Torsemide or bumetanide preferred — 80-100% reliable oral bioavailability"]','A','Variable furosemide absorption makes oral dosing less predictable. Torsemide also has longer duration of action, potentially improving adherence.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Loop Diuretics','medium','flashcard','What is the mechanism of ototoxicity with loop diuretics, and which drug in the class carries the highest risk?','["Inhibition of NKCC1 in the stria vascularis disrupts the endocochlear potential. Ethacrynic acid carries the highest ototoxicity risk."]','A','Ototoxicity risk increases with rapid IV infusion, high doses, and concurrent aminoglycoside use. Ethacrynic acid is the only non-sulfonamide loop diuretic, used for sulfonamide allergy.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Loop Diuretics','hard','flashcard','Describe the dose-response curve of loop diuretics and the clinical implication.','["Sigmoidal (S-shaped) curve: threshold → steep rise → ceiling. Clinicians adjust FREQUENCY (not dose beyond ceiling) to modulate daily diuresis."]','A','Below the threshold, no diuresis occurs. Above the ceiling, more drug produces no more diuresis — only toxicity. Adjust dosing intervals, not max dose.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Loop Diuretics','easy','flashcard','Loop diuretics are the drugs of CHOICE for which 3 acute clinical situations?','["1. Acute pulmonary edema; 2. Hypercalcemia (with saline); 3. Hyperkalemia (adjunct therapy)"]','A','For acute pulmonary edema, IV furosemide provides rapid venodilation (before diuresis) and then potent fluid removal. For hypercalcemia, promotes Ca2+ excretion.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Loop Diuretics','medium','flashcard','What is the mechanism of furosemide venodilation, and when does it occur?','["Prior to diuretic effect, furosemide stimulates renal prostaglandin synthesis, causing venodilation and reduction in left ventricular filling pressure"]','A','This pre-diuretic venodilation (within minutes of IV administration) is why furosemide rapidly relieves dyspnea in acute pulmonary edema before significant urine output occurs.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Loop Diuretics','hard','flashcard','Why do NSAIDs blunt the effect of loop diuretics?','["NSAIDs inhibit renal prostaglandin synthesis; prostaglandins are required for loop diuretic tubular secretion stimulation and vasodilatory action"]','A','This is a clinically significant pharmacodynamic interaction. Patients with heart failure or edema on furosemide plus NSAIDs often have inadequate diuresis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Loop Diuretics','medium','flashcard','Which loop diuretic is used when a patient has a sulfonamide allergy, and why?','["Ethacrynic acid — it is the only loop diuretic that is NOT a sulfonamide derivative"]','A','Although furosemide, bumetanide, and torsemide are sulfonamide derivatives, they do not typically cross-react with sulfonamide antimicrobial allergy. Ethacrynic acid is the clear choice when a true allergic reaction to sulfonamides is documented.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Thiazide Diuretics','easy','flashcard','Where do thiazide diuretics act, and which transporter do they inhibit?','["Distal convoluted tubule — inhibit Na+/Cl- cotransporter (NCC), reducing 5-10% of filtered NaCl reabsorption"]','A','Thiazides must be secreted into the proximal tubule lumen to reach the NCC in the DCT. They are ''''low-ceiling'''' diuretics with limited maximum efficacy.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Thiazide Diuretics','medium','flashcard','State the key metabolic adverse effects of thiazide diuretics (the ''5 Hs'').','["Hypokalemia, Hyponatremia, Hyperuricemia, Hyperglycemia, Hyperlipidemia (and Hypercalcemia)"]','A','Hypokalemia is most common. Hyperuricemia via competition with urate in organic acid secretory system. Hyperglycemia from impaired insulin secretion related to hypokalemia.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Thiazide Diuretics','easy','flashcard','How do thiazides affect urinary calcium, and what is the clinical use?','["Thiazides DECREASE urinary Ca2+ excretion (promote DCT Ca2+ reabsorption) — used for idiopathic hypercalciuria and calcium oxalate nephrolithiasis"]','A','This is the opposite of loop diuretics. Thiazides increase Ca2+ reabsorption in the DCT, useful for preventing recurrent Ca2+ stones and treating hypercalciuria.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Thiazide Diuretics','medium','flashcard','Why does hydrochlorothiazide become ineffective as a diuretic when GFR falls below 30 mL/min/1.73m2?','["Thiazides require proximal tubule secretion to reach the NCC in the DCT. In advanced CKD, reduced tubular secretion means insufficient drug reaches its site of action."]','A','Loop diuretics remain effective at low GFR. Thiazides are switched to loop diuretics in advanced CKD for fluid management, though thiazides may retain some antihypertensive effects via vascular mechanisms.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Thiazide Diuretics','hard','flashcard','Explain the paradoxical mechanism by which thiazides reduce urine volume in nephrogenic diabetes insipidus.','["Thiazide-induced mild volume depletion → increased proximal tubule Na+ and H2O reabsorption → less fluid delivery to the ADH-unresponsive distal segments → paradoxical reduction in urine output"]','A','A classic pharmacology paradox: a diuretic reducing urine volume. The principle is proximal tubule compensation for mild hypovolemia, not a direct anti-diuretic effect.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Thiazide Diuretics','medium','flashcard','How does indapamide differ from hydrochlorothiazide in its pharmacokinetics?','["Indapamide undergoes hepatic metabolism and is excreted in both bile and urine; most thiazides are excreted unchanged in the urine"]','A','This makes indapamide somewhat safer in mild-moderate CKD compared to HCTZ (which depends entirely on renal excretion). Indapamide also has vasodilatory properties independent of its diuretic effect.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Thiazide Diuretics','easy','flashcard','Why are thiazides used for hypertension in patients with recurrent kidney stones?','["Thiazides reduce urinary Ca2+ excretion by increasing DCT Ca2+ reabsorption — directly reducing stone-forming Ca2+ in the urine while also treating hypertension"]','A','This double benefit (antihypertensive + antiurolithic) makes thiazides a preferred antihypertensive in patients with Ca2+-containing kidney stones and hypertension.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Thiazide Diuretics','hard','flashcard','What is chlorthalidone''''s pharmacokinetic advantage over HCTZ, and does current evidence support one over the other?','["Chlorthalidone has a half-life of 50-60 hours (vs 10-15 hours for HCTZ), providing 24-hour BP control; ~2x more potent. However, current guidelines do NOT preferentially recommend one over the other."]','A','Chlorthalidone''''s prolonged duration is theoretically beneficial for consistent blood pressure control. Some clinicians prefer it for this reason, but head-to-head outcome data are lacking.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Thiazide Diuretics','medium','flashcard','Can thiazides be used safely in patients with sulfonamide antibiotic allergy?','["Yes — despite being sulfonamide derivatives, thiazides do NOT generally cause cross-hypersensitivity in patients with sulfonamide antimicrobial allergy due to structural differences in the sulfonamide group"]','A','The sulfonamide group in thiazides differs structurally from that in antimicrobials like sulfamethoxazole. Clinically meaningful cross-reactivity is rare, and thiazides are generally safe to use.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Thiazide Diuretics','easy','flashcard','What is the first-line thiazide indication beyond hypertension?','["Edematous states (mild heart failure, cirrhosis, nephrotic syndrome) as an adjunct; also idiopathic hypercalciuria, calcium nephrolithiasis, and nephrogenic DI"]','A','Thiazides reduce extracellular volume and are useful in mild edema. For severe edema/heart failure, loop diuretics are preferred. The two classes can be combined for diuretic resistance.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Potassium-Sparing Diuretics','easy','flashcard','Distinguish the mechanisms of spironolactone vs amiloride as potassium-sparing diuretics.','["Spironolactone: aldosterone receptor antagonist (prevents Na+-retaining protein synthesis). Amiloride: directly blocks ENaC (epithelial Na+ channels) — independent of aldosterone"]','A','Both act in the collecting duct/tubule principal cells, both retain K+ and excrete Na+. Key distinction: spironolactone requires aldosterone to be present to have effect; amiloride works regardless.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Potassium-Sparing Diuretics','easy','flashcard','What is the primary safety concern with potassium-sparing diuretics, and when are they contraindicated?','["Hyperkalemia — avoid in severe renal dysfunction (eGFR <30 mL/min) and with concomitant ACE inhibitors or ARBs without close monitoring"]','A','Impaired renal K+ excretion + reduced aldosterone (via RAAS blockade) = compounding K+ retention. Life-threatening hyperkalemia can occur rapidly in CKD patients.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Potassium-Sparing Diuretics','medium','flashcard','How does eplerenone differ from spironolactone in its receptor selectivity and adverse effect profile?','["Eplerenone is more selective for mineralocorticoid receptors — does NOT bind progesterone or androgen receptors → less gynecomastia, breast tenderness, menstrual irregularity vs spironolactone"]','A','Spironolactone''''s antiandrogenic effects cause gynecomastia in men and menstrual irregularities in women. Eplerenone is preferred when these effects are problematic, though it is more expensive.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Potassium-Sparing Diuretics','medium','flashcard','Why does spironolactone provide mortality benefit in heart failure beyond simple diuresis?','["Aldosterone causes cardiac fibrosis and ventricular remodeling — spironolactone blocks non-renal aldosterone receptors in the heart, preventing pathological remodeling and improving survival in HFrEF"]','A','RALES trial showed 30% mortality reduction with low-dose spironolactone in HFrEF. EPHESUS trial showed similar benefit with eplerenone in post-MI ventricular dysfunction.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Potassium-Sparing Diuretics','easy','flashcard','What is the maximum percentage of filtered sodium that can be affected by potassium-sparing diuretics, and why?','["Only 1-2% of filtered Na+ can be affected — because ENaC reabsorbs only 1-2% of filtered Na+ in the collecting duct"]','A','This limits the maximum diuretic efficacy of K+-sparing drugs, making them weak diuretics. They are most valuable for their K+-retaining properties and non-diuretic (cardiac, hormonal) benefits.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Potassium-Sparing Diuretics','hard','flashcard','Trimethoprim can cause hyperkalemia — explain the mechanism and relevance to drug interactions.','["Trimethoprim blocks ENaC in the collecting duct (like amiloride), reducing Na+ reabsorption and K+ secretion. Combined with other K+-sparing drugs or ACE inhibitors, hyperkalemia risk is additive."]','A','This trimethoprim-ENaC interaction is particularly dangerous in HIV patients (frequent trimethoprim use) with CKD on RAAS blockade. Potassium monitoring is essential when combining these agents.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Potassium-Sparing Diuretics','medium','flashcard','In primary hyperaldosteronism (Conn syndrome), why is spironolactone a uniquely appropriate antihypertensive?','["Excess aldosterone drives Na+ retention and K+ wasting. Spironolactone directly antagonizes the aldosterone receptor, reversing both hypertension and hypokalemia simultaneously"]','A','Spironolactone is both diagnostic (if BP and K+ normalize) and therapeutic in Conn syndrome. It is also used pre-operatively before adrenalectomy.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Potassium-Sparing Diuretics','easy','flashcard','What fixed-dose combination combines HCTZ with triamterene, and what is its therapeutic rationale?','["Dyazide / Maxzide (HCTZ + triamterene) — HCTZ causes hypokalemia; triamterene retains K+; combined effect: diuresis with minimized K+ changes"]','A','Combining a thiazide (or loop diuretic) that wastes K+ with a K+-sparing diuretic produces diuresis while maintaining K+ balance. This reduces need for K+ supplementation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Potassium-Sparing Diuretics','hard','flashcard','What is the difference between the onset of action of spironolactone vs amiloride/triamterene, and why?','["Spironolactone has a slow onset (2-4 days) because it must block aldosterone receptor-mediated protein synthesis; amiloride/triamterene have faster onset as direct ENaC blockers"]','A','Spironolactone''''s mechanism involves preventing aldosterone-stimulated gene expression and protein synthesis — a genomic mechanism with inherent delay. Direct ENaC blockade by amiloride is non-genomic and faster.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Potassium-Sparing Diuretics','medium','flashcard','Spironolactone is used in polycystic ovary syndrome (PCOS). What pharmacological property enables this use?','["Spironolactone blocks androgen receptors in addition to aldosterone receptors — its antiandrogenic effect reduces hirsutism, acne, and androgenic alopecia in PCOS"]','A','The same property that causes gynecomastia in men (anti-androgenic) is therapeutically useful in PCOS women. Spironolactone is used at 50-200 mg/day for androgen-dependent features of PCOS.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Osmotic Diuretics and Carbonic Anhydrase Inhibitors','easy','flashcard','What is the mechanism of action of mannitol as an osmotic diuretic?','["Mannitol is freely filtered but not reabsorbed — retains water in the tubular lumen osmotically, increasing urine flow. Also draws water from intracellular compartments."]','A','The non-reabsorbable solute creates an osmotic gradient that obligates water to remain in the tubular lumen, carrying it to the urine. This also reduces intracellular volume, useful for cerebral edema.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Osmotic Diuretics and Carbonic Anhydrase Inhibitors','easy','flashcard','State the primary clinical indications for mannitol.','["1. Cerebral edema / elevated ICP (head trauma, stroke); 2. Prophylaxis of acute renal failure in surgery/rhabdomyolysis; 3. Reduction of intraocular pressure"]','A','For cerebral edema: draws fluid from brain parenchyma into vasculature. For AKI prophylaxis: maintains tubular flow, preventing cast precipitation. Must be given IV only.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Osmotic Diuretics and Carbonic Anhydrase Inhibitors','medium','flashcard','Why is mannitol contraindicated in heart failure and pulmonary edema?','["Mannitol initially expands intravascular volume (by drawing intracellular fluid into circulation) — this volume expansion can precipitate acute pulmonary edema in patients with impaired cardiac function"]','A','Mannitol''''s initial action is to increase plasma volume before diuresis begins. In a patient who cannot handle increased preload, this can be catastrophic.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Osmotic Diuretics and Carbonic Anhydrase Inhibitors','medium','flashcard','What acid-base disturbance does acetazolamide cause, and what is the therapeutic implication for its diuretic use?','["Hyperchloremic metabolic acidosis from urinary HCO3- wasting — limits long-term diuretic utility as the acidosis reduces acetazolamide''''s own efficacy (self-limiting)"]','A','As HCO3- is wasted, less remains in the filtrate for carbonic anhydrase to act on. The self-limiting nature of metabolic acidosis caps acetazolamide''''s diuretic duration of action.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Osmotic Diuretics and Carbonic Anhydrase Inhibitors','easy','flashcard','List 4 clinical uses of acetazolamide beyond diuresis.','["1. Open-angle glaucoma (↓ aqueous humor); 2. Altitude sickness prophylaxis/treatment; 3. Idiopathic intracranial hypertension; 4. Alkalinize urine (salicylate/phenobarbital overdose)"]','A','Acetazolamide''''s effects stem from carbonic anhydrase inhibition in multiple tissues: ciliary body (glaucoma), choroid plexus (ICP), and proximal tubule (urine alkalinization for drug elimination enhancement).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Osmotic Diuretics and Carbonic Anhydrase Inhibitors','hard','flashcard','Why does acetazolamide help with altitude sickness, and what is the dosing strategy?','["Acetazolamide induces metabolic acidosis → stimulates ventilation via peripheral chemoreceptors → increased arterial PO2 at altitude. Typically started 24-48h BEFORE ascent."]','A','The carbonate in expired CO2 decreases; the metabolic acidosis partially compensates for the respiratory alkalosis of altitude, normalizing the ventilatory drive and improving oxygenation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Osmotic Diuretics and Carbonic Anhydrase Inhibitors','medium','flashcard','What distinguishes osmotic diuretics from other diuretic classes regarding their site of action in the nephron?','["Osmotic diuretics act primarily in the proximal convoluted tubule AND descending loop of Henle (water-permeable segments). Other diuretics act on specific later nephron segments."]','A','The descending limb is permeable to water but not solutes. Mannitol in the tubule retains water here by osmosis. In the proximal tubule, it reduces Na+ and water reabsorption.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Osmotic Diuretics and Carbonic Anhydrase Inhibitors','easy','flashcard','What is the clinical danger of excessive mannitol administration?','["Hyperosmolarity (serum osmolality >320 mOsm/kg) → risk of AKI from renal tubular toxicity and paradoxical cerebral edema from rebound when hyperosmolarity is corrected"]','A','Monitor serum Na+ and osmolality. An osmolal gap >10-20 mOsm/kg indicates significant mannitol accumulation. Stop if osmolality exceeds safe thresholds.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Osmotic Diuretics and Carbonic Anhydrase Inhibitors','medium','flashcard','Acetazolamide is used in contraction alkalosis in heart failure. What is the mechanism?','["Inhibiting carbonic anhydrase → proximal tubule cannot reabsorb HCO3- → HCO3- wasting in urine → correction of metabolic alkalosis without requiring Na+/Cl- replacement"]','A','Loop diuretics create Cl--depletion alkalosis that cannot self-correct without Cl- repletion. Acetazolamide bypasses this by directly eliminating excess HCO3- renally — useful when salt loading (for Cl- repletion) would worsen heart failure.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Osmotic Diuretics and Carbonic Anhydrase Inhibitors','hard','flashcard','Why is carbonic anhydrase inhibition in the eye useful for treating glaucoma?','["Carbonic anhydrase in the ciliary body epithelium secretes HCO3- into aqueous humor (driving Na+ and water). Inhibiting CA reduces aqueous humor production, lowering IOP."]','A','Topical CAIs (dorzolamide, brinzolamide) are preferred for chronic glaucoma (fewer systemic side effects). Acetazolamide is used systemically for acute angle-closure glaucoma crisis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','ACE Inhibitors and ARBs in Renal Disease','easy','flashcard','How do ACE inhibitors reduce intraglomerular pressure in diabetic nephropathy?','["Angiotensin II preferentially constricts the efferent arteriole. ACE inhibitors reduce angiotensin II → efferent dilation → reduced glomerular capillary pressure → reduced proteinuria and hyperfiltration"]','A','This hemodynamic renoprotection is independent of blood pressure lowering. ACE inhibitors are first-line in diabetic nephropathy even if blood pressure is normal.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','ACE Inhibitors and ARBs in Renal Disease','medium','flashcard','Why is a 25-30% rise in serum creatinine acceptable (and even expected) after starting an ACE inhibitor in CKD?','["The rise reflects the intended reduction in glomerular capillary pressure (efferent dilation reduces filtration pressure). This is the mechanism of renoprotection — not nephrotoxicity."]','A','A >30% rise in creatinine or rise beyond 2 weeks suggests a different problem: bilateral renal artery stenosis, severe volume depletion, or concurrent NSAID use. The 25-30% rise should stabilize.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','ACE Inhibitors and ARBs in Renal Disease','easy','flashcard','What is the mechanism of ACE inhibitor-induced cough, and what is the management?','["ACE inhibition prevents bradykinin degradation → bradykinin accumulates → stimulates cough receptors in the airways. Management: switch to an ARB (which does not inhibit ACE/bradykinin degradation)"]','A','Occurs in 10-15% of patients (up to 40% in Asian populations). The cough is dry, persistent, and nocturnal. It resolves within 1-4 weeks of stopping the ACE inhibitor.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','ACE Inhibitors and ARBs in Renal Disease','medium','flashcard','State the absolute contraindications to ACE inhibitors and ARBs.','["1. Pregnancy (fetopathy — renal tubular dysgenesis, oligohydramnios); 2. Bilateral renal artery stenosis; 3. History of angioedema from ACE inhibitors (for ACEi); 4. Hyperkalemia"]','A','Pregnancy is a Category X/D contraindication — RAAS blockade causes fetal renal malformation. Bilateral RAS: blockade of compensatory efferent vasoconstriction precipitates acute renal failure.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','ACE Inhibitors and ARBs in Renal Disease','hard','flashcard','Explain the mechanism of ACE inhibitor-induced angioedema and how it differs from allergic angioedema.','["Bradykinin accumulation increases vascular permeability → subcutaneous/submucosal edema. NOT IgE-mediated (no urticaria). Does not respond well to antihistamines; responds to icatibant (bradykinin B2 antagonist) or C1-esterase inhibitor"]','A','Can occur at any time during therapy, even years after starting. Involves lips, tongue, throat, and larynx — life-threatening if airway involved. ARBs carry a small (~0.1-0.3%) cross-reactivity risk for angioedema.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','ACE Inhibitors and ARBs in Renal Disease','medium','flashcard','Why is dual RAAS blockade (ACE inhibitor + ARB) no longer recommended?','["ONTARGET trial: dual blockade increased hypotension, hyperkalemia, and AKI without additional cardiovascular benefit. Risks outweigh benefits."]','A','Despite theoretical synergy (complementary RAAS blockade points), clinical outcomes were worse with the combination in the landmark ONTARGET trial. Current guidelines recommend monotherapy.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','ACE Inhibitors and ARBs in Renal Disease','easy','flashcard','Name two key differences between ACE inhibitors and ARBs.','["1. ARBs do NOT inhibit bradykinin degradation → no cough or angioedema (rare); 2. ARBs block AT1 receptors directly → allow angiotensin II to act on AT2 receptors (potentially vasodilatory)"]','A','Clinical implication: ARBs are used when ACE inhibitors cause intolerable cough. Both reduce proteinuria and BP; both are contraindicated in pregnancy and bilateral RAS.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','ACE Inhibitors and ARBs in Renal Disease','hard','flashcard','A patient with diabetic nephropathy has proteinuria 2 g/day on maximum-dose ACE inhibitor. What additional renoprotective strategy can be added?','["SGLT2 inhibitors (empagliflozin, dapagliflozin) — shown in CREDENCE, DAPA-CKD, EMPA-KIDNEY trials to reduce CKD progression independent of glycemia; finerenone (non-steroidal MRA) is also now indicated"]','A','SGLT2 inhibitors cause tubuloglomerular feedback-mediated afferent constriction, reducing glomerular pressure — complementary to ACE inhibitor''''s efferent dilation. Finerenone reduces cardiac and renal events in CKD with T2DM.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','ACE Inhibitors and ARBs in Renal Disease','medium','flashcard','What electrolyte abnormality do ACE inhibitors and ARBs most commonly cause, and which patients are at highest risk?','["Hyperkalemia — highest risk in patients with CKD, diabetes, or concurrent use of K+-sparing diuretics, NSAIDs, or trimethoprim"]','A','Reduced aldosterone from RAAS blockade decreases K+ secretion in the collecting duct. Monitoring serum K+ within 1-2 weeks of initiating or dose-escalating RAAS blockers is essential.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','ACE Inhibitors and ARBs in Renal Disease','easy','flashcard','What is the main reason ACE inhibitors are preferred over ARBs in heart failure with reduced ejection fraction?','["ACE inhibitors have more robust mortality evidence from landmark trials (CONSENSUS, SOLVD); ARBs are alternatives when ACE inhibitors are not tolerated (especially cough)"]','A','Both classes are acceptable in HFrEF. Current guidelines indicate ACE inhibitors as first-line (or sacubitril/valsartan as upgrade for symptomatic patients). ARBs (e.g., valsartan) are used if ACE inhibitors not tolerated.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drugs in CKD','easy','flashcard','What is the general pharmacokinetic principle for dose adjustment of renally cleared drugs in CKD?','["Loading dose unchanged (depends on Vd); REDUCE maintenance dose and/or EXTEND dosing interval proportional to degree of renal impairment (based on CrCl/eGFR)"]','A','Loading dose achieves therapeutic concentration quickly (Vd-dependent, not clearance-dependent). Maintenance dose maintains steady-state concentration — reduced in CKD to prevent accumulation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drugs in CKD','medium','flashcard','What is the mechanism of NSAID nephrotoxicity, and which patients are at greatest risk?','["NSAIDs inhibit renal prostaglandins → loss of prostaglandin-mediated afferent arteriolar vasodilation → renal ischemia and AKI. Greatest risk: CKD, heart failure, cirrhosis, dehydration (reduced effective circulating volume states)"]','A','In healthy people with normal perfusion, renal prostaglandins play a minor role. In low-perfusion states, they become critical for maintaining GFR — NSAIDs remove this compensatory mechanism.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drugs in CKD','easy','flashcard','At what eGFR threshold is metformin generally contraindicated, and what is the risk?','["Contraindicated when eGFR <30 mL/min; use with caution 30-45 mL/min. Risk: metformin accumulation → inhibition of mitochondrial complex I → lactic acidosis"]','A','Metformin is renally eliminated. In CKD, it accumulates and predisposes to lactic acidosis — particularly when renal function deteriorates further (dehydration, contrast, surgery, illness).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drugs in CKD','medium','flashcard','What is contrast-induced nephropathy (CIN), and what are the two most effective prevention strategies?','["CIN = AKI within 48-72h of iodinated contrast from direct tubular toxicity + renal medullary vasoconstriction. Prevention: 1. IV isotonic saline hydration; 2. Minimize contrast volume (use low-osmolar or iso-osmolar contrast)"]','A','N-acetylcysteine (NAC) has uncertain additional benefit beyond hydration. Stop nephrotoxic drugs (NSAIDs, aminoglycosides) before contrast. Delay contrast in patients with AKI.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drugs in CKD','hard','flashcard','Aminoglycoside pharmacodynamics: why does once-daily dosing reduce nephrotoxicity compared to multiple-daily dosing?','["Proximal tubular aminoglycoside uptake is SATURABLE. Once-daily dosing: high peak → better bacterial killing (concentration-dependent) + drug-free trough allows tubular cells to clear accumulated drug → less tubular accumulation and toxicity"]','A','Multiple daily doses maintain constant low tubular concentrations, leading to continuous saturation and maximal accumulation. The drug-free trough in once-daily dosing is protective for the tubule.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drugs in CKD','medium','flashcard','What is the mechanism of lithium-induced nephrogenic diabetes insipidus, and how is it treated?','["Lithium enters collecting duct principal cells via ENaC → intracellularly inhibits adenylyl cyclase downstream of V2 receptor → blocks cAMP-mediated AQP-2 insertion → nephrogenic DI. Treatment: amiloride (blocks ENaC, reducing Li+ entry)"]','A','Amiloride is preferred over thiazides for lithium-induced NDI because it reduces lithium entry into principal cells (via ENaC blockade), addressing the root cause. Also: indomethacin can help (but caution in CKD).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drugs in CKD','easy','flashcard','Name the safest analgesic in CKD and explain why.','["Acetaminophen (paracetamol) — hepatically metabolized; inactive metabolites are renally excreted but not nephrotoxic at therapeutic doses; does not affect renal blood flow"]','A','NSAIDs are contraindicated in advanced CKD. Opioids require caution (active metabolites accumulate). Acetaminophen is generally safe at standard doses in CKD (though some metabolites retain in severe CKD — monitor for accumulation).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drugs in CKD','hard','flashcard','Which direct oral anticoagulant has the highest renal dependence, and how does this affect its use in CKD?','["Dabigatran (~80% renal elimination) — contraindicated when CrCl <15-30 mL/min (depending on indication). Apixaban (~27% renal) has lowest renal dependence and is relatively safest in CKD."]','A','Rivaroxaban (~33% renal) and edoxaban (~35% renal) are intermediate. Warfarin (hepatically metabolized, monitored by INR) is an alternative but complicated by CKD-related drug interactions and INR instability.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drugs in CKD','medium','flashcard','What toxicity does allopurinol cause in CKD, and what is the mechanism?','["Allopurinol''''s active metabolite oxypurinol is renally cleared → accumulates in CKD → risk of severe adverse drug reactions: SJS/TEN, allopurinol hypersensitivity syndrome, bone marrow suppression. Dose reduction required based on eGFR."]','A','Oxypurinol''''s half-life extends dramatically in CKD. The HLA-B*5801 allele (common in Asian populations) increases risk of severe cutaneous reactions from allopurinol in CKD.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drugs in CKD','easy','flashcard','Which drugs are classic causes of acute interstitial nephritis (AIN)?','["Beta-lactam antibiotics, NSAIDs, proton pump inhibitors (most common currently), sulfonamides, rifampin, allopurinol. Classic triad: fever + rash + eosinophilia (often absent in NSAID/PPI-AIN)"]','A','AIN is an immune-mediated (T-cell) reaction causing interstitial inflammation. Biopsy shows interstitial infiltrate with eosinophils. Treatment: remove offending drug; corticosteroids in severe or progressive cases.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Phosphate Binders and Erythropoiesis-Stimulating Agents','easy','flashcard','What are the three main classes of phosphate binders used in CKD, and when is each preferred?','["1. Calcium-based (calcium carbonate, acetate): inexpensive, but worsen hypercalcemia/vascular calcification; 2. Sevelamer (non-absorbed polymer): preferred with hypercalcemia or high CV risk; 3. Lanthanum carbonate: effective non-calcium alternative"]','A','Aluminum hydroxide — highly effective but avoided long-term due to CNS and bone toxicity. Choose binder based on serum Ca, PTH, and vascular calcification status.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Phosphate Binders and Erythropoiesis-Stimulating Agents','medium','flashcard','What is the mechanism of action of sevelamer, and what additional benefit does it offer?','["Sevelamer is a non-absorbed cationic polymer that binds dietary phosphate AND bile acids in the gut → reduces phosphate absorption AND LDL cholesterol (~15-30% reduction)"]','A','This dual benefit may contribute to cardiovascular risk reduction in CKD patients who face high CVD burden. Sevelamer also does not contribute to calcium load or vascular calcification.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Phosphate Binders and Erythropoiesis-Stimulating Agents','easy','flashcard','What is the target hemoglobin range when using ESAs in CKD, and why is over-correction harmful?','["Target Hb 10-11.5 g/dL. Over-correction to Hb >13 g/dL increases cardiovascular events (stroke, MI, thrombosis) — CHOIR and TREAT trials demonstrated this harm"]','A','ESAs increase erythropoiesis but also cause dose-dependent hypertension and prothrombotic effects. Higher Hb targets worsen cardiovascular outcomes without quality of life benefit in CKD.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Phosphate Binders and Erythropoiesis-Stimulating Agents','medium','flashcard','What is the most common cause of ESA hyporesponsiveness in CKD patients?','["Iron deficiency (absolute: ferritin <200 ng/mL, TSAT <20%; or functional: ferritin adequate but TSAT low) — limits erythropoiesis even with adequate EPO levels"]','A','Always replete iron before and during ESA therapy. IV iron is preferred in hemodialysis patients (oral absorption is poor). Other causes: infection/inflammation (hepcidin excess), vitamin B12/folate deficiency, secondary hyperparathyroidism, aluminum toxicity.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Phosphate Binders and Erythropoiesis-Stimulating Agents','hard','flashcard','What is pure red cell aplasia (PRCA) and how does it relate to ESA therapy?','["PRCA: severe anemia + absent erythroblasts on bone marrow biopsy. Caused by neutralizing antibodies against recombinant EPO that cross-react with endogenous EPO. Must stop ESA immediately; treat with immunosuppression."]','A','PRCA is rare but life-threatening. Was most associated with subcutaneous epoetin alfa (one brand with changed formulation). Diagnosis: bone marrow biopsy + anti-EPO antibody test. Darbepoetin alfa substitution worsens it (antibodies cross-react).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Phosphate Binders and Erythropoiesis-Stimulating Agents','easy','flashcard','Describe the pathophysiology of secondary hyperparathyroidism in CKD in 4 steps.','["1. Reduced GFR → phosphate retention; 2. Elevated phosphate + reduced GFR → decreased calcitriol production (↓1α-hydroxylase); 3. Reduced calcitriol → hypocalcemia; 4. Hypocalcemia + low calcitriol → stimulate PTH secretion → secondary hyperparathyroidism"]','A','FGF-23 also plays a role — it is the earliest marker of CKD-MBD, rising before phosphate and PTH become abnormal. FGF-23 suppresses 1α-hydroxylase, contributing to low calcitriol.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Phosphate Binders and Erythropoiesis-Stimulating Agents','medium','flashcard','How does cinacalcet reduce PTH levels in secondary hyperparathyroidism?','["Cinacalcet is a calcimimetic — allosterically sensitizes the calcium-sensing receptor (CaSR) on parathyroid cells, making the receptor respond as if Ca2+ is higher → suppresses PTH release"]','A','Cinacalcet lowers PTH, Ca2+, and phosphate simultaneously — beneficial in hyperparathyroidism with hypercalcemia. Main adverse effect: hypocalcemia (can be severe). Must monitor serum Ca2+ closely.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Phosphate Binders and Erythropoiesis-Stimulating Agents','hard','flashcard','What is the role of active vitamin D analogs (calcitriol, paricalcitol) in CKD-MBD, and what complication limits their use?','["Replace deficient calcitriol to suppress PTH, enhance Ca2+ absorption, and maintain bone health. Limitation: can cause hypercalcemia and hyperphosphatemia → worsening vascular calcification"]','A','Paricalcitol (synthetic vitamin D analog) may cause less hypercalcemia/hyperphosphatemia than calcitriol. Often combined with phosphate binders to control both phosphate and PTH simultaneously.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Phosphate Binders and Erythropoiesis-Stimulating Agents','medium','flashcard','What should be monitored before and during IV iron therapy in CKD?','["Ferritin (iron stores), TSAT (transferrin saturation), CBC (hemoglobin response). Monitor for hypersensitivity reactions during infusion (especially first dose); have resuscitation equipment available."]','A','Target ferritin typically 200-500 ng/mL and TSAT 20-50% in dialysis patients. Avoid IV iron when active infection is present (iron fuels bacterial growth and may worsen sepsis).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Phosphate Binders and Erythropoiesis-Stimulating Agents','easy','flashcard','Why is IV iron preferred over oral iron in hemodialysis patients?','["Uremic gut inflammation reduces oral iron absorption (~2-10%); IV iron bypasses gut, providing reliable and rapid repletion; hemodialysis itself causes chronic blood loss requiring ongoing iron supplementation"]','A','Oral iron is used in predialysis CKD (non-dialysis CKD) where absorption is still partially intact. In dialysis patients, IV iron (iron sucrose, ferric gluconate) is standard of care.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Immunosuppressants in Transplant','easy','flashcard','What is the mechanism of cyclosporine and tacrolimus, and why are they both called calcineurin inhibitors?','["Both bind intracellular immunophilins (cyclosporine → cyclophilin; tacrolimus → FKBP-12), forming complexes that inhibit calcineurin phosphatase → prevent NFAT dephosphorylation → block IL-2 transcription → T-cell suppression"]','A','Calcineurin is the phosphatase that activates NFAT (nuclear factor of activated T cells). Blocking calcineurin = blocking IL-2 = blocking T-cell proliferation. Despite different binding proteins, both converge on the same target.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Immunosuppressants in Transplant','medium','flashcard','List 3 adverse effects unique to cyclosporine (not tacrolimus) and 2 unique to tacrolimus.','["Cyclosporine unique: hirsutism, gingival hyperplasia, hyperlipidemia (more). Tacrolimus unique: higher NODAT (new-onset diabetes), alopecia. Shared: nephrotoxicity, hypertension, hyperkalemia, neurotoxicity"]','A','Exam pearl: if asked about which CNI causes more hirsutism/gum hyperplasia → cyclosporine. Which causes more diabetes → tacrolimus. Which causes more neurotoxicity → tacrolimus (tremor, seizures at high levels).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Immunosuppressants in Transplant','easy','flashcard','What is the mechanism of mycophenolate mofetil (MMF) and its selectivity for lymphocytes?','["MMF → mycophenolic acid (MPA) → inhibits IMPDH (inosine monophosphate dehydrogenase) → blocks de novo purine synthesis. Selective for lymphocytes because they CANNOT use the salvage purine pathway (unlike other cells)"]','A','Other rapidly dividing cells can use the purine salvage pathway when de novo synthesis is blocked. Lymphocytes depend almost exclusively on de novo synthesis, making MMF relatively lymphocyte-selective.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Immunosuppressants in Transplant','medium','flashcard','What drug interactions with tacrolimus increase the risk of nephrotoxicity?','["CYP3A4 inhibitors increase tacrolimus levels: azole antifungals (fluconazole, voriconazole, itraconazole), macrolide antibiotics (clarithromycin, erythromycin), diltiazem, verapamil, grapefruit juice"]','A','CYP3A4 inducers (rifampin, phenytoin, carbamazepine, St. John''''s Wort) dramatically decrease tacrolimus/cyclosporine levels → risk of rejection. These interactions must be managed by TDM.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Immunosuppressants in Transplant','hard','flashcard','How does sirolimus (rapamycin) differ mechanistically from calcineurin inhibitors, and when is it used instead?','["Sirolimus binds FKBP-12 → complex inhibits mTOR → blocks G1-to-S phase progression in response to IL-2 (NOT IL-2 production). Used when calcineurin inhibitor nephrotoxicity is a major concern; deferred post-transplant due to wound healing impairment"]','A','Key distinction: calcineurin inhibitors block IL-2 PRODUCTION; sirolimus blocks T-cell RESPONSE TO IL-2. Sirolimus also has antiproliferative uses (coronary stent coating, certain cancers). It does not cause nephrotoxicity via afferent vasoconstriction.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Immunosuppressants in Transplant','medium','flashcard','Why is therapeutic drug monitoring (TDM) critical for calcineurin inhibitors?','["Narrow therapeutic index: subtherapeutic levels → graft rejection; supratherapeutic levels → nephrotoxicity, neurotoxicity, infection, hypertension. Trough whole-blood levels guide dosing."]','A','Highly variable pharmacokinetics (CYP3A4 metabolism, P-gp efflux, food interactions, drug-drug interactions) make empiric dosing unreliable. Target trough levels differ by time post-transplant and immunological risk.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Immunosuppressants in Transplant','easy','flashcard','What is the mechanism and clinical significance of tacrolimus-induced NODAT?','["Tacrolimus inhibits calcineurin in pancreatic beta-cells → blocks NFAT-mediated insulin gene transcription → impaired insulin synthesis and secretion → NODAT. Concurrent corticosteroids amplify risk."]','A','NODAT affects ~20-30% of tacrolimus-treated transplant recipients. Management: reduce tacrolimus dose if possible, start antidiabetic therapy. Converting to cyclosporine may improve glycemia but risks other toxicities.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Immunosuppressants in Transplant','hard','flashcard','Explain the rationale for triple immunosuppression in renal transplantation (CNI + antimetabolite + corticosteroid).','["Each drug targets a different step of T-cell activation: CNI blocks IL-2 production (TCR signaling); antimetabolite (MMF/azathioprine) blocks lymphocyte proliferation; corticosteroids suppress antigen presentation and inflammation. Synergistic efficacy allows lower doses of each → reduced individual toxicities."]','A','Triple therapy also provides coverage against different rejection mechanisms. The corticosteroid is often tapered/withdrawn over months, leaving dual CNI + antimetabolite maintenance to minimize long-term metabolic complications.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Immunosuppressants in Transplant','medium','flashcard','What is the primary adverse effect requiring monitoring with mycophenolate mofetil?','["GI toxicity (diarrhea, nausea, abdominal pain) and bone marrow suppression (leukopenia, anemia) — CBC and dose reductions required if significant cytopenias develop"]','A','MMF is also a potent teratogen — contraindicated in pregnancy. Female patients of reproductive age require two forms of contraception. Enteric-coated mycophenolate sodium has better GI tolerability.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Immunosuppressants in Transplant','easy','flashcard','Why are corticosteroids included in transplant immunosuppression despite their many adverse effects?','["Corticosteroids have rapid, potent, broad anti-inflammatory and immunosuppressive effects: suppress antigen presentation, reduce cytokine production, inhibit T-cell activation and migration. Essential for treating acute rejection episodes."]','A','Long-term steroid adverse effects (Cushingoid habitus, osteoporosis, hyperglycemia, hypertension, cataracts) drive steroid-minimization and steroid-withdrawal protocols — aiming to maintain immunosuppression with CNI + MMF while reducing steroid burden.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Urinary Tract Drugs','easy','flashcard','What is the mechanism and indication of tamsulosin?','["Alpha-1A selective adrenergic receptor antagonist → relaxes prostate smooth muscle and bladder neck → reduces urethral resistance and improves urine flow in BPH (benign prostatic hyperplasia)"]','A','Alpha-1A selectivity reduces orthostatic hypotension compared to non-selective alpha-blockers (doxazosin, terazosin). Tamsulosin is also used for ureteral stone passage (relaxes ureteral smooth muscle).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Urinary Tract Drugs','medium','flashcard','What is intraoperative floppy iris syndrome (IFIS) and which drug causes it?','["IFIS occurs during cataract surgery in patients on alpha-1 adrenergic antagonists (especially tamsulosin). Iris dilator muscle relaxation causes iris billowing, flopping, and prolapse through surgical incisions."]','A','Even if tamsulosin is stopped before surgery, IFIS can persist. Ophthalmologists must be informed pre-operatively. IFIS occurs because alpha-1A receptors in the iris dilator are blocked by the drug.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Urinary Tract Drugs','easy','flashcard','Compare the mechanisms of oxybutynin and mirabegron for overactive bladder.','["Oxybutynin: muscarinic (M3) receptor antagonist → blocks detrusor contractions. Mirabegron: beta-3 adrenergic agonist → relaxes detrusor → increases bladder capacity. Mirabegron avoids anticholinergic side effects."]','A','Mirabegron is preferred in elderly patients where anticholinergic side effects (confusion, dry mouth, constipation, urinary retention) are particularly harmful. Both drugs are effective for OAB urgency/frequency.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Urinary Tract Drugs','medium','flashcard','Compare finasteride and dutasteride for BPH treatment.','["Finasteride: inhibits 5-alpha reductase type 2 only (~70% DHT reduction). Dutasteride: inhibits types 1 AND 2 (~95% DHT reduction). Both require 3-6 months for clinical benefit. Dutasteride has ~5-week half-life vs ~6-hour finasteride."]','A','5-ARIs reduce prostate volume 20-30% over months, reducing urinary obstruction and long-term risk of acute urinary retention and need for surgery. Often combined with alpha-blockers for maximum efficacy in moderate-severe BPH.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Urinary Tract Drugs','hard','flashcard','Why is oxybutynin especially problematic in elderly patients, and what CNS adverse effect must be monitored?','["Oxybutynin readily crosses the blood-brain barrier and has high CNS anticholinergic activity → causes cognitive impairment, confusion, delirium, and memory problems in elderly. Avoid in patients with dementia or cognitive impairment."]','A','The Beers criteria list oxybutynin as a potentially inappropriate medication in older adults due to CNS anticholinergic effects. Tolterodine (extended-release), trospium, or mirabegron are preferred in the elderly.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Urinary Tract Drugs','easy','flashcard','Phenazopyridine: mechanism, indication, and key patient counseling point.','["Phenazopyridine: urinary analgesic (azo dye excreted in urine). Indication: symptomatic relief of UTI dysuria/urgency (not antibacterial). Counseling: causes orange-red discoloration of urine, tears, and contacts — harmless but expected."]','A','Phenazopyridine should be used for only 1-2 days while antibiotic therapy takes effect. It does NOT treat the underlying infection. Patients must be warned about discoloration to avoid unnecessary alarm.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Urinary Tract Drugs','medium','flashcard','What is the mechanism and indication for bethanechol?','["Bethanechol: direct M3 muscarinic agonist → stimulates detrusor contraction and bladder emptying. Indicated for non-obstructive urinary retention (post-operative bladder atony, neurogenic bladder with hypotonic detrusor)."]','A','Contraindicated in obstructive uropathy (BPH with urinary outlet obstruction) — forcing bladder contraction against obstruction risks bladder rupture. Cholinergic side effects: sweating, bradycardia, bronchospasm.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Urinary Tract Drugs','hard','flashcard','How does intravesical onabotulinumtoxin A work for neurogenic detrusor overactivity?','["Botulinum toxin cleaves SNAP-25 protein in cholinergic nerve terminals of the detrusor → blocks ACh vesicle fusion and release → prevents detrusor contractions. Effect lasts 6-12 months."]','A','Injected cystoscopically into the detrusor (not the urethra). Risk: urinary retention requiring self-catheterization in ~20-30% of patients — must be counseled before treatment. Alternative for anticholinergic-refractory OAB.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Urinary Tract Drugs','medium','flashcard','What is the advantage of extended-release formulations of anticholinergic drugs (e.g., oxybutynin ER, tolterodine ER) for overactive bladder?','["ER formulations reduce peak plasma concentrations → reduce systemic anticholinergic side effects (dry mouth, constipation) while maintaining therapeutic bladder effects. Better tolerability → improved adherence."]','A','The immediate-release forms of these drugs produce high peak concentrations that cause more side effects. Transdermal oxybutynin further reduces first-pass liver metabolism and peak concentration, minimizing dry mouth.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Urinary Tract Drugs','easy','flashcard','What are the two main drug classes for BPH, and how do they differ in mechanism and onset?','["1. Alpha-1 antagonists (tamsulosin, doxazosin): relax smooth muscle → rapid symptom relief within days. 2. 5-alpha reductase inhibitors (finasteride, dutasteride): reduce prostate size via DHT blockade → benefit over months"]','A','Combination therapy (alpha-blocker + 5-ARI) is used in larger prostates and severe symptoms. The MTOPS and CombAT trials support combination for reducing BPH progression and surgery risk.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drug-Induced Nephrotoxicity','easy','flashcard','What pattern of AKI do aminoglycosides cause, and how does once-daily dosing reduce toxicity?','["Non-oliguric acute tubular necrosis (proximal tubule). Once-daily dosing exploits saturable proximal tubule uptake — high peak for efficacy, drug-free trough allows cells to export accumulated drug → less nephrotoxicity"]','A','Risk factors: pre-existing CKD, volume depletion, prolonged therapy, concurrent nephrotoxins. Monitor creatinine, urine output, and aminoglycoside trough levels.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drug-Induced Nephrotoxicity','medium','flashcard','What is the mechanism of cisplatin nephrotoxicity, and how is it prevented?','["Cisplatin accumulates in proximal tubule cells → DNA crosslinking → p53-mediated apoptosis + ROS generation → tubular cell death and AKI. Prevention: aggressive IV saline hydration (diuresis dilutes cisplatin in tubule), mannitol, amifostine."]','A','Cisplatin nephrotoxicity is the dose-limiting toxicity. Carboplatin is less nephrotoxic. Magnesium wasting is also common with cisplatin (inhibits Mg2+ reabsorption in the loop of Henle) — requires Mg2+ supplementation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drug-Induced Nephrotoxicity','easy','flashcard','What is the mechanism and clinical presentation of NSAID-induced AKI?','["NSAIDs inhibit COX → reduce prostaglandin synthesis → afferent arteriolar vasoconstriction → reduced GFR. Presents as oliguria, rising creatinine, often functional/prerenal pattern (FENa <1%, concentrated urine) without tubular necrosis"]','A','Reversible with NSAID discontinuation and volume restoration in most cases. High-risk: dehydration, CKD, heart failure, cirrhosis, advanced age, concurrent ACE inhibitors/ARBs.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drug-Induced Nephrotoxicity','medium','flashcard','What are the 2 mechanisms of contrast-induced nephropathy (CIN)?','["1. Direct tubular cytotoxicity from hyperosmolar/ionic contrast molecules; 2. Renal medullary vasoconstriction of vasa recta → medullary ischemia (medulla is already borderline hypoxic)"]','A','The medullary thick ascending limb is exquisitely sensitive to ischemia (high metabolic demand, low oxygen environment). CIN risk reduced by hydration, using minimum contrast volume, iso-osmolar contrast, and avoiding concurrent nephrotoxins.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drug-Induced Nephrotoxicity','hard','flashcard','Describe the renal syndrome caused by tenofovir disoproxil fumarate (TDF) and how tenofovir alafenamide (TAF) reduces this risk.','["TDF causes Fanconi syndrome (proximal tubular dysfunction: phosphaturia, glucosuria, proteinuria, aminoaciduria) via mitochondrial toxicity. TAF is activated intracellularly in lymphocytes (not plasma) → lower plasma concentrations → less proximal tubule accumulation → ~90% less nephrotoxicity"]','A','Full Fanconi syndrome includes hypophosphatemia (bone loss/osteomalacia), glucosuria (despite normal glucose), low molecular weight proteinuria. TAF represents a significant safety improvement for HIV/HBV treatment in patients with or at risk for CKD.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drug-Induced Nephrotoxicity','medium','flashcard','What is the mechanism of methotrexate nephrotoxicity and how is it prevented?','["Methotrexate and 7-OH-methotrexate precipitate as crystals in renal tubules at acidic urine pH → intratubular obstruction → AKI. Prevention: aggressive IV hydration + urinary alkalinization (sodium bicarbonate to pH >7) + leucovorin rescue"]','A','High-dose methotrexate is used for lymphoma, osteosarcoma. Monitoring serum MTX levels is essential. Glucarpidase (carboxypeptidase G2) cleaves MTX in patients with toxic levels and AKI preventing normal renal elimination.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drug-Induced Nephrotoxicity','easy','flashcard','What are the two distinct renal toxicities of long-term lithium use?','["1. Nephrogenic diabetes insipidus (polyuria, polydipsia) — from inhibition of V2 receptor signaling reducing AQP-2 insertion; 2. Chronic tubulointerstitial nephritis → progressive CKD"]','A','Both toxicities require regular monitoring of renal function, urine osmolality, and lithium levels. Amiloride helps NDI by blocking ENaC (route of lithium entry into collecting duct cells).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drug-Induced Nephrotoxicity','hard','flashcard','What is vancomycin nephrotoxicity, how is it potentiated, and how is it monitored?','["Vancomycin causes proximal tubular damage via oxidative stress. Potentiated by aminoglycosides (synergistic tubular toxicity), loop diuretics (volume depletion), and piperacillin-tazobactam (recent evidence of synergistic nephrotoxicity). Monitor AUC24/MIC ratio (preferred over trough-only monitoring)."]','A','Traditional monitoring used trough levels alone (target 15-20 mg/L for serious infections). AUC-guided monitoring (target AUC24 400-600 mg·h/L) achieves therapeutic efficacy with less nephrotoxicity. Bayesian dosing software is used for AUC calculation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drug-Induced Nephrotoxicity','medium','flashcard','What is acute interstitial nephritis (AIN) and how does it differ from acute tubular necrosis (ATN)?','["AIN: immune-mediated (T-cell) interstitial inflammation from drugs/infection. Features: eosinophilia (50%), rash (25%), sterile pyuria, white cell casts, eosinophiluria. ATN: direct tubular cell death from ischemia or toxins. Features: muddy-brown granular casts, minimal inflammation."]','A','AIN biopsy: interstitial lymphocytes/eosinophils, edema, tubulitis. ATN biopsy: necrotic tubular cells, granular casts. Treatment differs: AIN → remove offending drug ± corticosteroids; ATN → supportive care, remove nephrotoxin, address ischemia.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Renal System','Pharmacology','Drug-Induced Nephrotoxicity','easy','flashcard','Which 4 drug classes/agents are most commonly associated with drug-induced nephrotoxicity that must be avoided in CKD?','["1. NSAIDs (afferent vasoconstriction); 2. Aminoglycosides (proximal tubular ATN); 3. Iodinated contrast (tubular toxicity + vasoconstriction); 4. Calcineurin inhibitors (cyclosporine, tacrolimus — afferent vasoconstriction + fibrosis)"]','A','Also: cisplatin, tenofovir, methotrexate, vancomycin + aminoglycosides, lithium. In CKD, reduced reserve for nephrotoxicity means standard doses of these agents cause disproportionate injury.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Pharmacology 7th Ed');

