-- ============================================================
-- Genetics Flashcards Part 2: Subtopics 6-10 (50 cards total)
-- Generated: 2026-06-23
-- ============================================================

-- ============================================================
-- SUBTOPIC 6: Epigenetics (10 flashcards)
-- ============================================================

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Epigenetics','easy','flashcard','What are CpG islands and how does DNA methylation at these sites affect gene expression?','["CpG islands are GC-rich regions in gene promoters. Methylation of cytosine at CpG sites silences gene transcription by blocking transcription factor binding and recruiting repressive complexes."]','A','DNA methylation adds a methyl group to the 5'' position of cytosine. Hypermethylation = gene silencing; hypomethylation = gene activation. Aberrant CpG methylation is a hallmark of many cancers.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Epigenetics','easy','flashcard','What is the effect of histone acetylation on gene expression, and how does it contrast with histone deacetylation?','["Histone acetylation (by HATs) neutralises positive lysine charges, loosening chromatin — ACTIVE transcription. Histone deacetylation (by HDACs) restores positive charge, tightening chromatin — SILENT transcription."]','A','Mnemonic: Acetylation = Active. HDAC inhibitors (e.g., vorinostat) are used in cancer therapy to reactivate silenced tumour suppressor genes.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Epigenetics','medium','flashcard','How is histone methylation different from histone acetylation in its effect on gene expression?','["Histone methylation is context-dependent: H3K4me3 marks active promoters; H3K9me3 and H3K27me3 mark repressed chromatin. Unlike acetylation, methylation does not change histone charge."]','A','Polycomb group proteins (PRC2) add H3K27me3 to silence developmental genes. Trithorax group proteins add H3K4me3 to activate them. Both are important in embryonic development.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Epigenetics','easy','flashcard','What is genomic imprinting?','["Genomic imprinting is the epigenetic phenomenon whereby only one parental allele is expressed (the other is silenced by methylation), in a parent-of-origin-specific manner."]','A','Imprinting is established in the germline and maintained throughout somatic cell divisions. Only ~100 genes in humans are imprinted. Disruption of imprinting causes diseases like Prader-Willi and Angelman syndromes.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Epigenetics','medium','flashcard','What is the genetic/epigenetic basis of Prader-Willi syndrome?','["Prader-Willi syndrome results from loss of paternally expressed genes at 15q11-13, usually due to paternal deletion (70%), maternal uniparental disomy (25%), or imprinting defect (5%)."]','A','Features: hypotonia at birth, hyperphagia, obesity, hypogonadism, short stature, intellectual disability. Mnemonic: PWS = Paternal. The SNRPN gene and SNORD116 cluster on the paternal chromosome are key.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Epigenetics','medium','flashcard','What is the difference between Prader-Willi and Angelman syndrome at the molecular level?','["Both involve 15q11-13: Prader-Willi = paternal deletion or maternal UPD (maternal copy silenced by imprinting); Angelman = maternal deletion or paternal UPD (UBE3A gene lost from maternal allele)."]','A','Mnemonic: PWS = Paternal, AS = Angelman (mAternal). Angelman features: happy demeanour, seizures, absent speech, ataxia — ''happy puppet'' syndrome. UBE3A is maternally expressed in neurons only.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Epigenetics','medium','flashcard','What is X-inactivation (lyonisation) and what is a Barr body?','["X-inactivation is the random epigenetic silencing of one X chromosome in each female somatic cell, forming a condensed Barr body visible at the nuclear periphery. Initiated by XIST RNA coating the inactivated X."]','A','Number of Barr bodies = number of X chromosomes minus 1. Normal female (46,XX) = 1 Barr body. Klinefelter (47,XXY) = 1 Barr body. Turner (45,X) = 0 Barr bodies. X-inactivation is irreversible once established.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Epigenetics','medium','flashcard','How does X-inactivation explain variable expression of X-linked diseases in female carriers?','["Because X-inactivation is random, female carriers have a mosaic of cells expressing either the normal or mutant allele. Skewed inactivation can cause symptomatic carrier females if most cells express the mutant X."]','A','Example: Female carriers of haemophilia A are usually unaffected (50:50 inactivation) but rare symptomatic carriers exist due to skewed inactivation. Skewed inactivation can also arise by selection in certain diseases.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Epigenetics','hard','flashcard','What is uniparental disomy (UPD) and what are its consequences?','["UPD = inheritance of both homologues of a chromosome pair from ONE parent. Consequences: (1) imprinting disorders if imprinted region involved; (2) autosomal recessive disease if parent is a carrier; (3) possible if isodisomy."]','A','Maternal UPD 15 → Prader-Willi syndrome (paternal-expressed genes missing). Paternal UPD 15 → Angelman syndrome. UPD 11p15 → Beckwith-Wiedemann (paternal) or Russell-Silver (maternal). UPD arises from trisomy rescue.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Epigenetics','hard','flashcard','What is transgenerational epigenetic inheritance and what evidence supports it in humans?','["Transgenerational epigenetic inheritance is the transmission of epigenetic marks (methylation patterns) through the germline across generations, independent of DNA sequence changes."]','A','Evidence includes the Overkalix cohort (grandpaternal nutrition affecting grandchildren''s mortality) and Dutch Hunger Winter studies (epigenetic changes in offspring of starved women). Challenges classical Mendelian inheritance concepts.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

-- ============================================================
-- SUBTOPIC 7: Oncogenetics (10 flashcards)
-- ============================================================

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Oncogenetics','easy','flashcard','What is the difference between a proto-oncogene and an oncogene?','["A proto-oncogene is a normal gene promoting cell growth/division. An oncogene is an abnormally activated form (gain-of-function mutation, amplification, or translocation) that drives uncontrolled proliferation."]','A','Oncogenes act in a dominant fashion — only ONE mutant allele is sufficient to drive cancer. Activation mechanisms: point mutation (RAS), gene amplification (HER2), chromosomal translocation (BCR-ABL, MYC).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Oncogenetics','easy','flashcard','What is the two-hit hypothesis for tumour suppressor genes?','["Both alleles of a tumour suppressor gene must be inactivated (''two hits'') for cancer to develop. In hereditary cancer, hit 1 is inherited (germline); hit 2 is a somatic mutation. Both hits are somatic in sporadic cancer."]','A','Proposed by Alfred Knudson (1971) studying retinoblastoma. Hereditary form: earlier onset, bilateral/multifocal tumours. Sporadic form: later onset, unilateral. TSGs act recessively at the cellular level.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Oncogenetics','medium','flashcard','What is the role of the RB1 gene and how does its loss lead to retinoblastoma?','["RB1 encodes the retinoblastoma protein (pRb), which normally sequesters E2F transcription factors to block cell cycle progression (G1 to S). Loss of both RB1 alleles releases E2F, driving uncontrolled proliferation."]','A','Classic two-hit hypothesis example. Hereditary retinoblastoma: AD inheritance, bilateral, early onset, risk of osteosarcoma. pRb is phosphorylated by CDK4/6-cyclin D, releasing E2F. CDK4/6 inhibitors (palbociclib) exploit this pathway.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Oncogenetics','medium','flashcard','Why is p53 called the guardian of the genome, and what syndrome results from germline TP53 mutation?','["p53 (encoded by TP53) senses DNA damage and triggers cell cycle arrest (via p21/CDKN1A), DNA repair, or apoptosis. Germline TP53 mutation causes Li-Fraumeni syndrome — multiple early-onset cancers."]','A','Li-Fraumeni syndrome cancers: sarcoma, breast, brain, adrenal cortex, leukaemia (mnemonic: SBLAs). p53 is mutated in >50% of all human cancers. MDM2 normally targets p53 for degradation; MDM2 is amplified in some sarcomas.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Oncogenetics','medium','flashcard','What is the role of BRCA1 and BRCA2 in cancer predisposition?','["BRCA1 and BRCA2 are tumour suppressor genes involved in homologous recombination DNA repair. Germline mutations confer high lifetime risk: ~70% breast cancer, ~40% ovarian cancer (BRCA1 > BRCA2)."]','A','BRCA2 also raises risk of male breast, prostate, and pancreatic cancer. PARP inhibitors (olaparib) exploit synthetic lethality in BRCA-deficient tumours. Testing offered to high-risk individuals (Ashkenazi Jewish ancestry, family history).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Oncogenetics','medium','flashcard','What is BCR-ABL and how does it cause chronic myeloid leukaemia (CML)?','["BCR-ABL is a fusion oncogene resulting from the t(9;22) Philadelphia chromosome translocation. It encodes a constitutively active tyrosine kinase that drives uncontrolled myeloid proliferation."]','A','Philadelphia chromosome is present in >95% of CML and some ALL cases. Imatinib (Gleevec) was the first targeted tyrosine kinase inhibitor designed against BCR-ABL — a landmark in oncogenetics. Resistance via T315I mutation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Oncogenetics','easy','flashcard','Which oncogene is most commonly mutated in human cancers, and what is its normal function?','["RAS (KRAS, NRAS, HRAS) is the most commonly mutated oncogene in human cancers (~25% overall, >90% in pancreatic cancer). Normal function: GTPase signalling protein that promotes growth when GTP-bound."]','A','Oncogenic RAS mutations (codon 12, 13, 61) impair GTPase activity, locking RAS in the active GTP-bound state and constitutively activating MAPK/PI3K pathways. KRAS inhibitors (sotorasib for KRAS G12C) are now approved.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Oncogenetics','medium','flashcard','What is HER2/ERBB2 amplification and what is its clinical significance in breast cancer?','["HER2/ERBB2 amplification (~20% of breast cancers) results in receptor tyrosine kinase overexpression, driving aggressive tumour growth. Targeted by trastuzumab (Herceptin), a monoclonal antibody, significantly improving prognosis."]','A','HER2-positive breast cancer was previously one of the worst subtypes; trastuzumab transformed it into a treatable disease. Pertuzumab, ado-trastuzumab emtansine (T-DM1) and tucatinib are additional HER2-targeted options.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Oncogenetics','hard','flashcard','What is the APC gene and how do its mutations lead to familial adenomatous polyposis (FAP) and colorectal cancer?','["APC (adenomatous polyposis coli) is a tumour suppressor that promotes beta-catenin degradation, inhibiting Wnt signalling. Germline APC mutations cause FAP (>100 colonic polyps by teens, near 100% CRC risk by age 40)."]','A','APC mutation is also the initiating event in sporadic colorectal cancer (Vogelstein''s adenoma-carcinoma sequence: APC then RAS then SMAD4 then TP53). Prophylactic colectomy is offered in FAP. Attenuated FAP (AFAP) has fewer polyps.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Oncogenetics','hard','flashcard','What is Lynch syndrome (HNPCC), and which genes are responsible?','["Lynch syndrome (HNPCC) is an autosomal dominant condition caused by germline mutations in DNA mismatch repair (MMR) genes: MLH1, MSH2, MSH6, PMS2. It causes microsatellite instability (MSI) and high CRC/endometrial cancer risk."]','A','Lynch syndrome accounts for ~3% of all CRC. Amsterdam criteria used for clinical diagnosis. MMR-deficient tumours are highly responsive to immune checkpoint inhibitors (pembrolizumab). Surveillance colonoscopy from age 20-25 recommended.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

-- ============================================================
-- SUBTOPIC 8: Mitochondrial Genetics (10 flashcards)
-- ============================================================

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mitochondrial Genetics','easy','flashcard','What is the inheritance pattern of mitochondrial DNA (mtDNA) diseases?','["Mitochondrial DNA is inherited exclusively maternally. An affected mother passes mitochondrial disease to ALL her children, but only daughters transmit it further. Fathers never transmit mtDNA."]','A','Key distinguishing feature in pedigree analysis: no paternal transmission. Sperm mitochondria are actively degraded after fertilisation (paternal mitochondrial elimination). This strict maternal inheritance aids diagnosis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mitochondrial Genetics','easy','flashcard','What is heteroplasmy and what is the threshold effect in mitochondrial disease?','["Heteroplasmy = coexistence of both mutant and wild-type mtDNA within a cell/tissue. The threshold effect = disease manifests only when mutant mtDNA exceeds a critical proportion (~60-90% depending on tissue energy demands)."]','A','High-energy tissues (brain, muscle, heart, retina) have lower thresholds and are most affected. Heteroplasmy level can vary between tissues in the same individual, and can shift across generations (mitotic segregation).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mitochondrial Genetics','easy','flashcard','What is homoplasmy in the context of mitochondrial genetics?','["Homoplasmy = all mtDNA copies within a cell are identical — either all wild-type (normal) or all mutant. Homoplasmic mutations have more predictable penetrance than heteroplasmic mutations."]','A','Some mtDNA diseases (e.g., Leber''s hereditary optic neuropathy) are usually homoplasmic, yet not all carriers are affected — suggesting nuclear modifier genes and environmental factors also influence expression.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mitochondrial Genetics','medium','flashcard','What is MELAS syndrome and what is its genetic cause?','["MELAS = Mitochondrial Encephalomyopathy, Lactic Acidosis, and Stroke-like episodes. Most commonly caused by m.3243A>G point mutation in MT-TL1 (mitochondrial tRNA-Leu gene), impairing oxidative phosphorylation."]','A','Features: stroke-like episodes before age 40, seizures, migraine, lactic acidosis, ragged red fibres on muscle biopsy. Elevated plasma/CSF lactate. Maternal inheritance. No curative treatment; management is supportive.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mitochondrial Genetics','medium','flashcard','What is MERRF syndrome and what are its characteristic features?','["MERRF = Myoclonic Epilepsy with Ragged Red Fibres. Caused by m.8344A>G mutation in MT-TK (mitochondrial tRNA-Lys gene). Features: myoclonic seizures, ataxia, ragged red fibres, progressive myopathy."]','A','Ragged red fibres on Gomori trichrome staining of muscle biopsy = accumulation of abnormal mitochondria at fibre periphery. This finding is characteristic of mtDNA diseases. Maternal inheritance, variable expression due to heteroplasmy.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mitochondrial Genetics','medium','flashcard','What is Leber''s hereditary optic neuropathy (LHON) and how does it differ from other mitochondrial diseases?','["LHON is a mitochondrial disease causing acute/subacute painless central vision loss in young adults, due to point mutations in complex I genes (most common: m.11778G>A in MT-ND4). Usually homoplasmic; male predominance despite maternal inheritance."]','A','Affects young males more than females (4:1) despite maternal inheritance — suggests X-linked or hormonal modifiers. Idebenone may help if treated early. Bilateral sequential optic neuropathy. No ragged red fibres (unlike MELAS/MERRF).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mitochondrial Genetics','easy','flashcard','What are the key structural features of mitochondrial DNA that distinguish it from nuclear DNA?','["mtDNA is a circular, double-stranded molecule of ~16,569 bp. Features: maternally inherited, no introns, no histones, uses a different genetic code (UGA = Trp not stop), ~37 genes (13 OXPHOS proteins, 22 tRNAs, 2 rRNAs)."]','A','Because mtDNA has no histones and limited repair mechanisms, its mutation rate is 10-20x higher than nuclear DNA. This high mutation rate makes mtDNA useful in evolutionary studies and forensic identification.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mitochondrial Genetics','medium','flashcard','Why is the mtDNA mutation rate much higher than that of nuclear DNA?','["mtDNA mutation rate is ~10-20x higher than nuclear DNA because: (1) proximity to reactive oxygen species (ROS) from oxidative phosphorylation, (2) no histones for protection, (3) limited DNA repair mechanisms."]','A','The high mtDNA mutation rate is exploited in population genetics (molecular clock) and forensic science (e.g., identifying skeletal remains via maternal lineage). ROS damage contributes to ageing and age-related diseases.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mitochondrial Genetics','hard','flashcard','What is Kearns-Sayre syndrome (KSS) and how does it differ genetically from point mutation mitochondrial diseases?','["KSS is caused by large-scale mtDNA deletions (most commonly a 4,977 bp common deletion), not point mutations. Features: progressive external ophthalmoplegia (PEO), pigmentary retinopathy, cardiac conduction defects, onset <20 years."]','A','KSS deletions are usually sporadic (de novo), not maternally inherited — because large deletions are selectively removed in the germline. Also associated with Pearson syndrome (sideroblastic anaemia in infancy) — same deletion, different tissue distribution.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mitochondrial Genetics','hard','flashcard','Why is clinical expression so variable in mitochondrial diseases even within the same family?','["Variability arises from: (1) heteroplasmy — different mutant mtDNA load in different tissues; (2) mitotic segregation — random mtDNA partitioning at cell division changes heteroplasmy over time; (3) nuclear modifier genes; (4) environmental factors."]','A','A mother with 40% mutant mtDNA may have mildly affected offspring with 80% mutant mtDNA (threshold exceeded) or unaffected offspring with 20%. This explains why penetrance is unpredictable and phenotype ranges from asymptomatic to severe.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

-- ============================================================
-- SUBTOPIC 9: Multifactorial Inheritance & Complex Traits (10 flashcards)
-- ============================================================

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Multifactorial Inheritance','easy','flashcard','What is the difference between polygenic and monogenic traits?','["Monogenic traits are caused by variants in a single gene (e.g., cystic fibrosis, sickle cell). Polygenic traits are influenced by multiple genes each with small additive effects (e.g., height, skin colour, blood pressure)."]','A','Most common complex diseases (diabetes, hypertension, schizophrenia) are both polygenic AND multifactorial — influenced by many genes AND environmental factors. Polygenic risk scores (PRS) aggregate the effects of many variants.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Multifactorial Inheritance','easy','flashcard','What is heritability (h2) and what does it measure?','["Heritability (h2) is the proportion of phenotypic variance in a population attributable to genetic variance. h2 = V_G / V_P. Ranges from 0 (entirely environmental) to 1 (entirely genetic)."]','A','Heritability is a population statistic — it applies to a specific population in a specific environment, NOT to individuals. Height has h2 ~0.8; BMI ~0.6-0.7; schizophrenia ~0.8. High heritability does NOT mean a trait is unchangeable.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Multifactorial Inheritance','easy','flashcard','How are twin studies used to estimate heritability, and what is concordance?','["Twin studies compare monozygotic (MZ, identical, 100% shared DNA) and dizygotic (DZ, fraternal, 50% shared DNA) twins. Concordance = percentage of twin pairs where both have the trait. Higher MZ vs DZ concordance implies genetic contribution."]','A','If MZ concordance = DZ concordance then environment dominates. If MZ concordance > DZ concordance but <100% then multifactorial. If MZ concordance = 100% then purely genetic. h2 approximately equals 2 x (concordance_MZ - concordance_DZ).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Multifactorial Inheritance','medium','flashcard','What is the threshold model for multifactorial traits?','["The threshold model proposes that liability (combined genetic + environmental risk) is normally distributed in the population. Disease manifests only when liability exceeds a threshold. Relatives of affected individuals have a higher mean liability distribution."]','A','The model explains why first-degree relatives have higher recurrence risk, why more severe disease = higher recurrence risk, and why a less commonly affected sex having the disease increases risk in relatives (Carter effect — e.g., pyloric stenosis).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Multifactorial Inheritance','medium','flashcard','What are the recurrence risks for neural tube defects (NTDs) and how does this illustrate multifactorial inheritance?','["NTD general population risk ~1/1000. After one affected child: recurrence risk ~4-5% (40-50x increase). After two affected children: ~10%. This empiric recurrence risk pattern fits the multifactorial threshold model."]','A','NTDs (spina bifida, anencephaly) involve genetic susceptibility (e.g., MTHFR C677T) plus environmental factors (folate deficiency). Periconceptional folic acid (400 micrograms/day) reduces NTD risk by 50-70%.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Multifactorial Inheritance','medium','flashcard','How does type 2 diabetes mellitus exemplify multifactorial inheritance?','["T2DM results from interaction of multiple susceptibility genes (TCF7L2, PPARG, KCNJ11, FTO, and hundreds more) with environmental factors (obesity, sedentary lifestyle, diet). Heritability ~40-70%; MZ concordance ~70-90%."]','A','No single gene causes T2DM. Polygenic risk scores (PRS) can identify high-risk individuals before clinical onset. GWAS have identified >400 loci. First-degree relative with T2DM increases risk ~3-fold. Lifestyle intervention is highly effective.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Multifactorial Inheritance','medium','flashcard','What does ~50% MZ concordance for schizophrenia tell us about its aetiology?','["MZ concordance of ~50% for schizophrenia (vs DZ ~15%) indicates strong genetic contribution (h2 ~0.8) but ALSO substantial environmental influence — otherwise MZ concordance would be 100%. It is a complex multifactorial disorder."]','A','Environmental risk factors for schizophrenia: advanced paternal age, prenatal infection/famine, cannabis use, urban birth, obstetric complications. GWAS identified >100 loci; copy number variants (22q11 deletion) also confer high risk (~25% lifetime risk).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Multifactorial Inheritance','hard','flashcard','What is the concept of liability distribution in multifactorial disease?','["Liability is the combined genetic and environmental susceptibility to a disease, assumed to be normally distributed in the population. Disease occurs when liability exceeds a threshold. Relatives of probands have a shifted (higher) liability distribution."]','A','The steeper the liability distribution shift in relatives, the higher the recurrence risk. First-degree relatives share ~50% of genes, shifting their distribution most. This explains empiric recurrence risks in conditions like cleft palate, hip dysplasia, and congenital heart disease.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Multifactorial Inheritance','hard','flashcard','What is a genome-wide association study (GWAS) and what has it revealed about complex disease?','["GWAS compares SNP frequencies across the genome in thousands of cases vs controls to identify common variants associated with disease. Revealed that most complex disease variants are common, each with small effect size (odds ratio 1.1-1.3)."]','A','GWAS principle: test ~1 million SNPs simultaneously (significance threshold p < 5x10-8 to correct for multiple testing). Missing heritability problem: GWAS-identified variants explain only a fraction of estimated heritability. Polygenic risk scores aggregate many GWAS SNPs.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Multifactorial Inheritance','hard','flashcard','What are gene-environment (GxE) interactions and give a clinical example?','["GxE interactions occur when genetic background modifies an individual''s response to an environmental exposure. Example: MTHFR C677T variant + low folate intake greatly increased NTD risk vs either factor alone."]','A','Other GxE examples: ALDH2*2 variant + alcohol consumption leads to severe flushing and cancer risk; apoE4 + high-fat diet increases Alzheimer''s risk; smoking + SERPINA1 (alpha-1 antitrypsin) mutation causes accelerated emphysema. GxE complicates heritability estimates.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

-- ============================================================
-- SUBTOPIC 10: Pharmacogenomics (10 flashcards)
-- ============================================================

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Pharmacogenomics','easy','flashcard','What is pharmacogenomics and what is its goal in personalised medicine?','["Pharmacogenomics studies how genetic variation affects drug response (efficacy, toxicity, dosing). Goal: tailor drug choice and dose to individual genotype to maximise efficacy and minimise adverse effects."]','A','Pharmacogenomics encompasses pharmacokinetics (absorption, metabolism, excretion — mainly CYP450 enzymes) and pharmacodynamics (drug targets, receptors). The FDA labels >300 drugs with pharmacogenomic biomarker information.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Pharmacogenomics','medium','flashcard','What is the significance of CYP2D6 polymorphisms and how do they affect codeine use?','["CYP2D6 metabolises ~25% of drugs. Poor metabolisers (PM) lack CYP2D6 activity; ultrarapid metabolisers (UM) have multiple gene copies. Codeine (a prodrug) requires CYP2D6 to convert to morphine. PMs get no analgesia; UMs risk morphine toxicity."]','A','Codeine is contraindicated in CYP2D6 UMs (especially children) and nursing mothers who are UMs — morphine transfers to breast milk. CYP2D6 also metabolises tramadol, tamoxifen (to active endoxifen), and many antidepressants/antipsychotics.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Pharmacogenomics','medium','flashcard','How do CYP2C19 polymorphisms affect clopidogrel therapy?','["Clopidogrel is a prodrug activated by CYP2C19. CYP2C19 poor metabolisers (e.g., *2/*2 genotype) cannot activate clopidogrel, resulting in inadequate platelet inhibition and higher risk of cardiovascular events (stent thrombosis) after PCI."]','A','CYP2C19 *2 loss-of-function allele is common (~30% East Asians, ~15-25% Europeans). FDA added black box warning to clopidogrel. Alternative: prasugrel or ticagrelor (not CYP2C19-dependent). Pre-PCI genotyping increasingly used in clinical practice.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Pharmacogenomics','medium','flashcard','How does CYP2C9 variation affect warfarin dosing?','["CYP2C9 metabolises S-warfarin (the active enantiomer). CYP2C9 *2 and *3 variants reduce enzyme activity, leading to warfarin accumulation and increased bleeding risk. VKORC1 variants also affect warfarin sensitivity."]','A','Warfarin dosing algorithms (e.g., IWPC) incorporate CYP2C9 (*2, *3) and VKORC1 (-1639G>A) genotypes plus clinical factors. Lower starting doses required for variant carriers. FDA-approved pharmacogenomics-guided warfarin labelling exists.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Pharmacogenomics','medium','flashcard','What is NAT2 and how do slow acetylators respond differently to isoniazid?','["NAT2 (N-acetyltransferase 2) acetylates isoniazid (TB treatment). Slow acetylators (NAT2 *5, *6, *7 variants) metabolise isoniazid slowly, causing drug accumulation and increased risk of peripheral neuropathy and hepatotoxicity."]','A','~50% of Europeans and ~90% of some Middle Eastern populations are slow acetylators. Fast acetylators may have reduced isoniazid efficacy. Co-prescribe pyridoxine (B6) with isoniazid to prevent neuropathy. Also relevant for hydralazine (drug-induced lupus) and procainamide.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Pharmacogenomics','medium','flashcard','What is TPMT and why is its activity important before prescribing 6-mercaptopurine?','["TPMT (thiopurine methyltransferase) inactivates 6-mercaptopurine (6-MP) and azathioprine. TPMT-deficient patients (homozygous variants ~1:300) cannot inactivate these drugs, causing accumulation of cytotoxic thioguanine nucleotides and severe myelosuppression."]','A','TPMT testing (genotype or phenotype) is recommended before starting 6-MP/azathioprine (e.g., in ALL, IBD). TPMT-deficient patients require >10-fold dose reduction. Heterozygotes also have intermediate risk. NUDT15 testing is now preferred in East Asian patients.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Pharmacogenomics','hard','flashcard','What is the HLA-B*57:01 allele and how does it cause abacavir hypersensitivity?','["HLA-B*57:01 presents abacavir (antiretroviral) as a neoantigenic complex to CD8+ T cells, causing a systemic hypersensitivity reaction (fever, rash, GI symptoms, respiratory symptoms) in ~5-8% of carriers. Can be fatal on rechallenge."]','A','Prospective HLA-B*57:01 screening before abacavir initiation virtually eliminates abacavir hypersensitivity (negative predictive value >99%). This is one of the most successful pharmacogenomics screening implementations in clinical practice. Mandated by FDA/EMA drug label.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Pharmacogenomics','hard','flashcard','What is HLA-B*15:02 and what is its clinical significance for carbamazepine?','["HLA-B*15:02 is strongly associated with carbamazepine-induced Stevens-Johnson syndrome (SJS) and toxic epidermal necrolysis (TEN) in Han Chinese and Southeast Asian populations (odds ratio >1000). Very rare in European populations."]','A','FDA/EMA mandate HLA-B*15:02 screening before carbamazepine in patients of Asian ancestry. Phenytoin and oxcarbazepine also carry some cross-reactivity risk. HLA-A*31:01 is associated with carbamazepine hypersensitivity in Europeans and Japanese patients.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Pharmacogenomics','easy','flashcard','How does G6PD deficiency cause primaquine-induced haemolytic anaemia?','["G6PD (glucose-6-phosphate dehydrogenase) deficiency impairs the pentose phosphate pathway, reducing NADPH and glutathione in RBCs. Oxidant drugs like primaquine generate ROS that overwhelm deficient RBCs, causing haemolytic anaemia."]','A','G6PD deficiency is X-linked recessive, common in malaria-endemic regions (heterozygous females have some protection against malaria). Triggers: primaquine, dapsone, rasburicase, high-dose aspirin, fava beans, infections. Screen before prescribing primaquine.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Pharmacogenomics','hard','flashcard','What is DPYD deficiency and what is its clinical significance for 5-fluorouracil (5-FU)?','["DPYD encodes dihydropyrimidine dehydrogenase, which degrades ~80% of 5-FU. DPYD variant carriers (*2A, *13, c.2846A>T, HapB3) have reduced DPYD activity causing 5-FU accumulation and severe/fatal toxicity: mucositis, neutropenia, diarrhoea, neurotoxicity."]','A','DPYD complete deficiency is rare but heterozygous variants affect ~3-8% of Europeans. EMA (2020) mandates DPYD genotyping before 5-FU/capecitabine — carriers require 50% dose reduction. This is now standard of care in many European countries.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');
