-- Endocrinology: Anatomy & Physiology MCQs (100 questions)
-- Source: Guyton & Hall Medical Physiology 14th Ed
-- Generated for Skoolie Medical Education Platform
-- Subtopics: Hypothalamic-Pituitary Axis, Thyroid Physiology, Adrenal Cortex,
--            Adrenal Medulla, Pancreatic Endocrine Function, Calcium & Phosphate Regulation,
--            Gonadal Hormones, Growth Hormone & IGF-1, Prolactin & Oxytocin/ADH,
--            Adipokines & Gut-Brain Axis

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Hypothalamic-Pituitary Axis','easy','mcq','Which structure carries hypothalamic releasing hormones directly to the anterior pituitary?','["A. Hypophyseal portal blood system","B. Internal carotid artery","C. Cerebral aqueduct","D. Optic chiasm plexus"]','A','The hypophyseal portal blood system carries releasing and inhibiting hormones from the median eminence to the anterior pituitary, allowing high local concentrations without systemic dilution.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Hypothalamic-Pituitary Axis','medium','mcq','GnRH is released from the arcuate nucleus in pulses. Structurally, GnRH is best classified as:','["A. A steroid derived from cholesterol","B. A decapeptide (10 amino acids)","C. A catecholamine derived from tyrosine","D. A glycoprotein with alpha and beta subunits"]','B','GnRH is a decapeptide released in episodic pulses from the arcuate nucleus. Pulsatile release is essential — continuous GnRH exposure downregulates gonadotroph receptors and suppresses FSH/LH.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Hypothalamic-Pituitary Axis','medium','mcq','Which hypothalamic hormone stimulates release of both TSH and prolactin from the anterior pituitary?','["A. Dopamine (PIH)","B. Somatostatin","C. TRH (thyrotropin-releasing hormone)","D. CRH"]','C','TRH stimulates thyrotrophs to release TSH and lactotrophs to release prolactin. Elevated TRH in primary hypothyroidism can cause hyperprolactinemia and galactorrhea.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Hypothalamic-Pituitary Axis','hard','mcq','Long-loop negative feedback in the HPA axis refers to which of the following?','["A. ACTH inhibiting CRH at the hypothalamus only","B. Cortisol inhibiting both CRH at the hypothalamus and ACTH at the anterior pituitary","C. CRH inhibiting its own release (ultra-short loop)","D. Cortisol stimulating ACTH to maintain homeostasis"]','B','Long-loop feedback involves the peripheral end-organ hormone (cortisol) feeding back to suppress both CRH release at the hypothalamus and ACTH release at the anterior pituitary. This is the classic glucocorticoid negative feedback mechanism.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Hypothalamic-Pituitary Axis','easy','mcq','Which two hormones are synthesized in the hypothalamus but stored and released from the posterior pituitary?','["A. ADH (vasopressin) and oxytocin","B. GH and prolactin","C. FSH and LH","D. TSH and ACTH"]','A','ADH is made in the supraoptic nucleus and oxytocin in the paraventricular nucleus; both are transported along axons to the posterior pituitary (neurohypophysis) where they are stored and released.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Hypothalamic-Pituitary Axis','medium','mcq','Dopamine released from the hypothalamus tonically inhibits which anterior pituitary hormone?','["A. Growth hormone (GH)","B. Prolactin","C. ACTH","D. TSH"]','B','Dopamine (prolactin-inhibiting hormone, PIH) acts on D2 receptors on lactotrophs to tonically suppress prolactin. Dopamine antagonists (e.g., metoclopramide, antipsychotics) elevate prolactin levels.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Hypothalamic-Pituitary Axis','medium','mcq','Somatostatin from the periventricular hypothalamic nucleus primarily:','["A. Stimulates GH and TSH release","B. Stimulates insulin secretion from beta cells","C. Inhibits GH release and also inhibits TSH","D. Inhibits CRH-mediated ACTH release"]','C','Somatostatin (GHIH) inhibits GH release from the anterior pituitary and also inhibits TSH. It is also produced in the pancreatic delta cells where it inhibits both insulin and glucagon.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Hypothalamic-Pituitary Axis','hard','mcq','Short-loop feedback in the hypothalamic-pituitary system refers to:','["A. Target organ hormones (e.g., cortisol) inhibiting hypothalamic releasing hormones","B. Anterior pituitary hormones feeding back to inhibit hypothalamic releasing hormone secretion","C. Portal blood flow reversal during physiologic stress","D. Hypothalamic hormone inhibiting its own neuron (ultra-short loop)"]','B','Short-loop feedback refers to anterior pituitary hormones (e.g., GH, ACTH) feeding back to inhibit the hypothalamic neurons that drive their release. Ultra-short loop is the hypothalamic hormone inhibiting its own neuron.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Hypothalamic-Pituitary Axis','easy','mcq','The anterior pituitary secretes how many distinct hormones?','["A. Four","B. Five","C. Six","D. Eight"]','C','The anterior pituitary secretes six hormones: GH (somatotrophs), TSH (thyrotrophs), ACTH (corticotrophs), FSH and LH (gonadotrophs), and prolactin (lactotrophs). Posterior pituitary stores ADH and oxytocin.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Hypothalamic-Pituitary Axis','medium','mcq','CRH stimulates ACTH release from which anterior pituitary cell type?','["A. Somatotrophs","B. Corticotrophs","C. Thyrotrophs","D. Gonadotrophs"]','B','CRH acts on corticotrophs (also termed corticotrophic cells or ACTH cells) in the anterior pituitary. Corticotrophs secrete ACTH, which drives cortisol synthesis in the adrenal cortex.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Thyroid Physiology','easy','mcq','How many iodine atoms does thyroxine (T4) contain?','["A. Four iodine atoms","B. Three iodine atoms","C. Two iodine atoms","D. One iodine atom"]','A','T4 (thyroxine) contains four iodine atoms. T3 (triiodothyronine) contains three. T4 is the predominant secretory product of the thyroid and is considered a prohormone for the more potent T3.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Thyroid Physiology','medium','mcq','The sodium-iodide symporter (NIS) is located on which membrane of thyroid follicular cells?','["A. Apical membrane facing the colloid","B. Basolateral membrane facing the bloodstream","C. Nuclear membrane","D. Mitochondrial inner membrane"]','B','NIS (sodium-iodide symporter) is on the basolateral membrane and uses the Na+ gradient (maintained by Na-K-ATPase) to actively transport iodide into the follicular cell against its electrochemical gradient — a process called iodide trapping.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Thyroid Physiology','medium','mcq','Thyroid peroxidase (TPO) is responsible for which steps in thyroid hormone synthesis?','["A. Iodide transport into follicular cells only","B. Thyroglobulin synthesis in the rough ER","C. Oxidation of iodide and organification onto tyrosine residues on thyroglobulin","D. Proteolysis of thyroglobulin to release T3 and T4"]','C','TPO catalyzes two key steps: (1) oxidation of iodide (I-) to active iodine and (2) organification — covalent attachment of iodine to tyrosine residues on thyroglobulin to form MIT and DIT.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Thyroid Physiology','hard','mcq','Which combination of iodotyrosines couples to form T3?','["A. DIT + DIT","B. MIT + DIT","C. MIT + MIT","D. DIT + T4"]','D','T3 (triiodothyronine) is formed by coupling of MIT (monoiodotyrosine, 1 iodine) + DIT (diiodotyrosine, 2 iodines) = 3 iodines total. T4 is formed by DIT + DIT = 4 iodines.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Thyroid Physiology','easy','mcq','T3 is approximately how many times more potent than T4 at thyroid hormone receptors?','["A. 3-4 times more potent","B. Equally potent","C. 10 times more potent","D. T4 is more potent than T3"]','A','T3 binds thyroid hormone nuclear receptors with ~10-fold higher affinity and is considered 3-4 times more biologically potent than T4. Most T3 in peripheral tissues is derived from deiodination of T4.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Thyroid Physiology','medium','mcq','TSH exerts its effects on thyroid follicular cells primarily through which signaling pathway?','["A. Tyrosine kinase receptor activation of PI3K","B. JAK2-STAT5 pathway","C. Gs protein coupled to adenylyl cyclase, increasing cAMP","D. Gq protein coupled to phospholipase C, increasing IP3/DAG"]','B','TSH binds its GPCR on thyroid cells coupled to Gs, activating adenylyl cyclase and increasing cAMP. This cAMP-PKA cascade stimulates all steps of thyroid hormone synthesis and secretion, as well as thyroid cell growth.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Thyroid Physiology','medium','mcq','What percentage of circulating T4 is protein-bound (to TBG, transthyretin, and albumin)?','["A. Approximately 50%","B. Approximately 75%","C. Approximately 90%","D. Approximately 99%"]','C','Approximately 99% of circulating T4 is bound to carrier proteins (predominantly TBG). Only ~0.04% of T4 is free (unbound) and biologically active. This large bound reservoir accounts for T4s long half-life of ~7 days.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Thyroid Physiology','hard','mcq','The normal half-life of T4 in the bloodstream is approximately:','["A. 2-3 minutes","B. 1 day","C. 7 days","D. 30 days"]','C','T4 has a plasma half-life of approximately 7 days due to extensive protein binding (99%). T3 has a shorter half-life of approximately 1 day. This long T4 half-life provides a stable hormonal reserve.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Thyroid Physiology','easy','mcq','The normal serum TSH reference range is approximately:','["A. 0.5-4.5 mIU/L","B. 5-12 mcg/dL","C. 0.05-0.45 mIU/L","D. 50-450 mIU/L"]','A','Normal TSH is 0.5-4.5 mIU/L. Normal free T4 is ~0.8-1.8 ng/dL and total T4 is ~5-12 mcg/dL. TSH is the most sensitive test for thyroid dysfunction.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Thyroid Physiology','medium','mcq','Pendrin, located on the apical membrane of thyroid follicular cells, functions to:','["A. Transport iodide from blood into the follicular cell","B. Transport iodide from the follicular cell into the colloid","C. Couple MIT and DIT to form T3 and T4","D. Endocytose thyroglobulin from the colloid"]','B','Pendrin is an iodide/chloride transporter on the apical membrane that transports iodide from inside the follicular cell into the colloid lumen, where it can be oxidized by TPO and organified onto thyroglobulin.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Cortex','easy','mcq','The zona glomerulosa of the adrenal cortex primarily produces which hormone?','["A. Aldosterone","B. Cortisol","C. DHEA","D. Epinephrine"]','A','The zona glomerulosa (outermost layer) produces mineralocorticoids, primarily aldosterone. The zona fasciculata (middle) produces glucocorticoids (cortisol). The zona reticularis (innermost) produces androgens (DHEA, androstenedione).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Cortex','medium','mcq','All adrenocortical hormones share which structural precursor?','["A. Tyrosine","B. Cholesterol","C. Pregnenolone from phenylalanine","D. Arachidonic acid"]','B','All adrenocortical steroid hormones are derived from cholesterol. The rate-limiting step is conversion of cholesterol to pregnenolone by CYP11A1 (cholesterol side-chain cleavage enzyme) on the inner mitochondrial membrane.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Cortex','medium','mcq','The enzyme aldosterone synthase (CYP11B2) is uniquely expressed in which adrenal zone?','["A. Zona fasciculata","B. Zona reticularis","C. Zona glomerulosa","D. Adrenal medulla"]','C','CYP11B2 (aldosterone synthase) is expressed exclusively in the zona glomerulosa. This zone-specific enzyme expression explains why only the glomerulosa can produce aldosterone.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Cortex','hard','mcq','What is the primary stimulus for aldosterone secretion from the zona glomerulosa?','["A. ACTH from the anterior pituitary","B. High serum sodium concentration","C. Angiotensin II and elevated plasma K+ concentration","D. Low serum calcium via the calcium-sensing receptor"]','D','The primary regulators of aldosterone are angiotensin II (the major stimulus) and hyperkalemia. ACTH plays a minor permissive role. Low sodium stimulates aldosterone indirectly via the renin-angiotensin system.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Cortex','easy','mcq','Cortisol has a diurnal rhythm with its peak serum concentration occurring at approximately:','["A. 8:00 AM (early morning)","B. 12:00 PM (noon)","C. 6:00 PM (early evening)","D. 12:00 AM (midnight)"]','A','Cortisol peaks between 6-8 AM (coinciding with wakening) and reaches its nadir around midnight. This diurnal rhythm is driven by pulsatile CRH/ACTH secretion. Normal morning cortisol is 5-25 mcg/dL.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Cortex','medium','mcq','Aldosterone acts on principal cells of the cortical collecting duct to:','["A. Increase Na+ reabsorption and K+ secretion via upregulation of ENaC and Na-K-ATPase","B. Decrease Na+ reabsorption and increase water excretion","C. Stimulate H2O reabsorption via AQP2 water channels","D. Increase K+ reabsorption and Na+ secretion"]','B','Aldosterone binds the nuclear mineralocorticoid receptor in principal cells, increasing transcription of ENaC (epithelial sodium channel) and Na-K-ATPase. This increases Na+ reabsorption with accompanying K+ and H+ secretion, expanding ECF volume.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Cortex','medium','mcq','Glucocorticoids such as cortisol exert their metabolic effects primarily through:','["A. Membrane-bound tyrosine kinase receptors","B. Nuclear glucocorticoid receptors that regulate gene transcription","C. Gs-coupled GPCRs increasing cAMP","D. JAK-STAT signaling activated by cytoplasmic receptors"]','C','Cortisol (a steroid) diffuses across the cell membrane and binds the cytoplasmic glucocorticoid receptor (GR). The hormone-receptor complex translocates to the nucleus, binds GREs, and regulates target gene transcription — a classic nuclear receptor mechanism.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Cortex','hard','mcq','The 11β-hydroxylase enzyme (CYP11B1) is required for synthesis of cortisol. A deficiency of this enzyme would lead to accumulation of which precursor?','["A. Cholesterol","B. Pregnenolone only","C. 11-Deoxycortisol and 11-deoxycorticosterone","D. Aldosterone"]','D','CYP11B1 converts 11-deoxycortisol to cortisol and 11-deoxycorticosterone to corticosterone. A deficiency causes accumulation of 11-deoxycortisol and 11-deoxycorticosterone (a weak mineralocorticoid), leading to CAH with hypertension (unlike 21-hydroxylase deficiency).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Cortex','easy','mcq','Which metabolic effect does cortisol NOT produce?','["A. Increased peripheral glucose uptake in muscle","B. Increased hepatic gluconeogenesis","C. Increased protein catabolism in muscle","D. Increased lipolysis in adipose tissue"]','A','Cortisol is anti-insulin and diabetogenic: it increases hepatic gluconeogenesis, promotes protein catabolism (substrate for gluconeogenesis), and stimulates lipolysis. It DECREASES peripheral glucose uptake, raising blood glucose levels.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Cortex','medium','mcq','ACTH stimulates cortisol synthesis in the zona fasciculata primarily by:','["A. Directly hydroxylating cholesterol","B. Activating adenylyl cyclase via Gs, increasing cAMP, which activates PKA and increases StAR protein expression","C. Binding nuclear receptors to upregulate CYP11A1 gene transcription only","D. Increasing adrenal blood flow without affecting enzyme activity"]','B','ACTH binds MC2R (melanocortin 2 receptor) on adrenocortical cells — a Gs-coupled GPCR. The resulting cAMP-PKA cascade rapidly increases StAR (steroidogenic acute regulatory protein), which transports cholesterol into mitochondria — the rate-limiting step.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Medulla','easy','mcq','Chromaffin cells of the adrenal medulla are embryologically derived from and functionally analogous to:','["A. Modified preganglionic parasympathetic neurons","B. Modified postganglionic sympathetic neurons","C. Neural crest cells that became adrenocortical cells","D. Smooth muscle cells of the adrenal capsule"]','A','Chromaffin cells are modified postganglionic sympathetic neurons derived from neural crest cells. They receive preganglionic sympathetic (cholinergic/nicotinic) innervation and secrete catecholamines directly into the bloodstream.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Medulla','medium','mcq','The biosynthetic pathway for adrenal catecholamines proceeds in which sequence?','["A. Tyrosine → Dopamine → DOPA → Norepinephrine → Epinephrine","B. Tyrosine → DOPA → Dopamine → Norepinephrine → Epinephrine","C. Phenylalanine → Epinephrine → Norepinephrine → Dopamine","D. Tryptophan → Serotonin → Dopamine → Norepinephrine"]','B','The catecholamine synthesis pathway: Tyrosine (hydroxylated by TH) → L-DOPA (decarboxylated by AADC) → Dopamine (hydroxylated by DBH) → Norepinephrine (methylated by PNMT) → Epinephrine.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Medulla','medium','mcq','The enzyme PNMT (phenylethanolamine N-methyltransferase) converts norepinephrine to epinephrine. High local concentrations of which hormone are required to maintain PNMT expression?','["A. ACTH from the anterior pituitary","B. Cortisol from the adrenal cortex via the intra-adrenal portal circulation","C. Aldosterone from the zona glomerulosa","D. Epinephrine via positive feedback"]','C','Cortisol flows from the adrenal cortex through the intra-adrenal portal circulation to the medulla in very high concentrations, maintaining PNMT expression. This explains why adrenal medullary epinephrine synthesis depends on an intact adrenal cortex.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Medulla','hard','mcq','Catecholamines released from the adrenal medulla are stored in chromaffin granules with which co-stored protein used as a diagnostic biomarker?','["A. Synaptophysin","B. Chromogranin A","C. Alpha-synuclein","D. Secretogranin III"]','B','Catecholamines are stored in chromaffin (dense-core) granules along with chromogranin A, ATP, and enkephalins. Chromogranin A is released with catecholamines and serves as a plasma biomarker for neuroendocrine tumors including pheochromocytoma.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Medulla','easy','mcq','Approximately what proportion of adrenal medullary secretion is epinephrine versus norepinephrine?','["A. Epinephrine ~80%, norepinephrine ~20%","B. Epinephrine ~50%, norepinephrine ~50%","C. Epinephrine ~20%, norepinephrine ~80%","D. Epinephrine ~99%, norepinephrine ~1%"]','A','The adrenal medulla secretes approximately 80% epinephrine and 20% norepinephrine. This ratio exists because the intra-adrenal cortisol maintains high PNMT activity, effectively converting most NE to epinephrine.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Medulla','medium','mcq','The plasma half-life of catecholamines (epinephrine and norepinephrine) is approximately:','["A. 30 seconds","B. 2-3 minutes","C. 20 minutes","D. 2-3 hours"]','B','Catecholamines have a very short plasma half-life of 2-3 minutes due to rapid metabolism by MAO (monoamine oxidase) and COMT (catechol-O-methyltransferase), as well as neuronal reuptake. Urine metabolites include metanephrines and VMA.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Medulla','medium','mcq','Epinephrine acting on beta-2 adrenergic receptors in bronchial smooth muscle causes:','["A. Bronchoconstriction via Gq-IP3 signaling","B. Bronchodilation via Gs-cAMP signaling","C. Bronchoconstriction via alpha-1 receptors","D. No effect on bronchial smooth muscle"]','C','Beta-2 receptors are Gs-coupled; activation increases cAMP, causing smooth muscle relaxation and bronchodilation. This is the basis for beta-2 agonist use in asthma (e.g., salbutamol). Epinephrine also acts on alpha-1 in larger vessels causing vasoconstriction.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Medulla','hard','mcq','Norepinephrine differs from epinephrine in receptor selectivity in which key way?','["A. NE has predominantly alpha-1 activity with weak beta-2 effect; epinephrine has strong alpha-1, beta-1, and beta-2 activity","B. NE is more potent than epinephrine at beta-2 receptors","C. NE selectively activates only beta-1 cardiac receptors","D. NE and epinephrine have identical receptor profiles"]','A','Norepinephrine (NE) acts predominantly on alpha-1 adrenergic receptors, causing vasoconstriction. It has minimal beta-2 activity. Epinephrine activates alpha-1, beta-1 (cardiac stimulation), and beta-2 (bronchodilation, skeletal muscle vasodilation).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Medulla','easy','mcq','Chromaffin cells are stimulated to release catecholamines by which neurotransmitter released from preganglionic sympathetic nerve terminals?','["A. Norepinephrine acting on beta-1 receptors","B. Acetylcholine acting on nicotinic receptors","C. Dopamine acting on D2 receptors","D. VIP acting on VPAC receptors"]','A','Preganglionic sympathetic fibers release acetylcholine (ACh), which acts on nicotinic acetylcholine receptors (nAChR) on chromaffin cells to trigger calcium influx and exocytosis of catecholamines — analogous to ganglionic neurotransmission.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adrenal Medulla','medium','mcq','The primary urinary metabolite of catecholamine metabolism measured in the clinical workup of pheochromocytoma is:','["A. Homovanillic acid (HVA)","B. Metanephrine and normetanephrine (fractionated metanephrines)","C. 5-HIAA (5-hydroxyindoleacetic acid)","D. Vanillylmandelic acid (VMA) alone"]','B','Plasma free metanephrines (metanephrine and normetanephrine) are the most sensitive test for pheochromocytoma. VMA is a downstream metabolite also measurable in urine. MAO and COMT convert catecholamines to metanephrines → VMA.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Pancreatic Endocrine Function','easy','mcq','Beta cells constitute approximately what percentage of the islets of Langerhans and secrete which hormone?','["A. 70% of islet cells; secrete insulin and amylin","B. 20% of islet cells; secrete glucagon","C. 5% of islet cells; secrete somatostatin","D. 70% of islet cells; secrete glucagon"]','A','Beta cells constitute approximately 70% of islet cells and secrete insulin (the primary glucose-lowering hormone) and amylin (which slows gastric emptying). Alpha cells (~20%) secrete glucagon; delta cells (~5%) secrete somatostatin.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Pancreatic Endocrine Function','medium','mcq','During biosynthesis of insulin, what is secreted in equimolar amounts with insulin and can be measured as a marker of endogenous insulin production?','["A. Proinsulin","B. C-peptide","C. Glucagon","D. Amylin"]','B','Proinsulin is cleaved by proteases (PC1/3 and PC2) in secretory granules to yield insulin + C-peptide in equimolar amounts. C-peptide has a longer half-life than insulin and is used clinically to assess residual beta cell function.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Pancreatic Endocrine Function','medium','mcq','The insulin receptor is classified as which type of cell surface receptor?','["A. G protein-coupled receptor (GPCR)","B. Receptor tyrosine kinase (RTK)","C. Nuclear steroid hormone receptor","D. Ligand-gated ion channel"]','C','The insulin receptor is a receptor tyrosine kinase (RTK) — a heterotetrameric receptor (2 alpha + 2 beta subunits). Insulin binding causes autophosphorylation of the beta subunits on tyrosine residues, activating PI3K-Akt and MAPK downstream signaling.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Pancreatic Endocrine Function','hard','mcq','GLUT2 is expressed in pancreatic beta cells and is critical for glucose sensing. Its key kinetic property is:','["A. Low Km (high affinity) — saturated at low glucose concentrations","B. High Km (low affinity) — uptake is proportional to blood glucose at physiologic concentrations","C. Active transport requiring ATP hydrolysis","D. Insulin-dependent translocation to the cell surface like GLUT4"]','B','GLUT2 has a high Km (~15-20 mM), meaning it is not saturated at normal blood glucose levels (~5 mM). Glucose entry into beta cells is therefore proportional to blood glucose, making GLUT2 the glucose sensor that couples insulin secretion to glycemia.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Pancreatic Endocrine Function','easy','mcq','The primary action of insulin on skeletal muscle and adipose tissue is to:','["A. Stimulate GLUT4 translocation to the cell surface, increasing glucose uptake","B. Stimulate GLUT1-mediated glucose uptake via cAMP signaling","C. Activate glycogenolysis and gluconeogenesis","D. Inhibit glycogen synthase activity"]','A','Insulin activates PI3K-Akt signaling, causing translocation of GLUT4-containing vesicles to the plasma membrane in muscle and adipose tissue. This insulin-dependent glucose uptake is responsible for the glucose-lowering effect of insulin post-meal.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Pancreatic Endocrine Function','medium','mcq','Glucagons primary mechanism of action in the liver involves which signaling pathway?','["A. Tyrosine kinase receptor activating PI3K","B. Gs-cAMP-PKA pathway activating glycogenolysis and gluconeogenesis","C. Nuclear receptor increasing PEPCK gene transcription acutely","D. Gq-IP3/DAG activating protein kinase C"]','B','Glucagon binds its GPCR on hepatocytes, activating Gs → adenylyl cyclase → cAMP → PKA. PKA activates glycogen phosphorylase (glycogenolysis) and inhibits glycogen synthase, while also activating CREB to increase PEPCK and G6Pase transcription (gluconeogenesis).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Pancreatic Endocrine Function','medium','mcq','Glucose-dependent insulinotropic peptide (GIP) and GLP-1 are both called "incretins" because they:','["A. Increase insulin secretion in a glucose-dependent manner after oral food intake","B. Directly inhibit glucagon secretion independent of glucose","C. Stimulate beta cell proliferation as their primary action","D. Act on nuclear receptors to increase insulin gene expression"]','C','Incretins (GIP from K cells, GLP-1 from L cells) amplify insulin secretion in response to oral glucose — the "incretin effect" explains why oral glucose produces more insulin than an equivalent IV glucose dose. They act in a glucose-dependent manner.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Pancreatic Endocrine Function','hard','mcq','The half-life of insulin in plasma is approximately 5-8 minutes. This rapid clearance is primarily due to:','["A. Rapid renal filtration and excretion","B. Hepatic insulinase (insulin-degrading enzyme) degradation on first pass, and also renal clearance","C. MAO-mediated oxidation in the liver","D. Binding to IGFBP which triggers rapid internalization"]','D','Insulin has a half-life of ~5-8 minutes. It is degraded primarily by insulin-degrading enzyme (IDE/insulinase) in the liver (~50% on first hepatic pass) and also in kidney and peripheral tissues. This explains why exogenous insulin formulations require modifications to extend duration.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Pancreatic Endocrine Function','easy','mcq','The normal fasting plasma glucose level is:','["A. 70-100 mg/dL","B. 110-140 mg/dL","C. 40-70 mg/dL","D. 100-125 mg/dL"]','A','Normal fasting plasma glucose is 70-100 mg/dL. Impaired fasting glucose (prediabetes) is 100-125 mg/dL. Diabetes mellitus is defined as fasting glucose ≥126 mg/dL on two occasions.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Pancreatic Endocrine Function','medium','mcq','Somatostatin from pancreatic delta cells inhibits which of the following?','["A. Only insulin secretion from beta cells","B. Only glucagon secretion from alpha cells","C. Both insulin and glucagon secretion in a paracrine manner","D. Digestive enzyme secretion from acinar cells only"]','B','Pancreatic delta cell somatostatin acts locally (paracrine) to inhibit both insulin (beta cells) and glucagon (alpha cells) secretion. Somatostatin also inhibits growth hormone from the pituitary and multiple GI hormones.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Calcium & Phosphate Regulation','easy','mcq','Normal serum total calcium concentration is approximately:','["A. 8.5-10.5 mg/dL (2.1-2.6 mmol/L)","B. 4.5-5.5 mg/dL","C. 12-14 mg/dL","D. 1.5-2.0 mg/dL"]','A','Normal total serum calcium is 8.5-10.5 mg/dL. Approximately 50% is ionized (free, biologically active), 40% bound to albumin, and 10% complexed to anions. The ionized fraction is the physiologically regulated form.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Calcium & Phosphate Regulation','medium','mcq','Parathyroid hormone (PTH) is synthesized and secreted by which cell type?','["A. C cells (parafollicular cells) of the thyroid","B. Chief cells of the parathyroid glands","C. Principal cells of the kidney collecting duct","D. Osteoclasts in bone"]','B','PTH is produced by chief cells (also called principal cells) of the parathyroid glands. There are typically four parathyroid glands embedded in the posterior thyroid capsule. PTH is an 84-amino-acid peptide.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Calcium & Phosphate Regulation','medium','mcq','PTH increases renal calcium reabsorption at which nephron segment?','["A. Proximal tubule via NHE3 inhibition","B. Thick ascending limb via NKCC2","C. Distal convoluted tubule via TRPV5 calcium channels","D. Collecting duct via AQP2 water channels"]','C','PTH acts on the distal convoluted tubule to increase calcium reabsorption via TRPV5 (transient receptor potential vanilloid-5) apical calcium channels and PMCA/NCX on the basolateral membrane. In the proximal tubule, PTH DECREASES phosphate reabsorption.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Calcium & Phosphate Regulation','hard','mcq','The calcium-sensing receptor (CaSR) regulates PTH secretion. An activating mutation of CaSR would cause:','["A. Familial hypocalciuric hypercalcemia (FHH)","B. Neonatal severe primary hyperparathyroidism","C. Autosomal dominant hypocalcemia (ADH) — suppresses PTH at normal calcium levels","D. Pseudohypoparathyroidism type Ia"]','D','The CaSR is a Gq-coupled GPCR that senses ionized Ca2+. An activating mutation lowers the set-point for calcium detection, suppressing PTH even at low-normal calcium — causing autosomal dominant hypocalcemia (ADH) with inappropriately low PTH.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Calcium & Phosphate Regulation','easy','mcq','Vitamin D3 (cholecalciferol) undergoes two hydroxylation steps to become active calcitriol. Where do these hydroxylations occur?','["A. First in the kidney (25-hydroxylation), then in the liver (1-alpha hydroxylation)","B. First in the skin (no hydroxylation), then active in plasma","C. First in the liver (25-hydroxylation), then in the kidney (1-alpha hydroxylation)","D. Both hydroxylations occur in the liver"]','A','25-hydroxylation occurs in the liver by CYP2R1/CYP27A1, producing 25(OH)D3 (calcidiol — the storage form measured in serum). The second step (1-alpha hydroxylation by CYP27B1) occurs in the kidney proximal tubule, producing 1,25(OH)2D3 (calcitriol, active form).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Calcium & Phosphate Regulation','medium','mcq','Calcitonin is secreted from parafollicular C cells of the thyroid. Its primary physiologic action is to:','["A. Increase bone resorption and raise serum calcium","B. Inhibit osteoclast activity, lowering serum calcium in response to hypercalcemia","C. Increase renal calcium reabsorption in the distal tubule","D. Stimulate 1-alpha hydroxylase activity in the kidney"]','B','Calcitonin is released when serum calcium rises above normal. It inhibits osteoclasts (decreasing bone resorption) and increases renal calcium excretion, lowering serum calcium. Its physiologic role is relatively minor compared to PTH and vitamin D.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Calcium & Phosphate Regulation','medium','mcq','PTH acts on osteoblasts to increase bone resorption indirectly. This occurs via which mechanism?','["A. PTH directly activates osteoclasts via PTH1R on osteoclasts","B. PTH stimulates chondrocytes to release collagenase","C. PTH stimulates osteoblasts to upregulate RANKL, which activates osteoclast differentiation","D. PTH directly lyses bone matrix via carbonic anhydrase activation"]','C','PTH receptor (PTH1R) is expressed on osteoblasts, not osteoclasts. PTH signaling increases RANKL and decreases OPG on osteoblasts. RANKL binds RANK on osteoclast precursors, promoting their differentiation and bone-resorbing activity.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Calcium & Phosphate Regulation','hard','mcq','FGF-23 is secreted by osteocytes and has which effects on calcium-phosphate homeostasis?','["A. Increases 1-alpha hydroxylase activity and increases renal phosphate reabsorption","B. Inhibits 1-alpha hydroxylase (reducing calcitriol synthesis) and inhibits NaPi-IIa/IIc (reducing phosphate reabsorption)","C. Stimulates PTH secretion from parathyroid chief cells","D. Directly inhibits osteoclast activity to reduce bone resorption"]','D','FGF-23 acts on the kidney (via FGFR1-klotho complex) to: (1) inhibit CYP27B1 (1-alpha hydroxylase), reducing calcitriol synthesis, and (2) downregulate NaPi-IIa and NaPi-IIc sodium-phosphate cotransporters in the proximal tubule, reducing phosphate reabsorption.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Calcium & Phosphate Regulation','easy','mcq','Which of the following is a major physiologic effect of calcitriol (1,25-dihydroxyvitamin D3)?','["A. Increased intestinal calcium and phosphate absorption via increased calbindin expression","B. Decreased intestinal calcium absorption (protective against hypercalcemia)","C. Inhibition of osteoclast activity in bone","D. Increased renal phosphate reabsorption via NaPi-IIa"]','A','Calcitriol acts on enterocytes to increase expression of TRPV6 (apical calcium channel), calbindin-D9k (calcium carrier), and PMCA1b (basolateral calcium pump), increasing intestinal calcium and phosphate absorption — accounting for 30-40% of dietary calcium uptake.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Calcium & Phosphate Regulation','medium','mcq','PTHs effects on the kidney include all of the following EXCEPT:','["A. Increased calcium reabsorption in the distal tubule","B. Decreased phosphate reabsorption in the proximal tubule","C. Activation of 1-alpha hydroxylase in the proximal tubule","D. Increased sodium reabsorption in the collecting duct"]','B','PTH increases distal calcium reabsorption, decreases proximal phosphate reabsorption (phosphaturia), and activates 1-alpha hydroxylase. PTH does NOT increase sodium reabsorption in the collecting duct — that is aldosterones role via ENaC.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Gonadal Hormones','easy','mcq','In males, LH acts on which testicular cell type to stimulate testosterone synthesis?','["A. Sertoli cells","B. Leydig cells","C. Spermatogonia","D. Peritubular myoid cells"]','A','LH acts on Leydig cells (interstitial cells of Leydig) to stimulate testosterone synthesis via the Gs-cAMP-PKA pathway, increasing StAR protein and activating steroidogenic enzymes. Sertoli cells respond to FSH to support spermatogenesis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Gonadal Hormones','medium','mcq','Which enzyme converts testosterone to dihydrotestosterone (DHT), and where is this conversion most important?','["A. Aromatase (CYP19A1), primarily in adipose tissue","B. 5-alpha reductase, primarily in the prostate, skin, and external genitalia","C. CYP11B1 (11-beta hydroxylase), primarily in the adrenal gland","D. 17-beta HSD, primarily in the testes"]','B','5-alpha reductase (types 1 and 2) converts testosterone to DHT, which is 2-3x more potent. Type 2 is expressed in the prostate and external genitalia (important for male genital development and BPH). 5-alpha reductase inhibitors (finasteride) are used for BPH.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Gonadal Hormones','medium','mcq','Inhibin B, secreted by Sertoli cells in males, specifically suppresses which anterior pituitary hormone?','["A. Both FSH and LH equally","B. LH preferentially","C. FSH specifically (does not inhibit LH)","D. Prolactin via dopamine inhibition"]','C','Inhibin B (from Sertoli cells in males, granulosa cells in females) selectively suppresses FSH secretion from the anterior pituitary without significantly affecting LH. This provides specific negative feedback on FSH to regulate spermatogenesis and follicular development.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Gonadal Hormones','hard','mcq','Mid-cycle estradiol surge causes a positive feedback effect on the hypothalamic-pituitary axis, resulting in:','["A. Suppression of both FSH and LH (classic negative feedback)","B. The LH surge that triggers ovulation, switching from negative to positive feedback","C. Increased somatostatin release inhibiting GH","D. Increased CRH release causing stress-like ACTH elevation"]','D','Estradiol normally exerts negative feedback. However, when estradiol reaches a high threshold (>200 pg/mL for >48h) in the late follicular phase, it switches to positive feedback on GnRH/LH, producing the mid-cycle LH surge that triggers ovulation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Gonadal Hormones','easy','mcq','Aromatase (CYP19A1) converts androgens to estrogens. In premenopausal women, the primary site of aromatase activity for estrogen production is:','["A. The ovarian granulosa cells","B. The adrenal cortex","C. Adipose tissue","D. The liver"]','A','In premenopausal women, aromatase in granulosa cells converts theca cell-derived androstenedione and testosterone to estrone and estradiol (the "two-cell, two-gonadotropin" model). Postmenopausally, adipose tissue becomes the primary source of estrogens.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Gonadal Hormones','medium','mcq','SHBG (sex hormone-binding globulin) regulates the bioavailability of sex hormones. Which condition would INCREASE SHBG levels, reducing free testosterone?','["A. Obesity and hyperinsulinemia","B. Exogenous androgen (testosterone) administration","C. Hypothyroidism","D. Elevated estrogens (e.g., pregnancy, oral contraceptives containing estrogen)"]','B','Estrogens increase SHBG synthesis in the liver, reducing free sex hormone levels. Androgens, insulin, obesity, and hypothyroidism DECREASE SHBG. High SHBG in the setting of estrogen exposure reduces free testosterone bioavailability.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Gonadal Hormones','medium','mcq','Progesterones primary role in the female reproductive cycle is to:','["A. Stimulate endometrial proliferation during the follicular phase","B. Maintain the secretory endometrium and prepare it for embryo implantation (luteal phase)","C. Stimulate LH surge via positive feedback on the pituitary","D. Increase FSH secretion by inhibiting inhibin B"]','C','Progesterone is produced by the corpus luteum during the luteal phase. It transforms the proliferative endometrium into a secretory endometrium (rich in glycogen), reduces uterine contractility, and thickens cervical mucus — all preparing for implantation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Gonadal Hormones','hard','mcq','GnRH pulse frequency determines the ratio of LH to FSH secreted. Which pulse pattern preferentially stimulates FSH?','["A. Rapid pulses (every 30-60 minutes) favor FSH over LH","B. Slow pulses (every 90-120 minutes or more) favor FSH over LH","C. Continuous (non-pulsatile) GnRH maximally stimulates FSH","D. Pulse frequency has no differential effect on FSH vs LH"]','D','Slow, infrequent GnRH pulses preferentially stimulate FSH secretion. Rapid pulses favor LH. Continuous GnRH suppresses both by downregulating GnRH receptors (used therapeutically as GnRH agonists for prostate cancer, endometriosis).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Gonadal Hormones','easy','mcq','FSH acts on which female reproductive cell type to stimulate estradiol production via aromatase?','["A. Theca cells","B. Granulosa cells","C. Luteinized stromal cells","D. Oocytes"]','B','FSH acts on granulosa cells to upregulate aromatase (CYP19A1), which converts androstenedione (produced by LH-stimulated theca cells) to estradiol. This two-cell, two-gonadotropin model requires both FSH (granulosa) and LH (theca).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Gonadal Hormones','medium','mcq','Testosterones biosynthetic pathway in Leydig cells proceeds through which intermediate, shared with adrenocortical steroidogenesis?','["A. Pregnenolone → DHEA → androstenedione → testosterone","B. Cholesterol → aldosterone → testosterone directly","C. Tyrosine → DOPA → testosterone","D. Cortisol → androstenedione → testosterone"]','B','Testosterone synthesis: Cholesterol → Pregnenolone (CYP11A1) → DHEA (CYP17A1, 17,20-lyase) → Androstenedione (17-beta HSD) → Testosterone. Pregnenolone and DHEA are shared intermediates with adrenal androgen synthesis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Growth Hormone & IGF-1','easy','mcq','Growth hormone (GH) is a peptide of how many amino acids, and it is secreted in what pattern?','["A. 191 amino acids; pulsatile secretion with peak during slow-wave sleep","B. 84 amino acids; continuous tonic secretion","C. 29 amino acids; pulsatile, peak after meals","D. 253 amino acids; circadian rhythm peaking at noon"]','A','GH is a 191 amino acid single-chain polypeptide secreted in pulses, with the largest pulse occurring during the first hours of slow-wave (deep) sleep. GH secretion is stimulated by GHRH and ghrelin, and inhibited by somatostatin and IGF-1.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Growth Hormone & IGF-1','medium','mcq','The GH receptor signals primarily through which intracellular pathway?','["A. PI3K-Akt pathway via receptor tyrosine kinase","B. Gs-cAMP-PKA via GPCR","C. JAK2-STAT5 pathway via cytokine receptor superfamily","D. Gq-IP3/DAG via phospholipase C"]','B','The GH receptor belongs to the cytokine receptor superfamily (no intrinsic kinase activity). GH binding causes receptor dimerization and activation of associated JAK2 (Janus kinase 2), which phosphorylates STAT5b. STAT5b dimerizes and translocates to the nucleus.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Growth Hormone & IGF-1','medium','mcq','IGF-1 is primarily produced in which organ and mediates which major GH effect?','["A. Muscle; primarily mediates lipolysis only","B. Liver; mediates most anabolic and growth-promoting effects of GH","C. Adipose tissue; mediates GHs anti-insulin effects","D. Bone; mediates GH-induced calcium reabsorption"]','B','IGF-1 (somatomedin C) is produced primarily in the liver in response to GH. It mediates most of GHs anabolic effects: protein synthesis, chondrocyte proliferation at epiphyseal plates (linear growth), and cellular anti-apoptotic signaling.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Growth Hormone & IGF-1','hard','mcq','Which of the following correctly describes GHs acute metabolic effects (as opposed to IGF-1-mediated effects)?','["A. Increased glucose uptake, decreased lipolysis, protein synthesis stimulation","B. Decreased lipolysis, increased glucose oxidation, anabolic effects on protein","C. Anti-insulin (diabetogenic): decreased glucose uptake, increased lipolysis, increased free fatty acids","D. Increased GLUT4 expression in adipose tissue, mimicking insulin"]','C','GH has direct anti-insulin (diabetogenic) effects: it inhibits insulin-stimulated glucose uptake in muscle and adipose (post-receptor insulin resistance), stimulates lipolysis (increasing free fatty acids), and raises fasting blood glucose. These are distinct from the anabolic IGF-1-mediated effects.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Growth Hormone & IGF-1','easy','mcq','Ghrelin, a peptide hormone from the stomach, stimulates GH secretion. What is ghrelins receptor, and what other major effect does ghrelin have?','["A. GHS-R (growth hormone secretagogue receptor); also potently stimulates appetite/food intake","B. GLP-1R; stimulates insulin secretion in a glucose-dependent manner","C. PTH1R; stimulates bone resorption and calcium release","D. TSH receptor; amplifies thyroid hormone synthesis"]','A','Ghrelin is produced by oxyntic (gastric fundal) cells and acts on GHS-R1a. In addition to stimulating GH release, ghrelin is a potent orexigenic (appetite-stimulating) hormone — levels rise before meals and fall after eating.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Growth Hormone & IGF-1','medium','mcq','IGF-1 is transported in blood bound to which protein, giving it its long half-life of ~20 hours?','["A. Albumin only","B. Insulin-binding globulin (IBG)","C. IGF-binding proteins (IGFBPs), particularly IGFBP-3","D. Transthyretin (prealbumin)"]','B','IGF-1 is primarily transported bound to IGFBP-3 (the most abundant IGFBP) in a ternary complex with ALS (acid-labile subunit). This binding extends IGF-1s half-life from minutes to ~20 hours and serves as a reservoir. IGFBP-3 is GH-dependent.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Growth Hormone & IGF-1','medium','mcq','GH promotes linear growth in children primarily by acting on which structure via IGF-1?','["A. Periosteum of long bones, stimulating appositional bone growth","B. Epiphyseal growth plates (chondrocytes), stimulating chondrocyte proliferation and matrix synthesis","C. Osteoblasts of the cortical bone, increasing bone density","D. Osteoclasts, resorbing old bone to allow linear growth"]','C','IGF-1 (induced by GH) stimulates chondrocyte proliferation and hypertrophy at the epiphyseal growth plates, driving longitudinal (linear) bone growth. After epiphyseal fusion (puberty), linear growth ceases regardless of GH levels.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Growth Hormone & IGF-1','hard','mcq','In acromegaly (excess GH in adults), which laboratory finding best confirms autonomous GH hypersecretion?','["A. Random serum GH >5 ng/mL","B. Failure to suppress GH below 1 ng/mL after oral glucose tolerance test (OGTT)","C. Elevated fasting cortisol with midnight salivary cortisol","D. Low IGF-1 for age"]','B','In acromegaly, the gold standard for diagnosis is failure to suppress GH below 1 ng/mL (or 0.4 ng/mL by newer assays) after a 75g OGTT. Normally, hyperglycemia suppresses GH via somatostatin. Random GH is unreliable due to pulsatile secretion.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Growth Hormone & IGF-1','easy','mcq','The plasma half-life of GH is approximately:','["A. 20 minutes","B. 20 hours","C. 7 days","D. 2-3 minutes"]','A','GH has a short plasma half-life of approximately 20 minutes. IGF-1 has a much longer half-life (~20 hours) due to binding to IGFBPs. This is why serum IGF-1 (not GH) is used as a screening test for GH excess (acromegaly/gigantism).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Growth Hormone & IGF-1','medium','mcq','IGF-1 exerts negative feedback on GH secretion at which level(s)?','["A. Anterior pituitary only (suppresses somatotrophs directly)","B. Hypothalamus only (stimulates somatostatin release)","C. Both the hypothalamus (stimulates somatostatin, inhibits GHRH) and anterior pituitary (directly suppresses somatotrophs)","D. Adrenal cortex, reducing cortisol levels that normally stimulate GH"]','B','IGF-1 exerts negative feedback at both the hypothalamus (stimulating somatostatin release and inhibiting GHRH neurons) and directly on pituitary somatotrophs (reducing GH synthesis and secretion). This long-loop feedback maintains GH within normal range.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Prolactin & Oxytocin/ADH','easy','mcq','The primary physiologic regulator of prolactin secretion from the anterior pituitary is:','["A. TRH, which tonically stimulates prolactin","B. Dopamine (PIH), which tonically inhibits prolactin release","C. Estradiol, which acutely suppresses prolactin","D. Oxytocin, which stimulates prolactin via paracrine signaling"]','B','Dopamine (PIH) tonically inhibits prolactin via D2 receptors on lactotrophs. This explains why dopamine antagonists (antipsychotics, metoclopramide) and pituitary stalk compression (which blocks dopamine delivery) cause hyperprolactinemia.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Prolactin & Oxytocin/ADH','medium','mcq','The suckling reflex stimulates prolactin secretion by which mechanism?','["A. Direct neural stimulation of lactotrophs via spinal cord afferents","B. Suckling inhibits hypothalamic dopamine release, removing tonic inhibition of prolactin","C. Suckling increases TRH, which is the primary driver of milk production","D. Suckling triggers oxytocin release from the posterior pituitary, which stimulates prolactin"]','B','Suckling generates afferent neural signals that inhibit hypothalamic tuberoinfundibular dopamine neurons, reducing dopamine delivery to the anterior pituitary. This disinhibition allows prolactin to surge, maintaining lactogenesis during breastfeeding.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Prolactin & Oxytocin/ADH','medium','mcq','Prolactin signals through which receptor/pathway to promote milk synthesis?','["A. Nuclear receptor, directly regulating milk protein gene transcription","B. Tyrosine kinase receptor activating MAPK","C. JAK2-STAT5 pathway (cytokine receptor family)","D. Gs-cAMP-PKA pathway via GPCR"]','C','The prolactin receptor belongs to the cytokine receptor superfamily. Prolactin binding causes receptor dimerization and activation of JAK2, which phosphorylates STAT5. STAT5 dimers translocate to the nucleus and activate genes for milk proteins (caseins, lactalbumin).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Prolactin & Oxytocin/ADH','hard','mcq','Hyperprolactinemia causes hypogonadism (amenorrhea in women, decreased testosterone in men) by which mechanism?','["A. Prolactin directly inhibits FSH and LH at the anterior pituitary","B. Prolactin suppresses hypothalamic GnRH pulse frequency and amplitude, reducing FSH and LH","C. Prolactin competes with estradiol for nuclear estrogen receptors","D. Prolactin stimulates SHBG production, reducing free testosterone"]','D','Hyperprolactinemia suppresses the hypothalamic GnRH pulse generator, reducing GnRH pulse frequency and amplitude. This decreases FSH and LH secretion, causing hypogonadotropic hypogonadism. This is the basis for lactational amenorrhea.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Prolactin & Oxytocin/ADH','easy','mcq','ADH (vasopressin) is synthesized primarily in which hypothalamic nucleus?','["A. Supraoptic nucleus (SON)","B. Paraventricular nucleus (PVN) exclusively","C. Arcuate nucleus","D. Ventromedial nucleus"]','A','ADH is produced predominantly in the supraoptic nucleus (SON), with additional production in the paraventricular nucleus (PVN). Both nuclei project axons to the posterior pituitary where ADH is stored and released in response to osmotic or volume stimuli.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Prolactin & Oxytocin/ADH','medium','mcq','ADH increases water reabsorption in the collecting duct by which V2 receptor-mediated mechanism?','["A. V2 receptor (Gq-IP3) activates PKC, which phosphorylates and opens water channels","B. V2 receptor (Gs-cAMP-PKA) phosphorylates AQP2 and stimulates its insertion into the apical membrane","C. V2 receptor directly opens ROMK potassium channels, creating the driving force for water","D. V2 receptor activates aldosterone gene expression in principal cells"]','B','ADH binds V2 receptors (Gs-coupled) on principal cells of the collecting duct. The cAMP-PKA cascade phosphorylates AQP2 water channels on intracellular vesicles, triggering their fusion with the apical membrane. Water moves from tubular lumen to hypertonic medullary interstitium.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Prolactin & Oxytocin/ADH','medium','mcq','The primary stimulus for ADH release from the posterior pituitary is:','["A. Increased plasma osmolality (>285 mOsm/kg) sensed by hypothalamic osmoreceptors","B. Hypokalemia detected by the JGA of the kidney","C. High plasma cortisol detected by the supraoptic nucleus","D. Hypocalcemia sensed by CaSR in the posterior pituitary"]','A','The primary trigger for ADH secretion is increased plasma osmolality (>285 mOsm/kg), sensed by osmoreceptors in the anterior hypothalamus (OVLT and adjacent areas). Volume depletion and hypotension (baroreceptors) are secondary stimuli that override osmolality when severe.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Prolactin & Oxytocin/ADH','hard','mcq','In central diabetes insipidus (CDI), which laboratory finding distinguishes it from nephrogenic DI (NDI)?','["A. Both show concentrated urine with low serum osmolality","B. CDI shows response to exogenous ADH (desmopressin) with urine concentration; NDI does not respond","C. NDI shows undetectable plasma ADH; CDI shows supranormal plasma ADH","D. CDI is associated with hyperkalemia; NDI with hypokalemia"]','B','In CDI, there is insufficient ADH production; exogenous desmopressin (V2 agonist) restores urine concentration. In NDI, the kidney cannot respond to ADH (V2 receptor or AQP2 mutations); desmopressin has no effect. Both present with dilute polyuria and polydipsia.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Prolactin & Oxytocin/ADH','easy','mcq','Oxytocin is produced in the paraventricular nucleus. The Ferguson reflex is an example of positive feedback involving oxytocin. What triggers this reflex?','["A. Cervical/vaginal distension → oxytocin → stronger uterine contractions → more distension (positive feedback loop of parturition)","B. High estrogen → oxytocin → cervical ripening → labor initiation","C. Suckling → oxytocin → increased milk letdown → more suckling","D. Progesterone withdrawal → oxytocin surge → labor induction"]','A','The Ferguson reflex: cervical distension during labor sends neural signals to the hypothalamus → oxytocin release from posterior pituitary → uterine contractions → more cervical distension → more oxytocin. This positive feedback loop continues until the baby is delivered.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Prolactin & Oxytocin/ADH','medium','mcq','SIADH (syndrome of inappropriate ADH) causes which electrolyte disturbance and why?','["A. Hypernatremia due to excessive water excretion","B. Hyponatremia due to water retention in excess of sodium, diluting plasma sodium","C. Hyperkalemia due to decreased renal potassium excretion","D. Hypercalcemia due to increased intestinal calcium absorption"]','B','In SIADH, inappropriately elevated ADH causes excessive water retention in the collecting duct via AQP2. This dilutes plasma, causing hyponatremia (<135 mEq/L) with inappropriately concentrated urine (>100 mOsm/kg). Treatment includes fluid restriction.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adipokines & Gut-Brain Axis','easy','mcq','Leptin is secreted by white adipose tissue and acts primarily on which brain region to regulate energy balance?','["A. Hypothalamic arcuate nucleus","B. Prefrontal cortex","C. Cerebellum","D. Brainstem nucleus tractus solitarius exclusively"]','A','Leptin acts on the hypothalamic arcuate nucleus (ARC) to stimulate POMC/CART neurons (anorexigenic — reduce feeding) and inhibit NPY/AgRP neurons (orexigenic — increase feeding). Net effect: decreased appetite and increased energy expenditure.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adipokines & Gut-Brain Axis','medium','mcq','In common obesity, leptin levels are typically high yet appetite is not suppressed — this phenomenon is called:','["A. Leptin deficiency","B. Leptin resistance","C. Hyperleptinemia paradox","D. Adipokine insensitivity syndrome"]','B','Leptin resistance: obese individuals have high circulating leptin (proportional to fat mass) but hypothalamic neurons fail to respond normally. Mechanisms include reduced leptin transport across the blood-brain barrier and downregulation of leptin receptor signaling (SOCS3 upregulation).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adipokines & Gut-Brain Axis','medium','mcq','Adiponectin levels are characteristically low in obesity and type 2 diabetes. Adiponectin improves metabolic health by:','["A. Stimulating appetite and increasing adipogenesis","B. Increasing insulin sensitivity, promoting fatty acid oxidation, and having anti-inflammatory effects","C. Directly stimulating insulin secretion from beta cells","D. Increasing hepatic gluconeogenesis to maintain blood glucose"]','C','Adiponectin (via AdipoR1 and AdipoR2) activates AMPK, promoting fatty acid oxidation and reducing hepatic gluconeogenesis. It increases insulin sensitivity and has anti-inflammatory effects. Adiponectin is paradoxically LOW in obesity and T2DM.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adipokines & Gut-Brain Axis','hard','mcq','DPP-4 (dipeptidyl peptidase-4) is a serine protease that rapidly degrades GLP-1. The half-life of native GLP-1 is approximately:','["A. 20-30 minutes","B. 2 minutes","C. 2 hours","D. 24 hours"]','B','Native GLP-1 has a very short half-life of approximately 2 minutes due to rapid degradation by DPP-4 (circulating and endothelial) and neutral endopeptidases. DPP-4 inhibitors (gliptins) extend GLP-1 half-life. GLP-1 receptor agonists are engineered to be DPP-4 resistant.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adipokines & Gut-Brain Axis','easy','mcq','GLP-1 (glucagon-like peptide-1) is secreted from which intestinal cell type and has which primary metabolic effect?','["A. K cells of the duodenum; stimulates glucagon secretion","B. L cells of the ileum/colon; stimulates insulin secretion in a glucose-dependent manner and inhibits glucagon","C. I cells of the duodenum; stimulates pancreatic enzyme secretion","D. G cells of the stomach; stimulates gastric acid secretion"]','B','GLP-1 is produced by L cells located primarily in the distal ileum and colon (also proximal small bowel). It stimulates glucose-dependent insulin secretion, inhibits glucagon, slows gastric emptying, and reduces appetite — the basis for GLP-1 receptor agonist therapy (e.g., semaglutide).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adipokines & Gut-Brain Axis','medium','mcq','GIP (glucose-dependent insulinotropic peptide) is secreted by which intestinal cell type and is classified as:','["A. L cells of the colon; a satiety hormone","B. K cells of the duodenum and jejunum; an incretin hormone amplifying insulin secretion","C. I cells of the duodenum; a cholecystokinin-related hormone","D. S cells of the duodenum; a secretin analog"]','B','GIP is produced by K cells in the duodenum and proximal jejunum. Along with GLP-1, GIP is an incretin — it amplifies glucose-induced insulin secretion after oral nutrient ingestion. The incretin effect explains why oral glucose evokes more insulin than IV glucose.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adipokines & Gut-Brain Axis','medium','mcq','Ghrelin is unique among gut hormones because it is predominantly:','["A. Anorexigenic (appetite-suppressing) and rises after meals","B. Orexigenic (appetite-stimulating) and rises before meals, falling after eating","C. A satiety hormone secreted by L cells of the ileum","D. Released by adipocytes, not the gastrointestinal tract"]','B','Ghrelin, produced by oxyntic cells of the gastric fundus, is the primary orexigenic gut hormone. Its levels rise before meals (anticipatory hunger signal) and fall after eating. Ghrelin also stimulates GH secretion from the anterior pituitary via GHS-R1a.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adipokines & Gut-Brain Axis','hard','mcq','PYY (peptide YY) reduces appetite after meals by acting on which receptor in the hypothalamus?','["A. Y1 receptor, stimulating NPY/AgRP neurons","B. Y2 receptor (inhibitory autoreceptors), suppressing NPY/AgRP orexigenic neurons in the arcuate nucleus","C. Leptin receptor (LepR), mimicking leptin signaling","D. GLP-1R on POMC neurons"]','B','PYY3-36 (the active truncated form released from L cells post-meal) acts on Y2 receptors on NPY/AgRP neurons in the arcuate nucleus. Y2 is an inhibitory autoreceptor — PYY binding suppresses these orexigenic neurons, reducing appetite and food intake.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adipokines & Gut-Brain Axis','easy','mcq','CCK (cholecystokinin) is released from I cells of the duodenum in response to dietary fat and protein. Its primary gastrointestinal actions include:','["A. Stimulating gallbladder contraction and pancreatic enzyme secretion; reducing appetite via vagal afferents","B. Stimulating gastric acid secretion and gastrin release","C. Inhibiting gallbladder contraction and stimulating pancreatic bicarbonate secretion","D. Exclusively acting on hepatic bile acid synthesis"]','A','CCK stimulates gallbladder contraction (releasing bile for fat emulsification), pancreatic acinar cells (releasing digestive enzymes), and reduces appetite via vagal afferent signaling to the brainstem. CCK also slows gastric emptying.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Endocrinology','Anatomy & Physiology','Adipokines & Gut-Brain Axis','easy','mcq','GLP-1 is secreted from which intestinal cell type and has which primary metabolic effect?','["A. L cells of the ileum/colon; stimulates insulin secretion in a glucose-dependent manner and inhibits glucagon","B. K cells of the duodenum; stimulates glucagon secretion","C. I cells of the duodenum; stimulates pancreatic enzyme secretion","D. G cells of the stomach; stimulates gastric acid secretion"]','A','GLP-1 is produced by L cells in the distal ileum and colon. It stimulates glucose-dependent insulin secretion, inhibits glucagon, slows gastric emptying, and reduces appetite. GLP-1 receptor agonists (semaglutide, liraglutide) exploit these effects therapeutically.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Guyton & Hall Medical Physiology 14th Ed');
