-- Reproductive System & OB-GYN: Pathology MCQs (110 questions)

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Cervical Disease','easy','mcq','Which HPV subtypes are most strongly associated with cervical squamous cell carcinoma?','["A. HPV 6 and 11","B. HPV 31 and 33","C. HPV 16 and 18","D. HPV 42 and 44"]','C','HPV 16 and 18 are high-risk oncogenic subtypes responsible for approximately 70% of cervical cancers. They encode E6 (inactivates p53) and E7 (inactivates Rb) oncoproteins. HPV 6 and 11 are low-risk types causing genital warts.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Cervical Disease','easy','mcq','CIN 3 is best described as which of the following?','["A. Full-thickness epithelial dysplasia without invasion","B. Dysplasia involving the lower two-thirds of the epithelium","C. Dysplasia confined to the lower third of the epithelium","D. Invasion through the basement membrane"]','A','CIN 3 (cervical intraepithelial neoplasia grade 3) encompasses severe dysplasia and carcinoma in situ — full-thickness epithelial involvement without stromal invasion. CIN 1 involves the lower third; CIN 2 the lower two-thirds.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Cervical Disease','easy','mcq','The transformation zone of the cervix is clinically important because it is the site where which process occurs?','["A. Squamous metaplasia occurs and CIN most commonly develops","B. Columnar epithelium replaces squamous epithelium permanently","C. Goblet cells appear following hormonal stimulation","D. Glandular dysplasia originates exclusively"]','A','The transformation zone (TZ) is where columnar endocervical epithelium meets squamous ectocervical epithelium. Squamous metaplasia occurs here, and this is the predominant site of HPV infection and CIN development. Pap smears specifically target this zone.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Cervical Disease','medium','mcq','A 32-year-old woman has a Pap smear showing high-grade squamous intraepithelial lesion (HSIL). Colposcopy-directed biopsy shows full-thickness dysplasia without basement membrane breach. What is the most appropriate management?','["A. Repeat Pap smear in 12 months","B. Loop electrosurgical excision procedure (LEEP)","C. Colposcopy and targeted biopsy only","D. Radical hysterectomy"]','B','HSIL on Pap smear corresponding to CIN 2/3 on biopsy requires excisional treatment. LEEP (loop electrosurgical excision procedure) removes the transformation zone and provides both treatment and tissue for histological diagnosis. Radical hysterectomy is reserved for invasive carcinoma.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Cervical Disease','medium','mcq','HPV E6 protein promotes carcinogenesis primarily by which mechanism?','["A. Activating telomerase directly","B. Phosphorylating the Rb protein","C. Inhibiting cyclin D1 transcription","D. Binding and degrading p53 via ubiquitin-mediated proteolysis"]','D','HPV E6 protein binds p53 and promotes its ubiquitin-mediated degradation, abrogating apoptosis and cell cycle arrest. HPV E7 targets the Rb protein (not E6). Together these two oncoproteins disrupt two major tumour suppressor pathways.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Cervical Disease','medium','mcq','A 45-year-old woman presents with postcoital bleeding. Colposcopy reveals an irregular lesion at the cervical os. Biopsy shows nests of malignant squamous cells invading the stroma. What is the most common histological type of invasive cervical cancer?','["A. Squamous cell carcinoma","B. Small cell carcinoma","C. Adenocarcinoma","D. Clear cell carcinoma"]','A','Squamous cell carcinoma accounts for approximately 70% of invasive cervical cancers. Adenocarcinoma (arising from endocervical glands) constitutes most of the remainder (~25%). Small cell and clear cell carcinomas are rare.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Cervical Disease','medium','mcq','Koilocytes on cervical cytology are pathognomonic of infection with which organism?','["A. Chlamydia trachomatis","B. Trichomonas vaginalis","C. Human papillomavirus","D. Herpes simplex virus"]','C','Koilocytes are squamous cells with perinuclear cytoplasmic clearing (halo) and nuclear enlargement/hyperchromasia. They are the cytopathic effect of HPV infection and their presence on Pap smear indicates HPV-related change (low-grade SIL/CIN 1).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Cervical Disease','hard','mcq','A 28-year-old woman has CIN 1 on biopsy following an ASCUS Pap smear. Which statement best describes the natural history of CIN 1?','["A. It invariably progresses to CIN 3 within 2 years","B. It has the same malignant potential as CIN 3","C. The majority regress spontaneously without treatment","D. Immediate LEEP is mandatory to prevent progression"]','C','CIN 1 (low-grade lesion) regresses spontaneously in approximately 60% of cases, persists in ~30%, and progresses to CIN 3 in only ~10%. It reflects transient or productive HPV infection. Management is conservative (repeat co-testing at 1 year), not immediate excision.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Cervical Disease','hard','mcq','Microinvasive cervical carcinoma (FIGO stage IA1) is defined as stromal invasion of no more than which depth?','["A. 1 mm","B. 5 mm","C. 3 mm","D. 7 mm"]','C','FIGO stage IA1 microinvasive cervical carcinoma is defined as stromal invasion ≤3 mm in depth and ≤7 mm in horizontal spread. This distinction is critical because IA1 has a very low risk of lymph node metastasis and may be managed conservatively with conisation.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Cervical Disease','hard','mcq','Which molecular alteration is most consistently found in cervical adenocarcinoma compared to squamous cell carcinoma of the cervix?','["A. Overexpression of p16INK4a due to Rb inactivation by HPV E7","B. Loss of BRCA1 expression","C. Activating KRAS mutation","D. Microsatellite instability"]','A','p16INK4a is a CDK inhibitor normally suppressed by Rb. When HPV E7 degrades Rb, p16 is upregulated as a compensatory feedback. Immunohistochemical p16 overexpression is a surrogate marker of high-risk HPV infection and is used diagnostically in both squamous and glandular cervical lesions.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed');

-- Subtopic 2: Endometrial Disease
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Endometrial Disease','easy','mcq','Endometrial carcinoma Type I is most strongly associated with which hormonal state?','["A. Progesterone excess","B. Prolactin excess","C. Androgen deficiency","D. Unopposed oestrogen stimulation"]','D','Type I endometrial carcinoma (endometrioid type) is oestrogen-driven. Unopposed oestrogen — from obesity (peripheral aromatisation), anovulation, oestrogen-secreting tumours, or exogenous oestrogen — drives endometrial hyperplasia and ultimately carcinoma. Progesterone is protective.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Endometrial Disease','easy','mcq','Which endometrial hyperplasia subtype carries the highest risk of progression to endometrial carcinoma?','["A. Simple hyperplasia without atypia","B. Complex hyperplasia without atypia","C. Atypical (complex) hyperplasia","D. Simple hyperplasia with atypia"]','C','Atypical hyperplasia (endometrial intraepithelial neoplasia) has the highest malignant potential — approximately 25–30% progress to carcinoma. Simple hyperplasia without atypia carries <1% risk; complex without atypia ~3%; simple with atypia ~8%.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Endometrial Disease','easy','mcq','Endometrial carcinoma Type II (serous type) is characterised by which molecular feature?','["A. PTEN mutation","B. TP53 mutation","C. Microsatellite instability","D. KRAS mutation"]','B','Type II endometrial carcinoma (uterine serous carcinoma) is oestrogen-independent, arises in atrophic endometrium in older women, and is characterised by TP53 mutations. It is histologically aggressive (papillary architecture) with poor prognosis. PTEN, MSI, and KRAS mutations typify Type I.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Endometrial Disease','medium','mcq','A 58-year-old obese postmenopausal woman presents with vaginal bleeding. Endometrial biopsy shows complex glands with back-to-back architecture, cribriform pattern, and cytological atypia invading the myometrium. What is the most likely diagnosis?','["A. Endometrial hyperplasia with atypia","B. Endometrioid carcinoma","C. Uterine serous carcinoma","D. Endometrial stromal sarcoma"]','B','This describes Type I endometrioid carcinoma: postmenopausal bleeding in an obese woman, complex glandular architecture with cribriform pattern, cytological atypia, and myometrial invasion. It arises in the background of endometrial hyperplasia driven by unopposed oestrogen.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Endometrial Disease','medium','mcq','Lynch syndrome (hereditary non-polyposis colorectal cancer) is associated with increased risk of which gynaecological malignancy?','["A. Ovarian clear cell carcinoma","B. Cervical squamous cell carcinoma","C. Endometrial carcinoma","D. Vulvar melanoma"]','C','Lynch syndrome (MLH1, MSH2, MSH6, PMS2 mismatch repair gene mutations) confers a lifetime risk of endometrial carcinoma of 40–60%, second only to colorectal cancer. Women with Lynch syndrome should undergo annual endometrial sampling from age 35.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Endometrial Disease','medium','mcq','Which tumour suppressor gene is most commonly mutated in Type I endometrial carcinoma?','["A. BRCA1","B. RB1","C. PTEN","D. APC"]','C','PTEN (phosphatase and tensin homolog) on chromosome 10q23 is mutated in up to 80% of Type I endometrioid endometrial carcinomas. PTEN normally inhibits the PI3K/AKT survival pathway; its loss promotes cell proliferation and survival.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Endometrial Disease','medium','mcq','Uterine serous carcinoma (Type II) differs from endometrioid carcinoma in which key feature?','["A. It occurs in younger, obese women","B. It always has a better prognosis","C. It arises from atrophic endometrium and is not oestrogen-dependent","D. It is associated with PTEN mutations"]','C','Type II uterine serous carcinoma arises in older, often thin postmenopausal women on a background of atrophic endometrium (not hyperplasia). It is not oestrogen-dependent, carries TP53 mutations, shows papillary/serous architecture, and has a significantly worse prognosis than Type I.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Endometrial Disease','hard','mcq','A 52-year-old woman on tamoxifen for breast cancer develops postmenopausal bleeding. Endometrial biopsy shows simple hyperplasia. Which statement best explains tamoxifen''s effect on the endometrium?','["A. Tamoxifen acts as a pure oestrogen antagonist in all tissues","B. Tamoxifen causes endometrial hyperplasia via progesterone receptor activation","C. Tamoxifen induces endometrial atrophy by blocking oestrogen receptors","D. Tamoxifen has partial oestrogen agonist activity in the endometrium, stimulating proliferation"]','D','Tamoxifen is a selective oestrogen receptor modulator (SERM) — it is an antagonist in breast tissue but a partial agonist in the endometrium. Long-term use increases the risk of endometrial polyps, hyperplasia, and carcinoma 2–3-fold. Any postmenopausal bleeding in a tamoxifen user warrants endometrial sampling.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Endometrial Disease','hard','mcq','Which histological finding distinguishes atypical endometrial hyperplasia from well-differentiated endometrioid carcinoma?','["A. Presence of mitotic figures","B. Cytological atypia of glandular cells","C. Stromal invasion (desmoplastic reaction or confluence of glands)","D. Back-to-back glandular crowding"]','C','The definitive criterion separating atypical hyperplasia from carcinoma is stromal invasion — either a desmoplastic stromal response or confluent/cribriform glandular growth replacing stroma. Cytological atypia, mitoses, and crowding may be seen in both; invasion is the carcinoma-defining feature.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Endometrial Disease','hard','mcq','A uterine tumour shows alternating hypercellular and hypocellular areas with spindle cells and thick-walled vessels, without significant atypia. What is the most likely diagnosis?','["A. Leiomyosarcoma","B. Endometrial stromal sarcoma","C. Carcinosarcoma (MMMT)","D. Adenomyosis"]','B','Low-grade endometrial stromal sarcoma (LG-ESS) shows tongue-like myometrial infiltration by cells resembling proliferative-phase endometrial stroma, with characteristic spiral arteriole-like vessels. It has low mitotic activity and mild atypia, unlike leiomyosarcoma (high mitoses, marked atypia) or carcinosarcoma (biphasic).','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed');

-- Subtopic 3: Ovarian Tumours
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Ovarian Tumours','easy','mcq','What is the most common type of ovarian tumour overall?','["A. Germ cell tumours","B. Surface epithelial tumours","C. Sex cord-stromal tumours","D. Metastatic tumours"]','B','Surface epithelial tumours (serous, mucinous, endometrioid, clear cell, transitional) account for approximately 65–70% of all ovarian tumours and 90% of ovarian malignancies. They arise from the coelomic epithelium covering the ovary.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Ovarian Tumours','easy','mcq','Which ovarian germ cell tumour is the most common and contains derivatives of all three germ layers?','["A. Dysgerminoma","B. Mature cystic teratoma (dermoid cyst)","C. Yolk sac tumour","D. Choriocarcinoma"]','B','Mature cystic teratoma (dermoid cyst) is the most common ovarian germ cell tumour, accounting for ~95% of germ cell tumours. It contains well-differentiated tissues from ectoderm (skin, hair, sebaceous glands), mesoderm, and endoderm. It is benign in >99% of cases.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Ovarian Tumours','easy','mcq','Psammoma bodies (laminated calcifications) are characteristically found in which ovarian tumour?','["A. Mucinous cystadenoma","B. Granulosa cell tumour","C. Mature teratoma","D. Serous cystadenocarcinoma"]','D','Psammoma bodies — concentric calcified laminations — are characteristic of serous ovarian tumours, particularly serous papillary cystadenocarcinoma. They also occur in serous borderline tumours. They result from dystrophic calcification in papillary fronds and necrotic tumour cells.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Ovarian Tumours','medium','mcq','A 25-year-old woman presents with signs of androgen excess (hirsutism, virilisation). Pelvic ultrasound shows a solid ovarian mass. Histology reveals cells in cords and nests with pale cytoplasm (Call-Exner bodies). What is the most likely diagnosis?','["A. Sertoli-Leydig cell tumour","B. Thecoma","C. Granulosa cell tumour","D. Dysgerminoma"]','C','Granulosa cell tumours are sex cord-stromal tumours that may secrete oestrogen (causing precocious puberty or endometrial hyperplasia) or, less commonly, androgens. Call-Exner bodies — small follicle-like structures with eosinophilic material — are pathognomonic. The adult type predominates and has a good prognosis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Ovarian Tumours','medium','mcq','A 35-year-old woman with oligomenorrhoea and hirsutism has bilateral enlarged ovaries with multiple small follicular cysts on ultrasound. Laboratory findings show elevated LH:FSH ratio and hyperinsulinaemia. What is the pathological ovarian finding?','["A. Multiple haemorrhagic corpora lutea","B. Bilateral serous cystadenomas","C. Cortical stromal hyperthecosis with multiple subcapsular follicular cysts","D. Bilateral mature teratomas"]','C','Polycystic ovarian syndrome (PCOS) shows bilaterally enlarged ovaries with a thickened fibrous cortex and multiple subcortical follicular cysts (2–8 mm). Histologically there is stromal hyperthecosis and luteinised theca interna cells. The elevated LH:FSH ratio drives androgen excess.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Ovarian Tumours','medium','mcq','Krukenberg tumour refers to which pathological entity?','["A. Primary mucinous carcinoma of the ovary","B. Bilateral granulosa cell tumours","C. Metastatic mucin-secreting carcinoma to the ovary with signet-ring cells","D. Bilateral mature teratomas"]','C','Krukenberg tumour is a metastatic mucin-secreting adenocarcinoma to the ovary (most commonly from the stomach, but also colon, breast, appendix). It is characterised by signet-ring cells (mucin-distended nucleus-displacing cells) within a cellular ovarian stroma. It is typically bilateral.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Ovarian Tumours','medium','mcq','Which gene mutation is most commonly associated with high-grade serous ovarian carcinoma in hereditary cases?','["A. BRCA1 or BRCA2","B. PTEN","C. MLH1","D. TP53 somatic only"]','A','Germline BRCA1 (chromosome 17q) or BRCA2 (chromosome 13q) mutations account for 10–15% of ovarian cancers, predominantly high-grade serous carcinoma. Lifetime ovarian cancer risk is 40–50% for BRCA1 and 15–25% for BRCA2. TP53 somatic mutation is nearly universal in high-grade serous carcinoma.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Ovarian Tumours','hard','mcq','A 22-year-old woman has a rapidly growing ovarian mass. AFP is markedly elevated. Histology shows a reticular/lacy pattern with Schiller-Duval bodies (perivascular glomeruloid structures). What is the diagnosis?','["A. Yolk sac tumour (endodermal sinus tumour)","B. Immature teratoma","C. Dysgerminoma","D. Embryonal carcinoma"]','A','Yolk sac tumour (endodermal sinus tumour) is the second most common malignant germ cell tumour in young women. It produces AFP (alpha-fetoprotein), which serves as a tumour marker. Pathognomonic are Schiller-Duval bodies — glomeruloid structures with a central vessel surrounded by tumour cells within a space.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Ovarian Tumours','hard','mcq','Mucinous ovarian tumours are distinguished from serous tumours in which key pathological feature?','["A. Mucinous tumours contain goblet cells and tall columnar mucin-secreting epithelium resembling intestinal or endocervical type","B. Mucinous tumours are always bilateral while serous are unilateral","C. Serous tumours produce CA-125 while mucinous tumours produce CEA only","D. Mucinous tumours exclusively arise from germ cells"]','A','Mucinous ovarian tumours are lined by tall columnar mucin-secreting epithelium resembling endocervical (Mullerian) or intestinal epithelium (with goblet cells). They are typically large, multilocular, unilateral cysts. Serous tumours mimic fallopian tube epithelium with cilia. Both may produce CA-125.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Ovarian Tumours','hard','mcq','Pseudomyxoma peritonei is most commonly associated with rupture of which tumour?','["A. Ovarian serous cystadenocarcinoma","B. Ovarian mucinous tumour or low-grade appendiceal mucinous neoplasm","C. Uterine leiomyosarcoma","D. Ovarian mature teratoma"]','B','Pseudomyxoma peritonei (gelatinous ascites with mucin-secreting implants filling the peritoneal cavity) is most commonly caused by a low-grade appendiceal mucinous neoplasm (LAMN) seeding the peritoneum, often with concurrent ovarian mucinous tumour involvement. Pure primary ovarian origin is now considered rare.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed');

-- Subtopic 4: Uterine Pathology
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Uterine Pathology','easy','mcq','Leiomyomas (fibroids) of the uterus are characterised by which histological feature?','["A. Marked nuclear pleomorphism and tumour cell necrosis","B. High mitotic rate exceeding 10 per 10 HPF","C. Intersecting fascicles of smooth muscle cells without significant atypia or necrosis","D. Infiltrative growth pattern destroying adjacent myometrium"]','C','Leiomyomas are benign smooth muscle tumours showing well-circumscribed whorled fascicles of bland smooth muscle cells with cigar-shaped nuclei. They have rare mitoses (<4/10 HPF), no significant atypia, and no coagulative tumour cell necrosis — features that distinguish them from leiomyosarcoma.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Uterine Pathology','easy','mcq','Adenomyosis is defined as which pathological finding?','["A. Endometrial tissue on the ovarian surface","B. Endometrial glands and stroma within the myometrium","C. Endometrial glands replacing the cervical epithelium","D. Ectopic endometrium within the fallopian tube lumen"]','B','Adenomyosis is the presence of endometrial glands and stroma within the myometrium (>2.5 mm from the basalis layer). It causes a diffusely enlarged, globular uterus (uterine junctional zone thickening >12 mm on MRI). Symptoms include dysmenorrhoea and menorrhagia.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Uterine Pathology','easy','mcq','Endometriosis most commonly affects which anatomical site?','["A. Ovaries","B. Appendix","C. Bladder","D. Umbilicus"]','A','Endometriosis most commonly involves the ovaries (in ~60% of cases), where it forms chocolate cysts (endometriomas) filled with dark haemorrhagic fluid. Other common sites include the pouch of Douglas, uterosacral ligaments, fallopian tubes, and pelvic peritoneum.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Uterine Pathology','medium','mcq','A 35-year-old woman has progressively worsening dysmenorrhoea, dyspareunia, and infertility. Laparoscopy reveals powder-burn lesions on the peritoneum and chocolate-coloured ovarian cysts. Biopsy of peritoneal implants shows endometrial glands, stroma, and haemosiderin-laden macrophages. What is the pathogenesis most supported by evidence?','["A. Coelomic metaplasia of peritoneal mesothelium","B. Haematogenous dissemination of endometrial cells","C. Retrograde menstruation and implantation of viable endometrial cells","D. Lymphatic spread from uterine adenomyosis"]','C','The retrograde menstruation (Sampson) theory is best supported: viable endometrial cells reflux through the fallopian tubes during menstruation and implant on pelvic peritoneum. Supporting evidence includes the prevalence of endometriosis in outflow-obstructed women and viability of shed endometrial cells.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Uterine Pathology','medium','mcq','Leiomyosarcoma differs from leiomyoma by which histological criteria?','["A. Presence of smooth muscle differentiation","B. Intramural location within the uterus","C. High mitotic count (>10/10 HPF), significant cytological atypia, and tumour cell necrosis","D. Response to GnRH analogue therapy"]','C','Leiomyosarcoma is diagnosed when at least 2 of 3 features are present: coagulative tumour cell necrosis, significant cytological atypia, and mitotic count >10/10 HPF. In the presence of all three, the diagnosis is unequivocal. It has a poor prognosis with 5-year survival <50%.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Uterine Pathology','medium','mcq','Leiomyomas are known to undergo various degenerative changes. Which type of degeneration is most common and appears as gelatinous softening?','["A. Red (carneous) degeneration","B. Calcific degeneration","C. Cystic degeneration","D. Hyaline degeneration"]','D','Hyaline degeneration is the most common degenerative change in leiomyomas, occurring in up to 65%. Collagen replaces smooth muscle, giving a white, glassy appearance. Red (carneous) degeneration occurs during pregnancy due to rapid growth outstripping blood supply and presents with acute pelvic pain.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Uterine Pathology','medium','mcq','A 38-year-old woman with endometriosis has infertility. Which mechanism best explains endometriosis-associated infertility?','["A. Premature ovarian failure from autoimmune destruction","B. Increased progesterone secretion from ectopic foci","C. Peritubal adhesions, altered peritoneal fluid environment, and impaired embryo implantation","D. Cervical stenosis from implants"]','C','Endometriosis impairs fertility through multiple mechanisms: peritubal and periovarian adhesions disrupting ovum pickup; altered peritoneal fluid (elevated prostaglandins, proteases, macrophages) impairing sperm function; endometriomas reducing ovarian reserve; and impaired endometrial receptivity.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Uterine Pathology','hard','mcq','A 42-year-old woman has a uterine mass. Histology shows smooth muscle cells with >10 mitoses/10 HPF but no cytological atypia and no tumour cell necrosis. How is this classified?','["A. Smooth muscle tumour of uncertain malignant potential (STUMP)","B. Leiomyosarcoma","C. Leiomyoma","D. Cellular leiomyoma"]','A','Smooth muscle tumour of uncertain malignant potential (STUMP) is diagnosed when histological criteria for benign leiomyoma and malignant leiomyosarcoma are not clearly met. High mitotic count alone, without atypia or necrosis, falls into this indeterminate category. These tumours require long-term surveillance.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Uterine Pathology','hard','mcq','Endometriosis implants appear as "powder burns" or "gunshot lesions" laparoscopically. Microscopically, the minimum diagnostic criteria require which finding?','["A. Haemosiderin-laden macrophages alone","B. Endometrial glands AND stroma in an ectopic location","C. Endometrial glands OR stroma (both not required) with haemosiderin","D. Peritoneal fibrosis with haemosiderin"]','B','The histological diagnosis of endometriosis requires the presence of both endometrial-type glands AND stroma in an ectopic location. Haemosiderin-laden macrophages and evidence of old haemorrhage support the diagnosis but are not sufficient alone. This criterion distinguishes endometriosis from endosalpingiosis or peritoneal fibrosis.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Uterine Pathology','hard','mcq','Which receptor status is primarily responsible for leiomyoma growth and explains their regression after menopause?','["A. Androgen receptor upregulation","B. HER2 overexpression","C. EGF receptor amplification","D. Oestrogen and progesterone receptor overexpression compared to normal myometrium"]','D','Leiomyomas express higher levels of oestrogen and progesterone receptors than surrounding myometrium. Both hormones promote growth — oestrogen increases receptor expression, progesterone drives mitosis. This explains growth during reproductive years and regression after menopause or with GnRH agonist therapy (medical menopause).','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed');

-- Subtopic 5: Gestational Trophoblastic Disease
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Gestational Trophoblastic Disease','easy','mcq','Which feature distinguishes a complete hydatidiform mole from a partial hydatidiform mole?','["A. Complete moles have a 69,XXX or 69,XXY karyotype while partial moles are 46,XX","B. Partial moles have higher risk of malignant transformation","C. Complete moles are 46,XX (or 46,XY) with no fetal tissue; partial moles are triploid with fetal parts","D. Complete moles result from fertilisation of a normal ovum by two sperm"]','C','Complete moles: 46,XX (androgenetic diploid — two paternal genomes, no maternal contribution); no fetal/embryonic tissue; all villi hydropic with diffuse trophoblastic hyperplasia. Partial moles: 69,XXX or 69,XXY (triploid); fetal/embryonic tissue present; focal villous hydrops. Malignant transformation risk is higher in complete moles (15–20% vs 1–5%).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Gestational Trophoblastic Disease','easy','mcq','Which tumour marker is used to diagnose and monitor gestational trophoblastic disease?','["A. AFP","B. CA-125","C. CEA","D. Beta-hCG"]','D','Beta-human chorionic gonadotrophin (beta-hCG) is produced by trophoblastic tissue and is the definitive marker for GTD. It is used for diagnosis, monitoring response to treatment, and detecting recurrence. In normal pregnancy hCG peaks at 10–12 weeks; markedly elevated levels disproportionate to gestational age suggest molar pregnancy.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Gestational Trophoblastic Disease','easy','mcq','A patient with a complete hydatidiform mole undergoes uterine evacuation. Histology shows grape-like vesicles with hydropic villi and circumferential trophoblastic hyperplasia. What is the characteristic ultrasound appearance before evacuation?','["A. Twin pregnancy with one normal and one abnormal sac","B. Snowstorm appearance with no fetal parts","C. Fetal hydrops with placentomegaly","D. Bilateral ovarian masses only"]','B','Complete hydatidiform mole has the classic "snowstorm" appearance on ultrasound — a uterus filled with echogenic material (hydropic villi) without an identifiable embryo or gestational sac. Bilateral theca-lutein cysts (from hCG overstimulation) may be seen on the ovaries.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Gestational Trophoblastic Disease','medium','mcq','A 26-year-old woman presents with haemoptysis 6 months after evacuation of a complete mole. Serum beta-hCG is markedly elevated. Chest X-ray shows multiple "cannonball" pulmonary metastases. What is the most likely diagnosis?','["A. Invasive mole","B. Placental site trophoblastic tumour","C. Gestational choriocarcinoma","D. Epithelioid trophoblastic tumour"]','C','Gestational choriocarcinoma is a highly malignant trophoblastic tumour characterised by sheets of cytotrophoblasts and syncytiotrophoblasts without chorionic villi. It metastasises haematogenously (lungs — "cannonball" metastases, brain, liver). Despite widespread metastases, it is highly chemosensitive; cure rates >90% with combination chemotherapy.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Gestational Trophoblastic Disease','medium','mcq','Complete hydatidiform moles most commonly arise from which mechanism?','["A. Normal ovum fertilised by two sperm (dispermy)","B. Fertilisation of an ovum with two female pronuclei","C. Normal fertilisation followed by meiotic error","D. Enucleate ovum fertilised by one sperm that duplicates (monospermy), or by two sperm (dispermy)"]','D','Complete moles most commonly arise from an enucleate (empty) ovum fertilised by a single sperm that then duplicates (giving 46,XX — most common, ~90%) or by two sperm (46,XX or 46,XY). All genetic material is paternal (androgenesis). There is no maternal contribution.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Gestational Trophoblastic Disease','medium','mcq','After evacuation of a complete mole, which hCG monitoring pattern indicates malignant transformation requiring chemotherapy?','["A. hCG falls to undetectable within 2 weeks","B. hCG remains elevated for 2 weeks post-evacuation","C. hCG halves every 2 weeks","D. hCG plateau for 3 consecutive weeks or rises over 2 consecutive weeks"]','D','Post-molar GTN is diagnosed by: hCG plateau (±10%) for ≥3 consecutive weekly values over 3 weeks; hCG rise (>10%) over 3 values in 2 weeks; persistence of hCG at 6 months post-evacuation; or histological choriocarcinoma. Prompt chemotherapy (single-agent methotrexate or actinomycin-D for low-risk) achieves near-100% cure.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Gestational Trophoblastic Disease','medium','mcq','Theca-lutein cysts, a complication of molar pregnancy, are caused by which mechanism?','["A. Oestrogen stimulation of the ovarian cortex","B. Progesterone excess causing follicular retention","C. Markedly elevated hCG stimulating FSH receptors on theca cells","D. Direct trophoblastic invasion of ovarian tissue"]','C','Theca-lutein cysts (bilateral, multi-locular, benign) develop in ~25–30% of complete moles due to massive hCG overstimulation of ovarian theca cells via LH/hCG receptors, causing luteinisation and cyst formation. They resolve spontaneously after mole evacuation and hCG decline. They should not be surgically removed.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Gestational Trophoblastic Disease','hard','mcq','Choriocarcinoma histologically differs from a hydatidiform mole in which critical feature?','["A. Presence of syncytiotrophoblasts in choriocarcinoma only","B. Absence of chorionic villi in choriocarcinoma","C. Choriocarcinoma exclusively contains cytotrophoblasts","D. Molar tissue shows more haemorrhage than choriocarcinoma"]','B','Choriocarcinoma is composed of sheets of anaplastic cytotrophoblasts and syncytiotrophoblasts with extensive haemorrhage and necrosis, but NO chorionic villi. Molar tissue always contains villi (even invasive mole). The absence of villi is a key histological criterion for diagnosing choriocarcinoma.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Gestational Trophoblastic Disease','hard','mcq','Placental site trophoblastic tumour (PSTT) differs from choriocarcinoma in which characteristic?','["A. PSTT is composed of intermediate trophoblasts, produces human placental lactogen (hPL), and is relatively chemoresistant","B. PSTT produces high levels of beta-hCG while choriocarcinoma produces low levels","C. PSTT always follows a molar pregnancy","D. PSTT metastasises more commonly to the lungs than choriocarcinoma"]','A','Placental site trophoblastic tumour (PSTT) arises from intermediate trophoblasts at the implantation site. It produces human placental lactogen (hPL) rather than large amounts of hCG. Unlike choriocarcinoma, it is relatively resistant to chemotherapy; hysterectomy is the treatment of choice. It has a better prognosis if confined to the uterus.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Gestational Trophoblastic Disease','hard','mcq','A woman is diagnosed with invasive mole following incomplete regression of hCG after molar evacuation. How does invasive mole differ from choriocarcinoma histologically?','["A. Invasive mole contains no trophoblastic tissue","B. Invasive mole retains hydropic chorionic villi that invade the myometrium","C. Invasive mole lacks syncytiotrophoblasts","D. Invasive mole is diploid while choriocarcinoma is aneuploid"]','B','Invasive mole (chorioadenoma destruens) retains identifiable hydropic chorionic villi that invade the myometrium and may perforate the uterus or embolise to distant sites (lungs, vagina). In contrast, choriocarcinoma has no villi — only sheets of malignant trophoblasts. Both respond well to chemotherapy.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed');

-- Subtopic 6: Breast Disease
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Breast Disease','easy','mcq','Fibroadenoma of the breast is most common in which demographic group?','["A. Postmenopausal women over 60","B. Women aged 20–35 years","C. Adolescent girls under 15","D. Men with gynaecomastia"]','B','Fibroadenoma is the most common benign breast tumour, typically occurring in women aged 20–35. It presents as a well-circumscribed, mobile, rubbery "breast mouse." Histologically it shows a biphasic proliferation of epithelium and stroma. It is oestrogen-sensitive and may enlarge during pregnancy.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Breast Disease','easy','mcq','Which is the most common form of breast cancer?','["A. Invasive ductal carcinoma (no special type)","B. Invasive lobular carcinoma","C. Lobular carcinoma in situ","D. Mucinous carcinoma"]','A','Invasive ductal carcinoma of no special type (NST) — also called infiltrating ductal carcinoma — accounts for approximately 70–80% of all invasive breast cancers. It typically presents as a hard, irregular, spiculated mass with desmoplastic stroma. It lacks the specific features that define special subtypes.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Breast Disease','easy','mcq','BRCA1 gene mutations are most strongly associated with which subtype of breast cancer?','["A. Hormone receptor-positive luminal A subtype","B. HER2-amplified subtype","C. Triple-negative (basal-like) breast cancer","D. Mucinous breast carcinoma"]','C','BRCA1-associated breast cancers are predominantly triple-negative (ER-negative, PR-negative, HER2-negative) and of high grade with medullary features. BRCA2 mutations more commonly give ER-positive tumours. Triple-negative breast cancer is generally more aggressive with limited targeted treatment options.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Breast Disease','medium','mcq','A 45-year-old woman has microcalcifications on mammography. Core biopsy shows a duct filled with pleomorphic cells showing central necrosis (comedo-type). No basement membrane breach is identified. What is the diagnosis?','["A. Ductal carcinoma in situ (DCIS) — comedo type","B. Invasive ductal carcinoma","C. Lobular carcinoma in situ","D. Atypical ductal hyperplasia"]','A','Comedo-type DCIS is characterised by high-grade pleomorphic cells filling and distending ducts with central comedonecrosis. The necrotic debris calcifies, producing the microcalcifications visible on mammography. Absence of basement membrane breach distinguishes it from invasive carcinoma.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Breast Disease','medium','mcq','Invasive lobular carcinoma of the breast is characterised by which histological pattern?','["A. Single-file (Indian file) arrangement of cells with signet-ring morphology infiltrating stroma","B. Comedo necrosis within ducts","C. Large sheets of cells with prominent nucleoli","D. Papillary architecture with fibrovascular cores"]','A','Invasive lobular carcinoma (ILC) shows neoplastic cells arranged in single files (Indian file pattern) or concentric rings (targetoid pattern) around ducts, infiltrating the stroma without a desmoplastic response. Cells are small, uniform, and often have signet-ring morphology due to intracytoplasmic mucin. Loss of E-cadherin is pathognomonic.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Breast Disease','medium','mcq','Fibrocystic change of the breast is most commonly associated with which histological features?','["A. Cyst formation, apocrine metaplasia, adenosis, and epithelial hyperplasia","B. Stromal fibrosis only with no epithelial changes","C. Lobular carcinoma in situ with pagetoid spread","D. Comedo necrosis within enlarged ducts"]','A','Fibrocystic change encompasses: (1) cyst formation — macro- and microcysts lined by flattened or apocrine metaplastic epithelium; (2) adenosis — increased number of acini per lobule; (3) fibrosis; (4) epithelial hyperplasia. Most changes are non-proliferative (no increased cancer risk) unless atypical hyperplasia is present.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Breast Disease','medium','mcq','Paget''s disease of the nipple indicates which underlying pathology?','["A. Paget''s disease of bone metastasising to the breast","B. Intraepidermal spread of DCIS or invasive carcinoma cells along the nipple epidermis","C. Inflammatory breast carcinoma involving the nipple dermis","D. Benign squamous metaplasia of the nipple ducts"]','B','Paget''s disease of the nipple presents as eczematous/erythematous nipple changes. Large, pale Paget cells (malignant adenocarcinoma cells) permeate the nipple epidermis. It nearly always indicates underlying DCIS or invasive carcinoma. Biopsy showing intraepidermal carcinoma cells (PAS-positive, mucin-containing) is diagnostic.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Breast Disease','hard','mcq','HER2 (ERBB2) gene amplification in breast cancer is clinically significant because it predicts response to which targeted therapy?','["A. Tamoxifen (selective oestrogen receptor modulator)","B. CDK4/6 inhibitors (palbociclib)","C. Aromatase inhibitors (letrozole, anastrozole)","D. Trastuzumab (Herceptin — anti-HER2 monoclonal antibody)"]','D','HER2 amplification/overexpression (present in ~15–20% of breast cancers) predicts response to trastuzumab (anti-HER2 monoclonal antibody) and pertuzumab. HER2-positive cancers have worse prognosis without targeted therapy but respond dramatically to anti-HER2 agents. HER2 status is determined by IHC and FISH.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Breast Disease','hard','mcq','Lobular carcinoma in situ (LCIS) differs from DCIS in which critical way that influences clinical management?','["A. LCIS is an obligate precursor requiring immediate excision; DCIS is a risk marker","B. LCIS is a risk marker for bilateral breast cancer but not an obligate precursor; DCIS is a direct precursor requiring excision","C. LCIS is detectable on mammography; DCIS is not","D. LCIS has a higher grade than DCIS"]','B','LCIS is a proliferation of small, discohesive cells within lobules (E-cadherin negative). It is an incidental histological finding (not detectable on imaging), indicates 8–10x increased bilateral breast cancer risk, and is managed with risk reduction strategies (surveillance/chemoprevention), not excision. DCIS is a direct precursor requiring surgical excision.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Breast Disease','hard','mcq','Which histological feature of invasive breast carcinoma is used in the Nottingham (Elston-Ellis) grading system?','["A. Tubule formation, nuclear pleomorphism, and mitotic count","B. Tumour size, lymph node status, and ER status","C. Lymphovascular invasion, perineural invasion, and necrosis","D. HER2 status, Ki-67 index, and histological subtype"]','A','The Nottingham grading system scores three features, each 1–3: (1) tubule/gland formation; (2) nuclear pleomorphism; (3) mitotic count. Total score: Grade 1 (well differentiated, 3–5), Grade 2 (moderately differentiated, 6–7), Grade 3 (poorly differentiated, 8–9). Grade is an independent prognostic factor.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed');

-- Subtopic 7: Pregnancy Complications — Early
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Early','easy','mcq','The most common site for ectopic pregnancy is which anatomical location?','["A. Ovary","B. Ampulla of the fallopian tube","C. Cervix","D. Interstitial portion of the fallopian tube"]','B','Approximately 70% of ectopic pregnancies occur in the ampulla of the fallopian tube. The isthmus accounts for ~12%, fimbria ~11%, and ovarian/cervical/abdominal sites the remainder. Ampullary ectopics typically present at 6–8 weeks with acute haemoperitoneum if they rupture.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Early','easy','mcq','Which is the most common cause of first-trimester miscarriage?','["A. Chromosomal abnormality in the conceptus","B. Uterine anatomical abnormality","C. Antiphospholipid syndrome","D. Cervical incompetence"]','A','Approximately 50–60% of first-trimester spontaneous abortions are caused by chromosomal abnormalities in the conceptus, most commonly trisomies (trisomy 16 being most frequent), followed by monosomy X and triploidy. Maternal uterine/immune causes are more common in recurrent pregnancy loss.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Early','easy','mcq','Chronic salpingitis (pelvic inflammatory disease) predisposes to ectopic pregnancy by which mechanism?','["A. Increased tubal peristalsis propelling the blastocyst into the tube","B. Tubal scarring and ciliary dysfunction impairing blastocyst transport to the uterus","C. Oestrogen excess preventing endometrial implantation","D. Progesterone deficiency causing premature corpus luteum failure"]','B','PID-related salpingitis causes peritubal adhesions and intraluminal scarring with ciliary damage, impairing normal transport of the fertilised ovum through the fallopian tube. The blastocyst implants in the damaged tube rather than reaching the endometrial cavity, resulting in ectopic pregnancy.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Early','medium','mcq','A 28-year-old woman with a history of PID presents with 7 weeks amenorrhoea, unilateral pelvic pain, and vaginal bleeding. Beta-hCG is 1800 IU/L but transvaginal ultrasound shows no intrauterine gestational sac. What is the most likely diagnosis?','["A. Threatened miscarriage","B. Ectopic pregnancy","C. Complete miscarriage","D. Molar pregnancy"]','B','An hCG level >1500–2000 IU/L (the discriminatory zone) should reliably show an intrauterine gestational sac on TVUS if intrauterine. Absence of an IU sac with hCG above this level, combined with PID history and symptoms, strongly suggests ectopic pregnancy. Haemoperitoneum may be present on ultrasound.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Early','medium','mcq','Blighted ovum (anembryonic pregnancy) is characterised by which finding?','["A. Fetal heartbeat absent at 12 weeks","B. Empty gestational sac >25 mm without an embryo on transvaginal ultrasound","C. hCG rising slower than expected for gestational age","D. Partial mole with triploidy"]','B','A blighted ovum (anembryonic pregnancy) occurs when a gestational sac develops but the embryo fails to form or stops developing very early. TVUS criteria: mean gestational sac diameter >25 mm with no embryo. Chromosomal abnormalities are the most common cause.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Early','medium','mcq','The Arias-Stella reaction of the endometrium occurs in the setting of ectopic pregnancy. Which histological appearance characterises this reaction?','["A. Decidualised stroma with hypertrophied endometrial glands showing hypersecretory pattern and nuclear atypia","B. Atrophic glands with stromal fibrosis","C. Acute inflammatory infiltrate with glandular destruction","D. Squamous metaplasia of endometrial glands"]','A','The Arias-Stella reaction is a hypersecretory endometrial change with enlarged, hyperchromatic nuclei and hobnail cells in glands, occurring in response to elevated hCG (including ectopic pregnancy, molar pregnancy, or normal IUP). It can mimic clear cell carcinoma but is a reactive, benign change.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Early','medium','mcq','Which of the following is NOT a recognised risk factor for ectopic pregnancy?','["A. Previous ectopic pregnancy","B. Use of combined oral contraceptive pill","C. Previous salpingitis","D. In vitro fertilisation (IVF)"]','B','Risk factors for ectopic pregnancy include: previous ectopic, PID/salpingitis, tubal surgery, intrauterine device use, IVF, and endometriosis. Combined oral contraceptive pill (COCP) actually reduces the risk of ectopic pregnancy by preventing ovulation altogether. IUDs reduce absolute risk of ectopic but increase relative risk if pregnancy occurs.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Early','hard','mcq','Antiphospholipid syndrome causes recurrent pregnancy loss primarily through which pathological mechanism?','["A. Chromosomal segregation errors during meiosis","B. Endometrial NK cell over-activation","C. Uterine cavity distortion from submucous fibroids","D. Placental thrombosis and infarction due to antiphospholipid antibody-mediated hypercoagulability"]','D','Antiphospholipid syndrome (anticardiolipin antibodies, anti-beta2-glycoprotein I, lupus anticoagulant) causes recurrent pregnancy loss predominantly through thrombosis of decidual and uteroplacental vessels, causing placental infarction and fetal death, typically in the second trimester. Treatment with heparin + aspirin significantly improves outcomes.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Early','hard','mcq','A curettage specimen from a suspected miscarriage shows decidua but no chorionic villi. What is the most important next step?','["A. Reassure the patient that the pregnancy has completely passed","B. Administer methotrexate empirically","C. Repeat the curettage immediately","D. Measure serum hCG to exclude ectopic pregnancy"]','D','Absence of chorionic villi in curettage specimen may indicate: complete passage of products before curettage, or more critically, an ectopic pregnancy (the curettage removed decidua from an intrauterine decidual reaction, not the actual pregnancy). Serum hCG must be checked urgently; if rising or plateauing, ectopic pregnancy must be excluded by TVUS and clinical assessment.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Early','hard','mcq','Septate uterus is associated with recurrent pregnancy loss due to which mechanism?','["A. Increased uterine vascularity causing early haemorrhage","B. Cervical incompetence from septal traction","C. Poor blood supply to the avascular fibromuscular septum impairing implantation and placentation","D. Obstruction of fallopian tube ostia"]','C','The uterine septum is composed of fibromuscular tissue with poor vascularity. When implantation occurs on the septum, inadequate blood supply impairs placentation and trophoblast invasion, leading to early pregnancy loss. Hysteroscopic septoplasty significantly reduces recurrent miscarriage rates in women with septate uterus.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed');

-- Subtopic 8: Pregnancy Complications — Late
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Late','easy','mcq','Pre-eclampsia is defined as which combination of findings after 20 weeks gestation?','["A. Hypertension alone (>140/90 mmHg)","B. Convulsions with elevated blood pressure","C. Proteinuria alone with oedema","D. Hypertension plus proteinuria (>300 mg/24h) and/or end-organ dysfunction"]','D','Pre-eclampsia is defined as new-onset hypertension (BP ≥140/90 mmHg on two occasions 4h apart) after 20 weeks gestation WITH proteinuria (≥300 mg/24h or PCR ≥30 mg/mmol) or evidence of end-organ dysfunction (renal, hepatic, neurological, haematological impairment). Eclampsia = pre-eclampsia + seizures.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Late','easy','mcq','Placenta praevia is defined as which condition?','["A. Placenta implanted in the lower uterine segment, partially or completely covering the internal cervical os","B. Premature separation of a normally situated placenta","C. Placenta accreta with invasion of the myometrium","D. Placental abruption with retroplacental haematoma"]','A','Placenta praevia describes a placenta that implants in the lower uterine segment, overlying or adjacent to the internal cervical os. It presents with painless antepartum haemorrhage in the third trimester. Digital vaginal examination is contraindicated. It is a leading cause of antepartum haemorrhage.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Late','easy','mcq','HELLP syndrome is a severe variant of pre-eclampsia characterised by which triad?','["A. Hypertension, elevated liver enzymes, low platelets","B. Hypertension, elevated lipids, low platelets","C. Haemolysis, elevated lipids, low protein","D. Haemolysis, elevated liver enzymes, low platelets"]','D','HELLP syndrome: H = Haemolysis (microangiopathic haemolytic anaemia); EL = Elevated Liver enzymes; LP = Low Platelets. It is a life-threatening complication of severe pre-eclampsia characterised by hepatic infarction and subcapsular haematoma. Delivery is the definitive treatment.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Late','medium','mcq','A 32-year-old primigravida at 36 weeks presents with sudden onset severe abdominal pain, vaginal bleeding, and a rigid tender uterus. The fetal heartbeat is absent. What is the most likely diagnosis?','["A. Placenta praevia","B. Placental abruption","C. Uterine rupture","D. Vasa praevia"]','B','Placental abruption (abruptio placentae) is premature separation of a normally sited placenta before delivery. It presents with painful antepartum haemorrhage, uterine rigidity (concealed haemorrhage behind the placenta), and fetal distress or death. Retroplacental haematoma is the pathological finding.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Late','medium','mcq','The underlying pathological mechanism of pre-eclampsia involves failure of which process?','["A. Adequate hCG secretion by the syncytiotrophoblast","B. Maternal immune tolerance of paternal antigens in the decidua","C. Progesterone production by the corpus luteum","D. Normal trophoblastic invasion of spiral arteries, resulting in high-resistance uteroplacental circulation"]','D','In normal pregnancy, extravillous trophoblasts invade and remodel the spiral arteries, replacing muscular/elastic vessel walls with fibrinoid material, creating high-flow, low-resistance uteroplacental circulation. In pre-eclampsia, this invasion fails (shallow trophoblastic invasion), maintaining high-resistance vessels, causing uteroplacental ischaemia, placental oxidative stress, and release of antiangiogenic factors (sFlt-1) into maternal circulation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Late','medium','mcq','Acute fatty liver of pregnancy (AFLP) is a life-threatening condition caused by which mechanism?','["A. Mitochondrial beta-oxidation defect (LCHAD deficiency) causing microvesicular fatty infiltration of hepatocytes","B. Excess glycogen deposition in hepatocytes","C. Pre-existing viral hepatitis B reactivation","D. Intrahepatic cholestasis from oestrogen excess"]','A','AFLP results from impaired mitochondrial fatty acid beta-oxidation, often in women carrying a fetus with long-chain 3-hydroxyacyl-CoA dehydrogenase (LCHAD) deficiency. Fatty acids accumulate in hepatocytes (microvesicular steatosis). It presents in the third trimester with nausea, vomiting, jaundice, and liver failure. Urgent delivery is life-saving.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Late','medium','mcq','Placenta accreta is defined as which condition and what is its most significant risk factor?','["A. Abnormal placental adherence to the myometrium without intervening decidua; risk factor: previous uterine scar (caesarean section)","B. Placenta covering the os; risk factor: multiparity","C. Placental separation before labour; risk factor: hypertension","D. Succenturiate placental lobe; risk factor: advanced maternal age"]','A','Placenta accreta occurs when chorionic villi attach directly to the myometrium (lacking the normal decidua basalis), preventing normal placental separation. Placenta increta = invades myometrium; percreta = penetrates through serosa. The primary risk factor is previous uterine scar (C-section + placenta praevia = >60% risk of accreta).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Late','hard','mcq','Fibrin deposits in glomerular capillaries ("glomerular endotheliosis") are the characteristic renal biopsy finding in which condition?','["A. Diabetic nephropathy in pregnancy","B. IgA nephropathy","C. Lupus nephritis flare during pregnancy","D. Pre-eclampsia"]','D','Glomerular endotheliosis is pathognomonic of pre-eclampsia on renal biopsy: swollen endothelial cells obliterating capillary lumina with subendothelial fibrin deposits, giving a bloodless glomerulus appearance. This results from the antiangiogenic state (elevated sFlt-1, reduced PlGF) causing endothelial injury.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Late','hard','mcq','Disseminated intravascular coagulation (DIC) can complicate placental abruption by which mechanism?','["A. Maternal hypertension causing platelet activation","B. Uterine hypoxia causing factor XII activation","C. Fetal blood entering the maternal circulation via the Kleihauer-Betke mechanism","D. Release of placental thromboplastin (tissue factor) into the maternal circulation activating the coagulation cascade"]','D','Placental abruption releases large amounts of thromboplastin (tissue factor) from the placenta into the maternal circulation, triggering the extrinsic coagulation pathway. This can cause consumptive coagulopathy (DIC) with depletion of clotting factors and platelets, fibrinogen, and activation of fibrinolysis, leading to haemorrhagic catastrophe.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Pregnancy Complications — Late','hard','mcq','Antiangiogenic factor sFlt-1 (soluble fms-like tyrosine kinase-1) contributes to pre-eclampsia pathogenesis by which mechanism?','["A. Stimulating trophoblast invasion of spiral arteries","B. Activating the renin-angiotensin system directly","C. Binding and sequestering VEGF and PlGF, causing endothelial dysfunction and hypertension","D. Inhibiting prostaglandin I2 (prostacyclin) synthesis in vessel walls"]','C','In pre-eclampsia, ischaemic placenta releases excess sFlt-1, which acts as a decoy receptor binding VEGF and PlGF (placental growth factor), preventing them from activating endothelial VEGF receptors. This causes widespread endothelial dysfunction: hypertension, proteinuria (glomerular endotheliosis), and multi-organ involvement. sFlt-1/PlGF ratio is a biomarker for pre-eclampsia prediction.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed');

-- Subtopic 9: Male Reproductive Pathology
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Male Reproductive Pathology','easy','mcq','Cryptorchidism increases the risk of which testicular pathology?','["A. Epididymo-orchitis","B. Hydrocele","C. Varicocele formation","D. Testicular germ cell tumours, particularly seminoma"]','D','Undescended testis (cryptorchidism) increases the risk of testicular germ cell tumours 3–5-fold (seminoma > non-seminomatous tumours). Risk persists even after orchidopexy, though the procedure reduces it. The contralateral normally descended testis also has a slightly increased risk, suggesting a systemic predisposition.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Male Reproductive Pathology','easy','mcq','Seminoma of the testis is characterised by which histological appearance?','["A. Glandular structures with yolk sac differentiation","B. Solid sheets of large uniform cells with clear glycogen-rich cytoplasm and lymphocytic infiltrate in fibrous septa","C. Cartilage and squamous epithelium with calcification","D. Small hyperchromatic cells arranged in rosettes"]','B','Seminoma shows uniform sheets or lobules of large cells with clear, glycogen-rich cytoplasm, central nuclei, and prominent nucleoli, separated by fibrous septa with lymphocytic infiltrate. PAS stain highlights intracellular glycogen. Granulomatous reaction may be present. It is exquisitely radiosensitive.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Male Reproductive Pathology','easy','mcq','Benign prostatic hyperplasia (BPH) predominantly affects which zone of the prostate?','["A. Peripheral zone","B. Central zone","C. Anterior fibromuscular stroma","D. Transitional zone"]','D','BPH predominantly arises in the transitional zone (periurethral glands) of the prostate, causing urethral compression and lower urinary tract symptoms (hesitancy, weak stream, nocturia, incomplete emptying). In contrast, prostate adenocarcinoma predominantly arises in the peripheral zone.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Male Reproductive Pathology','medium','mcq','A 25-year-old man has a painless testicular mass. AFP is 1200 ng/mL and beta-hCG is 150 IU/L. Orchiectomy shows a tumour with yolk sac areas, embryonal carcinoma, and teratoma. What is the diagnosis?','["A. Pure seminoma","B. Leydig cell tumour","C. Lymphoma of the testis","D. Mixed non-seminomatous germ cell tumour (NSGCT)"]','D','Elevated AFP confirms non-seminomatous component (seminomas do not produce AFP). Mixed NSGCT contains elements of embryonal carcinoma, yolk sac tumour, teratoma, and/or choriocarcinoma in any combination. AFP and beta-hCG are critical for staging, monitoring treatment response, and detecting relapse.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Male Reproductive Pathology','medium','mcq','The Gleason grading system for prostate carcinoma is based on which histological feature?','["A. Glandular differentiation and growth pattern (architectural pattern) of the tumour","B. Nuclear grade and mitotic count","C. Perineural invasion and lymphovascular invasion","D. Immunohistochemical expression of PSA"]','A','The Gleason system grades prostate carcinoma 1–5 based on architectural pattern (glandular differentiation): 1 = well-formed small glands; 3 = discrete glands; 4 = fused/cribriform glands; 5 = no gland formation/single cells. Gleason score = primary (most common) + secondary (second most common) pattern. Ranges 2–10; most clinically relevant is 6–10.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Male Reproductive Pathology','medium','mcq','Which serum marker is most useful for the detection and monitoring of prostate carcinoma?','["A. AFP","B. CEA","C. PSA (prostate-specific antigen)","D. LDH"]','C','PSA is a serine protease produced by prostatic epithelium. It is organ-specific but NOT cancer-specific (elevated in BPH, prostatitis, prostate cancer). PSA >4 ng/mL warrants further investigation. PSA velocity, PSA density, and free-to-total PSA ratio improve specificity. PSA is used for screening, staging, and post-treatment monitoring.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Male Reproductive Pathology','medium','mcq','Embryonal carcinoma of the testis differs from seminoma in which key feature?','["A. Embryonal carcinoma occurs in older men; seminoma in younger men","B. Embryonal carcinoma is always bilateral","C. Seminoma is more chemoresistant than embryonal carcinoma","D. Embryonal carcinoma is highly aggressive, may produce AFP/hCG, and shows pleomorphic cells with glandular or papillary patterns; seminoma is uniform and AFP-negative"]','D','Embryonal carcinoma (peak age 25–35) is more aggressive than seminoma. It shows pleomorphic anaplastic cells with indistinct cell borders, glandular/papillary/solid patterns, high mitotic rate, and haemorrhagic necrosis. It may produce AFP and/or beta-hCG. Seminoma is AFP-negative; elevated AFP excludes pure seminoma.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Male Reproductive Pathology','hard','mcq','Prostatic intraepithelial neoplasia (PIN) is considered the precursor lesion to prostate carcinoma. High-grade PIN is characterised by which feature?','["A. Small crowded glands with luminal crystalloids only","B. Glands showing stromal invasion with loss of basal cells","C. Glands lined by cells with large nuclei and prominent nucleoli, with intact basal cell layer","D. Glands with intraluminal calcifications and no nuclear atypia"]','C','High-grade PIN shows architecturally normal-sized glands with markedly atypical luminal cells (large nuclei, prominent nucleoli resembling invasive carcinoma), but the basal cell layer remains intact (demonstrable by p63 or CK5/6 IHC). Loss of basal cells and stromal invasion define invasive carcinoma.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Male Reproductive Pathology','hard','mcq','Isochromosome 12p [i(12p)] is the most characteristic chromosomal abnormality in which tumour?','["A. Prostate adenocarcinoma","B. Penile squamous cell carcinoma","C. Testicular germ cell tumours (both seminoma and NSGCT)","D. Adrenal cortical carcinoma"]','C','Isochromosome 12p [i(12p)] — duplication of the short arm of chromosome 12 — is present in >90% of all testicular germ cell tumours (seminomas and non-seminomatous). Its detection in a primary or metastatic tumour is diagnostic of GCT origin and is used when histology is ambiguous.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Male Reproductive Pathology','hard','mcq','Prostate carcinoma most commonly metastasises to which site, and what is the characteristic radiological appearance of these metastases?','["A. Lungs — lytic lesions on chest X-ray","B. Bone — osteoblastic (sclerotic) lesions on plain X-ray and bone scan","C. Liver — hypervascular lesions on CT","D. Brain — ring-enhancing lesions on MRI"]','B','Prostate carcinoma preferentially metastasises to axial skeleton (lumbar spine, pelvis, ribs, skull) via Batson''s vertebral venous plexus. Metastases are characteristically osteoblastic (sclerotic) on plain X-ray, appearing as increased bone density. Bone scan (technetium-99m) is sensitive for early detection. ALP and PSA are elevated.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed');

-- Subtopic 10: Sexually Transmitted Infections — Pathology
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Sexually Transmitted Infections — Pathology','easy','mcq','The primary lesion of syphilis (chancre) is characterised by which pathological features?','["A. Painless indurated ulcer with plasma cell-rich infiltrate and endarteritis obliterans","B. Painful vesicles with multinucleated giant cells","C. Purulent discharge with neutrophilic infiltrate","D. Raised warty lesion with koilocytic change"]','A','The primary chancre of Treponema pallidum infection is a painless, indurated, clean-based ulcer at the inoculation site. Histology shows dense perivascular plasma cell infiltrate and obliterative endarteritis (proliferative endotheliitis of small vessels). It heals spontaneously in 4–6 weeks.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Sexually Transmitted Infections — Pathology','easy','mcq','Condylomata lata are a feature of which stage of syphilis?','["A. Primary syphilis","B. Latent syphilis","C. Tertiary syphilis","D. Secondary syphilis"]','D','Condylomata lata are broad, flat, grey-white painless plaques in moist areas (perineum, perianal region) occurring in secondary syphilis. They differ from condylomata acuminata (HPV-induced genital warts) which are papillomatous. Condylomata lata contain numerous spirochaetes and are highly infectious.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Sexually Transmitted Infections — Pathology','easy','mcq','The pathological hallmark of tertiary syphilis is which lesion?','["A. Chancre at the inoculation site","B. Maculopapular rash on palms and soles","C. Condylomata lata in perineal skin","D. Gumma — a granulomatous lesion with central necrosis"]','D','Tertiary syphilis (occurring years after infection) is characterised by gummas — granulomatous lesions with central coagulative necrosis, epithelioid histiocytes, lymphocytes, and plasma cells, surrounded by fibrosis. They occur in skin, bone, liver, and other organs. Cardiovascular (aortitis) and neurosyphilis are other manifestations.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Sexually Transmitted Infections — Pathology','medium','mcq','Chlamydia trachomatis serovars D-K cause urogenital infection. What is the most serious long-term complication in women?','["A. Pelvic inflammatory disease leading to tubal damage and infertility","B. Vulvar carcinoma","C. Vulvar intraepithelial neoplasia","D. Ovarian carcinoma"]','A','C. trachomatis is the most common bacterial STI. Ascending infection causes endometritis, salpingitis, and pelvic peritonitis (PID). The resultant tubal scarring causes infertility (tubal factor), ectopic pregnancy, and chronic pelvic pain — the "silent epidemic" since infection is often asymptomatic.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Sexually Transmitted Infections — Pathology','medium','mcq','Gonorrhoea (Neisseria gonorrhoeae) causes acute urethritis. In women, what complication arises from ascending infection?','["A. Urethral stricture","B. Salpingitis, perihepatic adhesions (Fitz-Hugh-Curtis syndrome), and tubo-ovarian abscess","C. Vulvar carcinoma","D. Bartholin gland adenocarcinoma"]','B','Neisseria gonorrhoeae ascending infection in women causes acute salpingitis, pyosalpinx, tubo-ovarian abscess, and peritonitis. Perihepatic spread causes Fitz-Hugh-Curtis syndrome (violin string adhesions between liver capsule and peritoneum). Chronic damage leads to tubal factor infertility and ectopic pregnancy risk.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Sexually Transmitted Infections — Pathology','medium','mcq','Genital herpes (HSV-2 predominantly) characteristically produces which cytopathic changes on biopsy?','["A. Koilocytes with perinuclear halos","B. Signet-ring cells with intracytoplasmic mucin","C. Multinucleated giant cells with Cowdry type A intranuclear inclusions (Tzanck cells)","D. Reed-Sternberg cells with prominent nucleoli"]','C','HSV infection produces Tzanck cells — multinucleated giant cells with ground-glass nuclear chromatin and Cowdry type A eosinophilic intranuclear inclusions surrounded by a clear halo. These are seen on Tzanck smear from the base of a vesicle, and on biopsy. The Tzanck test has low sensitivity; PCR is preferred for diagnosis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Sexually Transmitted Infections — Pathology','medium','mcq','HPV types 6 and 11 cause condylomata acuminata (genital warts). Which histological feature is characteristic?','["A. Acanthotic squamous epithelium with papillomatosis, hyperkeratosis, and koilocytes","B. CIN 3 with full-thickness dysplasia","C. Invasive squamous cell carcinoma","D. Basaloid cells with palisading at the periphery"]','A','Condylomata acuminata (anogenital warts) caused by low-risk HPV 6/11 show papillomatous (finger-like projections), acanthotic squamous epithelium with hyperkeratosis and koilocytes (HPV cytopathic effect). They do not progress to carcinoma. High-risk HPV 16/18 cause CIN and eventual SCC, not warts.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Sexually Transmitted Infections — Pathology','hard','mcq','Lymphogranuloma venereum (LGV) is caused by which organism and what is its characteristic pathological finding?','["A. Haemophilus ducreyi; painful ulcer with undermined edges","B. Klebsiella granulomatis; intracytoplasmic Donovan bodies","C. Chlamydia trachomatis serovars L1-L3; stellate abscesses in lymph nodes with reactive follicular hyperplasia","D. Treponema pallidum; plasma cell-rich infiltrate with endarteritis"]','C','LGV is caused by C. trachomatis serovars L1-L3. It causes painful inguinal lymphadenopathy (buboes) that suppurate. Histologically the nodes show stellate (star-shaped) abscesses with central neutrophilic necrosis surrounded by epithelioid macrophages and plasma cells. Buboes may rupture forming sinuses.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Sexually Transmitted Infections — Pathology','hard','mcq','Donovanosis (granuloma inguinale) is caused by Klebsiella granulomatis. What is the pathological hallmark on tissue smear?','["A. Intranuclear Cowdry A inclusions in multinucleated cells","B. Dark-field microscopy showing spirochaetes","C. Gram-negative diplococci within neutrophils","D. Donovan bodies — intracytoplasmic organisms within macrophages (Giemsa stain showing safety-pin appearance)"]','D','Donovanosis (granuloma inguinale) caused by Klebsiella granulomatis (formerly Calymmatobacterium) is diagnosed by identifying Donovan bodies — encapsulated bacilli within the cytoplasm of large mononuclear cells (macrophages), appearing as safety-pin shaped organisms on Giemsa or Wright stain of a crush/tissue smear.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Sexually Transmitted Infections — Pathology','hard','mcq','In neurosyphilis, tabes dorsalis results from degeneration of which anatomical structure?','["A. Lateral corticospinal tracts","B. Dorsal root ganglia sensory neurons exclusively","C. Anterior horn motor neurons","D. Posterior columns and posterior nerve roots of the spinal cord"]','D','Tabes dorsalis is a late manifestation of neurosyphilis characterised by progressive degeneration of posterior columns (gracile and cuneate fasciculi) and posterior nerve roots, causing: ataxic wide-based gait, lancinating pains, loss of proprioception and vibration sense, Argyll Robertson pupils, and Charcot joints.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed');

-- Subtopic 11: Infertility — Pathology Causes
INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Infertility — Pathology Causes','easy','mcq','Which ovarian pathology is characterised by insulin resistance, hyperandrogenism, and chronic anovulation, making it the most common cause of anovulatory infertility?','["A. Polycystic ovarian syndrome (PCOS)","B. Premature ovarian insufficiency","C. Ovarian endometrioma","D. Granulosa cell tumour"]','A','PCOS (polycystic ovarian syndrome) is the most common endocrine disorder in reproductive-age women, affecting 5–10%. Insulin resistance drives compensatory hyperinsulinaemia, which stimulates ovarian theca cells to produce excess androgens, disrupting folliculogenesis and causing chronic anovulation. Rotterdam criteria: 2 of 3 — oligo/anovulation, hyperandrogenism, PCO morphology on US.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Infertility — Pathology Causes','easy','mcq','Azoospermia refers to which condition?','["A. Sperm count <15 million/mL","B. Sperm morphology <4% normal forms","C. Sperm motility <40%","D. Complete absence of sperm in the ejaculate"]','D','Azoospermia is the complete absence of spermatozoa in the ejaculate on two separate semen analyses after centrifugation. It is present in ~1% of men and ~10–15% of infertile men. Causes: obstructive (vas deferens obstruction — post-vasectomy, CF, epididymal obstruction) or non-obstructive (spermatogenic failure — Klinefelter, Y chromosome microdeletions, chemotherapy).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Infertility — Pathology Causes','easy','mcq','Varicocele causes male infertility primarily by which mechanism?','["A. Increasing scrotal temperature through venous blood reflux, impairing spermatogenesis","B. Obstructing the vas deferens","C. Reducing testosterone production by Leydig cells","D. Causing epididymal obstruction"]','A','Varicocele (dilated pampiniform plexus veins, predominantly left-sided due to drainage angle of left testicular vein into the renal vein) impairs fertility by raising intratesticular temperature (normally 2–4°C below core body temperature for optimal spermatogenesis). This causes abnormal sperm morphology, reduced motility, and decreased count.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Infertility — Pathology Causes','medium','mcq','A woman with primary infertility has a hysterosalpingogram showing bilateral tubal occlusion at the fimbriated ends and hydrosalpinx. What is the most likely underlying pathological cause?','["A. Endometriosis","B. Previous salpingitis (PID) causing chronic tubal scarring","C. Congenital tubal aplasia","D. Uterine synechiae (Asherman syndrome)"]','B','Hydrosalpinx and fimbrial occlusion are the hallmark sequelae of chronic salpingitis (PID). Repeated or inadequately treated episodes of gonococcal or chlamydial salpingitis lead to mucosal destruction, peritubal adhesions, and luminal scarring at the fimbriated end, causing distal occlusion and fluid accumulation (hydrosalpinx).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Infertility — Pathology Causes','medium','mcq','Klinefelter syndrome (47,XXY) causes male infertility through which primary testicular pathology?','["A. Obstructive azoospermia from epididymal cysts","B. Non-obstructive azoospermia from seminiferous tubule hyalinisation and Leydig cell hyperplasia with elevated FSH/LH","C. Androgen excess causing spermatogenic arrest","D. Varicocele due to venous anomaly"]','B','Klinefelter syndrome (47,XXY) causes progressive hyalinisation and fibrosis of seminiferous tubules, resulting in non-obstructive azoospermia. Leydig cells appear hyperplastic but function is impaired — testosterone is low, while FSH and LH are markedly elevated (hypergonadotrophic hypogonadism). Testicular sperm extraction (TESE) may recover rare sperm.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Infertility — Pathology Causes','medium','mcq','Asherman syndrome (intrauterine adhesions) causes infertility by which mechanism?','["A. Cervical factor infertility from os stenosis","B. Obliteration of the endometrial cavity preventing implantation, with destruction of the functional endometrium","C. Ovarian failure from immune-mediated destruction","D. Fallopian tube obstruction"]','B','Asherman syndrome results from intrauterine adhesions (synechiae) following aggressive curettage (especially post-partum or post-abortion), endometritis, or uterine surgery. Destruction of the stratum basalis prevents regeneration of functional endometrium, causing amenorrhoea/hypomenorrhoea and failure of implantation. Hysteroscopic adhesiolysis is treatment.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Infertility — Pathology Causes','medium','mcq','A 30-year-old man with cystic fibrosis (CFTR mutation) has obstructive azoospermia. What is the anatomical basis?','["A. Bilateral cryptorchidism from transabdominal testicular descent failure","B. Varicocele causing spermatogenic arrest","C. Epididymal obstruction from recurrent infections","D. Congenital bilateral absence of the vas deferens (CBAVD) due to CFTR mutation"]','D','Cystic fibrosis (CFTR mutations, especially delta-F508) causes congenital bilateral absence of the vas deferens (CBAVD) in >95% of male CF patients, resulting in obstructive azoospermia. Spermatogenesis is normal, so sperm can be retrieved by testicular aspiration (TESA/PESA) for ICSI. CBAVD may occur as an isolated finding in mild CFTR mutation carriers.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Infertility — Pathology Causes','hard','mcq','Y chromosome microdeletions causing male infertility most commonly affect which region?','["A. Long arm (Yq11) AZF (azoospermia factor) region — especially AZFc","B. Short arm (Yp) pseudoautosomal region","C. Centromeric heterochromatin","D. SRY gene on the short arm"]','A','AZF (azoospermia factor) region on Yq11 contains genes critical for spermatogenesis. Deletions at AZFa (USP9Y, DDX3Y), AZFb (RBMY), and AZFc (DAZ gene cluster) cause spermatogenic failure. AZFc deletions are most common (~60% of Y microdeletions) and may allow TESE/ICSI, while AZFa/b deletions predict complete spermatogenic failure.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Infertility — Pathology Causes','hard','mcq','Premature ovarian insufficiency (POI) before age 40 is most commonly associated with which pathological mechanism?','["A. Accelerated follicular atresia from autoimmune oophoritis or genetic causes (FMR1 premutation, Turner mosaic)","B. Excessive LH stimulation causing follicular exhaustion","C. Chronic endometritis destroying ovarian reserve","D. Hypothalamic suppression from low BMI only"]','A','POI results from accelerated follicular atresia or follicular dysfunction. Causes include: autoimmune oophoritis (lymphocytic infiltrate destroying follicles — associated with Addison disease, thyroiditis); FMR1 premutation (fragile X carrier); Turner mosaic (45,X/46,XX); chemotherapy/radiotherapy; and idiopathic. FSH is markedly elevated (hypergonadotrophic).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed'),

('{"medicine"}','Medicine','Reproductive System & OB-GYN','Pathology','Infertility — Pathology Causes','hard','mcq','Sertoli-cell-only syndrome (Del Castillo syndrome) on testicular biopsy shows which characteristic finding?','["A. Hyalinised tubules with no cells","B. Maturation arrest at the primary spermatocyte stage","C. Seminiferous tubules lined only by Sertoli cells with complete absence of germ cells","D. Peritubular fibrosis with Leydig cell atrophy"]','C','Sertoli-cell-only syndrome shows seminiferous tubules lined exclusively by Sertoli cells with complete absence of germ cells at all stages. It is confirmed by testicular biopsy and causes non-obstructive azoospermia with elevated FSH, normal testosterone. It may be idiopathic or result from Y chromosome AZFa deletions, chemotherapy, or radiation.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Robbins & Cotran Pathologic Basis of Disease 9th Ed');
