-- ============================================================
-- Genetics Flashcards Part 1 — Subtopics 1–5 (50 total)
-- Generated: 2026-06-23
-- ============================================================

-- ============================================================
-- SUBTOPIC 1: Mendelian Inheritance (10 flashcards)
-- ============================================================

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mendelian Inheritance','easy','flashcard','What defines an autosomal dominant inheritance pattern?','["Only ONE mutant allele is sufficient to produce the phenotype. Affected individuals are typically heterozygous (Aa). Male and female equally affected. Vertical transmission — disease appears in every generation."]','A','Key clue in pedigrees: every affected child has at least one affected parent (unless new mutation). 50% of offspring of an affected parent are affected. Examples: Huntington disease, Marfan syndrome, achondroplasia, NF1.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mendelian Inheritance','easy','flashcard','What defines an autosomal recessive inheritance pattern?','["TWO mutant alleles are required to produce the phenotype (homozygous aa). Carriers (Aa) are phenotypically normal. Often skips generations — horizontal transmission pattern. Both sexes equally affected."]','A','Clue in pedigrees: unaffected carrier parents → 25% affected offspring, 50% carriers, 25% homozygous normal. Consanguinity increases risk. Examples: cystic fibrosis, PKU, sickle cell anaemia.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mendelian Inheritance','easy','flashcard','What is the inheritance pattern of cystic fibrosis?','["Autosomal recessive — mutations in the CFTR gene on chromosome 7. Most common lethal AR disease in Caucasians."]','A','CFTR encodes a chloride channel. Most common mutation: ΔF508 (deletion of phenylalanine at position 508). Carriers: ~1 in 25 Caucasians. Features: recurrent lung infections, pancreatic exocrine insufficiency, male infertility (absent vas deferens).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mendelian Inheritance','medium','flashcard','What is Huntington disease and what molecular mechanism causes worsening with each generation?','["Autosomal dominant neurodegenerative disorder caused by CAG trinucleotide repeat expansion in the HTT gene (chromosome 4). Anticipation: the repeat expands during meiosis — later generations have more repeats and earlier onset."]','A','Normal: <36 CAG repeats. Pathological: >36 repeats. Polyglutamine tract causes toxic gain-of-function. Onset typically 30–50 yrs; juvenile form with paternal transmission. Features: chorea, dementia, psychiatric disturbance. No cure.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mendelian Inheritance','medium','flashcard','What is Marfan syndrome and which gene is affected?','["Autosomal dominant connective tissue disorder caused by mutations in FBN1 (fibrillin-1) on chromosome 15. Results in defective extracellular matrix microfibrils."]','A','Features (mnemonic MARFAN): Mitral valve prolapse, Aortic root dilation/dissection risk, Retinal detachment/lens dislocation (ectopia lentis), Features tall stature + arachnodactyly, Arachnodactyly, Negative thumb sign. Major cause of death: aortic dissection.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mendelian Inheritance','medium','flashcard','What causes achondroplasia and how is it inherited?','["Autosomal dominant — gain-of-function mutation in FGFR3 (fibroblast growth factor receptor 3) on chromosome 4. Constitutive FGFR3 activation inhibits chondrocyte proliferation → short-limb dwarfism."]','A','~80% arise as de novo mutations, often associated with advanced paternal age. Features: rhizomelic shortening (proximal limbs), macrocephaly, frontal bossing, trident hands. Intelligence normal. AD but de novo in most cases — parents often unaffected.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mendelian Inheritance','medium','flashcard','In a pedigree where two carrier parents (Aa × Aa) have 4 children, what is the probability that all 4 children are unaffected?','["(3/4)^4 = 81/256 ≈ 31.6%. Each child independently has a 3/4 chance of being unaffected (1/4 AA + 2/4 Aa). Probabilities multiply for independent events."]','A','Ratio from Aa × Aa cross: 1 AA : 2 Aa : 1 aa. Probability unaffected per child = 3/4. For n children all unaffected: (3/4)^n. Carrier probability among unaffected offspring = 2/3 (conditional probability).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mendelian Inheritance','medium','flashcard','What is neurofibromatosis type 1 (NF1) and which gene is mutated?','["Autosomal dominant disorder caused by loss-of-function mutations in NF1 (neurofibromin) on chromosome 17. Neurofibromin is a tumour suppressor (RAS-GAP). Loss → uncontrolled RAS signalling → tumour growth."]','A','Diagnosis: ≥2 of: ≥6 cafe-au-lait spots (>5mm prepubertal/>15mm postpubertal), ≥2 neurofibromas or 1 plexiform, Lisch nodules (iris hamartomas), axillary/inguinal freckling, optic glioma, bone dysplasia, 1st degree relative with NF1. 50% de novo mutations.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mendelian Inheritance','hard','flashcard','What is phenylketonuria (PKU) and what are the biochemical consequences of untreated disease?','["Autosomal recessive deficiency of phenylalanine hydroxylase (PAH gene, chromosome 12). Phenylalanine accumulates → neurotoxic metabolites (phenylpyruvate, phenylacetate, phenyllactate). Causes severe intellectual disability if untreated."]','A','Newborn screening (Guthrie test) enables early low-phenylalanine diet to prevent brain damage. Maternal PKU: high maternal phenylalanine is teratogenic — microcephaly, congenital heart defects, IUGR in offspring even if offspring does not have PKU. BH4 cofactor supplement (sapropterin) used in some variants.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Mendelian Inheritance','hard','flashcard','What is the dominant negative mechanism in osteogenesis imperfecta type II and why does one mutant COL1A1 allele cause disease?','["Osteogenesis imperfecta (OI) type II is autosomal dominant due to dominant negative effect. A single mutant COL1A1 or COL1A2 allele produces an abnormal procollagen alpha-chain that disrupts the entire collagen triple helix, rendering most collagen molecules non-functional even though 50% of chains are normal."]','A','Because type I collagen is a heterotrimer (2x alpha1, 1x alpha2), even one mutant chain incorporated into a triple helix can poison the whole molecule. OI type I (milder) is due to haploinsufficiency (null allele → quantitative reduction, no structural defect). OI features: brittle bones, blue sclerae, hearing loss, dentinogenesis imperfecta.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

-- ============================================================
-- SUBTOPIC 2: X-linked & Y-linked Disorders (10 flashcards)
-- ============================================================

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','X-linked & Y-linked Disorders','easy','flashcard','What is the inheritance pattern of X-linked recessive disorders and who is typically affected?','["Males are affected (hemizygous X^a Y). Females are carriers (X^A X^a) — usually unaffected. Carrier mothers pass the allele to 50% of sons (affected) and 50% of daughters (carriers). No male-to-male transmission."]','A','Key pedigree clues: predominantly males affected, no father-to-son transmission, carrier mothers link affected males across generations. If a female is affected, consider: homozygous, Turner syndrome (45,X), or X-inactivation skewing. Examples: haemophilia A and B, Duchenne MD, G6PD deficiency, colour blindness.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','X-linked & Y-linked Disorders','easy','flashcard','What is haemophilia A and what factor is deficient?','["X-linked recessive disorder caused by deficiency of Factor VIII (F8 gene on X chromosome). Results in impaired intrinsic coagulation pathway → prolonged aPTT, normal PT. Presents with haemarthroses, deep muscle bleeds, easy bruising."]','A','Treatment: recombinant Factor VIII concentrate. Severity: mild (>5% activity), moderate (1–5%), severe (<1%). ~30% of cases arise from new mutations (inversion of intron 22 is most common severe mutation). Distinguished from haemophilia B by specific factor assay.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','X-linked & Y-linked Disorders','easy','flashcard','What is haemophilia B (Christmas disease) and how does it differ from haemophilia A?','["X-linked recessive deficiency of Factor IX (F9 gene on X chromosome). Clinically identical to haemophilia A (haemarthroses, aPTT prolonged, normal PT) but treated with Factor IX concentrate. Named after Stephen Christmas, the first patient described."]','A','Haemophilia A: Factor VIII deficiency (~80% of cases). Haemophilia B: Factor IX deficiency (~20%). Both X-linked recessive, both affect males, both have prolonged aPTT. Distinguished only by specific factor assay. Haemophilia B Leyden: improves after puberty due to androgen-responsive regulatory element in F9 promoter.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','X-linked & Y-linked Disorders','medium','flashcard','What is the molecular difference between Duchenne and Becker muscular dystrophy?','["Both caused by mutations in the DMD gene (Xp21) encoding dystrophin. Duchenne MD: frameshift or nonsense mutation → no functional dystrophin (out-of-frame deletion). Becker MD: in-frame deletion → truncated but partially functional dystrophin → milder, later-onset phenotype."]','A','Duchenne: onset 3–5 yrs, wheelchair by ~12 yrs, cardiomyopathy, death by ~20s. Becker: onset >5 yrs, ambulatory past 15 yrs. Both X-linked recessive. CK markedly elevated in both. Dystrophin links actin cytoskeleton to extracellular matrix via dystrophin-associated protein complex. Exon-skipping therapy (e.g., eteplirsen) aims to convert Duchenne to Becker phenotype.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','X-linked & Y-linked Disorders','medium','flashcard','What is G6PD deficiency and what triggers haemolytic episodes?','["X-linked recessive deficiency of glucose-6-phosphate dehydrogenase (G6PD). G6PD is essential for the pentose phosphate pathway → generates NADPH → regenerates glutathione → protects RBCs from oxidative damage. Deficiency → oxidative stress → Heinz body formation → haemolysis."]','A','Triggers: oxidant drugs (primaquine, dapsone, nitrofurantoin, rasburicase), fava beans, infection, metabolic acidosis. Features: episodic haemolytic anaemia, Heinz bodies (denatured Hb), bite cells on blood film. Most common enzyme deficiency worldwide. Protective against P. falciparum malaria (heterozygote advantage in females).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','X-linked & Y-linked Disorders','medium','flashcard','What is Fragile X syndrome and what molecular mechanism causes anticipation?','["X-linked dominant/semi-dominant disorder caused by CGG trinucleotide repeat expansion in the 5-prime UTR of the FMR1 gene (Xq27.3). Expansion leads to methylation and transcriptional silencing of FMR1 → absent FMRP protein → intellectual disability."]','A','Normal: <45 repeats. Premutation (carrier): 55–200 repeats — may show premature ovarian insufficiency (females) or FXTAS (males). Full mutation: >200 repeats → methylation → gene silencing. Anticipation: premutation expands to full mutation when passed by a FEMALE (maternal) carrier. Unlike Huntington, expansion occurs during oogenesis not spermatogenesis. Leading cause of inherited intellectual disability in males.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','X-linked & Y-linked Disorders','medium','flashcard','What is Turner syndrome and what are its cardinal features?','["Turner syndrome: 45,X (monosomy X) — most common sex chromosome abnormality causing female phenotype. Features: short stature, primary amenorrhoea, streak gonads (increased FSH/LH), webbed neck, shield chest, widely spaced nipples, cubitus valgus, coarctation of aorta, bicuspid aortic valve, horseshoe kidney."]','A','Karyotype: 45,X (~50%); mosaics (45,X/46,XX) are milder. Most 45,X conceptuses are spontaneously aborted. Oestrogen replacement needed for pubertal development and bone protection. No Barr body visible (only 1 X). Intelligence usually normal. Lymphoedema of hands/feet at birth (cystic hygroma prenatally).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','X-linked & Y-linked Disorders','medium','flashcard','What is Klinefelter syndrome and what are its features?','["Klinefelter syndrome: 47,XXY — most common sex chromosome aneuploidy in males (1 in 600 males). Features: tall stature, small firm testes, azoospermia/infertility, gynaecomastia, sparse body hair, mild learning difficulties (especially language). Increased FSH/LH, decreased testosterone."]','A','Non-disjunction during maternal (or paternal) meiosis. One Barr body visible. Hyalinisation and fibrosis of seminiferous tubules. Increased risk: breast cancer (due to gynaecomastia), autoimmune diseases, osteoporosis. Treatment: testosterone replacement from puberty. Mosaic forms (46,XY/47,XXY) have milder phenotype and may be fertile.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','X-linked & Y-linked Disorders','hard','flashcard','A colour-blind father (X^b Y) and a carrier mother (X^B X^b) have a daughter. What is the probability that the daughter is colour-blind?','["50%. The daughter must receive X^b from her colour-blind father (all daughters inherit the father''s X). She also has a 50% chance of receiving X^b from her carrier mother. So 50% of daughters will be X^b X^b (affected) and 50% will be X^B X^b (carriers)."]','A','Colour blindness: X-linked recessive (red-green; OPN1LW/OPN1MW genes on Xq28). Affects ~8% of males, ~0.5% of females. Punnett square: Father X^b Y × Mother X^B X^b → daughters: X^B X^b (carrier) or X^b X^b (affected) in 1:1 ratio. Sons: 50% normal, 50% colour-blind. This is the scenario where affected daughters arise.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','X-linked & Y-linked Disorders','hard','flashcard','What is the Lyon hypothesis and how does skewed X-inactivation cause disease in female carriers of X-linked disorders?','["The Lyon hypothesis states that in every somatic cell of a female, one X chromosome is randomly inactivated (forming a Barr body) early in embryogenesis. The inactivated X is maintained through all daughter cells (clonal). If by chance most cells inactivate the normal X, a carrier female can manifest disease — this is skewed X-inactivation."]','A','X-inactivation is mediated by XIST RNA (X-inactive specific transcript) coating the inactive X and triggering chromatin compaction and DNA methylation. Pseudoautosomal regions and some other genes escape inactivation (explaining features of Turner syndrome beyond simple monosomy). Clinical relevance: some female carriers of Duchenne MD develop cardiomyopathy due to skewed X-inactivation in cardiac muscle.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

-- ============================================================
-- SUBTOPIC 3: Chromosomal Abnormalities (10 flashcards)
-- ============================================================

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Chromosomal Abnormalities','easy','flashcard','What are the key features of Down syndrome (trisomy 21) and what maternal factor increases risk?','["Trisomy 21 — most common autosomal trisomy compatible with survival. Features: intellectual disability, flat face/nasal bridge, upslanting palpebral fissures, epicanthic folds, single palmar (simian) crease, clinodactyly (5th finger), hypotonia, Brushfield spots. Risk increases with advanced maternal age (>35 yrs)."]','A','~95% due to meiosis I non-disjunction (maternal). ~4% due to Robertsonian translocation (14;21) — familial, NOT age-related. ~1% mosaic. Complications: AV septal defect (AVSD) most common heart defect, duodenal atresia (double bubble), increased risk of ALL and early-onset Alzheimer''s disease (APP gene on chr 21), Hirschsprung''s disease, atlantoaxial instability.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Chromosomal Abnormalities','easy','flashcard','What are the features of Edwards syndrome (trisomy 18)?','["Trisomy 18 — second most common autosomal trisomy at birth. Features: intellectual disability, micrognathia, overlapping fingers (index over middle finger), rocker-bottom feet, low-set ears, ventricular septal defect, horseshoe kidney. Median survival: <2 weeks; 90% die within 1 year."]','A','Mnemonic: EDWARDS — Extensive abnormalities, VSD, Wide occiput, Absent/low IQ, Rocker-bottom feet, Digits overlapping, Severe prognosis. 95% of trisomy 18 conceptions are spontaneously aborted. More common in females that survive to birth. Prenatal screening: decreased AFP, decreased uE3, decreased hCG, decreased inhibin A.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Chromosomal Abnormalities','easy','flashcard','What are the features of Patau syndrome (trisomy 13)?','["Trisomy 13 — third most common autosomal trisomy at birth. Features: holoprosencephaly, microcephaly, microphthalmia/anophthalmia, cleft lip/palate, polydactyly, scalp defects (cutis aplasia), congenital heart defects, renal cysts. Median survival: <1 week; 90% die within 1 year."]','A','Mnemonic for Patau: holoprosencephaly (midline brain defect — forebrain fails to divide), midline facial defects (single nostril, cyclopia in severe cases), polydactyly. Associated with maternal age. Distinction from trisomy 18: polydactyly and holoprosencephaly more characteristic of trisomy 13.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Chromosomal Abnormalities','medium','flashcard','What is a Robertsonian translocation and how does it cause familial Down syndrome?','["Robertsonian translocation: fusion of two acrocentric chromosomes (13, 14, 15, 21, 22) at their centromeres with loss of both short arms. In the t(14;21) carrier: karyotype is 45 chromosomes but all critical genetic material is present — carrier is phenotypically normal. When gametes form, offspring can receive the translocated chromosome 21 plus a free chromosome 21 → effective trisomy 21 → Down syndrome."]','A','t(14;21) carrier: 45,XX or XY, der(14;21). Risk to offspring depends on carrier parent sex — maternal carrier: ~10–15% risk of Down syndrome baby; paternal carrier: ~2–5% risk. This is FAMILIAL Down syndrome — NOT related to maternal age. Key exam point: young mother with Down syndrome child → check parental karyotypes for translocation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Chromosomal Abnormalities','medium','flashcard','What is cri-du-chat syndrome and what chromosomal abnormality causes it?','["Deletion of the short arm of chromosome 5 (5p deletion). Cri-du-chat = French for cry of the cat — characteristic high-pitched, cat-like cry in infancy due to laryngeal abnormality. Features: intellectual disability, microcephaly, hypertelorism, low birthweight, single palmar crease. Severity correlates with deletion size."]','A','Most cases de novo (not inherited). Deleted region includes CTNND2 gene (contributing to intellectual disability). Chromosomal microarray or FISH used for diagnosis. Contrast with Wolf-Hirschhorn syndrome (4p deletion): Greek warrior helmet facial appearance.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Chromosomal Abnormalities','medium','flashcard','What is DiGeorge syndrome and what chromosomal abnormality causes it?','["Microdeletion of chromosome 22q11.2 — most common microdeletion syndrome. Also called velocardiofacial syndrome or CATCH-22. Features: Cardiac defects (conotruncal — tetralogy of Fallot, truncus arteriosus, interrupted aortic arch), Abnormal facies, T-cell deficiency (thymic aplasia → recurrent infections), Cleft palate, Hypocalcaemia (parathyroid aplasia → neonatal tetany)."]','A','CATCH-22 mnemonic: Cardiac, Abnormal facies, Thymic hypoplasia, Cleft palate, Hypocalcaemia, chromosome 22. Also associated with psychiatric illness (schizophrenia risk increased). Detected by FISH with 22q11.2 probe or chromosomal microarray. Haploinsufficiency of TBX1 gene is the primary driver. Most cases are de novo; AD inheritance when familial.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Chromosomal Abnormalities','medium','flashcard','What is the difference between Prader-Willi syndrome and Angelman syndrome, both involving chromosome 15q11-13?','["Both involve deletion of 15q11-13 but differ by PARENT OF ORIGIN due to genomic imprinting. Prader-Willi: deletion of PATERNAL chromosome 15 (or maternal uniparental disomy) → hypotonia, hyperphagia, obesity, hypogonadism, intellectual disability. Angelman: deletion of MATERNAL chromosome 15 (or paternal UPD) → severe ID, absent speech, seizures, ataxia, inappropriate laughter (happy puppet syndrome)."]','A','Genomic imprinting: some genes are expressed only from one parental allele — methylation silences the other. SNRPN region: only expressed from paternal allele (so paternal deletion → loss of SNRPN → Prader-Willi). UBE3A: only expressed from maternal allele in neurons (maternal deletion → Angelman). Mnemonic: PW = Paternal deletion; AS = Angelman, mAternal deletion.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Chromosomal Abnormalities','medium','flashcard','What is non-disjunction and during which meiotic division does it most commonly cause trisomy 21?','["Non-disjunction: failure of homologous chromosomes (meiosis I) or sister chromatids (meiosis II) to separate during cell division. In trisomy 21, ~75% of cases arise from meiosis I non-disjunction in the MOTHER — both copies of chromosome 21 go to one secondary oocyte → fertilisation → trisomy 21."]','A','Meiosis I non-disjunction: homologous chromosomes fail to separate → one gamete has 2 copies, one has 0. Meiosis II non-disjunction: sister chromatids fail to separate. Monosomy X (Turner syndrome) often from paternal non-disjunction (loss of paternal sex chromosome). Risk increases with maternal age — thought to be due to prolonged arrest of oocytes in prophase I (for decades) → cohesin decay → premature chromatid separation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Chromosomal Abnormalities','hard','flashcard','What is chromosomal mosaicism and how does it arise? Give an example of its clinical impact.','["Mosaicism: an individual has two or more genetically distinct cell populations derived from a single zygote. Arises from non-disjunction, gene mutation, or chromosomal rearrangement in a mitotic division AFTER fertilisation. Clinical impact: mosaic Down syndrome (46,XX/47,XX+21) is phenotypically milder than full trisomy 21 — the proportion of trisomic cells determines severity."]','A','Also: mosaic Turner syndrome (45,X/46,XX) — milder than 45,X; mosaic NF1 — limited cafe-au-lait spots. Mosaicism can be somatic (body cells), germline (passed to offspring — carrier appears unaffected), or both. Detection: next-generation sequencing or chromosomal microarray more sensitive than karyotyping for low-level mosaicism.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Chromosomal Abnormalities','hard','flashcard','What is the Philadelphia chromosome and how does it cause CML?','["Philadelphia chromosome: t(9;22)(q34;q11.2) — translocation between chromosomes 9 and 22. BCR gene (chr 22) fuses with ABL1 proto-oncogene (chr 9) → BCR-ABL1 fusion gene on the shortened chromosome 22 (Philadelphia chromosome). BCR-ABL1 encodes a constitutively active tyrosine kinase → uncontrolled myeloid proliferation → chronic myeloid leukaemia (CML)."]','A','Present in >95% of CML and ~25% of adult ALL. Imatinib (Gleevec) — first targeted tyrosine kinase inhibitor — competitively inhibits BCR-ABL1 ATP-binding site → revolution in CML treatment. Detected by: karyotyping (G-banding), FISH (BCR-ABL1 fusion probe), RT-PCR (most sensitive for minimal residual disease monitoring). BCR-ABL1 transcript level used to monitor treatment response.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

-- ============================================================
-- SUBTOPIC 4: Molecular Genetics Techniques (10 flashcards)
-- ============================================================

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Molecular Genetics Techniques','easy','flashcard','What is the principle of PCR (polymerase chain reaction) and what are its three steps?','["PCR amplifies a specific DNA sequence exponentially using thermostable DNA polymerase (Taq). Three steps: (1) Denaturation: heat to ~95°C — double-stranded DNA separates; (2) Annealing: cool to ~55–65°C — primers bind to complementary sequences flanking the target; (3) Extension: heat to ~72°C — Taq polymerase synthesises new DNA strand from each primer."]','A','Each cycle doubles the number of target copies → exponential amplification (2^n copies after n cycles). 30 cycles → ~10^9-fold amplification. Key components: template DNA, primers (short oligonucleotides), dNTPs, Taq polymerase, Mg2+ cofactor, buffer. Clinical uses: infectious disease detection (e.g., COVID-19), prenatal diagnosis, forensics, carrier testing, BCR-ABL quantification in CML.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Molecular Genetics Techniques','easy','flashcard','What does FISH (fluorescence in situ hybridisation) detect and how does it work?','["FISH detects specific chromosomal sequences using fluorescently labelled DNA probes that hybridise to complementary sequences on denatured chromosomes or interphase nuclei. Visualised under fluorescence microscopy. Can detect chromosomal deletions, duplications, translocations, and gene amplifications."]','A','Types of FISH probes: locus-specific (detects single gene — e.g., 22q11.2 deletion for DiGeorge), centromeric/satellite (counts chromosomes — aneuploidy), whole-chromosome painting (identifies chromosomal rearrangements). Clinical uses: BCR-ABL in CML, HER2 amplification in breast cancer, DiGeorge (22q11), Williams syndrome (7q11), Prader-Willi/Angelman (15q11). Resolution: ~200 kb (much better than karyotyping at ~5 Mb for visible bands).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Molecular Genetics Techniques','easy','flashcard','What does each type of molecular blot detect? (Southern, Northern, Western)','["Southern blot: detects DNA (double-stranded). Northern blot: detects RNA (mRNA). Western blot: detects Protein. Mnemonic: SNow in the Winter — S=DNA, N=RNA, W=protein. Southwestern blot: detects DNA-binding proteins."]','A','Southern blot procedure: DNA digested with restriction enzymes → gel electrophoresis → transfer to membrane → hybridise with labelled probe → detect bands. Used for: fragile X repeat sizing, gene rearrangements. Northern blot: RNA gel → membrane → probe → quantify mRNA expression. Western blot: SDS-PAGE → transfer → antibody detection. Used to confirm HIV diagnosis (detects anti-HIV antibodies to specific viral proteins).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Molecular Genetics Techniques','medium','flashcard','What is Southern blotting and what is it used to detect in clinical genetics?','["Southern blotting: genomic DNA is digested with restriction enzymes → fragments separated by agarose gel electrophoresis → denatured and transferred (blotted) to a nitrocellulose or nylon membrane → hybridised with a radiolabelled or chemiluminescent probe → bands detected by autoradiography. Detects: specific DNA sequences, restriction fragment length polymorphisms, repeat expansions."]','A','Clinical uses: diagnosis of fragile X syndrome (large CGG repeat expansions visible as larger restriction fragments), detection of BCR-ABL rearrangements (historic — now RT-PCR preferred), detection of gene deletions or rearrangements in haemophilia, characterisation of gene rearrangements in lymphomas. Largely replaced by PCR and next-generation sequencing for most applications but still used for trinucleotide repeat sizing.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Molecular Genetics Techniques','medium','flashcard','What is the difference between Sanger sequencing and next-generation sequencing (NGS)?','["Sanger sequencing (chain-termination): uses dideoxynucleotides (ddNTPs) — each lacking 3-prime-OH → chain termination at each base → fragments of different lengths separated by capillary electrophoresis → sequence read from the pattern. Reads ~1 kb; gold standard for single-gene sequencing. NGS (massively parallel): millions of DNA fragments sequenced simultaneously → much higher throughput, lower cost per base, can sequence whole exomes or genomes."]','A','Sanger: accuracy >99.99%, reads 600–1000 bp, slow and expensive for large regions. NGS: whole genome sequencing (~3 billion bases), whole exome sequencing (~1–2% of genome but ~85% of disease-causing mutations), gene panels. Clinical NGS uses: BRCA1/2 testing, hereditary cancer panels, pharmacogenomics, prenatal cfDNA sequencing. Limitation of NGS: lower accuracy in repetitive regions, GC-rich sequences; Sanger still used for confirmation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Molecular Genetics Techniques','medium','flashcard','What is karyotyping and what level of chromosomal abnormality can it detect?','["Karyotyping: analysis of the chromosomal complement of a cell. Chromosomes condensed in metaphase → stained with Giemsa (G-banding) → ~400–850 bands visible → arranged in standard order (1–22 + X, Y) → interpreted for number and structural abnormalities. Resolution: ~5–10 Mb — detects large deletions, duplications, translocations, inversions, aneuploidy."]','A','Process: sample (blood, amniocytes, CVS, bone marrow) → cell culture → arrest in metaphase (colchicine) → hypotonic solution → fix → stain → microscopy → digital karyogram. Cannot detect: small microdeletions (need FISH or microarray), single nucleotide variants (need sequencing). Replaced for microdeletion syndromes by chromosomal microarray. Still gold standard for: aneuploidy detection, balanced translocations (microarray misses these).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Molecular Genetics Techniques','medium','flashcard','What are restriction fragment length polymorphisms (RFLPs) and how are they used in genetics?','["RFLPs: natural variations in DNA sequence that create or destroy restriction enzyme recognition sites. Different individuals have different-sized fragments when their DNA is cut with the same restriction enzyme. Used as genetic markers to track disease alleles through families (linkage analysis) even before the causative gene is identified."]','A','Historical significance: RFLPs were the first widely used molecular markers for genetic linkage studies (pre-PCR). Used to map the Huntington disease gene before HTT was cloned (1983 linkage study). Modern equivalents: SNP arrays and microsatellite markers (STRs) are more informative and PCR-based. RFLPs detected by Southern blot. Also used in forensic DNA fingerprinting (now replaced by STR profiling).','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Molecular Genetics Techniques','hard','flashcard','What is array CGH (comparative genomic hybridisation) and what does it detect that karyotyping cannot?','["Array CGH: patient DNA and reference (control) DNA are labelled with different fluorescent dyes (e.g., red/green), combined, and hybridised to a microarray containing thousands of known DNA sequences. Ratio of patient to reference signal at each probe location identifies copy number variants (CNVs) — gains or losses of chromosomal segments as small as 1–5 kb."]','A','Array CGH detects: microdeletion syndromes (DiGeorge, Williams, Prader-Willi), submicroscopic duplications, gene amplifications. Cannot detect: balanced translocations (no net gain or loss of DNA), point mutations, mosaicism below ~10–20%. Largely replaced standard FISH panels in clinical practice. Array CGH/SNP arrays are now first-line in children with unexplained intellectual disability, developmental delay, or multiple congenital anomalies. SNP arrays additionally detect uniparental disomy (UPD) and regions of homozygosity.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Molecular Genetics Techniques','hard','flashcard','Describe gene cloning using restriction enzymes and plasmid vectors.','["Gene cloning: (1) Cut target DNA and plasmid vector with the SAME restriction enzyme → complementary sticky ends. (2) Ligate target DNA into plasmid using DNA ligase → recombinant plasmid. (3) Transform into bacteria (e.g., E. coli). (4) Select colonies containing recombinant plasmid (antibiotic resistance or blue-white screening). (5) Culture → bacteria replicate plasmid → large quantity of cloned DNA or expressed protein."]','A','Key restriction enzyme property: recognise specific palindromic sequences (e.g., EcoRI: GAATTC) and cut → create sticky ends or blunt ends. Sticky ends allow efficient ligation of compatible fragments. Vectors: plasmids (small DNA, self-replicating), phage lambda (larger inserts), cosmids, BACs (bacterial artificial chromosomes — largest inserts). Applications: production of recombinant proteins (insulin, erythropoietin, clotting factors), gene therapy vectors, creation of transgenic organisms, cDNA libraries.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

-- ============================================================
-- SUBTOPIC 5: Population Genetics (10 flashcards)
-- ============================================================

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Population Genetics','easy','flashcard','What are the five conditions required for Hardy-Weinberg equilibrium?','["For allele and genotype frequencies to remain constant across generations, the population must be: (1) Large (no genetic drift); (2) No mutation; (3) No selection (all genotypes equally fit); (4) No gene flow (no migration in or out); (5) Random mating (no assortative mating or consanguinity). If ANY condition is violated, allele frequencies change."]','A','Hardy-Weinberg equilibrium (HWE) is a null model — it tells us what to expect in the absence of evolutionary forces. Deviations from HWE in a population study suggest selection, non-random mating, or population structure. Clinically used to estimate carrier frequency (2pq) from disease incidence (q^2) for autosomal recessive conditions. Named after G.H. Hardy (mathematician) and Wilhelm Weinberg (physician), independently derived in 1908.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Population Genetics','easy','flashcard','State the Hardy-Weinberg equations and what each term represents.','["For a biallelic locus with alleles A (frequency p) and a (frequency q): p + q = 1 (allele frequencies sum to 1). Genotype frequencies: p^2 (AA, homozygous dominant) + 2pq (Aa, heterozygous carrier) + q^2 (aa, homozygous recessive, affected) = 1."]','A','How to use: if disease incidence (q^2) is known, calculate q = square root of disease incidence, then p = 1 – q, then carrier frequency = 2pq. Example: CF incidence 1/2500 → q^2 = 1/2500 → q = 1/50 → p = 49/50 ≈ 1 → carrier frequency 2pq ≈ 2 × (1/50) = 1/25 (consistent with known CF carrier rate in Caucasians). Assumptions: large random-mating population at equilibrium.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Population Genetics','easy','flashcard','If the incidence of phenylketonuria (PKU) is 1 in 10,000 live births, what is the carrier frequency in the population?','["Disease incidence = q^2 = 1/10,000. Therefore q = square root of (1/10,000) = 1/100 = 0.01. Then p = 1 – q = 0.99. Carrier frequency = 2pq = 2 × 0.99 × 0.01 ≈ 0.0198 ≈ 1 in 50."]','A','This is a standard Hardy-Weinberg application. Steps: (1) Set q^2 = disease incidence. (2) q = square root. (3) p = 1 – q. (4) 2pq = carrier frequency. For rare diseases (q very small), p ≈ 1, so 2pq ≈ 2q. This approximation is useful: carrier frequency ≈ 2 × square root of disease incidence. Always check units — incidence is a proportion, not a percentage.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Population Genetics','medium','flashcard','What is the founder effect and give a medical example?','["The founder effect: a new population is established by a small number of individuals (founders) from a larger population. The small founding group carries only a subset of the original genetic variation. By chance, some alleles — including rare disease alleles — may be at much higher frequency in the new population than in the source population."]','A','Medical examples: (1) Tay-Sachs disease: ~10x higher frequency in Ashkenazi Jews (~1 in 30 carriers) than general population, due to founder effect in Eastern European Jewish communities. (2) Huntington disease: very high frequency in Lake Maracaibo, Venezuela — founders traced to one woman in 19th century. (3) BRCA1 founder mutations: three specific mutations account for ~90% of BRCA1/2 variants in Ashkenazi Jews. The founder effect is a specific type of genetic drift.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Population Genetics','medium','flashcard','What is genetic drift and why does it affect small populations more than large ones?','["Genetic drift: random fluctuations in allele frequencies from one generation to the next due to chance sampling of gametes (not selection). In small populations, random changes have a proportionally larger effect — alleles can become fixed (frequency = 1) or lost (frequency = 0) by chance alone, regardless of fitness."]','A','Analogy: flipping a coin 10 times vs 10,000 times — with 10 flips you can easily get 8 heads by chance; with 10,000 flips the proportion approaches 50%. Mathematical description: variance in allele frequency change per generation = pq/2N (N = population size). Genetic drift leads to: loss of genetic diversity, random fixation of alleles (including harmful ones), and divergence between isolated populations.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Population Genetics','medium','flashcard','How does natural selection affect allele frequencies and give an example from medicine?','["Natural selection changes allele frequencies when different genotypes have different reproductive fitness (survival + reproduction). Alleles that increase fitness increase in frequency; deleterious alleles decrease (but may persist if heterozygote advantage exists or if disease onset is post-reproductive)."]','A','Medical examples: (1) HbS (sickle cell) allele maintained at high frequency in malaria-endemic regions — heterozygote (HbAS) has survival advantage against P. falciparum. (2) Huntington disease allele persists because onset is post-reproductive — natural selection cannot act effectively. (3) CFTR delta-F508 allele may confer heterozygote resistance to cholera or typhoid (proposed). Selection against a recessive allele (aa) is inefficient because most copies are hidden in carriers (Aa).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Population Genetics','medium','flashcard','What is heterozygote advantage and how does sickle cell trait illustrate this concept?','["Heterozygote advantage (overdominance): heterozygotes (Aa) have higher fitness than EITHER homozygote (AA or aa). This maintains BOTH alleles in the population at a stable equilibrium (balanced polymorphism). Classic example: HbAS (sickle cell trait) — heterozygotes are protected against severe Plasmodium falciparum malaria compared to HbAA, while HbSS causes severe sickle cell disease."]','A','Mechanism of protection in HbAS: parasitised HbAS RBCs sickle under low O2 conditions in spleen → removed before parasite can complete lifecycle. Also, infected HbAS cells display parasite antigens on surface → better immune clearance. The HbS allele reaches ~40% in some sub-Saharan African populations with high malaria endemicity — maintained because loss from HbSS individuals is balanced by gain from HbAS advantage. This is a stable equilibrium — both alleles persist indefinitely.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Population Genetics','hard','flashcard','How does consanguinity increase the risk of autosomal recessive disease? Define the coefficient of relatedness (r) and give an example.','["Consanguinity (mating between relatives) increases the proportion of offspring who are homozygous for rare recessive alleles. The coefficient of relationship (r) measures the probability that two individuals share an allele identical by descent (IBD). First cousins: r = 1/8 → offspring of first cousins have coefficient of inbreeding F = 1/16 — each locus has a 1/16 probability of being homozygous IBD."]','A','Practical impact: for a rare AR condition with carrier frequency 2pq, first-cousin marriage increases risk dramatically compared to outbreeding. Example: if q = 0.01 (disease frequency 1/10,000 in general population), risk to offspring of first cousins = q^2 + Fpq ≈ 1/10,000 + (1/16)(0.01)(0.99) ≈ 7-fold increase. In populations with high consanguinity rates (some Middle Eastern, South Asian communities), AR diseases may be more common. Important in clinical genetics counselling.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Population Genetics','hard','flashcard','What is linkage disequilibrium (LD) and why is it important in disease gene mapping?','["Linkage disequilibrium (LD): non-random association of alleles at two or more loci in a population — specific combinations of alleles (haplotypes) occur more or less frequently than expected by chance. LD exists when alleles on the same chromosome are inherited together more often than predicted by their individual frequencies."]','A','LD arises because: (1) insufficient time for recombination to randomise alleles since a mutation occurred; (2) founder effect — new population carries limited haplotype diversity; (3) selection favours specific haplotype combinations. Measured by D-prime and r^2. Used in: GWAS (genome-wide association studies) — tag SNPs in LD with causal variants allow indirect association; HapMap project mapped LD blocks across the human genome. LD decays over generations as recombination separates alleles — alleles far apart on same chromosome eventually reach linkage equilibrium.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Population Genetics','hard','flashcard','What is a genetic bottleneck and how does it differ from the founder effect? Give a clinical example.','["A genetic bottleneck occurs when a population is dramatically reduced in size by a catastrophic event (disease, famine, natural disaster), severely reducing genetic diversity. The surviving (small) population may have very different allele frequencies from the original — rare alleles may be lost or accidentally enriched. The founder effect is specifically when a new population is established from a small group that leaves a larger population — a specific type of bottleneck."]','A','Key distinction: bottleneck = existing population crashes then recovers; founder effect = new colony established from migrants. Both cause: (1) reduced genetic diversity (fewer alleles per locus), (2) random fixation/loss of alleles, (3) potential enrichment of disease alleles by chance. Clinical example: Finnish disease heritage — many rare AR diseases (e.g., infantile neuronal ceroid lipofuscinosis, progressive myoclonus epilepsy) are unusually common in Finland due to a bottleneck when a small population colonised Finland ~2,000 years ago.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES
('{"medicine"}','Medicine','Biochemistry & Genetics','Genetics','Molecular Genetics Techniques','medium','flashcard','What is the Northern blot technique and how does it differ in application from Southern and Western blots?','["Northern blot detects and quantifies specific RNA (mRNA) sequences. RNA is separated by gel electrophoresis → transferred to a membrane → hybridised with a labelled DNA or RNA probe complementary to the target mRNA → band size indicates transcript length, band intensity indicates expression level."]','A','Key differences: Southern blot = DNA detection (uses restriction-digested genomic DNA); Northern blot = RNA/mRNA detection (no restriction digest needed — RNA is separated directly); Western blot = protein detection (uses SDS-PAGE + antibody). Northern blotting was used to characterise gene expression patterns and identify splice variants before RT-PCR became routine. RT-PCR (reverse transcriptase PCR) has largely replaced Northern blotting for quantifying mRNA due to higher sensitivity, but Northern blot is still used to confirm full-length transcript integrity.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','Lippincott Illustrated Reviews Biochemistry 7th Ed');
