-- Renal Pharmacology MCQs Q76-100: Drug dosing, UTI, Nephrotic syndrome, Misc pharmacology
-- Source: DiPiro Ch46-47, Ghana STG 2017 Ch14

INSERT INTO questions (professions, course, topic, subtopic, difficulty, category, question_type, question_text, options, correct_answer, explanation, year_level, region, high_yield, source_reference) VALUES

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Per the Ghana STG for ACUTE UNCOMPLICATED CYSTITIS in adults, the FIRST-LINE treatment is:',
'["A. Ciprofloxacin 500 mg 12 hourly for 5-7 days","B. Cefuroxime 500 mg 12 hourly for 5-7 days","C. Nitrofurantoin 100 mg 6 hourly for 5-7 days","D. Amoxicillin-clavulanate 500 mg 8 hourly for 7 days"]',
'C',
'Ghana STG Section 141 (Acute Cystitis) specifies nitrofurantoin 100 mg 6 hourly for 5-7 days as the first-line treatment for acute uncomplicated cystitis in adults. Children 12-18 years receive 50 mg 6 hourly; younger children receive 750 mcg/kg 6 hourly. Ciprofloxacin is listed as second-line. Note that nitrofurantoin should be avoided in patients with CrCl <30 mL/min as it cannot achieve adequate urinary concentrations.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'For COMPLICATED UTI in adult patients (including catheter-related) per the Ghana STG, the first-line intravenous antibiotic is:',
'["A. Gentamicin 40-80 mg 8 hourly for 7 days","B. Ceftriaxone 1-2 g daily for 7 days","C. Cefuroxime 1.5 g 8 hourly for 7 days","D. Ciprofloxacin 400 mg 8-12 hourly for 7 days (over 60 minutes)"]',
'D',
'Ghana STG Section 139 lists ciprofloxacin IV 400 mg 8-12 hourly for 7 days (administered over 60 minutes) as the first-line for complicated UTI in adults, including catheter-related, stone-related, urologic abnormalities, and pregnancy. Gentamicin is an alternative only if kidney function is normal. IV antibiotics are used until clinical improvement, then stepped down to oral therapy based on culture sensitivity results.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Why should nitrofurantoin be avoided in patients with significant CKD (CrCl <30 mL/min)?',
'["A. It accumulates systemically causing neuropathy and pneumonitis, while urinary concentrations are too low for antibacterial efficacy","B. It causes direct nephrotoxicity by crystal deposition","C. It has no activity against common urinary pathogens in CKD","D. It causes severe hepatotoxicity in patients with impaired renal function"]',
'A',
'Nitrofurantoin is renally excreted and requires adequate GFR for therapeutic urinary concentrations. In CKD with CrCl <30 mL/min, the drug accumulates systemically (causing peripheral neuropathy, pulmonary toxicity) while urinary concentrations are too low for antibacterial efficacy. This dual failure — toxicity from systemic accumulation and lack of efficacy from reduced urinary excretion — makes it contraindicated in significant renal impairment.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Per the Ghana STG, prednisolone in adult nephrotic syndrome (1 mg/kg daily) is appropriately used in which specific indication?',
'["A. All adult cases of nephrotic syndrome regardless of cause","B. Adults with minimal change nephrotic syndrome, prescribed by a specialist only","C. Adult membranous nephropathy as first-line therapy","D. Adults with focal segmental glomerulosclerosis as first-line therapy"]',
'B',
'Ghana STG Note 14-3 states: "Corticosteroids should be given to children and selected adults with minimal change nephrotic syndrome by specialists only." Minimal change disease is steroid-responsive and predominantly seen in children but also occurs in adults. For other causes (membranous nephropathy, FSGS), treatment is more complex and may require immunosuppressants. All nephrotic syndrome patients should be referred to a specialist after initial stabilisation.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Methotrexate nephrotoxicity prevention requires urinary alkalisation. What pH and fluids does the Ghana STG specify?',
'["A. pH >6.5 using 0.9% NaCl and sodium bicarbonate 25 mmol/day","B. pH >7.5 using 5% dextrose only","C. pH <7.0 to enhance methotrexate elimination","D. pH >7.0 using 3L of 5% dextrose plus 44-66 mmol NaHCO₃ per day"]',
'D',
'The Ghana STG specifies: "Prior hydration; Alkaline urine to pH >7.0 (3L of 5% Dextrose in water + 44-66 mmol of NaHCO₃ per day)." Methotrexate is poorly soluble in acidic urine and precipitates in renal tubules. Alkalising the urine maintains methotrexate in its ionised (soluble) form, preventing crystal deposition and tubular obstruction. Leucovorin rescue is also used for high-dose methotrexate regimens.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Which statement regarding aminoglycoside dosing strategy in CKD patients is CORRECT per the Ghana STG?',
'["A. Aminoglycosides are absolutely contraindicated in any degree of CKD","B. The dose should be doubled and interval extended to maintain efficacy","C. Maintaining therapeutic range by once-daily dosing reduces accumulation and toxicity","D. Standard twice-daily dosing should be maintained regardless of GFR"]',
'C',
'The Ghana STG recommends for aminoglycoside nephrotoxicity prevention: "Maintain therapeutic range. Give once daily dose if necessary." Once-daily (extended-interval) dosing exploits the concentration-dependent bactericidal activity of aminoglycosides while allowing trough levels to fall, reducing cortical accumulation and nephrotoxicity. However, avoidance is preferred; if aminoglycosides are essential, therapeutic drug monitoring (TDM) with trough levels <2 mg/L is required.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Cisplatin nephrotoxicity is characterised by which electrolyte abnormality that may persist long after completing treatment?',
'["A. Hypomagnesaemia","B. Hypokalaemia","C. Hyperphosphataemia","D. Hypercalcaemia"]',
'A',
'The Ghana STG lists cisplatin nephrotoxicity as causing "Nephrogenic diabetes insipidus, Hypomagnesaemia (may be persistent)." Cisplatin damages the loop of Henle and distal tubule, impairing magnesium reabsorption. This hypomagnesaemia can persist for months to years post-treatment. Prevention involves adequate pre-hydration (0.9% NaCl), maintaining chloride levels (chloride in cis-position protects against hydroxyl radical formation), and using mesna.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Radiocontrast nephropathy develops through which primary mechanism?',
'["A. Direct tubular toxicity via reactive oxygen species","B. Medullary vasoconstriction and increased oxygen demand in the thick ascending limb","C. Immune-mediated interstitial nephritis","D. Crystal deposition in proximal tubules"]',
'B',
'The Ghana STG explains radiocontrast nephropathy as: "High osmolarity → medullary vasoconstriction → active transport in thick ascending loop of Henle → increased oxygen demand [causing relative ischaemia]." Prevention includes hydration before and after, using iso-osmolar contrast, minimising contrast volume, and acetylcysteine (evidence uncertain per Ghana STG). Patients with diabetes and pre-existing CKD are at highest risk.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Which statement about lithium toxicity prevention in patients receiving lithium for bipolar disorder is TRUE per the Ghana STG?',
'["A. Thiazide diuretics help prevent lithium accumulation by promoting lithium excretion","B. A low-sodium diet protects the kidneys by reducing osmotic load","C. Avoiding thiazide diuretics prevents lithium-sodium reabsorption and accumulation","D. Loop diuretics are preferred to thiazides for concurrent hypertension management"]',
'C',
'The Ghana STG lists thiazide diuretics as a key risk factor for lithium toxicity (via sodium depletion → compensatory proximal tubular reabsorption of sodium AND lithium → lithium toxicity). Prevention includes: maintaining therapeutic range (0.6-1.2 mmol/L), preventing dehydration, avoiding low-sodium diet, and specifically AVOIDING thiazide diuretics. If a diuretic is needed, loop diuretics may be safer as they increase rather than promote sodium depletion.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'The therapeutic serum lithium concentration range stated in the Ghana STG is:',
'["A. 0.4-0.8 mmol/L","B. 0.8-1.5 mmol/L","C. 0.5-1.0 mmol/L","D. 0.6-1.2 mmol/L"]',
'D',
'The Ghana STG specifies the therapeutic lithium range as 0.6-1.2 mmol/L. Below this range, lithium is subtherapeutic for bipolar disorder; above it, toxicity occurs. Lithium toxicity symptoms include tremor, ataxia, confusion, and at higher levels (>2 mmol/L): cardiac arrhythmias and seizures. Regular TDM (12 hours post-dose), renal function monitoring, and electrolyte checks are essential during lithium therapy.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Secondary hyperparathyroidism evidenced by iPTH levels above 495 pg/mL in hemodialysis patients is associated with which serious complication?',
'["A. Metabolic alkalosis and hypomagnesaemia","B. Anaemia refractory to ESA therapy only","C. Secondary hyperparathyroidism causing increased morbidity, mortality and sudden death","D. Iron overload and hemosiderosis"]',
'C',
'DiPiro Ch47 states: "sHPT evidenced by PTH levels >495 pg/mL in CKD patients is associated with increased morbidity and mortality and sudden death in hemodialysis patients." Adverse consequences include alterations in lipid metabolism, insulin secretion, resistance to EPO therapy, myocardial and skeletal muscle dysfunction, and neurologic and immune alterations. Elevated Ca × P (particularly >72 mg²/dL²) from sHPT treatment also contributes to vascular calcification and death.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Patients with a calcium-phosphorus product (Ca × P) above what value have a 34% higher risk of death compared to those with Ca × P in the reference range?',
'["A. 55 mg²/dL²","B. 60 mg²/dL²","C. 65 mg²/dL²","D. 72 mg²/dL²"]',
'D',
'DiPiro Ch47 cites: "Patients with a Ca × P above 72 mg²/dL² were found to have a 34% higher risk of death compared with patients with a Ca × P in the reference range of 43 to 52 mg²/dL²." This elevated product drives soft tissue and vascular calcification. Calcium-containing phosphate binders contribute to elevated Ca × P, supporting a shift toward non-calcium binders (sevelamer, lanthanum) in patients with hypercalcaemia or elevated Ca × P.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Per Ghana STG Section 136, for AKI due to severe burns or other cases requiring plasma expansion, which fluid is recommended?',
'["A. Plasma replacement (e.g., fresh frozen plasma, albumin)","B. Ringer''s lactate","C. 0.9% NaCl","D. 5% albumin infusion only"]',
'A',
'Ghana STG Section 136 (AKI) treatment of hypovolaemia lists: "Sodium Chloride 0.9% IV; OR Ringer''s lactate (if there is no hyperkalaemia) in cases of diarrhoea and vomiting; OR Blood transfusion (in severe bleeding); OR Plasma replacement (in cases of severe burns)." Plasma-derived or colloid products replace oncotic pressure lost with burn injuries where protein and fluid exude from damaged skin.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Per Ghana STG Table 14-2, the management action for CKD Stage 5 is:',
'["A. Refer if eGFR ≤30 mL/min/1.73 m²","B. Kidney replacement therapy (dialysis or transplantation); refer to nephrologist","C. Estimate progression and manage as Stage 1","D. Prepare for kidney replacement therapy but defer referral"]',
'B',
'Ghana STG Table 14-2 specifies: Stage 5 = "Kidney Failure: Kidney replacement therapy — Dialysis or transplantation: Refer." Stage 4 is "Prepare for kidney replacement therapy: Refer." Stage 3 is where complications are estimated and treated (anaemia, bone disease). Early referral in Stage 4 allows planning for vascular access (arteriovenous fistula maturation takes months) before dialysis is urgently needed in Stage 5.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Which drug class is listed in the Ghana STG as absolutely contraindicated in patients with BILATERAL RENAL ARTERY STENOSIS due to risk of pre-renal AKI?',
'["A. NSAIDs","B. Aminoglycosides","C. ACE inhibitors and ARBs","D. Radiocontrast agents"]',
'C',
'The Ghana STG Ch14 explicitly states for ACE inhibitors/ARBs (e.g., Lisinopril/Losartan): "Vasoconstriction — pre-renal ARF. Avoid in bilateral renal artery stenosis." In bilateral RAS, GFR is maintained by angiotensin II-mediated efferent arteriolar constriction. ACEIs/ARBs block this compensatory mechanism, causing catastrophic GFR reduction. This is also relevant in severe heart failure where renal perfusion is similarly angiotensin-dependent.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'For hemodialysis patients with hyperkalaemia receiving both dietary restriction and pharmacological management, dialysate potassium concentrations should be:',
'["A. Increased to promote potassium equilibration","B. Maintained at standard levels regardless of serum potassium","C. Measured and adjusted based on plasma osmolality","D. Reduced to increase potassium removal during dialysis sessions"]',
'D',
'DiPiro Ch47 states hyperkalemia management in dialysis includes "dietary potassium restriction of 50 to 80 mEq/day AND a reduction in dialysate potassium concentrations for patients receiving hemodialysis or peritoneal dialysis." Lowering dialysate potassium (from standard ~2 mEq/L to 0-1 mEq/L) increases the potassium gradient across the dialysis membrane, enhancing potassium removal during each dialysis session. This is particularly important for acute severe hyperkalaemia in dialysis patients.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Per DiPiro Ch46, at what interval should ACEI dose be increased when titrating for CKD and proteinuria management?',
'["A. Every 4 weeks","B. Every 2 weeks","C. Every 6 weeks","D. Every 8 weeks"]',
'A',
'DiPiro Ch46 recommends: "customary to begin at low doses and increase the dose at 4-week intervals to control the level of proteinuria." This 4-week interval allows adequate time for renal haemodynamic adaptation and for serum creatinine and potassium to stabilise after each dose increment. The endpoint is either 30-50% reduction in proteinuria or development of side effects (Scr rise >30%, hyperkalaemia >5.5 mEq/L).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Which of the following statements about calcium CITRATE as a phosphate binder is TRUE?',
'["A. It is preferred over calcium carbonate due to superior phosphate binding","B. It requires an alkaline pH for optimal phosphate binding activity","C. It is NOT recommended because citrate increases aluminium absorption from the gut","D. It has the highest elemental calcium content of all calcium-based binders"]',
'C',
'DiPiro Ch47 states calcium citrate is "not recommended since the citrate component increases aluminum absorption." Citrate enhances aluminium absorption across the intestinal mucosa by forming soluble aluminium-citrate complexes. In CKD patients with impaired aluminium excretion, this can lead to dangerous aluminium accumulation causing osteomalacia, encephalopathy, and ESA-resistant anaemia. Calcium chloride is similarly not recommended (astringent, contributes to systemic acidosis).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'For paediatric nephrotic syndrome, the Ghana STG recommended prednisolone dose is:',
'["A. 1 mg/kg daily (maximum 60 mg)","B. 2 mg/kg daily (maximum 60 mg)","C. 1 mg/kg daily (maximum 80 mg)","D. 60 mg/m² or 2 mg/kg daily (maximum 80 mg)"]',
'D',
'Ghana STG Ch14 (Section 135) specifies for children: "Prednisolone, oral, Children 60 mg/m² or 2 mg/kg daily (max. 80 mg). For long-term management, refer to a paediatrician." Adult dose is 1 mg/kg daily. Minimal change disease (the most common cause in children) is highly steroid-responsive, with remission in >90% of children. Corticosteroids should only be initiated by specialists (Note 14-3).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'The K/DOQI recommended serum phosphorus range for CKD STAGE 5 (ESRD) differs from Stages 3-4. For Stage 5, it is:',
'["A. 2.7-4.6 mg/dL (same as Stage 3-4)","B. 3.5-5.5 mg/dL","C. 2.0-4.0 mg/dL","D. 4.0-6.0 mg/dL"]',
'B',
'DiPiro Table 47-5 shows phosphorus targets differ by CKD stage: Stages 3 and 4 = 2.7-4.6 mg/dL; Stage 5 (ESRD) = 3.5-5.5 mg/dL. The slightly higher acceptable range in Stage 5 reflects the difficulty of achieving strict phosphate control in dialysis patients requiring high protein intake. Despite this allowance, elevated phosphorus in ESRD remains strongly associated with cardiovascular mortality and is a primary target of phosphate binder therapy.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'The corrected calcium target for CKD STAGE 5 per K/DOQI (8.4-9.5 mg/dL) is LOWER than the normal range. The primary reason is:',
'["A. Increased dietary calcium absorption in ESRD patients","B. Decreased PTH activity in Stage 5 requiring lower calcium targets","C. Increased risk of soft tissue and vascular calcification in ESRD from dialysate calcium exposure","D. Aluminium toxicity reduces calcium levels requiring a lower target"]',
'C',
'DiPiro Ch47 explains: the lower corrected calcium target in Stage 5 CKD (8.4-9.5 mg/dL vs "normal" for Stages 3-4) "is based on the observation of an increased risk of soft tissue and vascular calcifications in this population and the exposure to dialysate calcium for the ESRD population." Calcium exposure from both diet, calcium-containing phosphate binders, and dialysate contributes to arterial calcification and cardiovascular mortality in ESRD patients.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Per the Ghana STG, for furosemide used to re-establish diuresis after adequate fluid replacement in CHILDREN with AKI, the dose and critical instruction is:',
'["A. 2-4 mg/kg IV stat; do NOT repeat","B. 1-2 mg/kg IV 8-12 hourly until diuresis established","C. 40 mg IV stat; may be repeated once if no response","D. 1 mg/kg/hour IV infusion until target urine output achieved"]',
'A',
'Ghana STG Ch14 Section B (AKI): "Furosemide, IV, Children: 2-4 mg/kg stat. Do not repeat." The adult dose is 40-80 mg stat (also not repeated). The instruction "Do not repeat" is important — failure of furosemide to establish diuresis despite adequate fluid resuscitation indicates established intrinsic AKI (ATN), and repeated high-dose loop diuretics are harmful (ototoxicity risk) without clinical benefit in established oliguric AKI.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'To slow CKD progression, the Ghana STG recommends avoidance of which class of over-the-counter analgesics as nephrotoxins?',
'["A. Paracetamol (acetaminophen)","B. Tramadol","C. Codeine","D. Non-steroidal anti-inflammatory drugs (NSAIDs)"]',
'D',
'Ghana STG Section 137 lists as non-pharmacological CKD management: "Avoid nephrotoxins e.g. NSAIDs, herbal medication." DiPiro Ch47 reinforces: "Chronic use of NSAIDs and cyclooxygenase-2 inhibitors should be avoided when possible." Patients should be educated on all brand and generic names of NSAIDs (e.g., ibuprofen, diclofenac, aspirin at anti-inflammatory doses) as many are purchased without prescription in Ghana.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'For post-parathyroidectomy ionised calcium maintenance infusion in adults, the recommended calcium gluconate dose is:',
'["A. 0.5-1 mg elemental calcium/kg/hour","B. 1-2 mg elemental calcium/kg/hour","C. 2-4 mg elemental calcium/kg/hour","D. 0.25-0.5 mg elemental calcium/kg/hour"]',
'B',
'DiPiro Ch47 specifies: "The recommended dose of calcium gluconate is 1 to 2 mg of elemental calcium per kilogram per hour, adjusted to maintain ionized calcium at 4.6 to 5.4 mg/dL (1.15 to 1.36 mmol/L)." This infusion prevents severe symptomatic hypocalcaemia (tetany, seizures) immediately after parathyroidectomy. Once stable, therapy is transitioned to oral calcium carbonate 1-2 g plus calcitriol up to 2 mcg/day.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Complications','medium','Pharmacology','mcq',
'Per the Ghana STG Table 14-2, the action for CKD Stage 4 (severely decreased GFR) is:',
'["A. Annual eGFR monitoring and treat as Stage 1","B. Check Hb, ferritin, B12 and folate; annual Ca, PO₄ and PTH","C. Prepare for kidney replacement therapy; REFER to nephrologist","D. Initiate ACEI and annual monitoring only"]',
'C',
'Ghana STG Table 14-2 for CKD Stage 4: "Severely decreased GFR: Prepare for kidney replacement therapy: Refer." Preparation includes creating arteriovenous fistula for hemodialysis (which needs 3-6 months to mature), educating on dialysis modality options (hemodialysis vs peritoneal dialysis), exploring transplantation candidacy, and optimising complication management. Stage 3 is where B12/folate/Ca/PO₄/PTH checks occur; Stage 5 is where dialysis/transplant is initiated.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14');

