-- Renal Pharmacology MCQs Q51-75: Phosphate binders, Vitamin D, Metabolic acidosis, Hyperkalaemia
-- Source: DiPiro Ch47, Ghana STG 2017 Ch14

INSERT INTO questions (professions, course, topic, subtopic, difficulty, category, question_type, question_text, options, correct_answer, explanation, year_level, region, high_yield, source_reference) VALUES

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Phosphate-binding agents must be administered with meals. What is the primary reason for this instruction?',
'["A. Food enhances their systemic absorption","B. They require alkaline pH from food digestion to bind phosphate","C. They cause severe nausea when taken on an empty stomach","D. They bind dietary phosphorus in the GI tract during digestion to prevent absorption"]',
'D',
'Phosphate-binding agents (calcium carbonate, calcium acetate, sevelamer, lanthanum carbonate) work by binding phosphate derived from food within the gastrointestinal tract, forming insoluble phosphate compounds that are excreted in faeces. They must be present when food phosphate is being released during digestion. Taking them away from meals reduces their phosphate-binding efficacy and does not benefit patients (DiPiro Ch47).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Which calcium-based phosphate binder is specifically NOT recommended because its citrate component enhances aluminium absorption from the gut?',
'["A. Calcium carbonate","B. Calcium acetate","C. Calcium citrate","D. Sevelamer hydrochloride"]',
'C',
'DiPiro Ch47 states calcium citrate is "not recommended since the citrate component increases aluminum absorption." This is important because patients with CKD already have impaired aluminium excretion, and absorbed aluminium accumulates — causing aluminium toxicity manifesting as osteomalacia (adynamic bone disease) and encephalopathy. Calcium carbonate and calcium acetate are the preferred calcium-based phosphate binders.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Calcium acetate has greater phosphate-binding capacity than calcium carbonate. Approximately how much more phosphorus does it bind at comparable elemental calcium doses?',
'["A. Twice as much","B. Three times as much","C. 1.5 times as much","D. Equal phosphate binding at same dose"]',
'A',
'DiPiro Ch47 states "Calcium acetate binds approximately twice as much phosphorus as calcium carbonate at comparable doses of elemental calcium." Increased binding potency also limits GI calcium absorption, reducing the risk of hypercalcaemia. However, calcium acetate is more soluble than carbonate, which may affect absorption characteristics. Both agents remain effective first-line phosphate binders in CKD.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Sevelamer hydrochloride differs fundamentally from calcium-based phosphate binders in that it:',
'["A. Requires co-administration with active vitamin D for efficacy","B. Does not contain calcium or aluminium (non-elemental agent)","C. Acts by alkaline pH to precipitate phosphate","D. Is absorbed systemically to bind phosphate in the bloodstream"]',
'B',
'Sevelamer hydrochloride (Renagel) is described as a "nonelemental agent" in DiPiro Table 47-6 — it contains neither calcium nor aluminium. It is a cross-linked polyamine polymer that binds phosphate in the gut through ion-exchange and hydrogen-bonding. It reduces the risk of hypercalcaemia seen with calcium-based binders and vascular calcification risk, making it preferred in patients with elevated calcium or Ca × P product.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'The K/DOQI guideline target for calcium-phosphorus product (Ca × P) in CKD Stage 3, 4, and 5 is:',
'["A. <65 mg²/dL²","B. <70 mg²/dL²","C. <60 mg²/dL²","D. <55 mg²/dL²"]',
'D',
'DiPiro Ch47 Table 47-5 specifies Ca × P <55 mg²/dL² for ALL stages 3, 4, and 5 CKD. This is lower than the previously cited 65-70 mg²/dL² target. A Ca × P above 72 mg²/dL² is associated with a 34% higher risk of death compared to the reference range. Elevated Ca × P drives soft tissue and vascular calcification, accelerating cardiovascular disease — the leading cause of death in ESRD.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'The K/DOQI target intact parathyroid hormone (iPTH) level for CKD Stage 4 is:',
'["A. 70-110 pg/mL","B. 35-70 pg/mL","C. 150-300 pg/mL","D. <35 pg/mL"]',
'A',
'DiPiro Ch47 Table 47-5 specifies iPTH targets by CKD stage: Stage 3 = 35-70 pg/mL; Stage 4 = 70-110 pg/mL; Stage 5 = 150-300 pg/mL. The iPTH target for later stages is maintained ABOVE the normal range to prevent adynamic bone disease (over-suppression). The target for Stage 5 is higher (150-300) because reduced vitamin D and calcium-sensing receptor activity in advanced disease means higher PTH is needed to maintain bone turnover.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Calcitriol (active vitamin D) suppresses secondary hyperparathyroidism by acting directly on which organ?',
'["A. Adrenal gland","B. Pituitary gland","C. Parathyroid gland","D. Thyroid gland"]',
'C',
'Calcitriol (1,25-dihydroxyvitamin D₃) suppresses PTH production by acting directly on the parathyroid gland, reducing prepro-PTH mRNA transcription and reducing parathyroid cell proliferation. It also promotes intestinal calcium absorption, which indirectly raises ionised calcium and suppresses PTH via the calcium-sensing receptor. In CKD, the kidneys fail to convert 25-OH vitamin D to active calcitriol via 1α-hydroxylase (DiPiro Ch47).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'In CKD Stages 3-4, 25-hydroxyvitamin D levels below what threshold are associated with elevated PTH and warrant supplementation?',
'["A. 20 ng/mL","B. 30 ng/mL","C. 40 ng/mL","D. 50 ng/mL"]',
'B',
'DiPiro Ch47 states: "In patients with stage 3 or 4 CKD, 25-hydroxyvitamin D levels of <30 ng/mL are associated with increased PTH." This has led to recommendations for evaluation of 25-OH vitamin D levels and supplementation with ergocalciferol (vitamin D₂) or cholecalciferol (vitamin D₃) in CKD Stages 3-4 patients with deficiency, prior to using active vitamin D analogues (calcitriol or paricalcitol).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Osteitis fibrosa cystica (high-turnover bone disease) in CKD renal osteodystrophy is caused by:',
'["A. Low bone turnover from aluminium toxicity","B. Low PTH and adynamic bone disease","C. Impaired bone mineralisation from vitamin D deficiency alone","D. Sustained high PTH causing peritrabecular fibrosis and high bone formation rates"]',
'D',
'Osteitis fibrosa cystica is the high-turnover bone disease caused by sustained elevation of PTH (secondary hyperparathyroidism). It is characterised by areas of peritrabecular fibrosis and a high bone formation rate. Dynamic measurements show elevated markers of bone turnover. Bone marrow fibrosis from OFC also causes decreased erythropoiesis, contributing to ESA resistance. Aluminium toxicity causes the opposite — low-turnover osteomalacia (DiPiro Ch47).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'K/DOQI guidelines recommend parathyroidectomy for secondary hyperparathyroidism when iPTH persistently exceeds what level, with refractory hypercalcaemia or hyperphosphataemia?',
'["A. 300 pg/mL","B. 500 pg/mL","C. 800 pg/mL","D. 1000 pg/mL"]',
'C',
'DiPiro Ch47 states: "K/DOQI recommends surgery only for patients with persistently elevated iPTH (iPTH >800 pg/mL) associated with hypercalcaemia and/or hyperphosphataemia that are refractory to medical therapy." Surgical options are subtotal parathyroidectomy or total parathyroidectomy with forearm autotransplantation. Postoperative "hungry bone syndrome" (hypocalcaemia, hypophosphataemia, hypomagnesaemia) requires intensive monitoring.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Clinically significant metabolic acidosis in CKD typically develops when GFR falls below:',
'["A. 20-30 mL/min per 1.73 m²","B. 45-60 mL/min per 1.73 m²","C. 10-15 mL/min per 1.73 m²","D. 30-45 mL/min per 1.73 m²"]',
'A',
'DiPiro Ch47 states that "a clinically significant metabolic acidosis is commonly seen when the GFR drops below 20 to 30 mL/min (stage 4 CKD)." In severe CKD, the kidney''s ability to synthesise ammonia (the primary urinary buffer for acid excretion) is impaired, leading to positive hydrogen ion balance. Plasma bicarbonate stabilises at 15-20 mEq/L. Treatment with oral sodium bicarbonate supplements aims to maintain bicarbonate >22 mEq/L.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'In severe CKD with metabolic acidosis, plasma bicarbonate concentration tends to stabilise at approximately:',
'["A. 10-15 mEq/L","B. 15-20 mEq/L","C. 20-22 mEq/L","D. 22-24 mEq/L (normal)"]',
'B',
'DiPiro Ch47 states that in patients with CKD-related metabolic acidosis (typically GFR <20-30 mL/min), "the plasma bicarbonate concentration tends to stabilize at 15 to 20 mEq/L." This occurs because hydrogen ion generation from protein metabolism continues, but renal acid excretion via urinary ammonium is impaired. Bone acts as a buffer by releasing calcium carbonate, contributing to renal osteodystrophy.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Significant hyperkalaemia in CKD patients typically does NOT develop until GFR falls below:',
'["A. 45 mL/min per 1.73 m²","B. 30 mL/min per 1.73 m²","C. 20 mL/min per 1.73 m²","D. 10 mL/min per 1.73 m²"]',
'C',
'DiPiro Ch47 states: "the serum potassium concentration is usually maintained in the normal range until the GFR is less than 20 mL/min per 1.73 m²." This is because as nephrons are lost, surviving tubules compensate by increasing aldosterone-mediated potassium secretion, and the colon also increases potassium excretion. However, these adaptations are overwhelmed below GFR 20 mL/min, causing mild hyperkalaemia to develop.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Per the Ghana STG, what is the FIRST drug to administer in the management of ADULT AKI hyperkalaemia (the sequence matters)?',
'["A. Soluble insulin 10 units in 50-100 mL Dextrose 50%","B. Sodium bicarbonate 8.4% (50 mEq/50 mL), 1-2 mL/kg over 5 min","C. Salbutamol nebulised 5 mg","D. Calcium gluconate 10%, 10-20 mL slow IV over 2-5 minutes"]',
'D',
'The Ghana STG hyperkalaemia management for adults lists calcium gluconate FIRST: "Calcium gluconate 10%, IV, 10-20 mL, slow IV, over 2-5 minutes" — followed by insulin/dextrose, then bicarbonate. Calcium gluconate acts within minutes to stabilise cardiac membranes (cardioprotective) without lowering potassium. Insulin/glucose and bicarbonate then shift potassium intracellularly. Note: calcium gluconate and bicarbonate MUST NOT be mixed in the same line (Ghana STG Ch14).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'In children OVER 25 kg with hyperkalaemia, the Ghana STG lists which treatment as PREFERRED (above calcium gluconate and insulin)?',
'["A. Salbutamol nebulised 5 mg","B. Calcium gluconate 10% IV 0.5-1 mL/kg over 5-10 minutes","C. Soluble insulin 0.2 units/kg in 5 mL Dextrose 20%","D. Sodium bicarbonate 8.4%, 1-2 mL/kg over 5 minutes"]',
'A',
'The Ghana STG Ch14 specifies for children with hyperkalaemia: "Salbutamol, nebulised, (preferred) >25 kg: 5 mg; <25 kg: 2.5 mg." Salbutamol activates β₂-adrenergic receptors, stimulating Na⁺/K⁺-ATPase and driving potassium intracellularly. It is listed as preferred in children because it is safe, non-invasive, and avoids IV access challenges. Calcium gluconate and insulin/dextrose are alternatives but not the preferred first-line in children per this guideline.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'For CKD patients with hyperkalaemia on hemodialysis, dietary potassium restriction is typically set at:',
'["A. 30-50 mEq/day","B. 50-80 mEq/day","C. 80-100 mEq/day","D. 100-120 mEq/day"]',
'B',
'DiPiro Ch47 specifies "dietary potassium restriction of 50 to 80 mEq/day" combined with reduction in dialysate potassium concentrations for hemodialysis patients. Peritoneal dialysis patients are allowed more liberal potassium intake because peritoneal dialysis removes more potassium. High-potassium foods to avoid include bananas, coconut, dried beans, and citrus fruits — consistent with the Ghana STG dietary advice.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'The K/DOQI recommended dietary phosphorus restriction for stage 3-5 CKD patients with hyperphosphataemia is:',
'["A. 500-700 mg/day","B. 700-800 mg/day","C. 800-1000 mg/day","D. 1000-1200 mg/day"]',
'C',
'DiPiro Ch47 states: "K/DOQI guidelines recommend phosphorus restriction to 800 to 1,000 mg/day when the upper levels of phosphorus are reached." The challenge is that foods high in phosphorus (meats, dairy products, dried beans, nuts, cola drinks, peanut butter) are also high in protein, and CKD patients must avoid malnutrition. Dialysis patients need ~1.2-1.3 g protein/kg/day, making phosphorus restriction even more difficult.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'The Ghana STG explicitly states that calcium gluconate and sodium bicarbonate must NOT be:',
'["A. Given to the same patient within 1 hour of each other","B. Administered to patients with hypocalcaemia","C. Used without continuous cardiac monitoring","D. Mixed in the same delivery system (IV line)"]',
'D',
'The Ghana STG (Notes 14-5, 14-6, 14-8, 14-9) repeatedly emphasises: "Do not mix calcium gluconate and bicarbonate in the same delivery system." Mixing causes precipitation of calcium carbonate, rendering both drugs ineffective and potentially blocking the IV line. In hyperkalaemia management, both drugs must be given sequentially through separate IV access or with a saline flush between them.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Secondary hyperparathyroidism in CKD initially develops in response to which metabolic disturbance caused by nephron loss?',
'["A. Hypocalcaemia and hyperphosphataemia stimulating PTH release","B. Decreased aldosterone production causing electrolyte imbalance","C. Increased calcitriol synthesis driving calcium reabsorption","D. Hypercalcaemia from dietary excess overwhelming renal excretion"]',
'A',
'As nephrons are lost, phosphate excretion decreases → hyperphosphataemia → reciprocal decrease in serum calcium → hypocalcaemia stimulates PTH release. Additionally, failing 1α-hydroxylase in the kidney reduces calcitriol production → less intestinal calcium absorption → further hypocalcaemia. Hyperphosphataemia also directly stimulates PTH synthesis. The result is secondary hyperparathyroidism — PTH "trades off" against normal calcium (DiPiro Ch47, Fig. 47-1).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Cyclosporin and tacrolimus cause calcineurin inhibitor nephrotoxicity primarily through which mechanism?',
'["A. Crystal deposition and proximal tubular obstruction","B. Decreased prostaglandin production causing vasoconstriction","C. Direct tubular cell DNA injury via reactive oxygen species","D. Immune-mediated interstitial nephritis from T-cell activation"]',
'B',
'The Ghana STG lists cyclosporin/tacrolimus nephrotoxicity as caused by "Decreased PG (prostaglandin) and increased 20-HETE acid production → vasoconstriction → generation of H₂O₂ → depleted glutathione → decreased GFR, ischaemic collapse or scarring of glomeruli, vacuolisation of tubules, and focal tubular atrophy and interstitial fibrosis." Prevention requires maintaining levels within the therapeutic range and avoiding CYP3A4 inhibitors that raise calcineurin inhibitor levels.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Which of the following is NOT listed in the Ghana STG as an indication for dialysis in AKI/CKD?',
'["A. Pulmonary oedema from fluid overload","B. Metabolic acidosis","C. Hyponatraemia","D. Uraemic symptoms (seizures, pericarditis)"]',
'C',
'Ghana STG (Note 14-7) lists dialysis indications: (1) congestive heart failure, (2) pulmonary oedema, (3) electrolyte abnormalities ESPECIALLY hyperkalaemia not controlled by conservative means, (4) metabolic acidosis, (5) uraemic symptoms (seizures, pericarditis), and (6) hypertensive crises/encephalopathy. Hyponatraemia alone is NOT listed as an indication — it is typically managed with fluid restriction or hypertonic saline, not dialysis.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Aminoglycoside nephrotoxicity causes AKI via which specific mechanism in the proximal tubule?',
'["A. Crystal precipitation blocking tubular lumens","B. Reduced prostaglandin-mediated vasoconstriction","C. Immune complex deposition causing membranoproliferative changes","D. Endocytic uptake via megalin receptor → intracellular accumulation → direct tubular cell toxicity"]',
'D',
'The Ghana STG explains: "In proximal tubule, aminoglycoside bound to anionic phospholipid, delivered to megalin (receptor on proximal tubule cells), endocytic uptake into the cell. Within cell, accumulates — direct toxicity — AKI." Aminoglycosides accumulate selectively in the renal cortex (proximal tubules). Prevention requires maintaining therapeutic drug monitoring (trough <2 mg/L for gentamicin), once-daily dosing where appropriate, and avoiding concurrent nephrotoxins.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Per the Ghana STG CKD management table (Table 14-2), annual monitoring for CKD Stage 3 should include:',
'["A. Serum calcium, phosphate, and PTH if Hb <11 g/dL check ferritin/B12/folate","B. Monthly serum creatinine and weekly haemoglobin","C. Quarterly lipid panels and monthly urine albumin","D. Daily blood pressure and weekly potassium levels"]',
'A',
'Ghana STG Table 14-2 for CKD Stage 3 specifies: "Estimate and treat complications: If Hb <11 g/dL check Ferritin, B12 and folate. Annual check of serum calcium, phosphate and PTH. Refer if eGFR ≤30 mL/min/1.73 m²." This annual monitoring aims to detect secondary hyperparathyroidism and metabolic bone disease early (before symptomatic renal osteodystrophy develops) and to screen for haematological deficiencies driving anaemia.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'"Hungry bone syndrome" following parathyroidectomy is characterised by which combination of electrolyte abnormalities?',
'["A. Hypercalcaemia, hyperphosphataemia, and hypermagnesaemia","B. Hypocalcaemia, hypophosphataemia, and hypomagnesaemia","C. Hypokalaemia, hyponatraemia, and hypocalcaemia","D. Hyperphosphataemia, hyperkalaemia, and hypocalcaemia"]',
'B',
'DiPiro Ch47 states that after parathyroidectomy, "postoperative hypocalcaemia, hypophosphataemia, and hypomagnesaemia may occur because of a marked increase in bone production in relation to bone absorption (''hungry bone syndrome'')." Removal of the chronically elevated PTH allows bone to avidly take up calcium and phosphate for remineralisation, dramatically lowering serum levels. Ionised calcium monitoring every 4-6 hours is required for the first 48-72 hours post-surgery.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Mineral and Bone Disorder','medium','Pharmacology','mcq',
'Following parathyroidectomy for secondary hyperparathyroidism, ionised calcium should be maintained above what level using calcium gluconate infusions if needed?',
'["A. 2.5 mg/dL (0.6 mmol/L)","B. 3.0 mg/dL (0.75 mmol/L)","C. 3.6 mg/dL (0.9 mmol/L)","D. 4.0 mg/dL (1.0 mmol/L)"]',
'C',
'DiPiro Ch47 specifies: "Ionized calcium should be maintained above 3.6 mg/dL (0.9 mmol/L), using calcium gluconate infusions if necessary. The recommended dose of calcium gluconate is 1 to 2 mg of elemental calcium per kilogram per hour, adjusted to maintain ionized calcium at 4.6 to 5.4 mg/dL (1.15 to 1.36 mmol/L)." Once stable, oral calcium carbonate (1-2 g) plus calcitriol up to 2 mcg/day is initiated.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14');

