-- Renal Pharmacology MCQs Q26-50: Anaemia management in CKD
-- Source: DiPiro Ch47, Ghana STG 2017 Ch14

INSERT INTO questions (professions, course, topic, subtopic, difficulty, category, question_type, question_text, options, correct_answer, explanation, year_level, region, high_yield, source_reference) VALUES

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'The primary cause of anaemia in chronic kidney disease is:',
'["A. Iron deficiency from occult gastrointestinal bleeding","B. Folate deficiency due to dietary restriction in CKD","C. Decreased erythropoietin production by the kidney","D. Haemolysis from uremic toxins"]',
'C',
'The kidneys produce 90% of endogenous erythropoietin. As GFR declines, erythropoietin production falls, leading to decreased red blood cell production (normochromic, normocytic anaemia). In ESRD, there is no correlation between anaemia severity and erythropoietin concentrations — EPO production is simply inadequate. Other contributing factors include shortened RBC lifespan (~60 days in ESRD vs normal 120 days), iron deficiency, and blood loss (DiPiro Ch47).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'In ESRD patients, red blood cell lifespan is reduced from the normal 120 days to approximately:',
'["A. 90 days","B. 80 days","C. 70 days","D. 60 days"]',
'D',
'Uraemic toxins impair red blood cell membrane function and accelerate haemolysis, reducing RBC lifespan from the normal 120 days to approximately 60 days in ESRD patients. This shortened survival contributes to anaemia alongside EPO deficiency, iron deficiency (from blood loss and inadequate absorption), and blood loss during hemodialysis sessions (DiPiro Ch47).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'The K/DOQI guidelines recommend evaluating haemoglobin in ALL patients with CKD, noting increased anaemia prevalence beginning at which stage?',
'["A. Stage 3","B. Stage 2","C. Stage 4","D. Stage 5"]',
'A',
'DiPiro Ch47 states that K/DOQI recommends evaluating haemoglobin in all CKD patients, "noting the increase in anemia prevalence beginning with stage 3." The prevalence of Hb <13 g/dL increases considerably in stages 3-5 CKD. The Ghana STG Table 14-2 also specifies that at CKD Stage 3, if Hb <11 g/dL, check ferritin, B12, and folate. Early detection allows timely iron supplementation and ESA therapy.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'The target haemoglobin range for anaemia of CKD per the Ghana STG is:',
'["A. 10-11 g/dL","B. 11-12 g/dL","C. 12-13 g/dL","D. 10-12 g/dL"]',
'B',
'The Ghana STG (Section 138) specifies a target Hb range of 11-12 g/dL for anaemia of CKD. DiPiro Ch47 similarly notes that the K/DOQI-recommended target Hb is ~11 g/dL (with ESA therapy withheld if Hb >12 g/dL per new FDA/CMS guidance). Targeting Hb >12 g/dL has not shown additional benefit and may increase cardiovascular risk in dialysis patients.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Which laboratory values define ABSOLUTE iron deficiency requiring iron supplementation in CKD patients on ESA therapy?',
'["A. TSat <30% and serum ferritin <200 ng/mL","B. TSat <25% and serum ferritin <150 ng/mL","C. TSat <20% and serum ferritin <100 ng/mL","D. TSat <15% and serum ferritin <50 ng/mL"]',
'C',
'DiPiro Ch47 defines absolute iron deficiency in non-hemodialysis CKD patients as TSat <20% and serum ferritin <100 ng/mL. For hemodialysis patients, the ferritin threshold is <200 ng/mL. These thresholds trigger iron supplementation (oral or IV). The recommended oral elemental iron dose is 200 mg/day. IV iron is preferred in hemodialysis patients due to poor oral absorption and blood loss from dialysis sessions.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'The recommended daily dose of ORAL elemental iron for correction of absolute iron deficiency in CKD patients is:',
'["A. 100 mg/day","B. 150 mg/day","C. 180 mg/day","D. 200 mg/day"]',
'D',
'DiPiro Ch47 recommends 200 mg of elemental iron per day as the oral iron dose for correction of absolute iron deficiency. Ferrous sulphate 325 mg tablets contain 65 mg elemental iron (requiring ~3 tablets daily). Adverse effects including constipation, nausea, and abdominal cramping affect >50% of patients receiving 200 mg elemental iron/day and may require administration with food (reducing absorption) or switching to IV iron.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Which intravenous iron preparation carries a BLACK BOX WARNING for anaphylactic reactions and requires a 25-mg test dose before the first full dose?',
'["A. Iron dextran","B. Iron sucrose","C. Sodium ferric gluconate","D. Ferric carboxymaltose"]',
'A',
'Iron dextran (INFeD, DexFerrum) carries a black box warning for risk of anaphylactic reactions (estimated 0.6% serious reactions including respiratory and cardiovascular collapse) and requires a 25-mg test dose before the full dose. Iron sucrose (Venofer) and sodium ferric gluconate (Ferrlecit) do NOT require test doses and have better safety profiles. Adverse reactions are reported more frequently with Dexferrum than INFeD (DiPiro Ch47 Table 47-4).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Iron sucrose (Venofer) is FDA-approved for hemodialysis patients. What is the approved IV push dose and rate?',
'["A. 50 mg over 1-2 min","B. 100 mg over 2-5 min","C. 125 mg over 10 min","D. 200 mg over 5 min"]',
'B',
'DiPiro Ch47 Table 47-4 specifies iron sucrose (Venofer) IV push at 100 mg over 2-5 minutes for hemodialysis patients. Alternatively, it can be given as an infusion: 100 mg in up to 100 mL 0.9% NaCl over 15 minutes. For non-dialysis CKD patients, iron sucrose is given as 200 mg over 2-5 min on 5 different occasions within 14 days. Iron sucrose is supplied as 5-mL vials containing 100 mg elemental iron (20 mg/mL).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'The anaemia of CKD (in the absence of iron or folate deficiency) is characteristically which morphological type?',
'["A. Microcytic hypochromic","B. Macrocytic (megaloblastic)","C. Normochromic normocytic","D. Microcytic normochromic"]',
'C',
'The anaemia of CKD due to EPO deficiency alone is normochromic normocytic — red cells are of normal size and haemoglobin content, but simply fewer in number. If iron deficiency co-exists, anaemia becomes microcytic hypochromic. If folate or B12 deficiency co-exists (e.g., in dialysis patients), it becomes macrocytic. The Ghana STG therefore recommends checking ferritin, B12, and folate when Hb <11 g/dL in CKD Stage 3 (DiPiro Ch47).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Per the Ghana STG for CKD Stages 1-2 anaemia, which is the FIRST-LINE pharmacological treatment?',
'["A. Ferrous sulphate 325 mg 8 hourly for 4 weeks","B. Iron sucrose IV (consult specialist)","C. Epoetin beta SC (consult specialist)","D. Ferrous gluconate 300 mg 8-12 hourly"]',
'A',
'The Ghana STG (Section 138) specifies ferrous sulphate 325 mg 8 hourly for 4 weeks as the first-line treatment for anaemia in CKD Stages 1-2. IV iron and ESAs are reserved for Stages 3-5 (with specialist consultation). Early oral iron supplementation corrects iron deficiency anaemia at low CKD stages before EPO deficiency becomes the dominant mechanism. Evaluating after 4-6 weeks assesses response.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Functional iron deficiency in dialysis patients is characterised by:',
'["A. Low TSat (<20%) and low serum ferritin (<100 ng/mL)","B. Low TSat (<20%) with normal or elevated serum ferritin","C. Normal TSat with low serum ferritin (<50 ng/mL)","D. High TSat (>50%) with low serum ferritin"]',
'B',
'Functional iron deficiency means iron is present in storage (normal/elevated ferritin) but is not being delivered to the bone marrow for erythropoiesis — reflected by low TSat (<20%) despite normal/elevated ferritin. This may be due to reticuloendothelial blockade in inflammatory states. A trial of IV iron may be warranted if Hb <11 g/dL and TSat <25% even with ferritin >500 ng/mL (DiPiro Ch47).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Per new FDA/CMS recommendations, ESA therapy should be withheld when haemoglobin exceeds:',
'["A. 10 g/dL","B. 11 g/dL","C. 11.5 g/dL","D. 12 g/dL"]',
'D',
'DiPiro Ch47 states: "New FDA and CMS recommendations advise health care providers to withhold ESA therapy if the Hb is >12 g/dL; some clinicians may institute a dosage reduction of ≥25% to prevent drastic shifts in Hb levels." Maintaining Hb above 13 g/dL in ESRD patients has been associated with increased cardiovascular events and mortality in landmark trials (CHOIR, CREATE).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'If a patient''s haemoglobin rises by more than 1 g/dL over a 2-WEEK period while on ESA therapy, the dose should be:',
'["A. Increased by 25%","B. Maintained at current dose","C. Reduced by 25%","D. Reduced by 50%"]',
'C',
'DiPiro Ch47 specifies: if Hb change is >1 g/dL over 2 weeks → reduce ESA dose by 25%. Conversely, if Hb change is <1 g/dL over 4 weeks → increase ESA dose by 25%. Rapid Hb increases risk hypertension, thrombosis, and cardiovascular events. Target Hb changes of approximately 1-2 g/dL/month are considered safe during initiation or dose changes.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Among oral iron preparations, which product contains the HIGHEST amount of elemental iron per tablet?',
'["A. Ferrous fumarate (Nephro-Fer 350 mg) — 115 mg elemental iron","B. Ferrous sulphate (325 mg) — 65 mg elemental iron","C. Ferrous gluconate (325 mg) — 36 mg elemental iron","D. Polysaccharide iron (Niferex 50 mg) — 50 mg elemental iron"]',
'A',
'DiPiro Table 47-3 lists oral iron preparations with their elemental iron content. Ferrous fumarate (Nephro-Fer 350 mg) contains 115 mg elemental iron — the highest per tablet among common preparations. Ferrous sulphate 325 mg contains 65 mg, ferrous gluconate 325 mg contains only 36 mg, and polysaccharide iron (Niferex 50 mg) contains 50 mg. Nephro-Fer is specifically formulated for renal patients.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Oral iron absorption can be significantly reduced by which class of medications commonly used in CKD patients?',
'["A. ACE inhibitors","B. Proton pump inhibitors and H2-antagonists","C. Calcium channel blockers","D. Beta-blockers"]',
'B',
'DiPiro Ch47 states that proton pump inhibitors and H2-antagonists increase gastric pH, which reduces iron absorption (iron absorption is maximised in an acidic duodenal environment). Calcium preparations and antacids also reduce oral iron absorption. Additionally, oral iron reduces absorption of quinolone antibiotics. Patients should be advised to take iron on an empty stomach for optimal absorption, although GI side effects may necessitate taking it with food.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Darbepoetin alfa differs from epoetin alfa as an ESA because it:',
'["A. Is given by the intravenous route only","B. Has a shorter half-life requiring more frequent dosing","C. Lacks erythropoietic activity and requires a co-factor","D. Is hyperglycosylated with a longer half-life, allowing less frequent dosing"]',
'D',
'Darbepoetin alfa is a hyperglycosylated analogue of erythropoietin with approximately 3× the half-life of epoetin alfa, allowing less frequent administration (e.g., once monthly vs. one to three times weekly for epoetin alfa). Both agents are effective at treating anaemia of CKD and the choice is primarily based on cost, as both are available. The longer half-life of darbepoetin may reduce administration costs (DiPiro Ch47).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'During initial ESA treatment, iron status (TSat and ferritin) should be monitored at what frequency?',
'["A. Every month","B. Every 2 months","C. Every 3 months","D. Every 6 months"]',
'A',
'DiPiro Ch47 states: "Iron status should be assessed every month during initial ESA treatment, and every 3 months for those receiving a stable ESA regimen." Monthly monitoring during initiation allows timely iron supplementation if iron deficiency develops from the increased erythropoiesis stimulated by ESA therapy. Haemoglobin should be monitored at least monthly, and more frequently (every 2 weeks) after ESA initiation or dose changes until stable.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Per Ghana STG Section 138, the preferred route of administration for ESA therapy (epoetin beta, darbepoetin alfa) in CKD Stages 3-4 is:',
'["A. Intravenous","B. Oral","C. Subcutaneous","D. Intramuscular"]',
'C',
'The Ghana STG lists all ESAs for CKD Stages 3-4 as given subcutaneously (SC): "Epoietin beta, SC, consult specialist" and "Methoxy polyethylene glycol epoietin beta (pegylated form), SC, consult specialist" and "Darbepoietin alfa, SC, consult specialist." SC administration is preferred over IV for non-hemodialysis patients for cost-effectiveness; SC dosing achieves equivalent clinical outcomes at lower doses than IV dosing.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Deferoxamine (Desferal) or phlebotomy may be required in CKD patients with which complication of iron therapy?',
'["A. Anaphylaxis","B. Iron overload","C. Functional iron deficiency","D. ESA resistance"]',
'B',
'Excess IV iron administration can cause iron overload, depositing in the liver, pancreas, and heart — leading to hepatic, pancreatic, and cardiac dysfunction. Bone marrow biopsy confirms iron overload definitively. If symptomatic overload occurs, deferoxamine chelation or phlebotomy (in non-anaemic patients) may be necessary. Prevention involves not administering IV iron when ferritin is already elevated (especially >500 ng/mL) without evidence of iron deficiency (DiPiro Ch47).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Oral iron supplements decrease the absorption of which class of antibiotics, requiring separation of administration?',
'["A. Beta-lactams (penicillins, cephalosporins)","B. Aminoglycosides","C. Macrolides","D. Quinolones (fluoroquinolones)"]',
'D',
'DiPiro Ch47 specifically notes that oral iron decreases the absorption of quinolone antibiotics (e.g., ciprofloxacin, levofloxacin). This interaction is clinically significant because quinolones are important agents for UTI treatment in CKD patients. Oral iron and quinolones should be separated by at least 2 hours. Calcium preparations and antacids similarly reduce quinolone absorption through chelation.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'In hemodialysis patients, the standard IV iron repletion regimen using iron dextran or iron sucrose involves administering 100 mg over how many dialysis sessions?',
'["A. 10 sessions","B. 8 sessions","C. 6 sessions","D. 5 sessions"]',
'A',
'DiPiro Ch47 states the FDA-approved repletion regimen: "100 mg as iron sucrose or iron dextran over 10 dialysis sessions, or 125 mg of sodium ferric gluconate over 8 dialysis sessions." Administering small divided doses over multiple sessions reduces the risk of adverse reactions compared to single large-dose infusions and aligns with the frequency of hemodialysis attendance (typically 3× per week = 10 sessions over ~3.5 weeks).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Sodium ferric gluconate (Ferrlecit) is FDA-approved for iron supplementation in which specific population?',
'["A. Peritoneal dialysis patients only","B. Adult and paediatric hemodialysis patients aged ≥6 years receiving ESA therapy","C. Non-dialysis CKD patients not receiving ESA therapy","D. Post-renal transplant patients"]',
'B',
'DiPiro Table 47-4 specifies that sodium ferric gluconate (Ferrlecit) is FDA-approved for "Adult and pediatric hemodialysis (HD) patients age 6 years and older receiving ESA therapy." The adult IV push dose is 125 mg over 10 min; the paediatric dose is 1.5 mg/kg in 25 mL 0.9% NaCl over 60 min (max 125 mg). Iron sucrose has broader approval including non-dialysis CKD patients.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Calcium carbonate is more effective as a phosphate binder when taken in which context?',
'["A. At bedtime, away from food","B. With a glass of milk or dairy","C. Before or with meals, when gastric acid is highest","D. On an empty stomach between meals"]',
'C',
'Calcium carbonate is more soluble in an acidic environment. DiPiro Ch47 states it "should be administered prior to meals when stomach acidity is highest." Acid-suppressing agents (PPIs, H2-antagonists) reduce gastric acid and may reduce calcium carbonate''s phosphate-binding efficacy. Additionally, calcium carbonate''s role as a phosphate binder requires food (phosphate source) to be present in the gut for binding to occur.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Proton pump inhibitors may reduce the phosphate-binding efficacy of calcium carbonate through which mechanism?',
'["A. Increasing gastric pH, reducing calcium carbonate solubility and disintegration","B. Directly binding to calcium carbonate in the gastrointestinal tract","C. Increasing intestinal motility, reducing contact time with phosphate","D. Competing with calcium ions for phosphate-binding sites"]',
'A',
'DiPiro Ch47 explains that "acid-suppressing agents such as ranitidine and proton pump inhibitors may reduce the phosphate-binding activity of calcium carbonate by increasing gastric pH." Calcium carbonate requires an acidic environment to dissolve and disintegrate properly. Higher pH reduces its solubility, impairs disintegration, and thus reduces its ability to bind dietary phosphate in the gastrointestinal tract.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','Anaemia of CKD','medium','Pharmacology','mcq',
'Per the Ghana STG, which intravenous fluid is preferred over 0.9% NaCl for AKI due to hypovolaemia from diarrhoea and vomiting, provided the patient does NOT have hyperkalaemia?',
'["A. 5% Dextrose","B. 0.45% NaCl (half-normal saline)","C. Hartmann''s solution","D. Ringer''s lactate"]',
'D',
'The Ghana STG Ch14 (Section 136) specifies: "Sodium Chloride 0.9% IV, OR Ringer''s lactate (if there is no hyperkalaemia) in cases of diarrhoea and vomiting." Ringer''s lactate more closely approximates plasma electrolyte composition and contains lactate which is metabolised to bicarbonate, helpful in metabolic acidosis from diarrhoea. However, it contains potassium (4 mEq/L), so it must be avoided in hyperkalaemia.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch47; Ghana STG 2017 Ch14');

