-- Renal A&P MCQs Batch 1 (Q1-25) — Nephron Anatomy & Glomerular Filtration
-- Source: DiPiro Pharmacotherapy 7th ed Ch.44 + Ghana STG 2017 Ch.14
-- Run when Supabase connector is back online

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Nephron Anatomy','easy','mcq','What is the functional unit of the kidney?','["A. Nephron","B. Glomerulus","C. Bowman''s capsule","D. Collecting duct"]','A','The nephron is the functional unit of the kidney. Each kidney contains approximately one million nephrons comprising a glomerulus, Bowman capsule, proximal tubule, loop of Henle, distal tubule, and collecting duct. Through filtration, secretion, and reabsorption the nephron regulates water, electrolytes, and solute excretion.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Nephron Anatomy','easy','mcq','Which structure directly receives the ultrafiltrate after it crosses the glomerular capillary wall?','["A. Proximal convoluted tubule","B. Loop of Henle","C. Bowman''s capsule","D. Distal convoluted tubule"]','C','The glomerular filtrate passes across the glomerular-capillary membrane into Bowman capsule. From there it enters the proximal convoluted tubule. The glomerulus and Bowman capsule together form the renal corpuscle.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Nephron Anatomy','easy','mcq','Glomerular filtration is primarily which type of process?','["A. Active transport requiring ATP","B. A passive process driven by hydrostatic pressure","C. Carrier-mediated facilitated diffusion","D. Receptor-mediated endocytosis"]','B','Glomerular filtration is a passive process. Water and small-molecular-weight solutes (<5-10 kDa) diffuse across the glomerular capillary membrane driven by the net hydrostatic pressure difference, minus the opposing oncotic pressure. No ATP is required.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Nephron Anatomy','medium','mcq','What is the approximate molecular weight cutoff below which substances are freely filtered at the glomerulus?','["A. Less than 60 kDa","B. Less than 40 kDa","C. Less than 20 kDa","D. Less than 5 to 10 kDa"]','D','Glomerular filtration allows passage of small-molecular-weight ions and molecules less than approximately 5 to 10 kDa. Most plasma proteins are too large (>60 kDa) to be substantially filtered. The electronegative charge on the glomerular epithelial surface also repels negatively charged proteins such as albumin.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Nephron Anatomy','medium','mcq','Why are protein-bound drugs generally NOT filtered at the glomerulus?','["A. The glomerular membrane completely lacks filtration pores","B. Active transport is required for drug filtration","C. Proteins are too large and electronegatively charged, preventing filtration of protein-bound compounds","D. Hydrostatic pressure is too low to filter any bound molecules"]','C','Compounds in the protein-bound state are not filtered because the binding protein (usually albumin, ~67 kDa) is too large to cross the glomerular membrane. The electronegative charge on the glomerular epithelial surface further restricts passage. Only the free (unbound) fraction of a drug is filtered.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','Where does active tubular secretion of drugs predominantly occur in the nephron?','["A. Proximal tubule","B. Glomerulus","C. Loop of Henle","D. Collecting duct"]','A','Secretion is an active process that predominantly occurs in the proximal tubule. Highly efficient anionic and cationic transport systems handle a wide range of endogenous and exogenous substances. The renal clearance of actively secreted compounds can greatly exceed GFR, reaching 600-1000 mL/min (e.g., PAH, penicillin).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','Creatinine is secreted in the proximal tubule by which transport system?','["A. Anionic transport system","B. P-glycoprotein efflux pump","C. Aquaporin water channels","D. Cationic transport system"]','D','The proximal tubule contains an anionic system (secretes PAH, penicillin, probenecid) and a cationic system (secretes creatinine, cimetidine, procainamide). Tubular secretion of creatinine means serum creatinine slightly overestimates GFR compared to true inulin clearance.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','PAH (para-aminohippurate) clearance is the clinical gold standard marker for measuring:','["A. Glomerular filtration rate","B. Renal plasma blood flow","C. Tubular reabsorption capacity","D. Distal tubule secretory capacity"]','B','PAH is almost completely extracted by the kidney on a single pass through both filtration and proximal tubule secretion (anionic system). Its clearance therefore approximates total renal plasma flow (RPF). Normal RPF is approximately 600-700 mL/min. 99mTc-MAG3 and 131I-OIH are nuclear medicine alternatives.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Inulin is the gold standard for measuring GFR because it is:','["A. Freely filtered and actively secreted by the proximal tubule","B. Filtered and partially reabsorbed in the distal tubule","C. Freely filtered and neither secreted nor reabsorbed by renal tubules","D. Bound to albumin but released during glomerular filtration"]','C','Inulin is freely filtered at the glomerulus and is neither secreted nor reabsorbed by the tubules. Its clearance therefore equals the volume of plasma completely cleared per unit time, which equals GFR. Other exogenous GFR markers include iothalamate, iohexol, and 99mTc-DTPA.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','Reabsorption of most lipid-soluble medications in the nephron occurs predominantly along:','["A. Distal tubule and collecting duct","B. Glomerulus and Bowman''s capsule","C. Proximal tubule and thick ascending limb only","D. Loop of Henle only"]','A','While the proximal tubule handles most electrolyte and nutrient reabsorption, drug reabsorption occurs predominantly along the distal tubule and collecting duct. Urine flow rate and pH influence this process. Highly ionized compounds are not readily reabsorbed; changes in urine pH that increase the un-ionized fraction facilitate drug reabsorption.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Nephron Anatomy','easy','mcq','The Bowman capsule channels its ultrafiltrate directly into which tubular segment?','["A. Loop of Henle directly","B. Distal convoluted tubule","C. Collecting duct","D. Proximal convoluted tubule"]','D','The glomerulus and Bowman capsule form the renal corpuscle. Filtrate flows from Bowman capsule into the proximal convoluted tubule (PCT). The PCT performs bulk reabsorption of sodium, glucose, amino acids, water, and bicarbonate — approximately 65-70% of the filtered load.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Nephron Anatomy','medium','mcq','The intact nephron hypothesis states that as nephrons are progressively lost due to disease:','["A. Remaining nephrons proportionally reduce their function","B. Remaining functional nephrons compensate by hyperfunctioning","C. The kidney regenerates new nephrons to maintain total GFR","D. GFR remains constant due to hormonal compensation alone"]','B','The intact nephron hypothesis (Bricker) proposes that remaining healthy nephrons compensate by increasing their individual (single-nephron) GFR. This is why whole-kidney GFR may remain near-normal until extensive injury occurs. This compensatory hyperfiltration ultimately contributes to progressive sclerosis and CKD progression.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','P-glycoprotein is an efflux transporter located on which membrane of the proximal tubule cell?','["A. Basolateral membrane","B. Basement membrane","C. Apical (luminal) membrane","D. Brush border of the distal tubule"]','C','P-glycoprotein (P-gp) is located on the apical (luminal) membrane of the proximal tubule, functioning as an efflux pump secreting substrates into the tubular lumen. Important substrates include digoxin, cimetidine, and procainamide. Inhibitors (verapamil, cyclosporine) reduce renal elimination of P-gp substrates.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','Which agent inhibits P-glycoprotein-mediated renal tubular secretion, potentially raising plasma levels of co-administered drugs?','["A. Furosemide","B. Probenecid","C. Metformin","D. Verapamil"]','D','Verapamil and cyclosporine are the two most widely studied P-glycoprotein inhibitors at the proximal tubule. Blockade of P-gp reduces renal elimination of substrates such as digoxin and procainamide, leading to increased drug exposure and potential toxicity. This is a clinically important drug-drug interaction.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','easy','mcq','The normal range of urine pH is:','["A. 4.5 to 7.8","B. 3.0 to 5.5","C. 5.5 to 9.0","D. 6.0 to 8.5"]','A','Normal urine pH ranges from 4.5 to 7.8. A pH above this may suggest urea-splitting bacteria causing UTI (e.g., Proteus mirabilis). In renal tubular acidosis type I (distal RTA), urine pH is persistently above 5.5 due to impaired H+ secretion in the distal tubule. Alkaline urine can also cause false-positive dipstick proteinuria.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Which is the MOST accurate exogenous method for measuring GFR?','["A. Serum creatinine concentration alone","B. Inulin clearance following intravenous administration","C. Cockcroft-Gault estimation from serum creatinine","D. Cystatin C serum level"]','B','Inulin clearance following IV administration is the gold standard for GFR measurement because inulin is freely filtered and neither secreted nor reabsorbed. Its limitations include the need for constant IV infusion and timed urine collections, making it impractical for routine clinical use. Equations (Cockcroft-Gault, MDRD, CKD-EPI) are estimates only.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','The Cockcroft-Gault formula estimates which parameter of renal function?','["A. GFR in mL/min/1.73 m2","B. Urine creatinine excretion rate","C. Creatinine clearance (CLcr) in mL/min","D. Cystatin C clearance"]','C','The Cockcroft-Gault equation estimates creatinine clearance (CLcr) in mL/min: CLcr = [(140 - age) x weight] / (72 x SCr), multiplied by 0.85 for females. It slightly overestimates GFR because creatinine is also secreted by the tubules. It remains the most widely used formula for drug dose individualisation in renal impairment.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','In the Cockcroft-Gault equation, the CLcr in females is adjusted by multiplying by:','["A. 0.72","B. 0.90","C. 1.15","D. 0.85"]','D','Women have less muscle mass than men of the same age and weight and therefore produce less creatinine. The Cockcroft-Gault correction factor for females is 0.85. Failure to apply this correction overestimates CLcr in females, potentially leading to drug overdosing in renally impaired female patients.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','easy','mcq','Which variable is NOT included in the Cockcroft-Gault formula for estimating creatinine clearance?','["A. Blood pressure","B. Age","C. Serum creatinine","D. Body weight"]','A','The Cockcroft-Gault formula uses age, body weight, serum creatinine, and sex (via the 0.85 female correction). Blood pressure is not a variable. For obese patients, ideal body weight or adjusted body weight is substituted to avoid overestimation of CLcr.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Persistent proteinuria observed on at least 3 occasions over 3 to 6 months is the principal marker of:','["A. Urinary tract infection","B. Kidney damage in chronic kidney disease","C. Acute glomerulonephritis only","D. Drug-induced nephrotoxicity"]','B','Persistent albuminuria or proteinuria is recognised as the principal marker of kidney damage in CKD. The NKF recommends spot urine albumin-to-creatinine ratio (ACR) for severity assessment. Microalbuminuria (ACR 3-30 mg/mmol) indicates early CKD, while macroalbuminuria (>30 mg/mmol) indicates more advanced damage.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','Glucosuria occurs when blood glucose exceeds which approximate renal threshold?','["A. 100 mg/dL","B. 140 mg/dL","C. 180 mg/dL","D. 250 mg/dL"]','C','The kidney reabsorbs glucose in the proximal tubule via SGLT2 and SGLT1 transporters. When blood glucose exceeds ~180 mg/dL, the transport maximum is exceeded and glucose appears in the urine. SGLT2 inhibitors exploit this mechanism by lowering the renal threshold for glucose, promoting glycosuria even at normal blood glucose levels.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','easy','mcq','The presence of nitrite on a urine dipstick most commonly indicates:','["A. Proteinuria from nephrotic syndrome","B. Haematuria from glomerulonephritis","C. Diabetic ketoacidosis","D. Urinary tract infection from gram-negative bacteria"]','D','Urinary nitrate is converted to nitrite by gram-negative bacteria (e.g., E. coli). A positive nitrite dipstick test suggests UTI. False-negatives occur with non-nitrate-reducing organisms (enterococci, Staphylococcus saprophyticus) or dilute urine. Leukocyte esterase is a complementary test. In Ghana, E. coli is the most common cause of UTI.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44; Ghana STG 7th ed Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','99mTc-DTPA is an exogenous marker used to measure:','["A. Glomerular filtration rate","B. Renal plasma blood flow","C. Tubular secretion capacity","D. Collecting duct function"]','A','99mTc-DTPA (technetium-99m diethylenetriaminepentaacetic acid) is freely filtered at the glomerulus and not secreted or reabsorbed, making it a GFR marker used in nuclear medicine renal scintigraphy. In contrast, 99mTc-MAG3 (mercaptoacetyltriglycine) is secreted by the proximal tubule and measures renal plasma flow.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Most healthy adults excrete approximately how much albumin in the urine per day?','["A. Less than 10 mg/day","B. 100 to 150 mg/day","C. Approximately 30 mg/day","D. 200 to 300 mg/day"]','C','Most healthy individuals excrete between 30 and 150 mg/day of total protein, of which approximately 30 mg/day is albumin. Excretion of 30-300 mg/day of albumin (microalbuminuria) is an early marker of CKD or diabetic nephropathy. The remainder of urinary protein includes Tamm-Horsfall protein and smaller proteins such as beta-2-microglobulin.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Nephron Anatomy','medium','mcq','Renal function includes all of the following EXCEPT:','["A. Filtration and excretion of nitrogenous wastes","B. Bile acid conjugation and secretion into bile","C. Erythropoietin synthesis and secretion","D. Activation of vitamin D3 to calcitriol"]','B','Bile acid conjugation is a hepatic function, not renal. The kidney''s functions include: excretory (filtration, secretion, reabsorption), endocrine (renin, erythropoietin, prostaglandins), and metabolic (1-alpha-hydroxylation of 25-OH vitamin D3 to calcitriol, gluconeogenesis, insulin metabolism). Loss of these metabolic functions contributes to complications of CKD.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44');
