-- Renal A&P MCQs Batch 4 (Q76-100) — Advanced Renal Physiology, Urinalysis, Ghana-specific AKI/CKD
-- Source: DiPiro Pharmacotherapy 7th ed Ch.44 + Ghana STG 2017 Ch.14
-- Correct answer distribution: A=7, B=6, C=6, D=6

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','In the emergency management of severe hyperkalaemia, which drug is given FIRST and why?','["A. Calcium gluconate 10% IV — to stabilize cardiac membranes","B. Sodium bicarbonate IV — to shift K+ into cells","C. Soluble insulin with dextrose IV — to promote intracellular K+ uptake","D. Furosemide IV — to increase renal K+ excretion"]','A','In severe hyperkalaemia with ECG changes (peaked T waves, wide QRS), calcium gluconate 10% IV (10-20 mL over 2-5 minutes) is given FIRST to stabilize cardiac cell membranes and prevent fatal arrhythmias — it does NOT lower serum K+. Subsequently, insulin/dextrose and sodium bicarbonate shift K+ intracellularly. Furosemide is used to promote K+ excretion only if the patient has adequate urine output. Calcium must NOT be mixed with bicarbonate in the same IV line (precipitates).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','In the management of hyperkalaemia, IV insulin (with dextrose) lowers serum potassium by which mechanism?','["A. Increasing renal K+ excretion via ROMK channel upregulation","B. Stimulating Na+/K+-ATPase, driving K+ into skeletal muscle and liver cells","C. Reducing dietary K+ absorption in the gastrointestinal tract","D. Inhibiting aldosterone, reducing K+ accumulation in the collecting duct"]','B','Insulin activates Na+/K+-ATPase, pumping K+ into skeletal muscle, liver, and other cells — typically lowering serum K+ by 0.5-1.5 mEq/L within 15-30 minutes. Per Ghana STG, 10 units soluble insulin is given in 50-100 mL dextrose 50% to prevent hypoglycaemia. This effect is temporary (2-4 hours) and must be followed by definitive K+ removal (dialysis, loop diuretics in those with adequate urine output, or sodium polystyrene sulfonate).','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','The nadir (lowest point) of diurnal variation in serum creatinine generally occurs at:','["A. 7:00 PM","B. Midnight","C. The morning","D. 3:00 PM"]','C','Serum creatinine exhibits diurnal variation; the peak occurs at approximately 7:00 PM and the nadir in the morning. For 24-hour creatinine clearance calculations, the plasma creatinine sample is typically obtained in the morning during stable renal function to minimise the impact of diurnal variation. The urine collection must span a full 24 hours and be stored at pH <6 to prevent creatinine-to-creatine interconversion.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Why do elderly, cachectic, or malnourished patients often have a "normal" serum creatinine despite significantly reduced GFR?','["A. They have increased tubular secretion of creatinine","B. They produce more creatinine from dietary meat","C. Their kidneys retain creatinine by increased tubular reabsorption","D. They have reduced muscle mass and therefore produce less creatinine"]','D','Creatinine is derived from creatine metabolism in skeletal muscle. Individuals with reduced muscle mass (elderly, cachexia, malnutrition, spinal cord injury) produce less creatinine; consequently, serum creatinine may appear normal even when GFR is significantly impaired. This is why relying on Scr alone is unreliable in these populations — GFR estimation equations (using age, weight) or cystatin C are preferred for accurate assessment.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Endocrine Functions','medium','mcq','A patient with CKD stage 4 has secondary hyperparathyroidism due to calcitriol deficiency. Which vitamin D preparation is MOST appropriate?','["A. Calcitriol or active vitamin D analogs (paricalcitol, doxercalciferol)","B. Cholecalciferol (vitamin D3) alone — relies on renal 1-alpha-hydroxylation","C. Ergocalciferol (vitamin D2) alone — most potent inactive form","D. Vitamin D-binding protein supplements"]','A','In CKD, 1-alpha-hydroxylase activity is impaired, so inactive forms (cholecalciferol, ergocalciferol) cannot be converted to active calcitriol. Calcitriol itself (1,25-dihydroxyvitamin D3) or analogs that bypass 1-alpha-hydroxylation (paricalcitol, doxercalciferol) must be prescribed. They suppress PTH, prevent secondary hyperparathyroidism, and prevent renal osteodystrophy (osteitis fibrosa cystica, osteomalacia). Cholecalciferol alone is insufficient in CKD stages 3-5.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','AKI Staging','medium','mcq','G6PD deficiency is listed in the Ghana STG 2017 as a medical cause of AKI primarily through which mechanism?','["A. Direct tubular toxicity from G6PD enzyme accumulation","B. Haemolysis with subsequent haemoglobinuria causing tubular injury","C. Glomerular immune complex deposition","D. Interstitial nephritis from oxidative stress"]','B','G6PD deficiency predisposes to acute intravascular haemolysis when triggered by oxidative stressors (antimalarials such as primaquine, sulfonamides, infections, fava beans). Massive haemolysis releases haemoglobin into circulation; free haemoglobin filtered at the glomerulus is directly toxic to proximal tubule cells, causing acute tubular necrosis and AKI. This is particularly important in Sub-Saharan Africa, including Ghana, where G6PD deficiency is prevalent (especially in males).','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','CKD Staging','medium','mcq','Which class of drugs is explicitly listed in the Ghana STG 2017 as a nephrotoxin to be avoided in CKD?','["A. ACE inhibitors","B. Loop diuretics","C. Non-steroidal anti-inflammatory drugs (NSAIDs)","D. Calcium channel blockers"]','C','Ghana STG 2017 explicitly advises avoiding nephrotoxins in CKD, specifically listing NSAIDs (and herbal medications). NSAIDs inhibit prostaglandin synthesis, reducing afferent arteriole vasodilation and GFR. In CKD, prostaglandins play a compensatory role in maintaining renal perfusion; blocking them can precipitate acute-on-chronic kidney injury. ACE inhibitors and ARBs are actually renoprotective in CKD with proteinuria.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Hyaline casts in urine are composed of which protein and are considered:','["A. Red blood cells — pathognomonic for glomerulonephritis","B. White blood cells — indicating interstitial nephritis","C. Fat droplets — diagnostic of nephrotic syndrome","D. Tamm-Horsfall mucoprotein — nonspecific, may appear in concentrated normal urine"]','D','Hyaline casts consist of Tamm-Horsfall mucoprotein, secreted by the renal tubules. They are nonspecific and may appear in concentrated urine, after vigorous exercise, or mild dehydration — not necessarily indicating pathology. In contrast: RBC casts indicate glomerulonephritis; WBC casts indicate interstitial nephritis or pyelonephritis; granular/muddy-brown casts are associated with acute tubular necrosis; fatty casts (with lipid droplets) are associated with nephrotic syndrome.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','The presence of dysmorphic red blood cells in urine microscopy suggests:','["A. Renal parenchymal origin, most likely glomerulonephritis","B. Lower urinary tract infection","C. Bladder transitional cell carcinoma","D. Prerenal azotaemia from volume depletion"]','A','Dysmorphic (acanthocytic) red blood cells indicate glomerular origin — RBCs are distorted as they squeeze through the damaged glomerular basement membrane and traverse the varying osmotic environments of the tubular lumen. More than 2 RBCs per high-power field on microscopy is abnormal. Isomorphic (normal-shaped) red cells suggest lower urinary tract bleeding (bladder cancer, calculi, infection). The combination of RBCs + RBC casts is highly specific for glomerulonephritis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Red blood cell (RBC) casts on urine microscopy are most strongly associated with:','["A. Prerenal azotaemia","B. Glomerulonephritis","C. Obstructive uropathy","D. Acute tubular necrosis"]','B','RBC casts indicate that red blood cells of renal (glomerular) origin became entrapped in Tamm-Horsfall protein within the collecting tubule. Their presence is highly specific for glomerulonephritis or renal vasculitis (e.g., lupus nephritis, IgA nephropathy, post-infectious GN). WBC casts indicate interstitial nephritis or pyelonephritis. Granular/muddy-brown granular casts are characteristic of acute tubular necrosis. Prerenal azotaemia typically shows normal urinalysis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Normal renal plasma flow (RPF), as measured by PAH clearance, is approximately:','["A. 120 mL/min","B. 350 mL/min","C. 600 to 700 mL/min","D. 1,000 mL/min"]','C','Normal RPF, measured by PAH clearance, is approximately 600-700 mL/min (total renal blood flow ~1,000 mL/min, with ~60% plasma). RPF can also be estimated by nuclear medicine using 99mTc-MAG3 and 131I-OIH. The filtration fraction (FF) = GFR/RPF ≈ 120/600 = 20%. In conditions such as severe heart failure, hepatorenal syndrome, or renal artery stenosis, RPF decreases, reducing FF and GFR.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','At normal GFR (120 mL/min) and renal plasma flow (600 mL/min), the filtration fraction is:','["A. 5%","B. 10%","C. 30%","D. 20%"]','D','Filtration fraction = GFR ÷ RPF = 120 ÷ 600 = 0.20 = 20%. This means 20% of plasma flowing through the glomerular capillaries is filtered into Bowman''s capsule. An elevated filtration fraction (e.g., in heart failure, where RPF falls more than GFR) indicates increased intraglomerular pressure or reduced RPF relative to GFR, which over time promotes glomerulosclerosis and proteinuria — contributing to CKD progression.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','The thick ascending limb (TAL) of the loop of Henle is impermeable to water. This property allows it to:','["A. Dilute tubular fluid and concentrate the medullary interstitium — essential for countercurrent multiplication and urine concentration","B. Passively reabsorb water via aquaporin-1","C. Produce highly concentrated urine directly","D. Prevent urea from recycling into the medullary interstitium"]','A','The TAL actively reabsorbs Na+, K+, and Cl- via NKCC2 without allowing water to follow (no aquaporins), thereby diluting tubular fluid and concentrating the medullary interstitium (the countercurrent multiplier mechanism). This osmotic gradient is required for water reabsorption in the collecting duct under ADH control, enabling production of concentrated urine. Furosemide disrupts this gradient by blocking NKCC2, impairing urinary concentration.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Endocrine Functions','medium','mcq','Which organ is responsible for the final activation step of vitamin D, converting 25-OH vitamin D3 to calcitriol?','["A. Liver","B. Kidney (proximal tubule)","C. Intestine","D. Parathyroid gland"]','B','Vitamin D activation is a two-step process: (1) cholecalciferol → 25-OH vitamin D3 (calcidiol) in the liver by CYP27A1; (2) calcidiol → 1,25-dihydroxyvitamin D3 (calcitriol) in the proximal tubule of the kidney by CYP27B1 (1-alpha-hydroxylase). Step 2 is stimulated by PTH, low phosphate, and low calcium, and inhibited by FGF-23. In CKD, step 2 is impaired, necessitating active vitamin D supplementation (calcitriol, paricalcitol).','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','AKI Staging','medium','mcq','In children presenting with AKI in Ghana, which common cause should be particularly considered?','["A. Amyloidosis","B. Polycystic kidney disease","C. Diarrhoea and dehydration","D. Lupus nephritis"]','C','The Ghana STG 2017 lists diarrhoea, vomiting, and dehydration prominently among medical causes of AKI, and congenital abnormalities of the genitourinary tract as predisposing factors in children. Malaria is also a major cause of AKI in Ghanaian children through haemolysis. Diarrhoeal disease causing severe dehydration is the most common reversible cause of prerenal AKI in children across Sub-Saharan Africa and should always be considered first.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','AKI Staging','medium','mcq','Which obstetric condition is listed in the Ghana STG 2017 as a cause of AKI?','["A. Gestational diabetes mellitus","B. Iron deficiency anaemia in pregnancy","C. Pre-term labour","D. Severe pre-eclampsia or eclampsia"]','D','Ghana STG 2017 lists the following obstetric causes of AKI: septic abortion, post-caesarean section, severe pre-eclampsia/eclampsia, postpartum haemorrhage (PPH), and HELLP syndrome (Haemolysis, Elevated Liver Enzymes, Low Platelets). Pre-eclampsia causes AKI through intense vasospasm reducing renal perfusion and glomerular endothelial injury. These obstetric AKI causes are particularly relevant in Ghana where access to antenatal care remains limited in some regions.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Post-infectious (post-streptococcal) glomerulonephritis characteristically presents with:','["A. Haematuria, erythrocyte casts, proteinuria, and oedema following streptococcal infection","B. Massive proteinuria (>3.5 g/day), hypoalbuminaemia, and hyperlipidaemia","C. Sterile pyuria, white cell casts, and flank pain","D. Painless haematuria with ring-shaped calcium oxalate crystals"]','A','Post-infectious GN (predominantly post-streptococcal, most common in children) presents with haematuria, erythrocyte casts, proteinuria <2 g/24h, oliguria, oedema, and hypertension, typically 1-3 weeks after streptococcal pharyngitis or skin infection. ASO titres may be elevated; complement C3 is typically low. Treatment is supportive: furosemide for oedema, antihypertensives for hypertension. Most cases resolve spontaneously in children.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Which Plasmodium species is most commonly associated with malarial nephropathy presenting as nephrotic syndrome in Ghana?','["A. Plasmodium vivax","B. Plasmodium malariae","C. Plasmodium falciparum","D. Plasmodium ovale"]','B','Plasmodium malariae causes quartan malarial nephropathy (membranoproliferative glomerulonephritis) presenting as nephrotic syndrome in Sub-Saharan Africa, including Ghana. Immune complex deposition (malarial antigen-antibody) in the glomerulus leads to proteinuria and progressive renal damage. P. falciparum causes acute renal failure through haemolysis and microvascular obstruction. Both species are endemic in Ghana.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','CKD Staging','medium','mcq','A patient with eGFR <15 mL/min/1.73 m2 and uraemic symptoms. According to the Ghana STG 2017, what is the definitive management?','["A. ACE inhibitor and dietary protein restriction alone","B. High-dose furosemide and fluid restriction only","C. Kidney replacement therapy — dialysis or transplantation","D. Erythropoietin injections to restore GFR"]','C','CKD Stage 5 (kidney failure) requires kidney replacement therapy (KRT): haemodialysis, peritoneal dialysis, or renal transplantation. Ghana STG specifies referral to a centre with dialysis facilities. Erythropoietin manages renal anaemia but does not restore GFR. ACE inhibitors and dietary restriction slow progression in earlier stages but are not curative at Stage 5. Without KRT, uraemia leads to multisystem failure and death.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','The normal adult reference range for serum cystatin C is:','["A. 0.20 to 0.60 mg/L","B. 1.50 to 3.00 mg/L","C. 0.30 to 1.00 mg/L","D. 0.54 to 1.21 mg/L"]','D','The normal adult serum cystatin C reference range is 0.54-1.21 mg/L. In children older than 1 year, the range is 0.70-1.38 mg/L. Cystatin C begins to rise when GFR falls below approximately 88 mL/min/1.73 m2 — detecting kidney injury earlier than serum creatinine (which rises at GFR ~75 mL/min/1.73 m2). However, specificity is limited by non-GFR variables including corticosteroid therapy, inflammation, and thyroid disease.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Endocrine Functions','hard','mcq','In CKD, impaired phosphate excretion leads to hyperphosphataemia, which triggers a cascade resulting in which skeletal complication?','["A. Renal osteodystrophy (bone demineralisation and pain)","B. Hypercalcaemic crisis","C. Hypophosphataemia and hypercalcaemia","D. Osteoporosis from vitamin D excess"]','A','In CKD: reduced GFR → impaired phosphate excretion → hyperphosphataemia → phosphate binds calcium → hypocalcaemia → secondary hyperparathyroidism (elevated PTH) → PTH mobilises calcium and phosphate from bone → renal osteodystrophy (osteitis fibrosa cystica, osteomalacia, adynamic bone disease). Treatment: dietary phosphate restriction, phosphate binders (calcium carbonate, sevelamer), calcitriol supplementation to suppress PTH.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Which blood investigation is essential in evaluating both AKI and anaemia of CKD, according to the Ghana STG 2017?','["A. Prothrombin time (PT/INR)","B. Full blood count (FBC) with reticulocyte count and serum ferritin","C. Thyroid function tests","D. Serum amylase and lipase"]','B','Ghana STG 2017 recommends FBC as part of the initial investigation for both AKI and CKD-related anaemia. In anaemia of CKD, reticulocyte count (typically low in EPO deficiency), transferrin saturation, and serum ferritin differentiate EPO deficiency from iron deficiency anaemia. Ferrous sulphate 325 mg 8-hourly is started for CKD stages 1-2; EPO-stimulating agents are added for stages 3-4 alongside iron. Target Hb is 11-12 g/dL.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Urine osmolality is considered more accurate than specific gravity for assessing renal concentrating ability when:','["A. A patient is severely dehydrated","B. Urine pH is very alkaline","C. Large quantities of heavy molecules such as glucose or radiographic contrast dye are present in urine","D. A patient is taking loop diuretics"]','C','Specific gravity measures urine weight relative to water and is influenced by the molecular mass of solutes. When heavy molecules like glucose (~180 Da) or iodinated contrast (>800 Da) are present, specific gravity is disproportionately elevated relative to the actual number of osmotically active particles. Osmolality (measuring particle number, not mass) provides a more accurate assessment. Normal urine osmolality ranges from 50 to 1200 mOsm/kg depending on hydration status.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','AKI Staging','medium','mcq','KDIGO Stage 2 AKI urine output criterion is:','["A. Urine output <0.5 mL/kg/hr for 6-12 hours","B. Urine output <0.3 mL/kg/hr for >24 hours","C. Anuria for >6 hours","D. Urine output <0.5 mL/kg/hr for more than 12 hours"]','D','KDIGO AKI urine output staging: Stage 1 = <0.5 mL/kg/hr for 6-12 hours; Stage 2 = <0.5 mL/kg/hr for >12 hours; Stage 3 = <0.3 mL/kg/hr for >24 hours OR anuria for >12 hours. These urine output criteria may detect AKI earlier than serum creatinine changes. Strict fluid balance monitoring with hourly urine output measurement is essential in any patient at risk of AKI, including post-surgical patients and those with sepsis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Strenuous physical exercise is associated with which change in serum creatinine?','["A. An approximate 10% increase due to increased creatine metabolism in exercising muscle","B. A decrease due to increased GFR from enhanced renal blood flow","C. No change — serum creatinine is unaffected by exercise","D. A 50% increase persisting for up to 7 days"]','A','Strenuous exercise increases creatine turnover in skeletal muscle, transiently raising serum creatinine by approximately 10%. This increase resolves within 24 hours of rest. In severe rhabdomyolysis (massive muscle breakdown), myoglobin and creatinine rise dramatically, causing AKI through tubular toxicity. Patients should avoid strenuous exercise for ≥24 hours before a 24-hour creatinine clearance test, and blood sampling should be timed consistently to minimise diurnal variation.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44');
