-- Renal A&P MCQs Batch 3 (Q51-75) — Tubular Physiology, Markers, CKD/AKI Management
-- Source: DiPiro Pharmacotherapy 7th ed Ch.44 + Ghana STG 2017 Ch.14
-- Correct answer distribution: A=6, B=6, C=7, D=6

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','Hydrochlorothiazide reduces sodium reabsorption by blocking which transporter in the distal convoluted tubule (DCT)?','["A. NKCC2 cotransporter","B. Epithelial sodium channel (ENaC)","C. Sodium-chloride cotransporter (NCC)","D. Na+/H+ exchanger (NHE3)"]','C','Thiazide diuretics inhibit the Na+-Cl- cotransporter (NCC, SLC12A3) on the apical membrane of the DCT. This reduces NaCl reabsorption and results in mild diuresis. Thiazides are first-line for hypertension in CKD stages 1-2. However, their efficacy decreases when GFR falls below 30 mL/min/1.73 m2 (stages 3-5), where loop diuretics (targeting NKCC2 in the TAL) are preferred. NKCC2 is the furosemide target in the TAL; ENaC is blocked by amiloride.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','The proximal convoluted tubule reabsorbs approximately what percentage of the filtered sodium load?','["A. 20 to 25%","B. 5 to 10%","C. 50 to 55%","D. 65 to 70%"]','D','The proximal convoluted tubule handles approximately 65-70% of filtered sodium, water, glucose, amino acids, and potassium, plus 80-90% of filtered bicarbonate. This bulk reabsorption is driven by Na+/K+-ATPase on the basolateral membrane and multiple luminal transporters including NHE3, SGLT2, and sodium-phosphate cotransporters. SGLT2 inhibitors (e.g., dapagliflozin) block proximal tubule glucose reabsorption, promoting glucosuria.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','Bicarbonate reabsorption in the proximal tubule is critically dependent on which enzyme?','["A. Carbonic anhydrase","B. Alkaline phosphatase","C. Gamma-glutamyl transferase","D. Renin"]','A','Carbonic anhydrase (CA II intracellular, CA IV luminal) catalyzes conversion of CO2 + H2O to H+ + HCO3-. H+ is secreted into the tubular lumen via NHE3, where it combines with filtered HCO3- to form H2CO3, which is converted back to CO2 + H2O by brush-border CA IV. CO2 diffuses into the cell and regenerates HCO3-. Net: filtered bicarbonate is reabsorbed. Acetazolamide (CA inhibitor) causes bicarbonate diuresis — used in altitude sickness and metabolic alkalosis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','CKD Staging','easy','mcq','According to the Ghana STG 2017, CKD Stage 5 (kidney failure) is defined by an eGFR of:','["A. Less than 30 mL/min/1.73 m2","B. Less than 15 mL/min/1.73 m2","C. Less than 45 mL/min/1.73 m2","D. Less than 60 mL/min/1.73 m2"]','B','Ghana STG 2017 CKD staging: Stage 1 (>90), Stage 2 (60-89), Stage 3 (30-59), Stage 4 (15-29), Stage 5 (<15 mL/min/1.73 m2). Stage 5 represents kidney failure requiring renal replacement therapy (dialysis or transplantation). At Stage 5, patients develop uraemic symptoms, severe electrolyte disturbances, and fluid overload. Referral to a nephrologist is mandatory.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','CKD Staging','medium','mcq','A patient has eGFR 72 mL/min/1.73 m2 with microalbuminuria persistently for 6 months. Which CKD stage does this represent?','["A. Stage 1","B. Stage 3","C. Stage 2","D. Stage 4"]','C','Stage 2 CKD is defined as kidney damage with mildly reduced eGFR of 60-89 mL/min/1.73 m2 persisting for >3 months. Note that Stage 1 (eGFR >90) can also be CKD if kidney damage markers (microalbuminuria, haematuria, structural abnormality) are present — GFR alone is insufficient without damage markers. Annual monitoring of eGFR and urinary ACR is recommended for Stage 2.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14; DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','AKI Staging','medium','mcq','Which of the following is a recognized indication for dialysis in AKI, according to the Ghana STG 2017?','["A. Serum creatinine 200 micromol/L","B. Urine output <1 mL/kg/hr for 3 hours","C. Nephrotic-range proteinuria","D. Metabolic acidosis unresponsive to medical treatment"]','D','Ghana STG 2017 dialysis indications for AKI include: congestive heart failure, pulmonary oedema, hyperkalaemia not controlled by conservative measures, metabolic acidosis, uraemic symptoms (seizures, pericarditis), and hypertensive crises/encephalopathy. Serum creatinine level alone does not determine dialysis need — clinical status drives the decision. Early referral to a dialysis-capable centre is essential.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','AKI Staging','medium','mcq','Which of the following is a Ghana-specific medical cause of AKI listed in the Ghana Standard Treatment Guidelines 2017?','["A. Use of herbal medicines","B. Obstructive prostatic hypertrophy","C. Contrast-induced nephropathy","D. Aminoglycoside nephrotoxicity"]','A','The Ghana STG 2017 explicitly lists herbal medicines (alongside malaria, typhoid fever, G6PD deficiency, diarrhoea/dehydration, and acute glomerulonephritis) as a medical cause of AKI. Herbal preparations may contain nephrotoxic plant compounds, aristolochic acid, or heavy metals. Patients should be counselled to avoid herbal medications in the context of renal impairment or AKI risk. This is a locally important consideration given widespread traditional medicine use in Ghana.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','AKI Staging','medium','mcq','According to KDIGO, which urine output criterion alone is sufficient to diagnose AKI Stage 3?','["A. Urine output <0.5 mL/kg/hr for 18 hours","B. Urine output <0.3 mL/kg/hr for more than 24 hours","C. Urine output <0.5 mL/kg/hr for more than 12 hours","D. Anuria for 6 hours"]','B','KDIGO AKI urine output criteria: Stage 1 = <0.5 mL/kg/hr for 6-12 hours; Stage 2 = <0.5 mL/kg/hr for >12 hours; Stage 3 = <0.3 mL/kg/hr for >24 hours OR anuria for >12 hours. A UO of <0.5 mL/kg/hr for 18h meets Stage 2, not Stage 3. Anuria for only 6 hours does not meet any stage by urine output alone. UO criteria may identify AKI earlier than serum creatinine changes.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','easy','mcq','The normal serum creatinine concentration for males and females is generally within which range?','["A. 0.2 to 0.8 mg/dL","B. 1.5 to 3.0 mg/dL","C. 0.5 to 1.5 mg/dL","D. 2.0 to 4.0 mg/dL"]','C','The normal serum creatinine range is 0.5 to 1.5 mg/dL, though values vary by sex, race, muscle mass, and age. Males typically have higher Scr due to greater muscle mass (mean 1.16 mg/dL vs 0.96 mg/dL in women per NHANES III). Serum creatinine alone is a poor GFR indicator — it only rises significantly when GFR falls below 50-60 mL/min. GFR estimation equations are required for accurate assessment.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','A patient is started on cimetidine. How does this affect the measured creatinine clearance?','["A. It increases CLcr by stimulating glomerular filtration","B. It reduces creatinine production by inhibiting muscle metabolism","C. It increases apparent CLcr by promoting tubular creatinine secretion","D. It decreases measured CLcr by inhibiting tubular secretion of creatinine"]','D','Cimetidine (and trimethoprim) compete with creatinine at the cationic organic cation transport system (OCT2) in the proximal tubule, reducing tubular secretion of creatinine. This lowers urinary creatinine concentration and thus reduces measured CLcr — making it a closer approximation of true GFR (since ideal GFR markers are not secreted). A 400 mg cimetidine dose reduces the CLcr:inulin clearance ratio from approximately 1.30 to 1.03.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Besides proteinuria and hypoalbuminaemia, which metabolic complication is part of the classic nephrotic syndrome tetrad?','["A. Hyperlipidaemia","B. Haematuria","C. Hypertension","D. Hypercalcaemia"]','A','The classic nephrotic syndrome tetrad is: massive proteinuria (>3.5 g/24h), hypoalbuminaemia, generalised oedema (from reduced oncotic pressure), and hyperlipidaemia (from increased hepatic lipoprotein synthesis compensating for low oncotic pressure). A hypercoagulable state also occurs due to urinary loss of antithrombin III and proteins C and S. Haematuria and hypertension are features of nephritic, not nephrotic, syndrome.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44; Ghana STG 7th ed Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Using spot urine albumin-to-creatinine ratio (ACR), microalbuminuria is defined as:','["A. ACR <3 mg/mmol","B. ACR 3 to 30 mg/mmol (approximately 30 to 300 mg/g)","C. ACR >30 mg/mmol","D. Total protein excretion >500 mg/g creatinine"]','B','Microalbuminuria is defined as an albumin-to-creatinine ratio of 3-30 mg/mmol (approximately 30-300 mg albumin per gram creatinine). Values <3 mg/mmol are normal; >30 mg/mmol represents macroalbuminuria (clinical proteinuria). Microalbuminuria is the earliest detectable marker of diabetic nephropathy and early CKD. Annual ACR screening is recommended for all patients with diabetes or hypertension per the NKF and Ghana STG.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44; Ghana STG 7th ed Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','easy','mcq','Normal GFR in healthy adult women averages:','["A. 127 ± 20 mL/min/1.73 m2","B. 100 ± 15 mL/min/1.73 m2","C. 118 ± 20 mL/min/1.73 m2","D. 140 ± 20 mL/min/1.73 m2"]','C','Normal GFR in healthy adult men is approximately 127 ± 20 mL/min/1.73 m2 while in women it is 118 ± 20 mL/min/1.73 m2. Women have lower GFR partly because of lower muscle mass and different renal haemodynamics. GFR declines with age. The Cockcroft-Gault formula accounts for sex by multiplying by 0.85 for females, reflecting their lower creatinine production rate.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','AKI Staging','medium','mcq','According to KDIGO AKI staging criteria, anuria for how long qualifies as Stage 3 AKI based on urine output alone?','["A. 3 hours","B. 6 hours","C. 18 hours","D. More than 12 hours"]','D','KDIGO AKI Stage 3 urine output criterion: <0.3 mL/kg/hr for >24 hours OR anuria for >12 hours. Anuria is complete absence of urine production. When present for >12 hours, it represents Stage 3 AKI even without serum creatinine data, and renal replacement therapy should be considered if conservative management fails. Maintaining strict fluid intake-output charts is essential in all AKI patients.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Endocrine Functions','medium','mcq','The primary mechanism of anaemia in chronic kidney disease is:','["A. Deficiency of erythropoietin production by the failing kidneys","B. Iron deficiency from urinary iron losses","C. Vitamin B12 malabsorption due to uraemic gastritis","D. Red cell aplasia from retained uraemic toxins"]','A','Anaemia of CKD is primarily caused by deficiency of erythropoietin (EPO), produced by peritubular fibroblasts. As renal mass decreases in CKD, EPO production falls proportionally. EPO deficiency is nearly universal at CKD Stage 5. Contributing factors include iron deficiency, shortened red cell survival from uraemic toxins, and bone marrow suppression. Iron supplementation is added alongside EPO-stimulating agents as most patients also have functional iron deficiency.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44; Ghana STG 7th ed Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Endocrine Functions','medium','mcq','Left ventricular hypertrophy (LVH) is present in what proportion of chronic kidney disease patients?','["A. Less than 10%","B. More than 40%","C. 60 to 80%","D. Approximately 25%"]','B','Left ventricular hypertrophy is present in more than 40% of CKD patients, driven by hypertension, volume overload, and anaemia-induced increased cardiac work. LVH is a major risk factor for sudden cardiac death, heart failure, and arrhythmias. The cardiorenal anaemia syndrome links CKD, EPO suppression, normocytic anaemia, and progressive cardiovascular disease in a vicious cycle. EPO-stimulating agents improving Hb to 11-12 g/dL help reduce LVH.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','CKD Staging','medium','mcq','The Ghana Standard Treatment Guidelines 2017 recommend restricting dietary protein in CKD patients to:','["A. 2 g/kg/day","B. 0.5 g/kg/day","C. 1 g/kg/day","D. 1.5 g/kg/day"]','C','Ghana STG 2017 recommends restricting dietary protein to 1 g/kg/day for CKD patients to reduce nitrogenous waste production and slow CKD progression. KDIGO recommends 0.8 g/kg/day for non-dialysis CKD, but protein intake should not fall below 0.6-0.8 g/kg/day to avoid malnutrition. Excessive protein increases urea production and proteinuria, accelerating nephron loss. Dialysis patients paradoxically require higher protein (1.2-1.4 g/kg/day) to compensate for dialytic losses.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','CKD Staging','medium','mcq','According to the Ghana STG 2017, what is the first-line treatment for fluid overload in CKD?','["A. Metolazone","B. Spironolactone","C. Hydrochlorothiazide","D. Furosemide 40-120 mg orally or IV daily"]','D','Ghana STG recommends furosemide 40-120 mg daily (oral or IV) as first-line treatment for fluid overload in CKD. Loop diuretics are preferred in CKD stages 3-5 because they retain efficacy at low GFR, unlike thiazides (which lose efficacy when eGFR <30). Metolazone can be combined with furosemide for resistant oedema via synergistic blockade at both the TAL (furosemide) and DCT (metolazone). Daily weight monitoring and fluid restriction are essential.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','CKD Staging','medium','mcq','A patient has eGFR 20 mL/min/1.73 m2 with diabetes for 4 months. What CKD stage is this and what is the recommended next step?','["A. Stage 4 — prepare for renal replacement therapy and refer to nephrologist","B. Stage 3 — annual monitoring with eGFR and ACR","C. Stage 5 — initiate dialysis immediately","D. Stage 2 — lifestyle modifications only"]','A','CKD Stage 4 (eGFR 15-29 mL/min/1.73 m2) represents severely reduced GFR. Per Ghana STG 2017, Stage 4 requires preparation for kidney replacement therapy and referral to a nephrologist. At this stage, patients are evaluated for vascular access creation (for haemodialysis), transplant suitability, and medications are reviewed for accumulation — metformin, NSAIDs, and many other renally cleared drugs require dose adjustment or discontinuation.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','AKI Staging','medium','mcq','KDIGO AKI Stage 2 is defined by which serum creatinine criterion?','["A. 1.5 to 1.9 times baseline","B. 2.0 to 2.9 times baseline","C. 3.0 times or greater than baseline","D. Any creatinine >353.6 micromol/L"]','B','KDIGO AKI serum creatinine staging: Stage 1 = 1.5-1.9x baseline or absolute +26.4 micromol/L; Stage 2 = 2.0-2.9x baseline; Stage 3 = ≥3.0x baseline, OR absolute Cr >353.6 micromol/L, OR initiation of renal replacement therapy. The urine output criteria parallel creatinine criteria for staging. Stage 2 requires ICU-level monitoring and strict fluid balance management.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Which of the following factors is known to affect serum cystatin C concentrations independently of GFR?','["A. Dietary meat intake","B. Tubular secretion of cystatin C","C. Corticosteroid therapy and rheumatoid arthritis","D. Strenuous exercise the day before measurement"]','C','Serum cystatin C can be altered by factors other than GFR, including: age, nutritional status, gender, weight, height, cigarette smoking, serum CRP, corticosteroid therapy, and rheumatoid arthritis. This limits its specificity as a GFR marker. In pediatric and adult renal transplant recipients, cystatin C may be weakly associated with measured GFR due to reduced tubular catabolism. Dietary meat affects creatinine but not cystatin C; exercise also primarily affects creatinine.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','Like cimetidine, trimethoprim can raise serum creatinine without a true change in GFR. What is the mechanism?','["A. Trimethoprim increases creatine synthesis in skeletal muscle","B. Trimethoprim stimulates glomerular vasoconstriction","C. Trimethoprim activates the Jaffé colorimetric reaction","D. Trimethoprim competitively inhibits cationic tubular secretion of creatinine"]','D','Trimethoprim competes with creatinine at the cationic organic cation transporter OCT2 in the proximal tubule, reducing tubular secretion of creatinine. This raises serum creatinine and lowers urinary creatinine — mimicking a decline in GFR when actual GFR is unchanged. This must be considered when monitoring renal function in patients on co-trimoxazole (trimethoprim + sulfamethoxazole), a commonly used antibiotic in Ghana for UTIs and pneumocystis prophylaxis.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','AKI Staging','medium','mcq','A patient with diarrhoea and oliguria is diagnosed with prerenal AKI. What is the MOST appropriate initial treatment?','["A. IV 0.9% sodium chloride to restore circulating volume","B. High-dose furosemide to increase urine output","C. Haemodialysis to clear nitrogenous wastes","D. Prednisolone to treat presumed glomerulonephritis"]','A','Prerenal AKI results from reduced renal perfusion (hypovolaemia). First-line treatment is restoration of circulating volume with isotonic crystalloid (0.9% NaCl or Ringer''s lactate if no hyperkalaemia, per Ghana STG). In haemorrhage, blood transfusion is appropriate. Furosemide may worsen hypovolaemia and is contraindicated before adequate fluid resuscitation. Dialysis is reserved for refractory cases with specific indications. Steroids are for immune-mediated glomerulonephritis only.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Nephron Anatomy','medium','mcq','The juxtaglomerular apparatus (JGA) consists of which cellular components?','["A. Podocytes, mesangial cells, and Bowman''s capsule epithelium","B. Juxtaglomerular (granular) cells, macula densa, and extraglomerular mesangial cells","C. Proximal tubule cells, pericytes, and afferent arteriole smooth muscle","D. Collecting duct intercalated cells and vasa recta"]','B','The juxtaglomerular apparatus comprises: (1) juxtaglomerular (granular) cells — renin-secreting modified smooth muscle cells of the afferent arteriole; (2) macula densa — NaCl-sensing cells at the junction of the TAL/DCT that regulate renin release and TGF; and (3) extraglomerular mesangial (lacis) cells. Together, these integrate systemic and local signals to maintain GFR and blood pressure homeostasis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Endocrine Functions','medium','mcq','Erythropoietin production is directly triggered by:','["A. Elevated serum calcium sensed by the parathyroid gland","B. Increased angiotensin II levels in the proximal tubule","C. Decreased oxygen tension detected by peritubular fibroblasts","D. Elevated serum phosphate activating the FGF-23 pathway"]','C','Decreased oxygen tension (hypoxia) is the primary stimulus for EPO production by peritubular fibroblasts in the renal cortex, mediated by hypoxia-inducible factor (HIF-1alpha). EPO stimulates red blood cell production in bone marrow. In CKD, remaining functional renal mass is insufficient to produce adequate EPO regardless of the hypoxic stimulus, resulting in normocytic normochromic anaemia that responds to exogenous EPO-stimulating agents.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44');
