-- Renal Pharmacology MCQs Q1-25
-- Source: DiPiro Pharmacotherapy 7th ed Ch46-47, Ghana STG 2017 Ch14
-- year_level: all years; category: Pharmacology; topic: Renal

INSERT INTO questions (professions, course, topic, subtopic, difficulty, category, question_type, question_text, options, correct_answer, explanation, year_level, region, high_yield, source_reference) VALUES

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'According to JNC-7 guidelines, what is the recommended blood pressure target for patients with chronic kidney disease (CKD)?',
'["A. <140/90 mmHg","B. <135/85 mmHg","C. <130/80 mmHg","D. <120/80 mmHg"]',
'C',
'JNC-7 recommends a BP goal of <130/80 mmHg for CKD patients. For those with proteinuria (elevated urinary protein:creatinine ratio), the target is even lower at <125/75 mmHg (DiPiro Ch46). These targets are stricter than the <140/90 mmHg goal for uncomplicated hypertension.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'Which ACE inhibitor has primarily hepatic (biliary) elimination rather than renal elimination, and therefore does NOT require dose reduction in CKD?',
'["A. Enalapril","B. Fosinopril","C. Ramipril","D. Captopril"]',
'B',
'Fosinopril is the exception among ACEIs: its clearance is NOT significantly reduced in CKD. All other ACEIs (enalapril, ramipril, captopril, lisinopril, etc.) are renally eliminated and require reduced doses in CKD. Clinicians should commence other ACEIs at lower initial doses and titrate up carefully (DiPiro Ch46).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'In a CKD patient with a creatinine clearance of 25 mL/min requiring a diuretic for blood pressure and fluid management, which diuretic class should be preferred?',
'["A. Potassium-sparing diuretics (e.g., spironolactone)","B. Thiazide diuretics (e.g., hydrochlorothiazide)","C. Loop diuretics (e.g., furosemide)","D. Osmotic diuretics (e.g., mannitol)"]',
'C',
'Per DiPiro Ch46 hypertension algorithm: if CrCl ≥30 mL/min, add a thiazide diuretic; if CrCl <30 mL/min, add a loop diuretic. Thiazides lose efficacy at low GFR. Loop diuretics (furosemide) remain effective even in advanced CKD. The Ghana STG also recommends furosemide 40-120 mg daily for CKD fluid overload.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'Angiotensin II preferentially constricts which renal arteriole, thereby increasing intraglomerular capillary pressure and filtration fraction?',
'["A. Afferent arteriole","B. Interlobular artery","C. Peritubular capillaries","D. Efferent arteriole"]',
'D',
'Angiotensin II is a potent vasoconstrictor of both afferent and efferent arterioles but preferentially affects the efferent arteriole. This raises pressure within glomerular capillaries (intraglomerular hypertension) and increases filtration fraction. ACE inhibitors and ARBs block this effect, reducing intraglomerular pressure and decreasing proteinuria (DiPiro Ch46).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'In the landmark captopril trial for type 1 diabetic nephropathy (Lewis et al.), captopril reduced the risk of doubling serum creatinine by approximately:',
'["A. 48%","B. 40%","C. 66%","D. 30%"]',
'A',
'The Lewis et al. trial (409 type 1 DM patients, 3 years) showed captopril 25 mg three times daily reduced the risk of doubling serum creatinine by 48% compared to placebo in patients with UPE ≥500 mg/day. The benefit was even greater (76%) when baseline Scr was around 2 g/dL. This trial established ACEIs as standard of care in diabetic nephropathy (DiPiro Table 46-4).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'Which angiotensin receptor blocker (ARB) was evaluated in the RENAAL trial and demonstrated a 16% risk reduction in the primary composite end point (doubling Scr, ESRD, or death) in type 2 diabetic nephropathy?',
'["A. Irbesartan","B. Losartan","C. Candesartan","D. Valsartan"]',
'B',
'The RENAAL trial (Brenner et al.) used losartan 50-100 mg daily in 1,513 type 2 diabetic patients with nephropathy over 3.4 years. Losartan produced a 16% risk reduction in the primary composite endpoint and a 35% reduction in proteinuria. This trial confirmed ARBs as renoprotective agents in diabetic nephropathy (DiPiro Table 46-5).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'A meta-analysis of ACEI studies in patients with overt proteinuria demonstrated what approximate risk reduction in ESRD or doubling of serum creatinine?',
'["A. 20%","B. 30%","C. 40%","D. 65%"]',
'C',
'A pooled meta-analysis showed ACEIs conferred a 40% reduction in the risk of developing ESRD or doubling of serum creatinine in patients with overt proteinuria (>300 mg protein/24 hours) and various renal disease etiologies. Separately, progression to proteinuria from microalbuminuria was reduced by 65% in diabetic patients (DiPiro Ch46, Fig. 46-3).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'When initiating ACEI therapy in a CKD patient, how soon should serum creatinine and potassium be rechecked, and what rise in Scr warrants discontinuation?',
'["A. 1 week; >30% rise","B. 2 weeks; >20% rise","C. 2 weeks; >30% rise","D. 4 weeks; >50% rise"]',
'A',
'Per the DiPiro Ch46 hypertension management algorithm, after starting an ACEI or ARB in CKD, serum creatinine and potassium should be rechecked in 1 week. If serum creatinine or potassium rises by more than 30%, the agent should be discontinued. This early monitoring detects haemodynamically mediated renal dysfunction or dangerous hyperkalaemia.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'Which subclass of calcium channel blockers lacks antiproteinuric effects in CKD, despite being effective antihypertensive agents?',
'["A. Non-dihydropyridines (diltiazem, verapamil)","B. Dihydropyridines (e.g., amlodipine, nifedipine)","C. Both subclasses have equivalent antiproteinuric effects","D. Neither subclass has any antihypertensive effect in CKD"]',
'B',
'Non-dihydropyridine CCBs (diltiazem, verapamil) have demonstrated antiproteinuric effects similar to ACEIs and are used as second-line antiproteinuric agents. Dihydropyridine CCBs (amlodipine) reduce blood pressure but do NOT have beneficial effects on proteinuria beyond BP reduction. Some studies suggest non-dihydropyridines plus ACEIs have additive proteinuria reduction (DiPiro Ch46).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'Per DiPiro Ch46, ACEI dose titration in proteinuric CKD should continue until proteinuria is reduced by what target?',
'["A. 10-20%","B. 20-30%","C. 30-50%","D. 50-70%"]',
'C',
'DiPiro recommends beginning ACEI therapy at low doses and increasing at 4-week intervals until proteinuria is reduced by 30-50% or side effects occur (Scr rise >30%, hyperkalaemia). The antiproteinuric ceiling dose may differ from the antihypertensive dose, so patients who have reached BP goals may still require dose adjustments for optimal proteinuria reduction (DiPiro Ch46).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'NSAIDs cause haemodynamically mediated AKI in CKD patients primarily through which mechanism?',
'["A. Direct tubular toxicity via oxidative stress","B. Immune-mediated interstitial nephritis","C. Crystal deposition in renal tubules","D. Vasoconstriction via reduced prostaglandin production"]',
'D',
'NSAIDs inhibit prostaglandin synthesis. In CKD and other states of reduced renal perfusion, prostaglandins maintain afferent arteriolar dilation. Blocking prostaglandins causes afferent vasoconstriction, reducing GFR (haemodynamically induced AKI). NSAIDs can also cause chronic tubulointerstitial nephritis and papillary necrosis with long-term use. The Ghana STG lists volume depletion and diuretic use as risk factors (Ghana STG Ch14).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'The Ghana STG recommends which drug for proteinuria control in adult patients with nephrotic syndrome?',
'["A. Lisinopril 5-20 mg daily","B. Captopril 25 mg three times daily","C. Losartan 50-100 mg daily","D. Enalapril 5-10 mg daily"]',
'A',
'The Ghana STG Ch14 (Section 135) recommends lisinopril 5-20 mg daily for control of proteinuria in adult nephrotic syndrome, alongside prednisolone for selected patients. ACE inhibitors reduce intraglomerular pressure, thereby reducing protein filtration. Lisinopril is on Ghana''s NHIS formulary and commonly available in tertiary facilities.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'For resistant oedema in adult nephrotic syndrome, the Ghana STG recommends adding which drug to furosemide?',
'["A. Spironolactone 25-100 mg daily","B. Metolazone 2.5-10 mg once daily","C. Amiloride 5-10 mg daily","D. Hydrochlorothiazide 25-50 mg daily"]',
'B',
'The Ghana STG recommends adding metolazone 2.5-10 mg once daily to furosemide for resistant oedema in adult nephrotic syndrome. This combination achieves profound natriuresis because metolazone blocks the NCC cotransporter in the distal convoluted tubule while furosemide blocks NKCC2 in the thick ascending limb, simultaneously targeting two nephron segments (Ghana STG Ch14 Section 135).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'The combination of loop diuretic plus metolazone produces profound sodium excretion because metolazone acts on which nephron segment?',
'["A. Thick ascending limb of Henle (NKCC2)","B. Proximal convoluted tubule","C. Distal convoluted tubule (NCC cotransporter)","D. Collecting duct (principal cells)"]',
'C',
'Metolazone is a thiazide-like diuretic that inhibits the NCC (sodium-chloride cotransporter) in the distal convoluted tubule. When combined with furosemide (which blocks NKCC2 in the thick ascending limb), the two drugs act on sequential nephron segments, preventing compensatory sodium reabsorption. This combination is particularly effective when the loop diuretic alone is insufficient (DiPiro Ch47; Ghana STG).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'The maximum daily oral dose of furosemide for nephrotic oedema in adults per the Ghana STG is:',
'["A. 80 mg","B. 120 mg","C. 160 mg","D. 240 mg"]',
'D',
'The Ghana STG Ch14 specifies furosemide oral: "40 mg daily, increasing to 80 mg daily; max. 240 mg daily" for adult nephrotic syndrome oedema. IV furosemide for nephrotic oedema is given at 40-80 mg 8-12 hourly (max. 160 mg daily). The higher oral maximum reflects reduced bioavailability due to intestinal oedema in nephrotic syndrome.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'Per the Ghana STG, what is the recommended dietary protein restriction for adult patients with CKD to slow progression?',
'["A. 1 g/kg/day","B. 0.6 g/kg/day","C. 1.2 g/kg/day","D. 0.8 g/kg/day"]',
'A',
'The Ghana STG (Section 137) recommends protein restriction to 1 g/kg/day for adult CKD patients as a non-pharmacological measure. This is consistent with K/DOQI recommendations. Dialysis patients require HIGHER protein intake (1.2-1.3 g/kg/day per DiPiro Ch47) because dialysis itself removes amino acids and protein. In contrast, DiPiro notes 0.6-0.8 g/kg/day may reduce proteinuria but requires careful monitoring for malnutrition.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'Which medication listed in the Ghana STG causes nephrotoxicity via crystal deposition in renal tubules (crystal nephropathy) leading to intratubular obstruction?',
'["A. Gentamicin","B. Aciclovir","C. Tenofovir","D. Methotrexate"]',
'B',
'Aciclovir at high IV doses can precipitate as crystals in renal tubules, causing intratubular obstruction and foci of interstitial inflammation (crystal nephropathy/proximal tubulopathy). Prevention requires adequate hydration (maintain urine output >75 mL/hour), avoiding IV bolus doses, and slow infusion over 1-2 hours. Methotrexate also precipitates but in acidic urine, and gentamicin causes direct tubular toxicity without crystallisation (Ghana STG Ch14).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'Per the DiPiro Ch46 hypertension management algorithm, which drug class should be initiated FIRST for blood pressure management in a patient with CKD?',
'["A. Beta-blocker","B. Calcium channel blocker","C. ACE inhibitor or ARB","D. Thiazide diuretic"]',
'C',
'Both DiPiro Ch46 and the Ghana STG recommend starting with an ACE inhibitor or ARB as first-step therapy in CKD patients with hypertension. These agents reduce intraglomerular pressure (via efferent arteriole dilation), decrease proteinuria, and slow CKD progression beyond their BP-lowering effects. If BP remains above goal after maximising the ACEI/ARB dose, a diuretic is added as step 2.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'The MICRO-HOPE trial showed ramipril 10 mg daily reduced the relative risk of overt nephropathy in type 2 diabetic patients. What relative risk value was observed?',
'["A. 0.35 (65% reduction)","B. 0.56 (44% reduction)","C. 0.66 (34% reduction)","D. 0.80 (20% reduction)"]',
'D',
'The HOPE/MICRO-HOPE trial (3,577 type 2 DM patients, 4.5 years) showed ramipril 10 mg daily lowered the risk of overt nephropathy with a relative risk of 0.8 (20% reduction) with and without baseline microalbuminuria. DiPiro Table 46-4 also shows lower UP:Cr at 1 and 4.5 years with ramipril treatment. This established ACEIs in primary nephroprotection even beyond BP effects.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'Lithium nephrotoxicity is particularly likely when co-prescribed with which class of diuretics?',
'["A. Thiazide diuretics","B. Loop diuretics","C. Potassium-sparing diuretics","D. Osmotic diuretics"]',
'A',
'The Ghana STG highlights thiazide diuretics as a key risk factor for lithium nephrotoxicity. Thiazides cause sodium depletion, which triggers compensatory proximal tubular sodium reabsorption — and lithium is reabsorbed along with sodium, causing lithium retention and toxicity. The therapeutic lithium range is 0.6-1.2 mmol/L. Prevention includes maintaining this range, preventing dehydration, and avoiding a low-sodium diet (Ghana STG Ch14).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'Per DiPiro Ch46, the blood pressure goal for CKD patients WITH elevated urinary protein-to-creatinine ratio (proteinuric CKD) is:',
'["A. <130/80 mmHg","B. <125/75 mmHg","C. <140/90 mmHg","D. <120/70 mmHg"]',
'B',
'While the JNC-7 target for CKD generally is <130/80 mmHg, DiPiro Ch46 Figure 46-2 specifies a more stringent goal of <125/75 mmHg for CKD patients with proteinuria (elevated UP:Cr). This tighter target reflects evidence that lower BP reduces both glomerular capillary pressure and proteinuria-driven nephron loss. Achieving this often requires three or more antihypertensive agents.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'Tenofovir (antiretroviral used in HIV/HBV treatment) causes which tubular syndrome as part of its nephrotoxicity profile?',
'["A. Bartter syndrome","B. Gitelman syndrome","C. Fanconi syndrome","D. Liddle syndrome"]',
'C',
'The Ghana STG lists tenofovir as causing tubular cell karyomegaly, degeneration and necrosis leading to interstitial nephritis, AKI, and Fanconi syndrome. Fanconi syndrome involves generalised proximal tubular dysfunction: phosphate wasting, glucosuria (normal blood glucose), aminoaciduria, and bicarbonate wasting. This is particularly relevant in Ghana where tenofovir-based ART is widely used in HIV management (Ghana STG Ch14).',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'Aciclovir nephrotoxicity prevention requires adequate hydration. The Ghana STG specifies maintaining urine output above:',
'["A. 30 mL/hour","B. 50 mL/hour","C. 60 mL/hour","D. 75 mL/hour"]',
'D',
'The Ghana STG Ch14 specifies that aciclovir nephrotoxicity prevention requires: (1) avoiding IV bolus doses, (2) prior hydration maintaining urine output >75 mL/hour, and (3) slow drug infusion over 1-2 hours. High urine output prevents aciclovir crystal precipitation in renal tubules. Patients with reduced renal function are at highest risk and require dose adjustment.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'In the benazepril study (Maschio et al.), the risk reduction for doubling of serum creatinine or requirement for dialysis in patients with MILD renal insufficiency (GFR 46-60 mL/min) was:',
'["A. 71%","B. 53%","C. 46%","D. 40%"]',
'A',
'DiPiro Table 46-7 reports the Maschio et al. study of benazepril 10 mg daily in 583 patients with renal disorders. Overall risk reduction was 53%, but subgroup analysis showed 71% risk reduction in the mild insufficiency group (GFR 46-60 mL/min) versus 46% in the moderate group (GFR 30-45 mL/min). This supports early initiation of ACEIs in CKD before advanced stages.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14'),

('{pharmacist}','Pharmacology','Renal','CKD Hypertension Management','medium','Pharmacology','mcq',
'To achieve adequate blood pressure goals in most patients with CKD, DiPiro states that how many antihypertensive medications are usually required?',
'["A. One medication","B. Three or more medications","C. Two medications","D. Four or more medications"]',
'B',
'DiPiro Ch46 explicitly states: "Elevated blood pressure is often more difficult to control in patients with CKD than in those with normal kidney function. Therefore, to achieve adequate blood pressure goals, three or more different blood pressure medications are usually required." This reflects the complex pathophysiology of hypertension in CKD (volume overload, RAAS activation, sympathetic activation) requiring multi-drug approaches.',
'{year1,year2,year3,year4,year5,year6,practitioner}','universal',true,'DiPiro Pharmacotherapy 7th ed, Ch46-47; Ghana STG 2017 Ch14');

