-- Renal A&P MCQs Batch 2 (Q26-50) — Endocrine/Metabolic Functions + AKI/CKD Staging
-- Source: DiPiro Pharmacotherapy 7th ed Ch.44 + Ghana STG 2017 Ch.14
-- Correct answer distribution: A=6, B=7, C=6, D=6

INSERT INTO questions (professions, course, topic, category, subtopic, difficulty, question_type, question_text, options, correct_answer, explanation, region, high_yield, year_level, source_reference) VALUES

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Endocrine Functions','medium','mcq','The hormone renin is produced and secreted by which renal cell type?','["A. Juxtaglomerular cells of the afferent arteriole","B. Mesangial cells of the glomerulus","C. Peritubular fibroblasts of the renal cortex","D. Intercalated cells of the collecting duct"]','A','Renin is secreted by juxtaglomerular (JG) granular cells of the afferent arteriole in response to decreased renal perfusion pressure, reduced sodium delivery to the macula densa, or sympathetic stimulation. Renin cleaves angiotensinogen to angiotensin I, initiating the renin-angiotensin-aldosterone system (RAAS), which regulates blood pressure and sodium balance.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Endocrine Functions','medium','mcq','Erythropoietin is produced by which renal cell type in response to hypoxia?','["A. Juxtaglomerular cells","B. Peritubular fibroblasts","C. Podocytes of the glomerulus","D. Proximal tubule epithelial cells"]','B','Erythropoietin (EPO) is produced and secreted by peritubular fibroblasts in the renal cortex in response to decreased oxygen tension. Because EPO production is proportional to functional renal mass, it is progressively impaired in CKD stages 3-5, leading to normocytic normochromic anaemia — a central feature of the cardiorenal anaemia syndrome.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Endocrine Functions','medium','mcq','The kidney activates vitamin D3 through which enzymatic step?','["A. 25-hydroxylation of cholecalciferol in the liver","B. Conjugation of calcitriol with glucuronide","C. 1-alpha-hydroxylation of 25-OH vitamin D3 to calcitriol","D. Decarboxylation of ergocalciferol to cholecalciferol"]','C','The kidney contains 1-alpha-hydroxylase (CYP27B1), which converts 25-OH vitamin D3 (calcidiol, formed in the liver) to 1,25-dihydroxyvitamin D3 (calcitriol), the active form. Calcitriol increases intestinal calcium and phosphate absorption and supports bone mineralization. In CKD, impaired 1-alpha-hydroxylase activity leads to calcitriol deficiency, hypocalcaemia, and renal osteodystrophy.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Endocrine Functions','medium','mcq','A patient with type 2 diabetes develops end-stage renal disease and begins haemodialysis. Which change in insulin therapy is MOST likely required?','["A. Insulin dose should be doubled due to increased volume of distribution","B. Insulin requirements increase due to reduced glucose excretion","C. Insulin type should be switched from long-acting to rapid-acting only","D. Insulin requirements decrease because the kidney contributes significantly to insulin degradation"]','D','The kidney is a major site of insulin metabolism. As GFR declines, insulin degradation by the kidney is reduced, extending its plasma half-life. Consequently, diabetic patients with CKD often require reduced insulin doses to prevent hypoglycaemia. This is an important clinical consideration, particularly when transitioning patients to dialysis.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','easy','mcq','What is the approximate normal glomerular filtration rate (GFR) in healthy adult men?','["A. 127 ± 20 mL/min/1.73 m2","B. 80 ± 10 mL/min/1.73 m2","C. 150 ± 25 mL/min/1.73 m2","D. 100 ± 15 mL/min/1.73 m2"]','A','Normal GFR in healthy adult men averages 127 ± 20 mL/min/1.73 m2, and in women 118 ± 20 mL/min/1.73 m2. GFR declines with age at approximately 1 mL/min/1.73 m2 per year after age 40. A GFR persistently below 60 mL/min/1.73 m2 for more than 3 months defines CKD in the absence of kidney damage markers.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','easy','mcq','What is the normal blood urea nitrogen (BUN) to serum creatinine ratio?','["A. 5 to 8:1","B. 10 to 15:1","C. 20 to 25:1","D. 30 to 40:1"]','B','The normal BUN-to-creatinine ratio is 10 to 15:1. An elevated ratio (>15:1) suggests decreased effective circulating volume (prerenal azotaemia), which stimulates water and urea reabsorption. A ratio below 10:1 may indicate hepatic disease (reduced urea synthesis) or malnutrition with low protein intake.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','A patient presents with vomiting and diarrhoea. BUN is 60 mg/dL and serum creatinine is 2 mg/dL. What does this clinical picture most likely suggest?','["A. Intrinsic renal failure due to acute tubular necrosis","B. Obstructive (post-renal) nephropathy","C. Prerenal azotaemia due to volume depletion","D. CKD Stage 4"]','C','The BUN:Cr ratio is 30:1, well above the normal upper limit of 15:1. This indicates increased urea reabsorption from volume depletion — classic prerenal azotaemia. Hypovolemia (from vomiting and diarrhoea) triggers enhanced water and urea reabsorption in the proximal tubule, disproportionately elevating BUN compared to creatinine. Initial treatment is IV fluid resuscitation with 0.9% NaCl.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44; Ghana STG 7th ed Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','CKD Staging','medium','mcq','According to the Ghana Standard Treatment Guidelines (2017), a patient with an eGFR of 45 mL/min/1.73 m2 for 4 months is classified as which CKD stage?','["A. Stage 1","B. Stage 2","C. Stage 4","D. Stage 3"]','D','Ghana STG 2017 CKD staging: Stage 1 (>90), Stage 2 (60-89), Stage 3 (30-59), Stage 4 (15-29), Stage 5 (<15 mL/min/1.73 m2). An eGFR of 45 falls in Stage 3 — moderately reduced GFR. Kidney damage must be present for >3 months to qualify as CKD. Stage 3 management includes estimating progression, treating complications, checking Hb/calcium/phosphate/PTH annually, and referring if eGFR ≤30.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14; DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','AKI Staging','medium','mcq','According to KDIGO criteria, AKI Stage 1 is defined by a serum creatinine rise to:','["A. 1.5 to 1.9 times baseline","B. 2.0 to 2.9 times baseline","C. 3.0 times baseline or greater","D. Any detectable rise above the upper limit of normal"]','A','KDIGO AKI staging: Stage 1 = Cr 1.5-1.9x baseline OR absolute increase >26.4 micromol/L, with UO <0.5 mL/kg/hr for 6-12h; Stage 2 = 2.0-2.9x baseline, UO <0.5 mL/kg/hr for >12h; Stage 3 = ≥3.0x baseline OR Cr >353.6 micromol/L OR initiation of renal replacement therapy, UO <0.3 mL/kg/hr for >24h or anuria >12h.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','AKI Staging','medium','mcq','Which clinical finding ALONE meets the KDIGO criteria for AKI Stage 3?','["A. Serum creatinine 2.5 times the patient''s baseline","B. Initiation of renal replacement therapy (dialysis)","C. Urine output <0.5 mL/kg/hr for 13 hours","D. Serum creatinine absolute increase of 30 micromol/L"]','B','KDIGO Stage 3 AKI is reached when Cr ≥3.0x baseline, OR absolute Cr >353.6 micromol/L, OR when renal replacement therapy is initiated — regardless of Cr level. Cr 2.5x baseline is Stage 2. UO <0.5 mL/kg/hr for 13h is Stage 2 (criterion: >12h). Absolute Cr rise of 30 micromol/L barely exceeds the Stage 1 threshold (>26.4). Initiation of dialysis is an automatic Stage 3 classification.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','AKI Staging','medium','mcq','According to the Ghana Standard Treatment Guidelines 2017, which infection is listed as a medical cause of Acute Kidney Injury (AKI)?','["A. Dengue fever","B. Yellow fever","C. Malaria","D. Meningococcal meningitis"]','C','The Ghana STG 2017 lists malaria (causing haemolysis) as a key medical cause of AKI, alongside diarrhoea/dehydration, typhoid fever, herbal medicines, G6PD deficiency, and acute glomerulonephritis. Haemolysis from malaria leads to free haemoglobin in the circulation, which filters at the glomerulus and is directly toxic to proximal tubule cells, causing acute tubular necrosis and AKI.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','The hallmark laboratory finding distinguishing nephrotic syndrome from nephritic syndrome is:','["A. Red blood cell casts in urine","B. Serum creatinine >353 micromol/L","C. Positive blood cultures for gram-negative organisms","D. Urine protein excretion greater than 3 to 3.5 g per 1.73 m2 daily"]','D','Nephrotic syndrome is defined by proteinuria >3-3.5 g/1.73 m2/day, accompanied by hypoalbuminaemia, oedema, hyperlipidaemia, and a hypercoagulable state. Nephritic syndrome is characterised by haematuria (RBC casts), mild-to-moderate proteinuria, oliguria, and hypertension. RBC casts are hallmarks of nephritic, not nephrotic, syndrome. In Ghana, malarial nephropathy (P. malariae) is a notable infectious cause of nephrotic syndrome.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14; DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Cystatin C is a GFR biomarker produced by all nucleated cells. What is its molecular weight?','["A. 13.3 kDa (132 amino acids)","B. 67 kDa","C. 5 kDa","D. 40 kDa"]','A','Cystatin C is a 132-amino-acid cysteine protease inhibitor with a molecular weight of approximately 13.3 kDa. It is freely filtered at the glomerulus and catabolized in the proximal tubule. Unlike creatinine, cystatin C levels are not significantly influenced by muscle mass, making it useful in patients with unusual body composition (e.g., amputees, cachexia). Normal adult reference range: 0.54-1.21 mg/L.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','easy','mcq','Normal urine specific gravity ranges from:','["A. 1.000 to 1.010","B. 1.003 to 1.030","C. 1.010 to 1.050","D. 1.020 to 1.040"]','B','Normal urine specific gravity ranges from 1.003 to 1.030, reflecting the kidney''s concentrating ability relative to water (SG = 1.000). Fixed SG of 1.010 (isosthenuria) indicates loss of concentrating and diluting ability. Values above 1.030 suggest dehydration; very dilute urine (<1.003) can be seen in diabetes insipidus or excessive fluid intake. Osmolality is more accurate when heavy molecules are present.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','easy','mcq','A positive leukocyte esterase on urine dipstick is most suggestive of:','["A. Diabetic nephropathy","B. Haemolytic anaemia","C. Urinary tract infection","D. Glomerulonephritis"]','C','Leukocyte esterase is released from lysed granulocytes (white blood cells) in the urine. A positive result suggests UTI or other inflammatory conditions such as interstitial nephritis. False positives can occur with Trichomonas infection or vaginal secretion contamination. False negatives occur with high protein or ascorbic acid concentrations. It is complementary to the nitrite test.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','A patient has a positive heme test on urinalysis but microscopy shows no red blood cells. What is the most likely explanation?','["A. Diabetic nephropathy","B. Nephrotic syndrome","C. Renal tubular acidosis","D. Red cell haemolysis or rhabdomyolysis"]','D','A positive urine heme test without visible RBCs on microscopy indicates free haemoglobin (from intravascular haemolysis, e.g., malaria, transfusion reaction, G6PD-triggered haemolysis) or myoglobin (from rhabdomyolysis). Both are filtered at the glomerulus when plasma levels are high and are directly toxic to proximal tubule cells, causing acute tubular necrosis. In Ghana, malaria is a key cause of haemolysis-related AKI.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44; Ghana STG 7th ed Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','What percentage of filtered urea is reabsorbed in the proximal tubule?','["A. Approximately 50%","B. 10 to 15%","C. 80 to 90%","D. Less than 5%"]','A','Approximately 50% of filtered urea is reabsorbed in the proximal tubule, primarily passively following water reabsorption. In volume depletion, enhanced water reabsorption increases urea reabsorption proportionally, disproportionately elevating BUN compared to creatinine (BUN:Cr >15:1 = prerenal azotaemia). Creatinine is not significantly reabsorbed, which is why BUN:Cr rises selectively in prerenal states.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Glomerular Filtration','medium','mcq','Which BUN:creatinine ratio is MOST consistent with prerenal azotaemia?','["A. 8:1","B. 25:1","C. 12:1","D. 15:1"]','B','A BUN:Cr ratio exceeding 15:1 is characteristic of prerenal azotaemia, caused by reduced effective arterial blood flow (e.g., dehydration, heart failure, hepatorenal syndrome). Volume depletion stimulates water and urea reabsorption. Creatinine is not significantly reabsorbed. A ratio of 8:1 may suggest hepatic failure or low protein intake. A ratio of 12-15:1 is within normal limits.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Endocrine Functions','medium','mcq','Cardiorenal anaemia syndrome describes the cyclical relationship between:','["A. Proteinuria, hypertension, and CKD progression","B. Hypoalbuminaemia, oedema, and renal vein thrombosis","C. CKD, reduced erythropoietin, anaemia, and cardiovascular disease","D. Diabetes, obesity, and accelerated GFR decline"]','C','The cardiorenal anaemia syndrome is the cyclical interplay of CKD, impaired EPO secretion, resulting normocytic normochromic anaemia, and cardiovascular disease. Anaemia-induced hypoxia activates EPO gene expression but remaining renal mass is insufficient to meet demand. Left ventricular hypertrophy is present in >40% of CKD patients driven by this syndrome. Treating anaemia with EPO-stimulating agents reduces cardiovascular morbidity.','universal',false,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Endocrine Functions','medium','mcq','According to the Ghana Standard Treatment Guidelines (2017), the target haemoglobin when treating renal anaemia with erythropoiesis-stimulating agents is:','["A. 13 to 14 g/dL","B. 10 to 11 g/dL","C. 8 to 9 g/dL","D. 11 to 12 g/dL"]','D','The Ghana STG 2017 specifies a target Hb of 11-12 g/dL for renal anaemia. Targeting higher Hb (>13 g/dL) with ESAs has been associated with increased cardiovascular events (CHOIR, TREAT trials). ESAs available include epoetin beta, darbepoetin alfa, and methoxy PEG-epoetin beta. Iron supplementation (ferrous sulphate or IV iron sucrose) is given alongside ESA therapy to ensure adequate substrate for erythropoiesis.','ghana',true,'{year1,year2,year3,year4,year5,year6,practitioner}','Ghana STG 7th ed 2017, Ch. 14'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Endocrine Functions','medium','mcq','Impaired 1-alpha-hydroxylase activity in CKD leads to deficiency of which active metabolite, contributing to renal osteodystrophy?','["A. 7-dehydrocholesterol","B. Calcitriol (1,25-dihydroxyvitamin D3)","C. Ergocalciferol (vitamin D2)","D. 25-OH vitamin D3 (calcidiol)"]','B','1-alpha-hydroxylase in the kidney converts 25-OH vitamin D3 (calcidiol) to calcitriol (1,25-dihydroxyvitamin D3), the active form. In CKD, this step is impaired, causing calcitriol deficiency → reduced intestinal calcium absorption → hypocalcaemia → secondary hyperparathyroidism → renal osteodystrophy. Treatment: calcitriol supplementation or vitamin D analogs (paricalcitol, doxercalciferol) that do not require renal 1-alpha-hydroxylation.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','Furosemide exerts its diuretic effect by blocking which transporter in the thick ascending limb of the loop of Henle?','["A. Na+/K+-ATPase on the basolateral membrane","B. Sodium-chloride cotransporter (NCC)","C. Na+-K+-2Cl- cotransporter (NKCC2)","D. Amiloride-sensitive epithelial sodium channel (ENaC)"]','C','Furosemide is a loop diuretic that inhibits the Na+-K+-2Cl- (NKCC2) cotransporter in the thick ascending limb (TAL) of the loop of Henle. The TAL is impermeable to water; blocking NKCC2 prevents concentration of the medullary interstitium, impairing free water reabsorption in the collecting duct. Thiazides inhibit NCC in the DCT. Amiloride/triamterene block ENaC in the collecting duct.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','Aldosterone promotes sodium retention and potassium excretion by acting on which nephron segment?','["A. Proximal convoluted tubule","B. Thick ascending limb of loop of Henle","C. Bowman''s capsule","D. Principal cells of the collecting duct"]','D','Aldosterone binds mineralocorticoid receptors in principal cells of the collecting duct (and late distal tubule). It upregulates ENaC (Na+ reabsorption) and ROMK (K+ secretion) on the apical membrane, and Na+/K+-ATPase on the basolateral membrane. Net effect: Na+ and water retention, K+ and H+ excretion. Potassium-sparing diuretics (spironolactone blocks aldosterone receptor; amiloride blocks ENaC) act at this site.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Tubular Function','medium','mcq','Antidiuretic hormone (ADH/vasopressin) promotes water reabsorption in the collecting duct primarily by inserting which water channels into the apical membrane?','["A. Aquaporin-2 (AQP2)","B. Aquaporin-1 (AQP1)","C. Aquaporin-4 (AQP4)","D. SGLT2 (sodium-glucose cotransporter 2)"]','A','ADH acts via V2 receptors on collecting duct principal cells, stimulating cAMP-mediated insertion of aquaporin-2 (AQP2) into the apical membrane, allowing water reabsorption. AQP1 is constitutively expressed in the proximal tubule and descending thin limb. Diabetes insipidus results from ADH deficiency (central) or resistance (nephrogenic). Lithium and demeclocycline can cause nephrogenic DI by blocking AQP2 insertion.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44'),

('{"pharmacist"}','Pharmacology','Renal','Anatomy & Physiology','Nephron Anatomy','medium','mcq','The macula densa cells sense tubular NaCl concentration and send feedback signals to the afferent arteriole in a process known as:','["A. Pressure natriuresis","B. Tubuloglomerular feedback (TGF)","C. Aldosterone escape","D. Myogenic autoregulation"]','B','The macula densa is a specialized region of the thick ascending limb adjacent to the glomerulus, forming part of the juxtaglomerular apparatus (JGA). It senses NaCl delivery; high NaCl triggers vasoconstriction of the afferent arteriole (reducing GFR) and suppresses renin release. This tubuloglomerular feedback (TGF) maintains GFR within narrow limits. NSAIDs impair prostaglandin-mediated vasodilation at this site, potentially causing acute kidney injury.','universal',true,'{year1,year2,year3,year4,year5,year6,practitioner}','DiPiro Pharmacotherapy 7th ed, Ch. 44');
